package mcp

import (
	"context"
	"strconv"
	"strings"
	"time"

	"github.com/go-viper/mapstructure/v2"
	"github.com/jinzhu/gorm"
	"github.com/yaklang/yaklang/common/mcp/mcp-go/mcp"
	"github.com/yaklang/yaklang/common/mcp/mcp-go/server"
	"github.com/yaklang/yaklang/common/schema"
	"github.com/yaklang/yaklang/common/utils"
	grpcmodel "github.com/yaklang/yaklang/common/yakgrpc/model"
	"github.com/yaklang/yaklang/common/yakgrpc/yakit"
	"github.com/yaklang/yaklang/common/yakgrpc/ypb"
)

var filterHTTPFlowToolOptions = []mcp.ToolOption{
	mcp.WithPaging("pagination",
		[]string{"id", "created_at", "updated_at", "deleted_at", "hidden_index", "no_fix_content_length", "hash", "is_http_s", "url", "path", "method", "body_length", "content_type", "status_code", "source_type", "request", "response", "duration", "get_params_total", "post_params_total", "cookie_params_total", "ip_address", "remote_addr", "ip_integer", "tags", "payload", "is_websocket", "websocket_hash", "runtime_id", "from_plugin", "process_name", "is_too_large_response", "too_large_response_header_file", "too_large_response_body_file", "is_too_large_request", "too_large_request_header_file", "too_large_request_body_file", "upload_online"},
		mcp.Description("Pagination settings for the query"),
	),
	mcp.WithString("sourceType",
		mcp.Description("Source type of the HTTP flow"),
	),
	mcp.WithString("methods",
		mcp.Description("HTTP methods to filter"),
	),
	mcp.WithString("searchURL",
		mcp.Description("URL to search for"),
	),
	mcp.WithString("statusCode",
		mcp.Description("HTTP status code to filter"),
	),
	mcp.WithBool("haveBody",
		mcp.Description("Whether the HTTP flow has a body"),
	),
	mcp.WithString("searchContentType",
		mcp.Description("Content type to search for"),
	),
	mcp.WithNumber("beforeUpdatedAt",
		mcp.Description("Filter flows updated before this timestamp"),
	),
	mcp.WithNumber("afterUpdatedAt",
		mcp.Description("Filter flows updated after this timestamp"),
	),
	mcp.WithNumber("afterId",
		mcp.Description("Filter flows with ID greater than this value"),
	),
	mcp.WithNumber("beforeId",
		mcp.Description("Filter flows with ID less than this value"),
	),
	mcp.WithString("keyword",
		mcp.Description("Keyword to search for in the flow"),
	),
	mcp.WithBool("onlyWebsocket",
		mcp.Description("Filter only websocket flows"),
	),
	mcp.WithStringArray("includeInUrl",
		mcp.Description("Include flows with these URLs"),
	),
	mcp.WithStringArray("excludeInUrl",
		mcp.Description("Exclude flows with these URLs"),
	),
	mcp.WithStringArray("includeInIP",
		mcp.Description("Include flows with these IPs"),
	),
	mcp.WithStringArray("excludeInIP",
		mcp.Description("Exclude flows with these IPs"),
	),
	mcp.WithStringArray("tags",
		mcp.Description("Filter flows by these tags"),
	),
	mcp.WithNumber("afterBodyLength",
		mcp.Description("Filter flows with body length greater than this value"),
	),
	mcp.WithNumber("beforeBodyLength",
		mcp.Description("Filter flows with body length less than this value"),
	),
	mcp.WithString("isWebsocket",
		mcp.Description(`Filter by websocket status: "http/https" for HTTP only, "websocket" for WebSocket only, omit for all`),
	),
	mcp.WithString("fromPlugin",
		mcp.Description("Filter flows generated by this plugin"),
	),
	mcp.WithBool("full",
		mcp.Description("Whether to return full flow data"),
	),
	mcp.WithStringArray("includePath",
		mcp.Description("Include flows with these paths"),
	),
	mcp.WithStringArray("excludePath",
		mcp.Description("Exclude flows with these paths"),
	),
	mcp.WithStringArray("includeSuffix",
		mcp.Description("Include flows with these suffixes"),
	),
	mcp.WithStringArray("excludeSuffix",
		mcp.Description("Exclude flows with these suffixes"),
	),
	mcp.WithStringArray("excludeContentType",
		mcp.Description("Exclude flows with these content types"),
	),
	mcp.WithBool("withPayload",
		mcp.Description("Whether to include payload in the flow"),
	),
	mcp.WithStringArray("processName",
		mcp.Description("Filter flows by process name"),
	),
	mcp.WithStringArray("excludeKeywords",
		mcp.Description("Exclude flows containing these keywords"),
	),
	mcp.WithString("keywordType",
		mcp.Description(`Type of keyword to search for. Allowed values: "response", "request", or leave empty to search all`),
		mcp.Enum("response", "request"),
	),
	mcp.WithBool("haveCommonParams",
		mcp.Description("Filter flows that have common parameters (GET/POST/Cookie)"),
	),
	mcp.WithNumberArray("excludeId",
		mcp.Description("Exclude flows with these IDs"),
	),
	mcp.WithNumberArray("includeId",
		mcp.Description("Include only flows with these IDs"),
	),
	mcp.WithString("haveParamsTotal",
		mcp.Description("Filter flows by total parameter count expression, e.g. \">0\" or \"=3\""),
	),
	mcp.WithStringArray("color",
		mcp.Description("Filter flows by color labels"),
	),
	mcp.WithNumber("offsetId",
		mcp.Description("Offset ID for cursor-based pagination"),
	),
	mcp.WithStringArray("includeHash",
		mcp.Description("Include only flows matching these hashes"),
	),
	mcp.WithString("payloadKeyword",
		mcp.Description("Keyword to search within the payload field"),
	),
	mcp.WithString("excludeStatusCode",
		mcp.Description("HTTP status codes to exclude, e.g. \"200,301\""),
	),
	mcp.WithStringArray("hostnameFilter",
		mcp.Description("Fuzzy-match filter on hostname"),
	),
	mcp.WithStructArray("mitmExtractAggregateFilterRows",
		[]mcp.PropertyOption{
			mcp.Description("MITM extract aggregate filter rows for advanced filtering"),
		},
		mcp.WithString("ruleVerbose",
			mcp.Description("Rule verbose name"),
		),
		mcp.WithString("displayData",
			mcp.Description("Display data value to match"),
		),
	),
}

// httpFlowDatabaseHint is appended to every HTTP-flow tool description so that
// AI clients keep HTTP traffic analysis scoped to the current project database.
const httpFlowDatabaseHint = `
<IMPORTANT>
HTTP flow records are read from the current Yakit project database. By default, query_http_flow returns only current MITM/capture traffic (sourceType=mitm) and only the newest page ordered by updated_at desc. Pass sourceType="all" only when the user explicitly asks for all HTTP flow sources.
Use returned_count as the number of flow records included in this tool response. Use total_matched_count as the total number of records matching the effective filter in the current project database. Do not call a paged response "read N records" by using the pagination limit or total_matched_count.
Do not iterate pages, query unrelated tables, or call risk/port/MITM-rule tools as substitutes for HTTP traffic unless the user explicitly asks for those data types.
If no HTTP flows are returned, report the current_project/current_database from the tool result and ask the user to confirm that Yakit is using the intended project and that capture/MITM traffic has been written to it.
</IMPORTANT>`

func init() {
	AddGlobalToolSet("httpflow",
		WithTool(mcp.NewTool("query_http_flow",
			append([]mcp.ToolOption{
				mcp.WithDescription("Query HTTP flow data with flexible filters." + httpFlowDatabaseHint),
			}, filterHTTPFlowToolOptions...)...,
		), handleQueryHTTPFlows),
		WithTool(mcp.NewTool(string("set_tag_for_http_flow"),
			mcp.WithDescription("Sets tags for an HTTP flow."+httpFlowDatabaseHint),
			mcp.WithNumber("id",
				mcp.Description("The ID of the HTTP flow, maybe use query_http_flow to get the ID of the flow to be tagged"),
				mcp.Required(),
			),
			mcp.WithString("hash",
				mcp.Description("The hash of the HTTP flow; alternative to id for locating the flow"),
			),
			mcp.WithStringArray("tags",
				mcp.Description("The tags to be set for the HTTP flow"),
				mcp.Required(),
			),
		), handleSetTagForHTTPFlow),
		WithTool(mcp.NewTool(string("delete_http_flow"),
			mcp.WithDescription("Delete HTTP flow with flexible filters."+httpFlowDatabaseHint),
			mcp.WithBool("deleteAll",
				mcp.Description("Delete all flows")),
			mcp.WithNumberArray("id",
				mcp.Description("Delete flows with these specific IDs"),
			),
			mcp.WithStringArray("itemHash",
				mcp.Description("Delete flows matching these hashes"),
			),
			mcp.WithString("urlPrefix",
				mcp.Description("Delete flows whose URL starts with this prefix"),
			),
			mcp.WithStringArray("urlPrefixBatch",
				mcp.Description("Delete flows whose URL starts with any of these prefixes"),
			),
			mcp.WithStruct("filter",
				[]mcp.PropertyOption{
					mcp.Description("Filter that same with query_http_flow arguments"),
				},
				filterHTTPFlowToolOptions...,
			),
		), handleDeleteHTTPFlows),
	)
}

func ypbHTTPFlowToFriendlyHTTPFlow(f *ypb.HTTPFlow) *schema.HTTPFlow {
	flow := &schema.HTTPFlow{
		Model: gorm.Model{
			ID:        uint(f.Id),
			CreatedAt: time.Unix(f.CreatedAt, 0),
			UpdatedAt: time.Unix(f.UpdatedAt, 0),
		},
		NoFixContentLength:         f.NoFixContentLength,
		IsHTTPS:                    f.IsHTTPS,
		Url:                        f.Url,
		Path:                       f.Path,
		Method:                     f.Method,
		RequestLength:              f.RequestLength,
		BodyLength:                 f.BodyLength,
		ContentType:                f.ContentType,
		StatusCode:                 f.StatusCode,
		SourceType:                 f.SourceType,
		Duration:                   f.DurationMs * int64(time.Millisecond),
		GetParamsTotal:             int(f.GetParamsTotal),
		PostParamsTotal:            int(f.PostParamsTotal),
		CookieParamsTotal:          int(f.CookieParamsTotal),
		IPAddress:                  f.IPAddress,
		RemoteAddr:                 f.HostPort,
		Tags:                       f.Tags,
		Payload:                    strings.Join(f.Payloads, ","),
		IsWebsocket:                f.IsWebsocket,
		WebsocketHash:              f.WebsocketHash,
		FromPlugin:                 f.FromPlugin,
		IsTooLargeResponse:         f.IsTooLargeResponse,
		TooLargeResponseBodyFile:   string(f.TooLargeResponseBodyFile),
		TooLargeResponseHeaderFile: string(f.TooLargeResponseHeaderFile),
		IsTooLargeRequest:          f.IsTooLargeRequest,
		TooLargeRequestBodyFile:    string(f.TooLargeRequestBodyFile),
		TooLargeRequestHeaderFile:  string(f.TooLargeRequestHeaderFile),
	}

	flow.Response = strconv.Quote(string(f.Response))
	flow.Request = strconv.Quote(string(f.Request))

	return flow
}

func applyHTTPFlowQueryDefaults(req *ypb.QueryHTTPFlowRequest) {
	if req == nil {
		return
	}
	if req.Pagination == nil {
		req.Pagination = &ypb.Paging{}
	}
	if req.Pagination.Page <= 0 {
		req.Pagination.Page = 1
	}
	if req.Pagination.Limit <= 0 {
		req.Pagination.Limit = 30
	}
	if strings.TrimSpace(req.Pagination.OrderBy) == "" {
		req.Pagination.OrderBy = "updated_at"
	}
	if strings.TrimSpace(req.Pagination.Order) == "" {
		req.Pagination.Order = "desc"
	}
	sourceType := strings.TrimSpace(req.SourceType)
	if sourceType == "" {
		req.SourceType = schema.HTTPFlow_SourceType_MITM
	} else if strings.EqualFold(sourceType, "all") {
		req.SourceType = ""
	}
}

func currentHTTPFlowProjectDB(s *MCPServer) *gorm.DB {
	if s == nil {
		return nil
	}
	if s.projectDBProvider != nil {
		return s.projectDBProvider()
	}
	return s.projectDB
}

func queryHTTPFlows(ctx context.Context, s *MCPServer, req *ypb.QueryHTTPFlowRequest) (*ypb.QueryHTTPFlowResponse, error) {
	db := currentHTTPFlowProjectDB(s)
	if db == nil {
		return s.grpcClient.QueryHTTPFlows(ctx, req)
	}
	paging, data, err := yakit.QueryHTTPFlow(db, req)
	if err != nil {
		return nil, err
	}
	rsp := &ypb.QueryHTTPFlowResponse{}
	if paging != nil {
		rsp.Total = int64(paging.TotalRecord)
		rsp.Pagination = &ypb.Paging{
			Page:    int64(paging.Page),
			Limit:   int64(paging.Limit),
			OrderBy: req.GetPagination().GetOrderBy(),
			Order:   req.GetPagination().GetOrder(),
		}
	}
	for _, flow := range data {
		if flow == nil {
			continue
		}
		item, err := grpcmodel.ToHTTPFlowGRPCModel(flow, req.GetFull())
		if err != nil {
			return nil, utils.Errorf("cannot convert httpflow failed: %s", err)
		}
		rsp.Data = append(rsp.Data, item)
	}
	return rsp, nil
}

func setTagForHTTPFlow(ctx context.Context, s *MCPServer, req *ypb.SetTagForHTTPFlowRequest) error {
	db := currentHTTPFlowProjectDB(s)
	if db == nil {
		_, err := s.grpcClient.SetTagForHTTPFlow(ctx, req)
		return err
	}
	if len(req.GetCheckTags()) > 0 {
		return utils.GormTransaction(db, func(tx *gorm.DB) error {
			for _, tag := range req.GetCheckTags() {
				if err := yakit.SaveSetTagForHTTPFlow(tx, tag.GetId(), tag.GetHash(), tag.GetTags()); err != nil {
					return err
				}
			}
			return nil
		})
	}
	return yakit.SaveSetTagForHTTPFlow(db, req.GetId(), req.GetHash(), req.GetTags())
}

func deleteHTTPFlows(ctx context.Context, s *MCPServer, req *ypb.DeleteHTTPFlowRequest) error {
	db := currentHTTPFlowProjectDB(s)
	if db == nil {
		_, err := s.grpcClient.DeleteHTTPFlows(ctx, req)
		return err
	}
	if req.GetDeleteAll() {
		yakit.DropWebsocketFlowTable(db)
		yakit.DropExtractedDataTable(db)
		grpcmodel.DropHTTPFlowCacheGRPCModelByFlow()
		return yakit.DeleteHTTPFlow(db, req)
	}

	queryDB := yakit.QueryWebsocketFlowsByHTTPFlowHash(db, req).Select([]string{"id", "websocket_hash", "hash"})
	var httpFlowHashes []string
	for flow := range yakit.YieldHTTPFlows(queryDB, ctx) {
		httpFlowHashes = append(httpFlowHashes, flow.Hash)
		grpcmodel.DeleteHTTPFlowCacheGRPCModel(flow)
	}
	if len(httpFlowHashes) > 0 {
		if err := utils.GormTransaction(db, func(tx *gorm.DB) error {
			for _, hash := range httpFlowHashes {
				if err := yakit.DeleteWebsocketFlowsByHTTPFlowHash(tx, hash); err != nil {
					return err
				}
			}
			return nil
		}); err != nil {
			return err
		}
		if err := utils.GormTransaction(db, func(tx *gorm.DB) error {
			for _, hash := range httpFlowHashes {
				if err := yakit.DeleteExtractedDataByTraceId(tx, hash); err != nil {
					return err
				}
			}
			return nil
		}); err != nil {
			return err
		}
	}
	return yakit.DeleteHTTPFlow(db, req)
}

func handleQueryHTTPFlows(s *MCPServer) server.ToolHandlerFunc {
	return func(
		ctx context.Context,
		request mcp.CallToolRequest,
	) (*mcp.CallToolResult, error) {
		var req ypb.QueryHTTPFlowRequest
		err := mapstructure.Decode(request.Params.Arguments, &req)
		if err != nil {
			return nil, utils.Wrap(err, "invalid argument")
		}
		applyHTTPFlowQueryDefaults(&req)
		rsp, err := queryHTTPFlows(ctx, s, &req)
		if err != nil {
			return nil, utils.Wrap(err, "failed to query HTTPFlows")
		}
		results := make([]*schema.HTTPFlow, 0, len(rsp.Data))
		for _, flow := range rsp.Data {
			if flow == nil {
				continue
			}
			results = append(results, ypbHTTPFlowToFriendlyHTTPFlow(flow))
		}

		dbCtx := buildCurrentDatabaseContext(ctx, s, "")
		projectName := "(default)"
		if dbCtx.CurrentProject != nil && dbCtx.CurrentProject.GetProjectName() != "" {
			projectName = dbCtx.CurrentProject.GetProjectName()
		}
		sourceType := req.GetSourceType()
		if sourceType == "" {
			sourceType = "all"
		}
		pagination := req.GetPagination()
		ret := map[string]any{
			"current_project":     projectName,
			"current_database":    dbCtx.CurrentProjectDBPath,
			"query_scope":         "current_project_http_flows",
			"flows":               results,
			"returned_count":      len(results),
			"total_matched_count": rsp.GetTotal(),
			"count_note":          "returned_count is the number of records in this response page; total_matched_count is the total number of records matching the effective_filter in the current project database.",
			"effective_filter": map[string]any{
				"source_type": sourceType,
				"page":        pagination.GetPage(),
				"limit":       pagination.GetLimit(),
				"order_by":    pagination.GetOrderBy(),
				"order":       pagination.GetOrder(),
			},
		}
		if len(results) == 0 {
			ret["hint"] = "No HTTP flows found in the current project database. Report current_project/current_database to the user and ask them to confirm that Yakit is using the intended project and that capture/MITM traffic has been written to it. Do not inspect risks, ports, or MITM rules as substitutes unless the user asks for those data types."
		}
		return NewCommonCallToolResult(ret)
	}
}

func handleSetTagForHTTPFlow(s *MCPServer) server.ToolHandlerFunc {
	return func(
		ctx context.Context,
		request mcp.CallToolRequest,
	) (*mcp.CallToolResult, error) {
		var req ypb.SetTagForHTTPFlowRequest
		err := mapstructure.Decode(request.Params.Arguments, &req)
		if err != nil {
			return nil, utils.Wrap(err, "invalid argument")
		}
		if err := setTagForHTTPFlow(ctx, s, &req); err != nil {
			return nil, utils.Wrap(err, "failed to set tag for httpflow(s)")
		}
		return NewCommonCallToolResult("set tag for httpflow(s) success")
	}
}

func handleDeleteHTTPFlows(s *MCPServer) server.ToolHandlerFunc {
	return func(
		ctx context.Context,
		request mcp.CallToolRequest,
	) (*mcp.CallToolResult, error) {
		var req ypb.DeleteHTTPFlowRequest
		err := mapstructure.Decode(request.Params.Arguments, &req)
		if err != nil {
			return nil, utils.Wrap(err, "invalid argument")
		}
		if err := deleteHTTPFlows(ctx, s, &req); err != nil {
			return nil, utils.Wrap(err, "failed to delete httpflow(s)")
		}
		return NewCommonCallToolResult("delete httpflow(s) success")
	}
}
