is_build_in_struct: true
libname: ldap
struct_name: crypto/tls.Config
description: ""
fields:
- structname: crypto/tls.Config
  name: Certificates
  param_alias: ""
  type_alias: ""
  description: ""
  relative_structname: crypto/tls.Certificate
  type_str: '[]tls.Certificate'
- structname: crypto/tls.Config
  name: CipherSuites
  param_alias: ""
  type_alias: ""
  description: ""
  type_str: '[]uint16'
- structname: crypto/tls.Config
  name: ClientAuth
  param_alias: ""
  type_alias: ""
  description: ""
  type_str: tls.ClientAuthType
- structname: crypto/tls.Config
  name: ClientCAs
  param_alias: ""
  type_alias: ""
  description: ""
  relative_structname: crypto/x509.CertPool
  type_str: '*x509.CertPool'
- structname: crypto/tls.Config
  name: ClientSessionCache
  param_alias: ""
  type_alias: ""
  description: ""
  type_str: tls.ClientSessionCache
- structname: crypto/tls.Config
  name: CurvePreferences
  param_alias: ""
  type_alias: ""
  description: ""
  type_str: '[]tls.CurveID'
- structname: crypto/tls.Config
  name: DynamicRecordSizingDisabled
  param_alias: ""
  type_alias: ""
  description: ""
  type_str: bool
- structname: crypto/tls.Config
  name: GetCertificate
  param_alias: ""
  type_alias: ""
  description: ""
  type_str: 'func (v1: *tls.ClientHelloInfo) return(*tls.Certificate, error) '
- structname: crypto/tls.Config
  name: GetClientCertificate
  param_alias: ""
  type_alias: ""
  description: ""
  type_str: 'func (v1: *tls.CertificateRequestInfo) return(*tls.Certificate, error) '
- structname: crypto/tls.Config
  name: GetConfigForClient
  param_alias: ""
  type_alias: ""
  description: ""
  type_str: 'func (v1: *tls.ClientHelloInfo) return(*tls.Config, error) '
- structname: crypto/tls.Config
  name: InsecureSkipVerify
  param_alias: ""
  type_alias: ""
  description: ""
  type_str: bool
- structname: crypto/tls.Config
  name: KeyLogWriter
  param_alias: ""
  type_alias: ""
  description: ""
  type_str: io.Writer
- structname: crypto/tls.Config
  name: MaxVersion
  param_alias: ""
  type_alias: ""
  description: ""
  type_str: uint16
- structname: crypto/tls.Config
  name: MinVersion
  param_alias: ""
  type_alias: ""
  description: ""
  type_str: uint16
- structname: crypto/tls.Config
  name: NameToCertificate
  param_alias: ""
  type_alias: ""
  description: ""
  relative_structname: crypto/tls.Certificate
  type_str: map[string]*tls.Certificate
- structname: crypto/tls.Config
  name: NextProtos
  param_alias: ""
  type_alias: ""
  description: ""
  type_str: '[]string'
- structname: crypto/tls.Config
  name: PreferServerCipherSuites
  param_alias: ""
  type_alias: ""
  description: ""
  type_str: bool
- structname: crypto/tls.Config
  name: Rand
  param_alias: ""
  type_alias: ""
  description: ""
  type_str: io.Reader
- structname: crypto/tls.Config
  name: Renegotiation
  param_alias: ""
  type_alias: ""
  description: ""
  type_str: tls.RenegotiationSupport
- structname: crypto/tls.Config
  name: RootCAs
  param_alias: ""
  type_alias: ""
  description: ""
  relative_structname: crypto/x509.CertPool
  type_str: '*x509.CertPool'
- structname: crypto/tls.Config
  name: ServerName
  param_alias: ""
  type_alias: ""
  description: ""
  type_str: string
- structname: crypto/tls.Config
  name: SessionTicketKey
  param_alias: ""
  type_alias: ""
  description: ""
  type_str: '[32]uint8'
- structname: crypto/tls.Config
  name: SessionTicketsDisabled
  param_alias: ""
  type_alias: ""
  description: ""
  type_str: bool
- structname: crypto/tls.Config
  name: Time
  param_alias: ""
  type_alias: ""
  description: ""
  type_str: 'func () return(time.Time) '
- structname: crypto/tls.Config
  name: VerifyConnection
  param_alias: ""
  type_alias: ""
  description: ""
  type_str: 'func (v1: tls.ConnectionState) return(error) '
- structname: crypto/tls.Config
  name: VerifyPeerCertificate
  param_alias: ""
  type_alias: ""
  description: ""
  type_str: 'func (v1: [][]uint8, v2: [][]*x509.Certificate) return(error) '
methods:
- ptr: true
  description: ""
  structname: crypto/tls.Config
  name: BuildNameToCertificate
  relative_struct_name: []
- ptr: true
  description: ""
  structname: crypto/tls.Config
  name: Clone
  returns:
  - name: r0
    param_alias: ""
    type_alias: ""
    description: ""
    type_str: '*tls.Config'
  relative_struct_name: []
- ptr: true
  description: ""
  structname: crypto/tls.Config
  name: SetSessionTicketKeys
  params:
  - name: v2
    param_alias: ""
    type_alias: ""
    description: ""
    type_str: '[][32]uint8'
  relative_struct_name: []
ptr_methods: []
