package schema

import (
	"encoding/json"
	"fmt"
	"strconv"
	"strings"
	"time"

	"github.com/yaklang/yaklang/common/yakgrpc/ypb"

	"github.com/yaklang/yaklang/common/yak/yaklib/codec"

	"github.com/jinzhu/gorm"
	"github.com/yaklang/yaklang/common/utils"
)

type AIAgentRuntimeType string

const (
	AIAgentRuntimeType_PlanAndExec AIAgentRuntimeType = "plan-exec"
	AIAgentRuntimeType_ReAct       AIAgentRuntimeType = "re-act"
	AIAgentRuntimeType_Unknown     AIAgentRuntimeType = ""
)

type AIAgentRuntime struct {
	gorm.Model

	Uuid              string `json:"uuid" gorm:"unique_index"`
	PersistentSession string `gorm:"index"`
	Name              string `json:"name"`
	Seq               int64  `json:"seq" gorm:"index"`

	TypeName       AIAgentRuntimeType `gorm:"index"`
	QuotedTimeline string             `json:"timeline"`

	QuotedUserInput string `json:"quoted_user_input"`
	ForgeName       string `json:"forge_name"`

	// semantic label for the session, generated by LiteForge from user input context
	SemanticLabel string `json:"semantic_label" gorm:"index"`
	// final working directory absolute path for artifacts
	WorkDir string `json:"work_dir"`

	// LoadedSkillNames stores comma-separated skill names that were loaded in this session.
	// Used to restore skills across conversations within the same persistent session.
	LoadedSkillNames string `json:"loaded_skill_names"`

	// RecentToolsCache stores JSON-serialized recently-used tool entries for directly_call_tool.
	// Persisted per persistent_session so that tools used in one conversation are available in the next.
	RecentToolsCache string `json:"recent_tools_cache"`

	// QuotedEvidence stores session-level evidence as quoted JSON (EvidenceStore).
	// Persisted per persistent_session so that observations survive across loops and conversations.
	QuotedEvidence string `json:"quoted_evidence"`
}

type AIAgentUserInputRecord struct {
	Round     int       `json:"round"`
	Timestamp time.Time `json:"timestamp"`
	UserInput string    `json:"user_input"`
}

func (a *AIAgentRuntime) GetTimeline() string {
	if a == nil {
		return ""
	}
	result, err := strconv.Unquote(a.QuotedTimeline)
	if err != nil {
		return a.QuotedTimeline
	}
	return result
}

func (a *AIAgentRuntime) GetEvidence() string {
	if a == nil {
		return ""
	}
	return strings.TrimSpace(string(codec.StrConvUnquoteForce(a.QuotedEvidence)))
}

func (a *AIAgentRuntime) GetUserInputHistory() []AIAgentUserInputRecord {
	if a == nil {
		return nil
	}

	raw := strings.TrimSpace(string(codec.StrConvUnquoteForce(a.QuotedUserInput)))
	if raw == "" || raw == "[]" {
		return nil
	}

	var history []AIAgentUserInputRecord
	if err := json.Unmarshal([]byte(raw), &history); err == nil && len(history) > 0 {
		fallbackTs := a.UpdatedAt
		if fallbackTs.IsZero() {
			fallbackTs = a.CreatedAt
		}
		for i := range history {
			if history[i].Round <= 0 {
				history[i].Round = i + 1
			}
			if history[i].Timestamp.IsZero() {
				history[i].Timestamp = fallbackTs
			}
		}
		return history
	}

	fallbackTs := a.UpdatedAt
	if fallbackTs.IsZero() {
		fallbackTs = a.CreatedAt
	}
	return []AIAgentUserInputRecord{{
		Round:     1,
		Timestamp: fallbackTs,
		UserInput: raw,
	}}
}

func QuoteUserInputHistory(history []AIAgentUserInputRecord) (string, error) {
	if len(history) == 0 {
		return codec.StrConvQuote(""), nil
	}
	payload, err := json.Marshal(history)
	if err != nil {
		return "", err
	}
	return codec.StrConvQuote(string(payload)), nil
}

func (a *AIAgentRuntime) GetUserInput() string {
	history := a.GetUserInputHistory()
	if len(history) == 0 {
		return strings.TrimSpace(string(codec.StrConvUnquoteForce(a.QuotedUserInput)))
	}
	return history[len(history)-1].UserInput
}

func (a *AIAgentRuntime) ToGRPC() *ypb.AITask {
	return &ypb.AITask{
		CoordinatorId: a.Uuid,
		Name:          a.Name,
		Seq:           a.Seq,
		UserInput:     a.GetUserInput(),
		ForgeName:     a.ForgeName,
	}
}

type AiCheckpointType string

const (
	AiCheckpointType_AIInteractive AiCheckpointType = "ai-request"
	AiCheckpointType_ToolCall      AiCheckpointType = "tool-call"
	AiCheckpointType_Review        AiCheckpointType = "review"
)

type AiCheckpoint struct {
	gorm.Model

	CoordinatorUuid    string           `json:"coordinator_uuid" gorm:"index"`
	Seq                int64            `json:"seq" gorm:"index"`
	Type               AiCheckpointType `json:"type" gorm:"index"`
	RequestQuotedJson  string           `json:"request_quoted_json"`
	ResponseQuotedJson string           `json:"response_quoted_json"`
	Finished           bool             `json:"finished"`

	Hash string `json:"hash" gorm:"unique_index"`
}

func (c *AiCheckpoint) CalcHash() string {
	return utils.CalcSha256(c.CoordinatorUuid, c.Seq, c.Type)
}

func (c *AiCheckpoint) BeforeSave() error {
	if c.Hash == "" {
		c.Hash = c.CalcHash()
	}

	switch c.Type {
	case AiCheckpointType_AIInteractive, AiCheckpointType_ToolCall, AiCheckpointType_Review:
		break
	default:
		return fmt.Errorf("invalid checkpoint type: %s", c.Type)
	}

	if c.Seq <= 0 {
		return fmt.Errorf("seq must be greater than 0")
	}

	if c.CoordinatorUuid == "" {
		return fmt.Errorf("coordinator_uuid must be set")
	}

	return nil
}

type AiProvider struct {
	gorm.Model

	WrapperName  string `json:"wrapper_name" gorm:"index"`
	ModelName    string `json:"model_name" gorm:"index"`
	TypeName     string `json:"type_name" gorm:"index"`
	DomainOrURL  string `json:"domain_or_url" gorm:"index"`
	APIKey       string `json:"api_key" gorm:"index"`
	NoHTTPS      bool   `json:"no_https"`
	ProviderMode        string `json:"provider_mode" gorm:"default:'chat'"` // Provider 模式: "chat" 或 "embedding"
	OptionalAllowReason string `json:"optional_allow_reason" gorm:"default:''"`

	// ActiveCacheControl 决定是否在路由到该 provider 之前主动给最末 system 消息
	// 注入 cache_control:{"type":"ephemeral"} baseline 标记。
	// 关键词: aibalance Provider ActiveCacheControl Flag, 显式缓存通用化, dashscope/anthropic ephemeral 缓存
	//
	// 取值语义 (与 RewriteMessagesForProviderInstance 对齐):
	//   - true  -> 该 provider 视为 cache-control aware: 客户端自带 cc 时 pass-through,
	//              客户端无 cc 时给最末 system 注入 ephemeral cc (与 model 名无关)
	//   - false -> 老路径兜底: tongyi+dashscope 白名单走显式缓存注入, 其它 provider strip cc
	//
	// 默认 false 是为了完全保留现有 tongyi+白名单 provider 行为, 不写 DB 迁移脚本。
	ActiveCacheControl bool `json:"active_cache_control" gorm:"default:false"`

	// 可用性指标
	SuccessCount  int64 `json:"success_count"`  // 成功请求总数
	FailureCount  int64 `json:"failure_count"`  // 失败请求总数
	TotalRequests int64 `json:"total_requests"` // 总请求数

	// 最后一次请求信息
	LastRequestTime   time.Time `json:"last_request_time"`   // 最后一次请求时间
	LastRequestStatus bool      `json:"last_request_status"` // 最后一次请求状态 (true=成功, false=失败)
	LastLatency       int64     `json:"last_latency"`        // 最后一次请求延迟 (毫秒)

	// 健康状态
	IsHealthy             bool      `json:"is_healthy"`                                    // 提供者是否健康
	HealthCheckTime       time.Time `json:"health_check_time"`                             // 最后一次健康检查时间
	IsFirstCheckCompleted bool      `json:"is_first_check_completed" gorm:"default:false"` // 首次健康检查是否完成

	// 工具调用兼容能力 (capability matrix v1, 仅 tool_calls 维度)
	// 关键词: aibalance Tool Calls Capability Matrix, ToolCallsRound1Mode, ToolCallsRound2Mode
	//
	// Round1 = 客户端首次带 tools=[...] 的请求 (让模型决定要不要调工具)
	// Round2 = 客户端发完整 round-trip 消息 (含 assistant.tool_calls + role=tool 回灌)
	//
	// 取值语义:
	//   ""        : unknown, 未 probe (新 provider 默认), server 走 auto-fallback (透传 + 空回检测 + react 重试)
	//   "native"  : 上游原生支持 OpenAI tool_calls 协议, 直接透传
	//   "react"   : 上游不识别 tool_calls, aibalance 在请求侧降级 (round1 tools 注入 system prompt / round2 flatten)
	//               + 响应侧反解析 [tool_call name=...]args[/tool_call] 文本回 OpenAI tool_calls 结构
	//
	// 兼容策略:
	//   - 老 113 个 provider 默认值全空, 行为完全不变 (走 unknown auto-fallback)
	//   - 运维通过 Portal 按钮 / cmd `capability probe-tools` 手动触发 probe 后落 DB
	//   - 环境变量 AIBALANCE_FLATTEN_TOOLCALLS_ALL / AIBALANCE_FLATTEN_TOOLCALLS_FOR_MODELS 仍是最高优先级
	ToolCallsRound1Mode string    `json:"tool_calls_round1_mode" gorm:"default:''"`
	ToolCallsRound2Mode string    `json:"tool_calls_round2_mode" gorm:"default:''"`
	ToolCallsProbeAt    time.Time `json:"tool_calls_probe_at"`
	ToolCallsProbeError string    `json:"tool_calls_probe_error" gorm:"default:''"`
}

type AiApiKeys struct {
	gorm.Model
	APIKey        string    `json:"api_key" gorm:"index"`
	AllowedModels string    `json:"allowed_models"`
	InputBytes    int64     `json:"input_bytes"`                // 输入字节数统计
	OutputBytes   int64     `json:"output_bytes"`               // 输出字节数统计
	UsageCount    int64     `json:"usage_count"`                // 使用次数统计
	SuccessCount  int64     `json:"success_count"`              // 成功请求数
	FailureCount  int64     `json:"failure_count"`              // 失败请求数
	LastUsedTime  time.Time `json:"last_used_time"`             // 上次使用时间
	Active        bool      `json:"active" gorm:"default:true"` // API Key 激活状态

	// Web Search 使用统计
	WebSearchCount int64 `json:"web_search_count" gorm:"default:0"` // Web Search 使用次数

	// 流量限制相关字段
	TrafficLimit       int64 `json:"traffic_limit" gorm:"default:0"`            // 流量限额(字节)，0表示不限制
	TrafficUsed        int64 `json:"traffic_used" gorm:"default:0"`             // 已使用流量(经倍数计算后)
	TrafficLimitEnable bool  `json:"traffic_limit_enable" gorm:"default:false"` // 是否启用流量限制

	// Token 维度限额（与字节维度并行，按上游 SSE 末帧 usage 经多维倍率加权后累加）
	// 关键词: AiApiKeys TokenLimit, Token 计费, 与字节计费并行
	TokenLimit       int64 `json:"token_limit" gorm:"default:0"`            // Token 限额(raw token)，0 表示不限制
	TokenUsed        int64 `json:"token_used" gorm:"default:0"`             // 已使用 Token (经四维倍率加权后)
	TokenLimitEnable bool  `json:"token_limit_enable" gorm:"default:false"` // 是否启用 Token 限制

	// Creator tracking (for OPS user audit)
	CreatedByOpsID   uint   `json:"created_by_ops_id" gorm:"index"`  // Creator OpsUser.ID (0 means admin created)
	CreatedByOpsName string `json:"created_by_ops_name" gorm:"index"` // Creator username
}

type LoginSession struct {
	gorm.Model

	SessionID string    `json:"session_id" gorm:"index"`
	ExpiresAt time.Time `json:"expires_at"`

	// User information for role-based access control
	UserID   uint   `json:"user_id" gorm:"index"`          // Associated user ID (0 for root admin)
	Username string `json:"username" gorm:"index"`         // Username for quick access
	UserRole string `json:"user_role" gorm:"default:'admin'"` // User role: admin/ops
}

// OpsUser represents an operations user
type OpsUser struct {
	gorm.Model

	Username     string `json:"username" gorm:"unique_index"`      // Username
	Password     string `json:"password"`                          // Password (bcrypt encrypted)
	OpsKey       string `json:"ops_key" gorm:"unique_index"`       // ops-{uuid} format key for API access
	Role         string `json:"role" gorm:"default:'ops'"`         // Role: admin/ops
	Active       bool   `json:"active" gorm:"default:true"`        // Whether the user is active
	DefaultLimit int64  `json:"default_limit" gorm:"default:52428800"` // Default traffic limit (50MB)
}

// OpsActionLog records operations user actions
type OpsActionLog struct {
	gorm.Model

	OperatorID   uint   `json:"operator_id" gorm:"index"`   // Operator user ID
	OperatorName string `json:"operator_name" gorm:"index"` // Operator username
	Action       string `json:"action" gorm:"index"`        // Action type: create_api_key, reset_ops_key, change_password
	TargetType   string `json:"target_type"`                // Target type: api_key, ops_user
	TargetID     string `json:"target_id"`                  // Target ID
	Detail       string `json:"detail" gorm:"type:text"`    // Action detail (JSON)
	IPAddress    string `json:"ip_address"`                 // Client IP address
}

// AiBalanceRateLimitConfig stores global rate-limit configuration for AIBalance (singleton row, ID=1)
type AiBalanceRateLimitConfig struct {
	gorm.Model

	DefaultRPM          int64  `json:"default_rpm" gorm:"default:600"`         // Global default RPM per API key, default 600
	FreeUserDelaySec    int64  `json:"free_user_delay_sec" gorm:"default:3"`   // Pre-call delay (seconds) for free users, actual delay is N~2N random
	ModelRPMOverrides   string `json:"model_rpm_overrides" gorm:"type:text"`   // JSON map: {"model-name": rpm_int, ...}
	ModelDelayOverrides string `json:"model_delay_overrides" gorm:"type:text"` // JSON map: {"model-name": delay_sec_int, ...}, only applies to free users

	// 免费用户日 Token 限额相关字段
	// 关键词: 免费用户 Token 日限额, 全局共享池, 模型级覆盖, 模型豁免
	FreeUserTokenLimitM            int64  `json:"free_user_token_limit_m" gorm:"default:1200"` // 免费用户全局共享日 Token 限额，单位 M tokens，默认 1200M
	FreeUserTokenModelOverrides    string `json:"free_user_token_model_overrides" gorm:"type:text"` // JSON map: {"model": {"limit_m": int, "exempt": bool}}; exempt=true 表示该 -free 模型不计费
}

func (a *AiBalanceRateLimitConfig) TableName() string {
	return "ai_balance_rate_limit_configs"
}

// WebSearchConfig stores global configuration for web search (singleton row, ID=1)
type WebSearchConfig struct {
	gorm.Model

	Proxy                  string `json:"proxy"`                      // Global proxy for all web search requests
	AllowFreeUserWebSearch bool   `json:"allow_free_user_web_search"` // Allow free users (Trace-ID only, no API key) to use web-search
	TotalWebSearchRequests int64  `json:"total_web_search_requests"`  // Persistent cumulative web-search request count (survives restarts)
}

func (w *WebSearchConfig) TableName() string {
	return "web_search_configs"
}

// WebSearchApiKey stores API keys for web search providers (Brave, Tavily, ChatGLM, Bocha, Unifuncs)
type WebSearchApiKey struct {
	gorm.Model

	SearcherType string `json:"searcher_type" gorm:"index"` // "brave", "tavily", "chatglm", "bocha" or "unifuncs"
	APIKey       string `json:"api_key"`
	BaseURL      string `json:"base_url"`                     // Optional custom base URL
	Proxy        string `json:"proxy"`                        // Optional proxy
	Active       bool   `json:"active" gorm:"default:true"`   // Whether the key is active

	// Statistics
	SuccessCount         int64     `json:"success_count"`
	FailureCount         int64     `json:"failure_count"`
	ConsecutiveFailures  int64     `json:"consecutive_failures"`  // Reset to 0 on success, incremented on failure
	TotalRequests        int64     `json:"total_requests"`
	LastUsedTime         time.Time `json:"last_used_time"`
	LastLatency          int64     `json:"last_latency"` // Milliseconds
	IsHealthy            bool      `json:"is_healthy" gorm:"default:true"`
}

// AmapConfig stores global configuration for Amap API proxy (singleton row, ID=1)
type AmapConfig struct {
	gorm.Model

	AllowFreeUserAmap  bool  `json:"allow_free_user_amap"`  // Allow free users (TOTP only) to use amap proxy
	TotalAmapRequests  int64 `json:"total_amap_requests"`   // Persistent cumulative amap request count (survives restarts)
}

func (a *AmapConfig) TableName() string {
	return "amap_configs"
}

// AmapApiKey stores API keys for Amap (Gaode Maps) API proxy
type AmapApiKey struct {
	gorm.Model

	APIKey string `json:"api_key"`
	Active bool   `json:"active" gorm:"default:true"` // Whether the key is active

	// Health check
	IsHealthy       bool      `json:"is_healthy" gorm:"default:true"`
	HealthCheckTime time.Time `json:"health_check_time"` // Last health check time
	LastCheckError  string    `json:"last_check_error"`  // Last check error message, empty means success

	// Statistics
	SuccessCount        int64     `json:"success_count"`
	FailureCount        int64     `json:"failure_count"`
	ConsecutiveFailures int64     `json:"consecutive_failures"` // Reset to 0 on success, incremented on failure
	TotalRequests       int64     `json:"total_requests"`
	LastUsedTime        time.Time `json:"last_used_time"`
	LastLatency         int64     `json:"last_latency"` // Milliseconds
}

func (a *AmapApiKey) TableName() string {
	return "amap_api_keys"
}

// AiProviderHealthRecord stores historical health check results for uptime tracking
type AiProviderHealthRecord struct {
	gorm.Model

	ProviderID  uint      `json:"provider_id" gorm:"index"`
	WrapperName string    `json:"wrapper_name" gorm:"index"`
	IsHealthy   bool      `json:"is_healthy"`
	LatencyMs   int64     `json:"latency_ms"`
	CheckTime   time.Time `json:"check_time" gorm:"index"`
	ErrorMessage string   `json:"error_message" gorm:"type:text"`
}

func (a *AiProviderHealthRecord) TableName() string {
	return "ai_provider_health_records"
}

// AiDailyCacheStat 是 aibalance 每日「细粒度上游 token 用量与缓存命中」聚合行。
// 主键唯一约束 (date + wrapper_name + model_name + provider_type + provider_domain + api_key_hash)
// 由 RecordDailyCacheStats 用 UPSERT (gorm.Expr + ?) 累加。
// 100 天前的记录由 cleanup_scheduler 每天 0:01 删除，避免 SQLite 膨胀。
// 关键词: ai_daily_cache_stats, cached_tokens 持久化, aibalance 缓存命中比例
type AiDailyCacheStat struct {
	gorm.Model

	Date             string `json:"date" gorm:"size:10;unique_index:idx_cache_unique;index:idx_cache_date;not null"`
	WrapperName      string `json:"wrapper_name" gorm:"size:128;unique_index:idx_cache_unique;not null"`
	ModelName        string `json:"model_name" gorm:"size:128;unique_index:idx_cache_unique;not null"`
	ProviderTypeName string `json:"provider_type_name" gorm:"size:64;unique_index:idx_cache_unique;not null"`
	ProviderDomain   string `json:"provider_domain" gorm:"size:255;unique_index:idx_cache_unique;not null"`
	APIKeyHash       string `json:"api_key_hash" gorm:"size:32;unique_index:idx_cache_unique;not null"`
	APIKeyShrink     string `json:"api_key_shrink" gorm:"size:32;not null"`

	RequestCount     int64 `json:"request_count"`
	PromptTokens     int64 `json:"prompt_tokens"`
	CompletionTokens int64 `json:"completion_tokens"`
	TotalTokens      int64 `json:"total_tokens"`
	CachedTokens     int64 `json:"cached_tokens"`
}

func (a *AiDailyCacheStat) TableName() string {
	return "ai_daily_cache_stats"
}

// AiDailyUserSeen 是 aibalance 每日「客户端身份指纹去重」表。
// 一行 = 当天某 source_kind 下首次出现的 user_hash 指纹（INSERT IGNORE 重复不增行）。
// source_kind 取 "api_key" / "free_trace" / "free_ip" 三类。
// QueryDAU60Days 用 GROUP BY date,source_kind 统计 COUNT(DISTINCT user_hash)。
// 100 天前记录由 cleanup_scheduler 删除；同时 RecordDailyUserSeen 内置
// 1,000,000 行/天/source_kind 的硬上限做 DB 防爆。
// 关键词: ai_daily_user_seen, DAU 去重指纹, 防爆 cap
type AiDailyUserSeen struct {
	gorm.Model

	Date       string    `json:"date" gorm:"size:10;unique_index:idx_seen_unique;index:idx_seen_date;not null"`
	SourceKind string    `json:"source_kind" gorm:"size:16;unique_index:idx_seen_unique;not null"`
	UserHash   string    `json:"user_hash" gorm:"size:32;unique_index:idx_seen_unique;not null"`
	LastSeenAt time.Time `json:"last_seen_at"`
}

func (a *AiDailyUserSeen) TableName() string {
	return "ai_daily_user_seen"
}

// AiDailySummary 是 aibalance 每日「极轻量聚合快照」表。
// 一天一行（Date 唯一），由内存 atomic 累加 + 后台 30s tick flush，
// 永久保留（每天 1 行，年增长 365 行，长期可忽略）。
// 关键词: ai_daily_summary, 每日聚合快照, 内存 atomic flush
type AiDailySummary struct {
	gorm.Model

	Date             string `json:"date" gorm:"size:10;unique_index;not null"`
	TotalRequests    int64  `json:"total_requests"`
	PromptTokens     int64  `json:"prompt_tokens"`
	CompletionTokens int64  `json:"completion_tokens"`
	CachedTokens     int64  `json:"cached_tokens"`
}

func (a *AiDailySummary) TableName() string {
	return "ai_daily_summary"
}

// FreeUserDailyTokenUsage 持久化免费用户「每日 Token 已用量」聚合行。
// 一行 = (date, model_name) 唯一；model_name == "" 表示「全局共享池」。
// 跨日由首次访问时 Date != today 触发归零（轻量、无定时任务）。
// 关键词: free_user_daily_token_usage, 免费 Token 限额, 全局/模型桶
type FreeUserDailyTokenUsage struct {
	gorm.Model

	Date       string `json:"date" gorm:"size:10;unique_index:idx_free_token;not null"`
	ModelName  string `json:"model_name" gorm:"size:128;unique_index:idx_free_token;not null"`
	TokensUsed int64  `json:"tokens_used"`
}

func (a *FreeUserDailyTokenUsage) TableName() string {
	return "free_user_daily_token_usage"
}

// AIMemoryEntity 存储AI记忆条目
type AIMemoryEntity struct {
	gorm.Model

	// 记忆条目唯一标识
	MemoryID string `json:"memory_id" gorm:"unique_index;not null"`

	// 会话ID，关联到特定的AI会话
	SessionID string `json:"session_id" gorm:"index;not null"`

	// 记忆内容
	Content string `json:"content" gorm:"type:text;not null"`

	// 领域标签，用于分类和过滤
	Tags StringArray `json:"tags" gorm:"type:text"`

	// 潜在问题列表，用于RAG检索
	PotentialQuestions StringArray `json:"potential_questions" gorm:"type:text"`

	// C.O.R.E. P.A.C.T. Framework 评分 (0.0-1.0)
	C_Score float64 `json:"c_score"` // Connectivity Score 关联度
	O_Score float64 `json:"o_score"` // Origin Score 来源与确定性
	R_Score float64 `json:"r_score"` // Relevance Score 相关性
	E_Score float64 `json:"e_score"` // Emotion Score 情感
	P_Score float64 `json:"p_score"` // Preference Score 个人偏好
	A_Score float64 `json:"a_score"` // Actionability Score 可操作性
	T_Score float64 `json:"t_score"` // Temporality Score 时效性

	// C.O.R.E. P.A.C.T. 向量，用于快速过滤和排序
	CorePactVector FloatArray `json:"core_pact_vector" gorm:"type:text"`
}

func (a *AIMemoryEntity) TableName() string {
	return "ai_memory_entities_v1"
}

func (a *AIMemoryEntity) BeforeSave() error {
	if a.MemoryID == "" {
		return utils.Errorf("memory_id must be set")
	}
	if a.SessionID == "" {
		return utils.Errorf("session_id must be set")
	}
	if a.Content == "" {
		return utils.Errorf("content must be set")
	}
	return nil
}

func (a *AIMemoryEntity) QuestionHashID(question string) string {
	if a == nil {
		return ""
	}
	question = strings.TrimSpace(question)
	if a.MemoryID == "" || question == "" {
		return ""
	}
	return fmt.Sprintf("%s-%s", a.MemoryID, utils.CalcMd5(question))
}

func (a *AIMemoryEntity) DocumentQuestionHashIDs() []string {
	if a == nil || len(a.PotentialQuestions) == 0 {
		return nil
	}
	ids := make([]string, 0, len(a.PotentialQuestions))
	for _, q := range a.PotentialQuestions {
		id := a.QuestionHashID(q)
		if id == "" {
			continue
		}
		ids = append(ids, id)
	}
	return ids
}
