package yso

const (
	RuntimeExecClass               = "RuntimeExec"
	ProcessBuilderExecClass        = "ProcessBuilderExec"
	ProcessImplExecClass           = "ProcessImplExec"
	DNSlogClass                    = "DNSLog"
	SpringEchoClass                = "SpringEcho"
	AutoEchoClass                  = "SpringEcho"
	ModifyTomcatMaxHeaderSizeClass = "ModifyTomcatMaxHeaderSize"
	EmptyClassInTemplate           = "EmptyClassInTemplate"
	TcpReverseClass                = "TcpReverse"
	TcpReverseShellClass           = "TcpReverseShell"
	TomcatEchoClass                = "TomcatEcho"
	BytesClass                     = "TemplateImplClassLoader"
	MultiEchoClass                 = "MultiEcho"
	HeaderEchoClass                = "HeaderEcho"
	SleepClass                     = "Sleep"
)
const (
	BeanShell1GadgetName              = "BeanShell1"
	CommonsCollections1GadgetName     = "CommonsCollections1"
	CommonsCollections5GadgetName     = "CommonsCollections5"
	CommonsCollections6GadgetName     = "CommonsCollections6"
	CommonsCollections7GadgetName     = "CommonsCollections7"
	CommonsCollectionsK3GadgetName    = "CommonsCollectionsK3"
	CommonsCollectionsK4GadgetName    = "CommonsCollectionsK4"
	Groovy1GadgetName                 = "Groovy1"
	Click1GadgetName                  = "Click1"
	CommonsBeanutils1GadgetName       = "CommonsBeanutils1"
	CommonsBeanutils183NOCCGadgetName = "CommonsBeanutils183NOCC"
	CommonsBeanutils192NOCCGadgetName = "CommonsBeanutils192NOCC"
	CommonsCollections2GadgetName     = "CommonsCollections2"
	CommonsCollections3GadgetName     = "CommonsCollections3"
	CommonsCollections4GadgetName     = "CommonsCollections4"
	CommonsCollections8GadgetName     = "CommonsCollections8"
	CommonsCollectionsK1GadgetName    = "CommonsCollectionsK1"
	CommonsCollectionsK2GadgetName    = "CommonsCollectionsK2"
	JBossInterceptors1GadgetName      = "JBossInterceptors1"
	JSON1GadgetName                   = "JSON1"
	JavassistWeld1GadgetName          = "JavassistWeld1"
	Jdk7u21GadgetName                 = "Jdk7u21"
	Jdk8u20GadgetName                 = "Jdk8u20"
	URLDNS                            = "URLDNS"
	FindGadgetByDNS                   = "FindGadgetByDNS"
	FindClassByBomb                   = "FindClassByBomb"
)
