# https://taskfile.dev

version: '3'

includes:
  yak: 
    taskfile: ./yak_Taskfile.yml
    dir: ./
  antlr: 
    taskfile: ./common/yak/antlr_Taskfile.yml
    dir: ./common/yak
  generate: 
    taskfile: ./common/generate_Taskfile.yml
    dir: ./common

tasks:
  yak_build:
    desc: Build Yaklang
    vars:
      binary: '{{if eq OS "windows"}}yak.exe{{else}}yak{{end}}'
    cmds:
      - |
        go build -ldflags "-s -w" -o {{ .binary }} ./common/yak/cmd/yak.go
    generates:
      - '{{ .binary }}'
    aliases: [yb]
  yak_grpc:
    desc: Run the gRPC server on port 8087
    cmds:
      - go run common/yak/cmd/yak.go grpc
    aliases: [yg]
  vulinbox_build:
    desc: Build vulinbox
    cmds:
      - go build -ldflags "-linkmode external -extldflags '-static' -s -w -X 'main.goVersion=$(go version)' -X 'main.gitHash=$(git show -s --format=%H)' -X 'main.buildTime=$(git show -s --format=%cd)'" -o "./vulinbox_$(go env "GOOS")_$( go env "GOARCH"){{if eq OS "windows"}}.exe{{end}}" common/vulinboxrunner/vulinbox.go
    aliases: [vb]
  gen_proto:
    silent: true
    desc: Generate protobuf files
    cmds:
      - ./scripts/gen-yakgrpc.sh
    aliases: [gp,proto]
  install_dep:
    silent: true
    desc: Install golang dependencies and protoc
    cmds:
     - go mod tidy
     - go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.34.2
     - go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.3.0
     - echo "download protoc from https://github.com/protocolbuffers/protobuf/releases/tag/v27.3"