// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.4
// source: common/notify/drivers/feishu/pbbp2.proto

package feishu

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Header struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_common_notify_drivers_feishu_pbbp2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_common_notify_drivers_feishu_pbbp2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_common_notify_drivers_feishu_pbbp2_proto_rawDescGZIP(), []int{0}
}

func (x *Header) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Header) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Frame is the binary envelope used by Feishu long connections.
// Field numbers intentionally match the legacy proto2/gogo schema.
type Frame struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SeqID           uint64                 `protobuf:"varint,1,opt,name=SeqID,proto3" json:"SeqID,omitempty"`
	LogID           uint64                 `protobuf:"varint,2,opt,name=LogID,proto3" json:"LogID,omitempty"`
	Service         int32                  `protobuf:"varint,3,opt,name=service,proto3" json:"service,omitempty"`
	Method          int32                  `protobuf:"varint,4,opt,name=method,proto3" json:"method,omitempty"`
	Headers         []*Header              `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty"`
	PayloadEncoding string                 `protobuf:"bytes,6,opt,name=payload_encoding,json=payloadEncoding,proto3" json:"payload_encoding,omitempty"`
	PayloadType     string                 `protobuf:"bytes,7,opt,name=payload_type,json=payloadType,proto3" json:"payload_type,omitempty"`
	Payload         []byte                 `protobuf:"bytes,8,opt,name=payload,proto3" json:"payload,omitempty"`
	LogIDNew        string                 `protobuf:"bytes,9,opt,name=LogIDNew,proto3" json:"LogIDNew,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_common_notify_drivers_feishu_pbbp2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_common_notify_drivers_feishu_pbbp2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_common_notify_drivers_feishu_pbbp2_proto_rawDescGZIP(), []int{1}
}

func (x *Frame) GetSeqID() uint64 {
	if x != nil {
		return x.SeqID
	}
	return 0
}

func (x *Frame) GetLogID() uint64 {
	if x != nil {
		return x.LogID
	}
	return 0
}

func (x *Frame) GetService() int32 {
	if x != nil {
		return x.Service
	}
	return 0
}

func (x *Frame) GetMethod() int32 {
	if x != nil {
		return x.Method
	}
	return 0
}

func (x *Frame) GetHeaders() []*Header {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Frame) GetPayloadEncoding() string {
	if x != nil {
		return x.PayloadEncoding
	}
	return ""
}

func (x *Frame) GetPayloadType() string {
	if x != nil {
		return x.PayloadType
	}
	return ""
}

func (x *Frame) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Frame) GetLogIDNew() string {
	if x != nil {
		return x.LogIDNew
	}
	return ""
}

var File_common_notify_drivers_feishu_pbbp2_proto protoreflect.FileDescriptor

const file_common_notify_drivers_feishu_pbbp2_proto_rawDesc = "" +
	"\n" +
	"(common/notify/drivers/feishu/pbbp2.proto\x12\x05pbbp2\"0\n" +
	"\x06Header\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x92\x02\n" +
	"\x05Frame\x12\x14\n" +
	"\x05SeqID\x18\x01 \x01(\x04R\x05SeqID\x12\x14\n" +
	"\x05LogID\x18\x02 \x01(\x04R\x05LogID\x12\x18\n" +
	"\aservice\x18\x03 \x01(\x05R\aservice\x12\x16\n" +
	"\x06method\x18\x04 \x01(\x05R\x06method\x12'\n" +
	"\aheaders\x18\x05 \x03(\v2\r.pbbp2.HeaderR\aheaders\x12)\n" +
	"\x10payload_encoding\x18\x06 \x01(\tR\x0fpayloadEncoding\x12!\n" +
	"\fpayload_type\x18\a \x01(\tR\vpayloadType\x12\x18\n" +
	"\apayload\x18\b \x01(\fR\apayload\x12\x1a\n" +
	"\bLogIDNew\x18\t \x01(\tR\bLogIDNewB@Z>github.com/yaklang/yaklang/common/notify/drivers/feishu;feishub\x06proto3"

var (
	file_common_notify_drivers_feishu_pbbp2_proto_rawDescOnce sync.Once
	file_common_notify_drivers_feishu_pbbp2_proto_rawDescData []byte
)

func file_common_notify_drivers_feishu_pbbp2_proto_rawDescGZIP() []byte {
	file_common_notify_drivers_feishu_pbbp2_proto_rawDescOnce.Do(func() {
		file_common_notify_drivers_feishu_pbbp2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_notify_drivers_feishu_pbbp2_proto_rawDesc), len(file_common_notify_drivers_feishu_pbbp2_proto_rawDesc)))
	})
	return file_common_notify_drivers_feishu_pbbp2_proto_rawDescData
}

var file_common_notify_drivers_feishu_pbbp2_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_notify_drivers_feishu_pbbp2_proto_goTypes = []any{
	(*Header)(nil), // 0: pbbp2.Header
	(*Frame)(nil),  // 1: pbbp2.Frame
}
var file_common_notify_drivers_feishu_pbbp2_proto_depIdxs = []int32{
	0, // 0: pbbp2.Frame.headers:type_name -> pbbp2.Header
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_common_notify_drivers_feishu_pbbp2_proto_init() }
func file_common_notify_drivers_feishu_pbbp2_proto_init() {
	if File_common_notify_drivers_feishu_pbbp2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_notify_drivers_feishu_pbbp2_proto_rawDesc), len(file_common_notify_drivers_feishu_pbbp2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_notify_drivers_feishu_pbbp2_proto_goTypes,
		DependencyIndexes: file_common_notify_drivers_feishu_pbbp2_proto_depIdxs,
		MessageInfos:      file_common_notify_drivers_feishu_pbbp2_proto_msgTypes,
	}.Build()
	File_common_notify_drivers_feishu_pbbp2_proto = out.File
	file_common_notify_drivers_feishu_pbbp2_proto_goTypes = nil
	file_common_notify_drivers_feishu_pbbp2_proto_depIdxs = nil
}
