# LibVNCServer (different stack from TigerVNC / x11vnc).
#   docker build -t yak-vnc-libvnc -f Dockerfile.libvnc .
#   docker run -d --rm -p 5900:5900 -e VNC_PASSWORD=LibVncPass! yak-vnc-libvnc
FROM alpine:3.20
RUN apk add --no-cache gcc musl-dev libvncserver-dev
COPY libvnc-login.c /tmp/libvnc-login.c
RUN gcc -O2 -o /usr/local/bin/libvnc-login /tmp/libvnc-login.c -lvncserver \
    && apk del gcc musl-dev \
    && rm -f /tmp/libvnc-login.c
EXPOSE 5900
ENTRYPOINT ["/usr/local/bin/libvnc-login"]
