// Generated from CSharpParser.g4 keyword alternatives: each keyword is used as an attribute target.
// This exercises the reachable parser rule `keyword` (via attribute_target).
using System;
namespace KeywordAttrTargets {
    [abstract: Obsolete] class KW_0 { }
    [as: Obsolete] class KW_1 { }
    [base: Obsolete] class KW_2 { }
    [bool: Obsolete] class KW_3 { }
    [break: Obsolete] class KW_4 { }
    [byte: Obsolete] class KW_5 { }
    [case: Obsolete] class KW_6 { }
    [catch: Obsolete] class KW_7 { }
    [char: Obsolete] class KW_8 { }
    [checked: Obsolete] class KW_9 { }
    [class: Obsolete] class KW_10 { }
    [const: Obsolete] class KW_11 { }
    [continue: Obsolete] class KW_12 { }
    [decimal: Obsolete] class KW_13 { }
    [default: Obsolete] class KW_14 { }
    [delegate: Obsolete] class KW_15 { }
    [do: Obsolete] class KW_16 { }
    [double: Obsolete] class KW_17 { }
    [else: Obsolete] class KW_18 { }
    [enum: Obsolete] class KW_19 { }
    [event: Obsolete] class KW_20 { }
    [explicit: Obsolete] class KW_21 { }
    [extern: Obsolete] class KW_22 { }
    [false: Obsolete] class KW_23 { }
    [finally: Obsolete] class KW_24 { }
    [fixed: Obsolete] class KW_25 { }
    [float: Obsolete] class KW_26 { }
    [for: Obsolete] class KW_27 { }
    [foreach: Obsolete] class KW_28 { }
    [goto: Obsolete] class KW_29 { }
    [if: Obsolete] class KW_30 { }
    [implicit: Obsolete] class KW_31 { }
    [in: Obsolete] class KW_32 { }
    [int: Obsolete] class KW_33 { }
    [interface: Obsolete] class KW_34 { }
    [internal: Obsolete] class KW_35 { }
    [is: Obsolete] class KW_36 { }
    [lock: Obsolete] class KW_37 { }
    [long: Obsolete] class KW_38 { }
    [namespace: Obsolete] class KW_39 { }
    [new: Obsolete] class KW_40 { }
    [null: Obsolete] class KW_41 { }
    [object: Obsolete] class KW_42 { }
    [operator: Obsolete] class KW_43 { }
    [out: Obsolete] class KW_44 { }
    [override: Obsolete] class KW_45 { }
    [params: Obsolete] class KW_46 { }
    [private: Obsolete] class KW_47 { }
    [protected: Obsolete] class KW_48 { }
    [public: Obsolete] class KW_49 { }
    [readonly: Obsolete] class KW_50 { }
    [ref: Obsolete] class KW_51 { }
    [return: Obsolete] class KW_52 { }
    [sbyte: Obsolete] class KW_53 { }
    [sealed: Obsolete] class KW_54 { }
    [short: Obsolete] class KW_55 { }
    [sizeof: Obsolete] class KW_56 { }
    [stackalloc: Obsolete] class KW_57 { }
    [static: Obsolete] class KW_58 { }
    [string: Obsolete] class KW_59 { }
    [struct: Obsolete] class KW_60 { }
    [switch: Obsolete] class KW_61 { }
    [this: Obsolete] class KW_62 { }
    [throw: Obsolete] class KW_63 { }
    [true: Obsolete] class KW_64 { }
    [try: Obsolete] class KW_65 { }
    [typeof: Obsolete] class KW_66 { }
    [uint: Obsolete] class KW_67 { }
    [ulong: Obsolete] class KW_68 { }
    [unchecked: Obsolete] class KW_69 { }
    [unsafe: Obsolete] class KW_70 { }
    [ushort: Obsolete] class KW_71 { }
    [using: Obsolete] class KW_72 { }
    [virtual: Obsolete] class KW_73 { }
    [void: Obsolete] class KW_74 { }
    [volatile: Obsolete] class KW_75 { }
    [while: Obsolete] class KW_76 { }
}
