package bin_parser

import "testing"

func TestP1FailPaths(t *testing.T) {
	cases := []struct {
		rule string
		keys []string
		data []byte
	}{
		{"vxlan", []string{"VXLAN"}, nil},
		{"vxlan", []string{"VXLAN"}, []byte{0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}},
		{"l2tp", []string{"L2TP"}, nil},
		{"l2tp", []string{"L2TP"}, []byte{0x00, 0x01}},
		{"ike", []string{"IKE"}, nil},
		{"ike", []string{"IKE"}, []byte{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x30}},
		{"openvpn", []string{"OpenVPN"}, nil},
		{"openvpn", []string{"OpenVPN"}, []byte{0x00}},
		{"wireguard", []string{"WireGuard"}, nil},
		{"wireguard", []string{"WireGuard"}, []byte{0x09, 0, 0, 0}},
		{"ospf", []string{"OSPF"}, nil},
		{"ospf", []string{"OSPF"}, []byte{0x01}},
		{"bgp", []string{"BGP"}, nil},
		{"bgp", []string{"BGP"}, []byte{0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x00, 0x12, 0x09}},
		{"rip", []string{"RIP"}, nil},
		{"rip", []string{"RIP"}, []byte{0x09, 0x02}},
		{"eigrp", []string{"EIGRP"}, nil},
		{"eigrp", []string{"EIGRP"}, []byte{0x01}},
		{"vrrp", []string{"VRRP"}, nil},
		{"vrrp", []string{"VRRP"}, []byte{0x11}},
		{"hsrp", []string{"HSRP"}, nil},
		{"hsrp", []string{"HSRP"}, []byte{0x01}},
		{"sctp", []string{"SCTP"}, nil},
		{"nbt_dg", []string{"NBTDG"}, nil},
		{"nbt_dg", []string{"NBTDG"}, []byte{0x01}},
		{"dhcpv6", []string{"DHCPv6"}, nil},
		{"dhcpv6", []string{"DHCPv6"}, []byte{0x99}},
		{"tftp", []string{"TFTP"}, nil},
		{"tftp", []string{"TFTP"}, []byte{0x00, 0x09}},
		{"syslog", []string{"Syslog"}, nil},
		{"syslog", []string{"Syslog"}, []byte("no-pri\n")},
		{"stun", []string{"STUN"}, nil},
		{"stun", []string{"STUN"}, []byte{0, 1, 0, 0, 0, 0, 0, 0}},
		{"sip", []string{"SIP"}, nil},
		{"sip", []string{"SIP"}, []byte("FOO sip:a SIP/2.0\r\n\r\n")},
		{"rtp", []string{"RTP"}, nil},
		{"rtp", []string{"RTP"}, []byte{0x00}},
		{"rtp", []string{"RTCP"}, []byte{0x80, 100}},
		{"socks4", []string{"SOCKS4"}, nil},
		{"socks4", []string{"SOCKS4"}, []byte{0x05, 0x01}},
		{"telnet", []string{"Telnet"}, nil},
		{"pop3", []string{"POP3"}, nil},
		{"pop3", []string{"POP3"}, []byte("NOPE x\r\n")},
		{"imap", []string{"IMAP"}, nil},
		{"imap", []string{"IMAP"}, []byte("a1 ZZ\r\n")},
		{"vnc", []string{"VNC"}, nil},
		{"vnc", []string{"VNC"}, []byte("HTTP/1.0\n")},
		{"mongodb", []string{"MongoDB"}, nil},
		{"mongodb", []string{"MongoDB"}, []byte{0x04, 0, 0, 0}},
		{"memcached", []string{"Memcached"}, nil},
		{"memcached", []string{"Memcached"}, []byte{0x00}},
		{"amqp", []string{"AMQP"}, nil},
		{"amqp", []string{"AMQP"}, []byte{9}},
		{"kafka", []string{"Kafka"}, nil},
		{"kafka", []string{"Kafka"}, []byte{0, 0, 0, 1}},
		{"jsonrpc", []string{"JSONRPC"}, nil},
		{"jsonrpc", []string{"JSONRPC"}, []byte("[]\n")},
		{"tacacs", []string{"TACACS"}, nil},
		{"tacacs", []string{"TACACS"}, []byte{0x10}},
		{"dtls", []string{"DTLS"}, nil},
		{"dtls", []string{"DTLS"}, []byte{0x16, 0x03, 0x03}},
		{"onc_rpc", []string{"ONCRPC"}, nil},
		{"onc_rpc", []string{"ONCRPC"}, []byte{0, 0, 0, 0, 0, 0, 0, 2}},
		{"ipmi", []string{"IPMI"}, nil},
		{"ipmi", []string{"IPMI"}, []byte{0x05}},
		{"bittorrent", []string{"BitTorrent"}, nil},
		{"bittorrent", []string{"BitTorrent"}, []byte{0x13, 'n', 'o'}},
		{"fastcgi", []string{"FastCGI"}, nil},
		{"fastcgi", []string{"FastCGI"}, []byte{0x02}},
		{"jdwp", []string{"JDWP"}, nil},
		{"jdwp", []string{"JDWP"}, []byte("not-handshake-")},
		{"php_ser", []string{"PHPSer"}, nil},
		{"php_ser", []string{"PHPSer"}, []byte{0x78, 0x3a, 0x31, 0x3b}},
		{"pickle", []string{"Pickle"}, nil},
		{"pickle", []string{"Pickle"}, []byte{0x00}},
		{"rmi", []string{"RMI"}, nil},
		{"rmi", []string{"RMI"}, []byte("JAVA")},
		{"thrift", []string{"Thrift"}, nil},
		{"thrift", []string{"Thrift"}, []byte{0x00, 0x00, 0x00, 0x01}},
		{"protobuf", []string{"Protobuf"}, nil},
		{"protobuf", []string{"Protobuf"}, []byte{0x07}},
		{"zabbix", []string{"Zabbix"}, nil},
		{"zabbix", []string{"Zabbix"}, []byte("XXXX")},
		{"hessian", []string{"Hessian"}, nil},
		{"hessian", []string{"Hessian"}, []byte{0x00}},
		{"rsync", []string{"Rsync"}, nil},
		{"rsync", []string{"Rsync"}, []byte("HELLO\n")},
		{"rtsp", []string{"RTSP"}, nil},
		{"rtsp", []string{"RTSP"}, []byte("FOO rtsp://x RTSP/1.0\r\n\r\n")},
		{"rtmp", []string{"RTMP"}, nil},
		{"rtmp", []string{"RTMP"}, []byte{0x01}},
		{"ftp_data", []string{"FTPData"}, nil},
		{"jenkins", []string{"Jenkins"}, nil},
		{"jenkins", []string{"Jenkins"}, []byte("hello\n")},
		{"salt", []string{"Salt"}, nil},
		{"salt", []string{"Salt"}, []byte{0, 0, 0, 0}},
		{"net_remoting", []string{"NetRemoting"}, nil},
		{"net_remoting", []string{"NetRemoting"}, []byte("HTTP")},
		{"application-layer.iiop", []string{"GIOP"}, nil},
		{"application-layer.iiop", []string{"GIOP"}, []byte("XXXX")},
		{"application-layer.t3", []string{"T3"}, nil},
		{"application-layer.t3", []string{"T3"}, []byte{0, 0, 0, 1}},
		{"application-layer.pptp", []string{"PPTP"}, nil},
		{"application-layer.pptp", []string{"PPTP"}, []byte{0, 12, 0, 1, 0, 0, 0, 0}},
		{"application-layer.ntp", []string{"NTP"}, nil},
		{"application-layer.ntp", []string{"NTP"}, []byte{0x00}},
		{"stp", []string{"STP"}, nil},
		{"stp", []string{"STP"}, []byte{0x00, 0x01}},
		{"lldp", []string{"LLDP"}, nil},
		{"cdp", []string{"CDP"}, nil},
		{"cdp", []string{"CDP"}, []byte{0x03}},
		{"pppoe", []string{"PPPoE"}, nil},
		{"pppoe", []string{"PPPoE"}, []byte{0x21}},
		{"igmp", []string{"IGMP"}, nil},
		{"igmp", []string{"IGMP"}, []byte{0x01}},
		{"ipsec", []string{"AH"}, nil},
		{"ipsec", []string{"ESP"}, nil},
		{"llc", []string{"LLC"}, nil},
		{"ieee_802_1ad", []string{"QinQ"}, nil},
		{"ieee_802_11", []string{"Dot11"}, nil},
		{"ieee_802_11", []string{"RSN"}, []byte{0x01}},
		{"linux_sll", []string{"LinuxSLL"}, nil},
		{"loopback", []string{"Loopback"}, nil},
		{"mpls", []string{"MPLS"}, nil},
		{"password_authentication_protocol", []string{"PAP"}, nil},
		{"challenge_handshake_authentication_protocol", []string{"CHAP"}, nil},
		{"link_control_protocol", []string{"LCP"}, nil},
		{"ppp", []string{"PPP"}, nil},
		{"generic_routing_encapsulation", []string{"GRE"}, nil},
		{"eapol", []string{"EAPOL"}, nil},
		{"application-layer.ber", []string{"BER Element"}, nil},
		{"application-layer.snmp", []string{"SNMPv3"}, nil},
		{"application-layer.snmp", []string{"SNMPv3"}, []byte{0x31, 0x03, 0x02, 0x01, 0x03}},
	}
	for _, tc := range cases {
		t.Run(tc.rule+"/"+tc.keys[0], func(t *testing.T) {
			parseMustFail(t, tc.data, tc.rule, tc.keys...)
		})
	}
}
