package bin_parser

import (
	"fmt"
	"testing"
)

type p1FailCase struct {
	rule string
	keys []string
	data []byte
	name string
}

var p1FailCases = []p1FailCase{
		{"internet_control_message_protocol", []string{"ICMP"}, nil, "empty"},
		{"internet_control_message_protocol", []string{"ICMP"}, []byte{0x08}, "trunc"},
		{"internet_control_message_protocol", []string{"ICMP"}, []byte{0x08, 0x00}, "trunc-hdr"},
		{"internet_control_message_protocol_v6", []string{"ICMPV6"}, nil, "empty"},
		{"internet_control_message_protocol_v6", []string{"ICMPV6"}, []byte{0x80}, "trunc"},
		{"internet_control_message_protocol_v6", []string{"ICMPV6"}, []byte{0x80, 0x00}, "trunc-hdr"},
		{"vxlan", []string{"VXLAN"}, nil, "empty"},
		{"vxlan", []string{"VXLAN"}, []byte{0x00}, "trunc"},
		{"vxlan", []string{"VXLAN"}, []byte{0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}, "no-i-flag"},
		{"l2tp", []string{"L2TP"}, nil, "empty"},
		{"l2tp", []string{"L2TP"}, []byte{0x00, 0x01}, "trunc"},
		{"l2tp", []string{"L2TP"}, []byte{0x00, 0x01, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, "bad-ver"},
		{"ike", []string{"IKE"}, nil, "empty"},
		{"ike", []string{"IKE"}, []byte{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0x30}, "bad-ver"},
		{"ike", []string{"IKE"}, make([]byte, 27), "trunc"},
		{"openvpn", []string{"OpenVPN"}, nil, "empty"},
		{"openvpn", []string{"OpenVPN"}, []byte{0x00}, "bad-op"},
		{"openvpn", []string{"OpenVPN"}, []byte{0x08}, "trunc"},
		{"wireguard", []string{"WireGuard"}, nil, "empty"},
		{"wireguard", []string{"WireGuard"}, []byte{0x09, 0, 0, 0}, "bad-type"},
		{"wireguard", []string{"WireGuard"}, []byte{0x01}, "trunc"},
		{"ospf", []string{"OSPF"}, nil, "empty"},
		{"ospf", []string{"OSPF"}, []byte{0x01}, "bad-ver"},
		{"ospf", []string{"OSPF"}, []byte{0x02, 0x09}, "bad-type"},
		{"bgp", []string{"BGP"}, nil, "empty"},
		{"bgp", []string{"BGP"}, []byte{0xff, 0xff}, "trunc"},
		{"bgp", []string{"BGP"}, append(bytesRepeat(0xff, 16), 0x00, 0x12, 0x09), "bad-type"},
		{"rip", []string{"RIP"}, nil, "empty"},
		{"rip", []string{"RIP"}, []byte{0x09, 0x02}, "bad-cmd"},
		{"rip", []string{"RIP"}, []byte{0x01, 0x09}, "bad-ver"},
		{"eigrp", []string{"EIGRP"}, nil, "empty"},
		{"eigrp", []string{"EIGRP"}, []byte{0x01}, "bad-ver"},
		{"eigrp", []string{"EIGRP"}, []byte{0x02}, "trunc"},
		{"vrrp", []string{"VRRP"}, nil, "empty"},
		{"vrrp", []string{"VRRP"}, []byte{0x11}, "bad-ver"},
		{"vrrp", []string{"VRRP"}, []byte{0x22}, "bad-type"},
		{"hsrp", []string{"HSRP"}, nil, "empty"},
		{"hsrp", []string{"HSRP"}, []byte{0x01}, "bad-ver"},
		{"hsrp", []string{"HSRP"}, []byte{0x00, 0x09}, "bad-op"},
		{"sctp", []string{"SCTP"}, nil, "empty"},
		{"sctp", []string{"SCTP"}, []byte{0x00}, "trunc"},
		{"sctp", []string{"SCTP"}, make([]byte, 11), "trunc-hdr"},
		{"nbt_dg", []string{"NBTDG"}, nil, "empty"},
		{"nbt_dg", []string{"NBTDG"}, []byte{0x01}, "bad-type"},
		{"nbt_dg", []string{"NBTDG"}, []byte{0x10}, "trunc"},
		{"dhcpv6", []string{"DHCPv6"}, nil, "empty"},
		{"dhcpv6", []string{"DHCPv6"}, []byte{0x99}, "bad-type"},
		{"dhcpv6", []string{"DHCPv6"}, []byte{0x01}, "trunc"},
		{"tftp", []string{"TFTP"}, nil, "empty"},
		{"tftp", []string{"TFTP"}, []byte{0x00, 0x09}, "bad-op"},
		{"tftp", []string{"TFTP"}, []byte{0x00}, "trunc"},
		{"syslog", []string{"Syslog"}, nil, "empty"},
		{"syslog", []string{"Syslog"}, []byte("no-pri\n"), "bad-pri"},
		{"syslog", []string{"Syslog"}, []byte("<>\n"), "empty-pri"},
		{"stun", []string{"STUN"}, nil, "empty"},
		{"stun", []string{"STUN"}, []byte{0, 1, 0, 0, 0, 0, 0, 0}, "bad-magic"},
		{"stun", []string{"STUN"}, []byte{0, 1}, "trunc"},
		{"sip", []string{"SIP"}, nil, "empty"},
		{"sip", []string{"SIP"}, []byte("FOO sip:a SIP/2.0\r\n\r\n"), "bad-method"},
		{"sip", []string{"SIP"}, []byte("INVITE"), "trunc"},
		{"sdp", []string{"SDP"}, nil, "sdp-empty"},
		{"sdp", []string{"SDP"}, []byte("x=0\r\n"), "sdp-bad"},
		{"sdp", []string{"SDP"}, []byte("v0\r\n"), "sdp-no-eq"},
		{"rtp", []string{"RTP"}, nil, "empty"},
		{"rtp", []string{"RTP"}, []byte{0x00}, "bad-ver"},
		{"rtp", []string{"RTP"}, []byte{0x80}, "trunc"},
		{"rtp", []string{"RTCP"}, []byte{0x80, 100}, "bad-pt"},
		{"rtp", []string{"RTCP"}, nil, "rtcp-empty"},
		{"rtp", []string{"RTCP"}, []byte{0x00, 200}, "rtcp-ver"},
		{"socks4", []string{"SOCKS4"}, nil, "empty"},
		{"socks4", []string{"SOCKS4"}, []byte{0x05, 0x01}, "bad-ver"},
		{"socks4", []string{"SOCKS4"}, []byte{0x04}, "trunc"},
		{"telnet", []string{"Telnet"}, nil, "empty"},
		{"telnet", []string{"Telnet"}, []byte{0xff}, "trunc-iac"},
		{"telnet", []string{"Telnet"}, []byte{0xff, 0x00}, "bad-cmd"},
		{"pop3", []string{"POP3"}, nil, "empty"},
		{"pop3", []string{"POP3"}, []byte("NOPE x\r\n"), "bad-status"},
		{"pop3", []string{"POP3"}, []byte("+O"), "trunc"},
		{"imap", []string{"IMAP"}, nil, "empty"},
		{"imap", []string{"IMAP"}, []byte("a1 ZZ\r\n"), "bad-cmd"},
		{"imap", []string{"IMAP"}, []byte("*"), "trunc"},
		{"vnc", []string{"VNC"}, nil, "empty"},
		{"vnc", []string{"VNC"}, []byte("HTTP/1.0\n"), "bad-magic"},
		{"vnc", []string{"VNC"}, []byte("RFB"), "trunc"},
		{"mongodb", []string{"MongoDB"}, nil, "empty"},
		{"mongodb", []string{"MongoDB"}, []byte{0x04, 0, 0, 0}, "short-len"},
		{"mongodb", []string{"MongoDB"}, []byte{0x10, 0, 0, 0}, "trunc"},
		{"memcached", []string{"Memcached"}, nil, "empty"},
		{"memcached", []string{"Memcached"}, []byte{0x00}, "bad-magic"},
		{"memcached", []string{"Memcached"}, []byte{0x80}, "trunc"},
		{"amqp", []string{"AMQP"}, nil, "empty"},
		{"amqp", []string{"AMQP"}, []byte{9}, "bad-type"},
		{"amqp", []string{"AMQP"}, []byte{'A'}, "trunc"},
		{"kafka", []string{"Kafka"}, nil, "empty"},
		{"kafka", []string{"Kafka"}, []byte{0, 0, 0, 1}, "short-len"},
		{"kafka", []string{"Kafka"}, []byte{0, 0, 0, 8}, "trunc"},
		{"jsonrpc", []string{"JSONRPC"}, nil, "empty"},
		{"jsonrpc", []string{"JSONRPC"}, []byte("[]\n"), "bad-lead"},
		{"jsonrpc", []string{"JSONRPC"}, []byte("{\"jsonrpc\":\"2.0\"}\n"), "no-method"},
		{"tacacs", []string{"TACACS"}, nil, "empty"},
		{"tacacs", []string{"TACACS"}, []byte{0x10}, "bad-ver"},
		{"tacacs", []string{"TACACS"}, []byte{0xc0}, "trunc"},
		{"dtls", []string{"DTLS"}, nil, "empty"},
		{"dtls", []string{"DTLS"}, []byte{0x16, 0x03, 0x03}, "bad-ver"},
		{"dtls", []string{"DTLS"}, []byte{0x16}, "trunc"},
		{"onc_rpc", []string{"ONCRPC"}, nil, "empty"},
		{"onc_rpc", []string{"ONCRPC"}, []byte{0, 0, 0, 0, 0, 0, 0, 2}, "bad-type"},
		{"onc_rpc", []string{"ONCRPC"}, []byte{0, 0, 0, 0}, "trunc"},
		{"ipmi", []string{"IPMI"}, nil, "empty"},
		{"ipmi", []string{"IPMI"}, []byte{0x05}, "bad-ver"},
		{"ipmi", []string{"IPMI"}, []byte{0x06, 0, 0, 0x01}, "bad-class"},
		{"bittorrent", []string{"BitTorrent"}, nil, "empty"},
		{"bittorrent", []string{"BitTorrent"}, []byte{0x13, 'n', 'o'}, "bad-pstr"},
		{"bittorrent", []string{"BitTorrent"}, []byte{0x12}, "bad-pstrlen"},
		{"fastcgi", []string{"FastCGI"}, nil, "empty"},
		{"fastcgi", []string{"FastCGI"}, []byte{0x02}, "bad-ver"},
		{"fastcgi", []string{"FastCGI"}, []byte{0x01, 0x63}, "bad-type"},
		{"jdwp", []string{"JDWP"}, nil, "empty"},
		{"jdwp", []string{"JDWP"}, []byte("not-handshake-"), "bad-hs"},
		{"jdwp", []string{"JDWP"}, []byte("JDWP-Hand"), "trunc"},
		{"php_ser", []string{"PHPSer"}, nil, "empty"},
		{"php_ser", []string{"PHPSer"}, []byte{0x78, 0x3a, 0x31, 0x3b}, "bad-kind"},
		{"php_ser", []string{"PHPSer"}, []byte{'i'}, "trunc"},
		{"pickle", []string{"Pickle"}, nil, "empty"},
		{"pickle", []string{"Pickle"}, []byte{0xff}, "bad-op"},
		{"pickle", []string{"Pickle"}, []byte{0x80, 0x06}, "bad-ver"},
		{"rmi", []string{"RMI"}, nil, "empty"},
		{"rmi", []string{"RMI"}, []byte("JAVA"), "bad-magic"},
		{"rmi", []string{"RMI"}, []byte("JR"), "trunc"},
		{"thrift", []string{"Thrift"}, nil, "empty"},
		{"thrift", []string{"Thrift"}, []byte{0x00, 0x00, 0x00, 0x01}, "bad-ver"},
		{"thrift", []string{"Thrift"}, []byte{0x80, 0x01, 0x00, 0x01}, "trunc"},
		{"protobuf", []string{"Protobuf"}, nil, "empty"},
		{"protobuf", []string{"Protobuf"}, []byte{0x07}, "bad-wt"},
		{"protobuf", []string{"Protobuf"}, []byte{0x08}, "trunc-varint"},
		{"zabbix", []string{"Zabbix"}, nil, "empty"},
		{"zabbix", []string{"Zabbix"}, []byte("XXXX"), "bad-magic"},
		{"zabbix", []string{"Zabbix"}, []byte("ZBX"), "trunc"},
		{"hessian", []string{"Hessian"}, nil, "empty"},
		{"hessian", []string{"Hessian"}, []byte{0x00}, "bad-magic"},
		{"hessian", []string{"Hessian"}, []byte{'H'}, "trunc"},
		{"rsync", []string{"Rsync"}, nil, "empty"},
		{"rsync", []string{"Rsync"}, []byte("HELLO\n"), "bad-magic"},
		{"rsync", []string{"Rsync"}, []byte("@RSYNC"), "trunc"},
		{"rtsp", []string{"RTSP"}, nil, "empty"},
		{"rtsp", []string{"RTSP"}, []byte("FOO rtsp://x RTSP/1.0\r\n\r\n"), "bad-method"},
		{"rtsp", []string{"RTSP"}, []byte("OPTIONS"), "trunc"},
		{"rtmp", []string{"RTMP"}, nil, "empty"},
		{"rtmp", []string{"RTMP"}, []byte{0x01}, "bad-ver"},
		{"rtmp", []string{"RTMP"}, []byte{}, "empty2"},
		{"ftp_data", []string{"FTPData"}, nil, "empty"},
		{"ftp_data", []string{"FTPData"}, []byte{0x80}, "trunc-hdr"},
		{"ftp_data", []string{"FTPData"}, []byte{0x80, 0x00, 0x0a}, "count-overflow"},
		{"jenkins", []string{"Jenkins"}, nil, "empty"},
		{"jenkins", []string{"Jenkins"}, []byte("hello\n"), "bad-prefix"},
		{"jenkins", []string{"Jenkins"}, []byte("Protocol"), "trunc"},
		{"salt", []string{"Salt"}, nil, "empty"},
		{"salt", []string{"Salt"}, []byte{0, 0, 0, 0}, "zero-len"},
		{"salt", []string{"Salt"}, []byte{0, 0, 0, 1}, "trunc"},
		{"net_remoting", []string{"NetRemoting"}, nil, "empty"},
		{"net_remoting", []string{"NetRemoting"}, []byte("HTTP"), "bad-preamble"},
		{"net_remoting", []string{"NetRemoting"}, []byte(".NE"), "trunc"},
		{"application-layer.iiop", []string{"GIOP"}, nil, "empty"},
		{"application-layer.iiop", []string{"GIOP"}, []byte("XXXX"), "bad-magic"},
		{"application-layer.iiop", []string{"GIOP"}, []byte("GI"), "trunc"},
		{"application-layer.t3", []string{"T3"}, nil, "empty"},
		{"application-layer.t3", []string{"T3"}, []byte{0, 0, 0, 1}, "short-len"},
		{"application-layer.t3", []string{"T3"}, []byte{0, 0, 0, 19}, "trunc"},
		{"application-layer.pptp", []string{"PPTP"}, nil, "empty"},
		{"application-layer.pptp", []string{"PPTP"}, []byte{0, 12, 0, 1, 0, 0, 0, 0}, "bad-magic"},
		{"application-layer.pptp", []string{"PPTP"}, []byte{0, 12, 0, 2}, "bad-msgtype"},
		{"application-layer.ntp", []string{"NTP"}, nil, "empty"},
		{"application-layer.ntp", []string{"NTP"}, []byte{0xe8}, "bad-ver"},
		{"application-layer.ntp", []string{"NTP"}, []byte{0x1c}, "trunc"},
		{"stp", []string{"STP"}, nil, "empty"},
		{"stp", []string{"STP"}, []byte{0x00, 0x01}, "bad-id"},
		{"stp", []string{"STP"}, []byte{0x00}, "trunc"},
		{"lldp", []string{"LLDP"}, nil, "empty"},
		{"lldp", []string{"LLDP"}, []byte{0x00}, "trunc"},
		{"lldp", []string{"LLDP"}, []byte{0xff, 0xff}, "trunc-tlv"},
		{"cdp", []string{"CDP"}, nil, "empty"},
		{"cdp", []string{"CDP"}, []byte{0x03}, "bad-ver"},
		{"cdp", []string{"CDP"}, []byte{0x02}, "trunc"},
		{"pppoe", []string{"PPPoE"}, nil, "empty"},
		{"pppoe", []string{"PPPoE"}, []byte{0x21}, "bad-ver"},
		{"pppoe", []string{"PPPoE"}, []byte{0x11}, "trunc"},
		{"application-layer.radius", []string{"RADIUS"}, nil, "empty"},
		{"application-layer.radius", []string{"RADIUS"}, []byte{99, 1, 0, 20}, "bad-code"},
		{"application-layer.radius", []string{"RADIUS"}, []byte{1, 1, 0, 19}, "short-len"},
		{"igmp", []string{"IGMP"}, nil, "empty"},
		{"igmp", []string{"IGMP"}, []byte{0x01}, "bad-type"},
		{"igmp", []string{"IGMP"}, []byte{0x11}, "trunc"},
		{"ipsec", []string{"AH"}, nil, "empty"},
		{"ipsec", []string{"AH"}, []byte{0x00}, "trunc"},
		{"ipsec", []string{"ESP"}, nil, "esp-empty"},
		{"ipsec", []string{"ESP"}, []byte{0x00}, "esp-trunc"},
		{"llc", []string{"LLC"}, nil, "empty"},
		{"llc", []string{"LLC"}, []byte{0x00}, "trunc"},
		{"llc", []string{"LLC"}, []byte{0xaa}, "trunc-ssap"},
		{"ieee_802_1ad", []string{"QinQ"}, nil, "empty"},
		{"ieee_802_1ad", []string{"QinQ"}, []byte{0x00}, "trunc"},
		{"ieee_802_1ad", []string{"QinQ"}, []byte{0x00, 0x01}, "trunc-type"},
		{"ieee_802_11", []string{"Dot11"}, nil, "empty"},
		{"ieee_802_11", []string{"Dot11"}, []byte{0x00}, "trunc"},
		{"ieee_802_11", []string{"Dot11"}, []byte{0x0c, 0x00}, "reserved-type"},
		{"ieee_802_11", []string{"RSN"}, []byte{0x01}, "bad-eid"},
		{"ieee_802_11", []string{"RSN"}, nil, "rsn-empty"},
		{"ieee_802_11", []string{"RSN"}, []byte{48}, "rsn-trunc"},
		{"linux_sll", []string{"LinuxSLL"}, nil, "empty"},
		{"linux_sll", []string{"LinuxSLL"}, []byte{0x00}, "trunc"},
		{"linux_sll", []string{"LinuxSLL"}, []byte{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, "trunc-proto"},
		{"loopback", []string{"Loopback"}, nil, "empty"},
		{"loopback", []string{"Loopback"}, []byte{0x00}, "trunc"},
		{"loopback", []string{"Loopback"}, []byte{0x08}, "trunc2"},
		{"mpls", []string{"MPLS"}, nil, "empty"},
		{"mpls", []string{"MPLS"}, []byte{0x00}, "trunc"},
		{"mpls", []string{"MPLS"}, []byte{0x00, 0x00, 0x00}, "trunc2"},
		{"password_authentication_protocol", []string{"PAP"}, nil, "empty"},
		{"password_authentication_protocol", []string{"PAP"}, []byte{0x01}, "trunc"},
		{"password_authentication_protocol", []string{"PAP"}, []byte{0x01, 0, 0, 14}, "trunc-body"},
		{"challenge_handshake_authentication_protocol", []string{"CHAP"}, nil, "empty"},
		{"challenge_handshake_authentication_protocol", []string{"CHAP"}, []byte{0x01}, "trunc"},
		{"challenge_handshake_authentication_protocol", []string{"CHAP"}, []byte{0x01, 0, 0, 34}, "trunc-len"},
		{"link_control_protocol", []string{"LCP"}, nil, "empty"},
		{"link_control_protocol", []string{"LCP"}, []byte{0x01}, "trunc"},
		{"link_control_protocol", []string{"LCP"}, []byte{0x00, 0, 0, 4}, "bad-code"},
		{"ppp", []string{"PPP"}, nil, "empty"},
		{"ppp", []string{"PPP"}, []byte{0xff}, "trunc"},
		{"ppp", []string{"PPP"}, []byte{0xff, 0x03}, "trunc-proto"},
		{"generic_routing_encapsulation", []string{"GRE"}, nil, "empty"},
		{"generic_routing_encapsulation", []string{"GRE"}, []byte{0x00}, "trunc"},
		{"generic_routing_encapsulation", []string{"GRE"}, []byte{0x00, 0x00}, "trunc2"},
		{"generic_routing_encapsulation", []string{"GRE"}, []byte{0x20, 0x00, 0x08, 0x00}, "trunc-key"},
		{"eapol", []string{"EAPOL"}, nil, "empty"},
		{"eapol", []string{"EAPOL"}, []byte{0x01}, "trunc"},
		{"eapol", []string{"EAPOL"}, []byte{0x01, 0x00, 0x00, 0x10}, "trunc-body"},
		{"transmission_control_protocol", []string{"TCP"}, nil, "empty"},
		{"transmission_control_protocol", []string{"TCP"}, []byte{0x00}, "trunc"},
		{"transmission_control_protocol", []string{"TCP"}, make([]byte, 19), "trunc-hdr"},
		{"application-layer.ber", []string{"BER Element"}, nil, "empty"},
		{"application-layer.ber", []string{"BER Element"}, []byte{0x02}, "trunc"},
		{"application-layer.ber", []string{"BER Element"}, []byte{0x02, 0x81}, "trunc-len"},
		{"application-layer.snmp", []string{"SNMPv3"}, nil, "empty"},
		{"application-layer.snmp", []string{"SNMPv3"}, []byte{0x31, 0x03, 0x02, 0x01, 0x03}, "bad-seq"},
		{"application-layer.snmp", []string{"SNMPv3"}, []byte{0x30, 0x03, 0x02, 0x01, 0x01}, "bad-ver"},
}

func TestP1FailPaths(t *testing.T) {
	for i, tc := range p1FailCases {
		t.Run(fmt.Sprintf("%s/%s/%s/%d", tc.rule, tc.keys[0], tc.name, i), func(t *testing.T) {
			parseMustFail(t, tc.data, tc.rule, tc.keys...)
		})
	}
}

func bytesRepeat(b byte, n int) []byte {
	out := make([]byte, n)
	for i := range out {
		out[i] = b
	}
	return out
}
