package bin_parser

import (
	"bytes"
	"crypto/sha256"
	"fmt"
	"io"
	"net/url"
	"os"
	"strings"
	"sync"
	"testing"

	"github.com/gopacket/gopacket"
	"github.com/gopacket/gopacket/layers"
	"github.com/stretchr/testify/require"
	"github.com/yaklang/yaklang/common/bin-parser/parser"
	"github.com/yaklang/yaklang/common/bin-parser/parser/base"
	"github.com/yaklang/yaklang/common/bin-parser/parser/stream_parser"
)

const redfishCorpusRule = "application-layer.redfish"
const redfishDirect = "RedfishServiceRootRequest"
const redfishCarrier = "RedfishServiceRootRequestCarrier"

type redfishTestFixture struct {
	target  string
	headers []string
	body    string
	chunked bool
	info    map[string]any
}

func (f redfishTestFixture) wire() []byte {
	wire := "GET " + f.target + " HTTP/1.1\r\n"
	for _, header := range f.headers {
		wire += header + "\r\n"
	}
	return []byte(wire + "\r\n" + f.body)
}

// Record zero is the original captured request. Other literals are assembled
// independently from DSP0266 1.23.1 §§6.7/7.1/7.2.1/7.3, never generated by
// the parser. Their scope is the request codec, not endpoint or service state.
func redfishTestFixtures() []redfishTestFixture {
	return []redfishTestFixture{
		{"/redfish/v1/", []string{"Host: bmc.lab", "OData-Version: 4.0"}, "", false, map[string]any{
			"Host Header": "bmc.lab", "Hostname": "bmc.lab", "Port": "", "OData Version": "4.0", "OData Version Present": true,
			"OData Maximum Version": "", "OData Maximum Version Present": false, "Excerpt": false, "Include Origin Of Condition": false, "Expand Present": false, "Select Present": false,
		}},
		{"/redfish/v1?excerpt=&OEM-Example-View=summary&x=a+b&x=%2B", []string{"Host: [2001:db8::1]:8443", "Accept: application/json", "If-None-Match: W/\"fixture\""}, "", false, map[string]any{
			"Host Header": "[2001:db8::1]:8443", "Hostname": "2001:db8::1", "Port": "8443", "OData Version": "", "OData Version Present": false,
			"Excerpt": true, "Include Origin Of Condition": false, "Expand Present": false, "Select Present": false,
			"Unknown Query Values": map[string][]string{"OEM-Example-View": {"summary"}, "x": {"a+b", "+"}},
		}},
		{"/redfish/v1/?$expand=*($levels=2)&$select=RedfishVersion,Links/Sessions&includeoriginofcondition", []string{"Host: bmc.example:443", "OData-MaxVersion: 4.0", "Content-Type: application/json", "Content-Length: 2", "User-Agent: binparser-fixture/1.0"}, "{}", false, map[string]any{
			"Host Header": "bmc.example:443", "Hostname": "bmc.example", "Port": "443", "OData Version Present": false,
			"OData Maximum Version": "4.0", "OData Maximum Version Present": true, "Excerpt": false, "Include Origin Of Condition": true,
			"Expand Present": true, "Expand Mode": "*", "Expand Levels": uint64(2), "Expand Levels Present": true,
			"Select Present": true, "Selected Property Paths": []string{"RedfishVersion", "Links/Sessions"},
		}},
		{"/redfish/v1/?$expand=~&$select=Name,Links", []string{"hOsT:\tbmc.lab \t", "odata-version: 4.0", "Transfer-Encoding: chunked", "Content-Type: application/octet-stream"}, "3\r\nabc\r\n0\r\nX-End: yes\r\n\r\n", true, map[string]any{
			"Host Header": "bmc.lab", "Hostname": "bmc.lab", "Port": "", "OData Version": "4.0", "OData Version Present": true,
			"Excerpt": false, "Include Origin Of Condition": false, "Expand Present": true, "Expand Mode": "~", "Expand Levels": uint64(1), "Expand Levels Present": false,
			"Select Present": true, "Selected Property Paths": []string{"Name", "Links"},
		}},
	}
}

func redfishTestInfo(t *testing.T, node *base.Node) map[string]any {
	t.Helper()
	http := protocolCorpusFindNode(node, "HTTP")
	require.NotNil(t, http)
	return alljoynTestInfo(t, http.Cfg.GetItem(base.CfgParent).(*base.Node))
}

func redfishTestFields(t *testing.T, node *base.Node, fixture redfishTestFixture, offset uint64) {
	t.Helper()
	var expected, actual []alljoynTestLeaf
	cursor := offset
	leaf := func(name, value, delimiter string) {
		expected = append(expected, alljoynTestLeaf{Name: name, Value: value, Span: [2]uint64{cursor, cursor + uint64(len(value))*8}})
		cursor += uint64(len(value)+len(delimiter)) * 8
	}
	leaf("Method", "GET", " ")
	leaf("Path", fixture.target, " ")
	leaf("Version", "HTTP/1.1", "\r\n")
	for _, header := range append(append([]string{}, fixture.headers...), "") {
		leaf("Item", header, "\r\n")
	}
	if fixture.chunked {
		require.Equal(t, "3\r\nabc\r\n0\r\nX-End: yes\r\n\r\n", fixture.body)
		leaf("Size", "3", "\r\n")
		leaf("Octets", "abc", "")
		leaf("End", "", "\r\n")
		leaf("Size", "0", "\r\n")
		leaf("Item", "X-End: yes", "\r\n")
		leaf("Item", "", "\r\n")
	} else if fixture.body != "" {
		leaf("Octets", fixture.body, "")
	}
	var visit func(*base.Node)
	visit = func(n *base.Node) {
		if protocolCorpusNodeHasResult(n) {
			result, err := n.Result()
			require.NoError(t, err)
			require.Same(t, n, result.Origin)
		}
		if stream_parser.NodeHasResult(n) {
			result, err := n.Result()
			require.NoError(t, err)
			require.IsType(t, "", result.Value)
			require.Equal(t, "string", n.Cfg.GetItem(base.CfgType))
			actual = append(actual, alljoynTestLeaf{Name: n.Name, Value: result.Value, Span: stream_parser.GetNodeResultPos(n)})
			return
		}
		for _, child := range n.Children {
			require.Same(t, n, child.Cfg.GetItem(base.CfgParent))
			visit(child)
		}
	}
	visit(node)
	require.Equal(t, expected, actual)
	require.Equal(t, offset+uint64(len(fixture.wire()))*8, cursor)
	info := redfishTestInfo(t, node)
	path, query, present := strings.Cut(fixture.target, "?")
	for key, value := range map[string]any{
		"Profile": "Redfish v1 service-root HTTP request parameter codec", "Method": "GET", "Request Target Form": "origin-form",
		"Service Root Path": "/redfish/v1/", "Request Path": path, "Trailing Slash Present": strings.HasSuffix(path, "/"),
		"Parameter Span Coordinate System": "request-target-relative-bits", "Major Version Target Bit Span": [2]uint64{80, 88},
		"Raw Query": query, "Query Present": present, "GET Body Ignored By Specification": true, "Body Node Present": fixture.body != "",
		"Full Protocol Version Observed": false, "ServiceRoot Schema Parsed": false, "Redirect Observed": false, "Service Capabilities Observed": false, "Query Semantics Evaluated": false,
		"Accept Semantics Validated": false, "Conditional Outcome Validated": false, "Body Semantics Decoded": false, "Response Schema Parsed": false, "Session Observed": false, "TLS Observed": false, "Endpoint Identity Proven": false,
	} {
		require.Equal(t, value, info[key], key)
	}
	require.EqualValues(t, 1, info["Major Version"])
	require.EqualValues(t, 16384, info["Maximum Request Bytes"])
	for key, value := range fixture.info {
		if key == "Expand Levels" {
			require.EqualValues(t, value, info[key], key)
		} else {
			require.Equal(t, value, info[key], key)
		}
	}
	for header, key := range map[string]string{"accept": "Accept Values", "if-none-match": "If-None-Match Values", "user-agent": "User-Agent Values"} {
		values := []string{}
		for _, line := range fixture.headers {
			name, value, _ := strings.Cut(line, ":")
			if strings.EqualFold(name, header) {
				values = append(values, strings.Trim(value, " \t"))
			}
		}
		require.Equal(t, values, info[key])
		if header == "accept" {
			require.Equal(t, len(values) != 0, info["Accept Header Present"])
		}
	}
	pairs, ok := info["Query Pairs"].([]map[string]any)
	require.True(t, ok)
	values := map[string][]string{}
	start, index := len(path)+1, 0
	for _, raw := range strings.Split(query, "&") {
		if raw != "" {
			name, value, equal := strings.Cut(raw, "=")
			decodedName, err := url.PathUnescape(name)
			require.NoError(t, err)
			decodedValue, err := url.PathUnescape(value)
			require.NoError(t, err)
			valueStart := start + len(name)
			if equal {
				valueStart++
			}
			recognized := map[string]bool{"excerpt": true, "includeoriginofcondition": true, "$expand": true, "$select": true}[strings.ToLower(decodedName)]
			require.Equal(t, map[string]any{"Name": decodedName, "Value": decodedValue, "Raw Name": name, "Raw Value": value, "Equals Present": equal, "Recognized": recognized,
				"Name Target Bit Span": [2]uint64{uint64(start) * 8, uint64(start+len(name)) * 8}, "Value Target Bit Span": [2]uint64{uint64(valueStart) * 8, uint64(start+len(raw)) * 8}}, pairs[index])
			values[decodedName] = append(values[decodedName], decodedValue)
			index++
		}
		start += len(raw) + 1
	}
	require.Len(t, pairs, index)
	require.Equal(t, index, info["Query Pair Count"])
	require.Equal(t, values, info["Query Values"])
}

func TestProtocolCorpusRedfishFields(t *testing.T) {
	for index, fixture := range redfishTestFixtures() {
		for _, entry := range []string{redfishDirect, redfishCarrier} {
			t.Run(fmt.Sprintf("%d/%s", index, entry), func(t *testing.T) {
				node := protocolCorpusRequireBoundedRuleParse(t, fixture.wire(), redfishCorpusRule, entry)
				require.Equal(t, fixture.wire(), NodeToBytes(node))
				redfishTestFields(t, node, fixture, 0)
				t.Logf("literal %d len=%d hex=%x", index+1, len(fixture.wire()), fixture.wire())
			})
		}
	}
}

func TestProtocolCorpusRedfishAllOriginalRecords(t *testing.T) {
	seen, dataSeen := 0, 0
	for _, capture := range []struct{ path, sha string }{
		{"generated-local/gen-redfish", "1af201bf8bb3489f6812bb08ae5a0fb67d2377e94706ff63a2a967fd4f28f74d"},
		{"generated-pr5023/pr5023-gen-redfish", "b74b6b7b39a11b863cfc6e566af629651ef2d54266b715419c449b11a7518fee"},
	} {
		path := "testdata/protocol-corpus/captures/" + capture.path + ".pcap"
		data, err := os.ReadFile(path)
		require.NoError(t, err)
		require.Equal(t, capture.sha, fmt.Sprintf("%x", sha256.Sum256(data)))
		frames := protocolCorpusAuditPackets(t, path)
		require.Len(t, frames, 4)
		for i, frame := range frames {
			seen++
			packet := gopacket.NewPacket(frame, layers.LayerTypeEthernet, gopacket.Default)
			require.Nil(t, packet.ErrorLayer())
			tcp := packet.Layer(layers.LayerTypeTCP).(*layers.TCP)
			node := protocolCorpusRequireBoundedRuleParse(t, frame, "ethernet", "Ethernet")
			require.Equal(t, frame, NodeToBytes(node))
			require.Nil(t, protocolCorpusFindNode(node, redfishDirect))
			if i < 3 {
				require.Len(t, frame, 54)
				require.Empty(t, tcp.Payload)
				require.Equal(t, i < 2, tcp.SYN)
				require.Equal(t, i > 0, tcp.ACK)
				require.False(t, tcp.PSH || tcp.FIN || tcp.RST || tcp.URG || tcp.ECE || tcp.CWR)
				require.Nil(t, protocolCorpusFindNode(node, "Method"))
				continue
			}
			dataSeen++
			fixture := redfishTestFixtures()[0]
			require.Len(t, frame, 118)
			require.Equal(t, fixture.wire(), tcp.Payload)
			require.EqualValues(t, 40100, tcp.SrcPort)
			require.EqualValues(t, 443, tcp.DstPort)
			// Port 443 does not turn these unchanged plaintext HTTP bytes
			// into TLS, or establish the endpoint's product identity.
			protocolCorpusRequireValue(t, node, "Method", "GET")
			protocolCorpusRequireValue(t, node, "Path", fixture.target)
			for _, entry := range []string{redfishDirect, redfishCarrier} {
				strict := protocolCorpusRequireBoundedRuleParse(t, tcp.Payload, redfishCorpusRule, entry)
				redfishTestFields(t, strict, fixture, 0)
			}
		}
	}
	require.Equal(t, 8, seen)
	require.Equal(t, 2, dataSeen)
}

func redfishTestReject(t *testing.T, wire []byte) {
	t.Helper()
	_, err := parser.ParseBinary(newProtocolCorpusBoundedReader(wire), redfishCorpusRule, redfishDirect)
	require.Error(t, err, string(wire))
	if len(wire) == 0 {
		return
	}
	node := protocolCorpusRequireBoundedRuleParse(t, wire, redfishCorpusRule, redfishCarrier)
	protocolCorpusRequireValue(t, node, "Unparsed Redfish Service Root Request", wire)
	require.Nil(t, protocolCorpusFindNode(node, "Method"))
	require.Equal(t, wire, NodeToBytes(node))
}

func TestProtocolCorpusRedfishAllCompanionRecords(t *testing.T) {
	const path = "testdata/protocol-corpus/captures/generated-validated/gen-redfish-valid.pcap"
	data, err := os.ReadFile(path)
	require.NoError(t, err)
	require.Equal(t, "702d6a37ce476c39448ea3df7401d0f7afec2287673566793b6bed9f48aa7298", fmt.Sprintf("%x", sha256.Sum256(data)))
	frames := protocolCorpusAuditPackets(t, path)
	fixtures := redfishTestFixtures()
	require.Len(t, frames, len(fixtures))
	for index, frame := range frames {
		fixture := fixtures[index]
		packet := gopacket.NewPacket(frame, layers.LayerTypeEthernet, gopacket.Default)
		require.Nil(t, packet.ErrorLayer())
		tcp := packet.Layer(layers.LayerTypeTCP).(*layers.TCP)
		require.EqualValues(t, 40100, tcp.SrcPort)
		require.EqualValues(t, 443, tcp.DstPort)
		require.Equal(t, fixture.wire(), tcp.Payload)
		require.Len(t, frame, 54+len(tcp.Payload))
		node := protocolCorpusRequireBoundedRuleParse(t, frame, "ethernet", "Ethernet")
		require.Equal(t, frame, NodeToBytes(node))
		protocolCorpusRequireValue(t, node, "Method", "GET")
		protocolCorpusRequireValue(t, node, "Path", fixture.target)
		for _, entry := range []string{redfishDirect, redfishCarrier} {
			strict := protocolCorpusRequireBoundedRuleParse(t, tcp.Payload, redfishCorpusRule, entry)
			redfishTestFields(t, strict, fixture, 0)
			require.Equal(t, fixture.wire(), NodeToBytes(strict))
			// Opt-in parsing after the real Ethernet/IP/TCP prefix. Neither
			// port 443 nor this cleartext fixture establishes a TLS session.
			root := fcoeTestInline(t, fmt.Sprintf(`Package:
  Frame:
    operator: |
      this.ProcessSubNode("Prefix")
      this.GetSubNode("Request").SetMaxLength(%d)
      this.ProcessSubNode("Request")
    Prefix: raw,54
    Request: "import:application-layer/redfish.yaml;node:%s"
`, len(tcp.Payload), entry))
			root.Cfg.SetItem(base.CfgLength, uint64(len(frame))*8)
			require.NoError(t, root.ParseSubNode(base.NewBitReader(bytes.NewReader(frame)), "Frame"))
			envelope := base.GetNodeByPath(root, "@Frame")
			redfishTestFields(t, protocolCorpusFindNode(envelope, "Request"), fixture, 54*8)
			require.Equal(t, frame, NodeToBytes(envelope))
		}
	}
}

func TestProtocolCorpusRedfishPrefixesAndExactBounds(t *testing.T) {
	for _, fixture := range redfishTestFixtures() {
		wire := fixture.wire()
		for cut := 0; cut < len(wire); cut++ {
			redfishTestReject(t, wire[:cut])
		}
		for _, suffix := range [][]byte{{0}, {'\r', '\n'}, wire} {
			redfishTestReject(t, append(bytes.Clone(wire), suffix...))
		}
	}
	for _, entry := range []string{redfishDirect, redfishCarrier} {
		_, err := parser.ParseBinary(bytes.NewBuffer(redfishTestFixtures()[0].wire()), redfishCorpusRule, entry)
		require.ErrorContains(t, err, "explicit")
		node, err := parser.GenerateBinary(map[string]any{}, redfishCorpusRule, entry)
		require.Nil(t, node)
		require.ErrorContains(t, err, "explicit")
		for extra := uint64(1); extra < 8; extra++ {
			wire := append(redfishTestFixtures()[0].wire(), 0)
			reader := &alljoynTestBitBoundaryReader{bytes.NewReader(wire), uint64(len(wire)-1)*8 + extra}
			_, err := parser.ParseBinary(reader, redfishCorpusRule, entry)
			require.ErrorContains(t, err, "explicit byte boundary")
			require.Equal(t, len(wire), reader.Len())
		}
	}
	_, err := parser.ParseBinary(newProtocolCorpusBoundedReader(nil), redfishCorpusRule, redfishCarrier)
	require.ErrorContains(t, err, "empty carrier")
}

func TestProtocolCorpusRedfishParameterBoundsAndCompatibility(t *testing.T) {
	for _, query := range []string{"$top=1", "$skip=0", "$filter=Name%20eq%20'x'", "only", "$future=x", "excerpt=1", "includeoriginofcondition=true", "excerpt&EXCERPT", "$expand=*&$EXPAND=.", "$select=Name&$select=Name", "$expand=", "$expand=foo", "$expand=**", "$expand=*($levels=)", "$expand=*($levels=-1)", "$expand=*($levels=4294967296)", "$expand=*($levels=1);x", "$select=", "$select=Name,", "$select=/Name", "$select=Name//State", "$select=Members/0/Name", "$select=*", "x=%", "x=%ZZ", "x=#fragment", "x=[raw]", "x=\\"} {
		fixture := redfishTestFixtures()[0]
		fixture.target += "?" + query
		redfishTestReject(t, fixture.wire())
	}
	for _, target := range []string{"*", "/redfish", "/redfish/v2/", "/redfish/v1/Systems", "/redfish/V1/", "/redfish/%761/", "http://bmc.lab/redfish/v1/"} {
		fixture := redfishTestFixtures()[0]
		fixture.target = target
		redfishTestReject(t, fixture.wire())
	}
	for _, header := range []string{"OData-Version: 3.0", "OData-Version:", "OData-Version: 4.0\r\nOData-Version: 4.0", "OData-MaxVersion: 3.0", "OData-MaxVersion:", "OData-MaxVersion: 4.0\r\nOData-MaxVersion: 4.0"} {
		fixture := redfishTestFixtures()[0]
		fixture.headers = []string{"Host: bmc.lab", header}
		redfishTestReject(t, fixture.wire())
	}
	for _, header := range []string{"Host:", "Host: a\r\nHost: a", "Host: a/b", "Host: a?b", "Host: a@b", "Host: [hostname]", "Host: a:65536", "Host: a:", "Host: a b", "Host: 2001:db8::1"} {
		fixture := redfishTestFixtures()[0]
		fixture.headers = []string{header}
		redfishTestReject(t, fixture.wire())
	}
	for _, wire := range []string{"GET /redfish/v1/ HTTP/1.1\r\n\r\n", "GET /redfish/v1/ HTTP/1.0\r\nHost: bmc.lab\r\n\r\n", "POST /redfish/v1/ HTTP/1.1\r\nHost: bmc.lab\r\n\r\n", "HTTP/1.1 200 OK\r\nContent-Length: 2\r\n\r\n{}"} {
		redfishTestReject(t, []byte(wire))
	}
	for _, test := range []struct {
		query string
		info  map[string]any
	}{
		{"", map[string]any{"Query Present": true, "Query Pair Count": 0}},
		{"&&ExCeRpT=&INCLUDEORIGINOFCONDITION&", map[string]any{"Excerpt": true, "Include Origin Of Condition": true}},
		{"%24expand=.($levels=0)", map[string]any{"Expand Mode": ".", "Expand Levels": uint64(0), "Expand Levels Present": true}},
		{"$expand=*($levels=4294967295)", map[string]any{"Expand Levels": uint64(4294967295)}},
		{"$SELECT=Name,@odata.type,Links%2FSessions", map[string]any{"Selected Property Paths": []string{"Name", "@odata.type", "Links/Sessions"}}},
		{"unknown=a+b&unknown=a%20b&x=1;2", map[string]any{"Unknown Query Values": map[string][]string{"unknown": {"a+b", "a b"}, "x": {"1;2"}}}},
	} {
		fixture := redfishTestFixtures()[0]
		fixture.target += "?" + test.query
		node := protocolCorpusRequireBoundedRuleParse(t, fixture.wire(), redfishCorpusRule, redfishDirect)
		info := redfishTestInfo(t, node)
		for key, want := range test.info {
			if key == "Expand Levels" {
				require.EqualValues(t, want, info[key], test.query)
			} else {
				require.Equal(t, want, info[key], test.query)
			}
		}
	}
}

func TestProtocolCorpusRedfishResourceAndBodyConfig(t *testing.T) {
	fixture := redfishTestFixtures()[0]
	fixture.target += "?" + strings.TrimSuffix(strings.Repeat("x=1&", 256), "&")
	node := protocolCorpusRequireBoundedRuleParse(t, fixture.wire(), redfishCorpusRule, redfishDirect)
	require.Equal(t, 256, redfishTestInfo(t, node)["Query Pair Count"])
	fixture.target += "&x=1"
	redfishTestReject(t, fixture.wire())
	fixture = redfishTestFixtures()[0]
	fixture.target += "?x=" + strings.Repeat("a", 8192-len(fixture.target)-3)
	require.Len(t, fixture.target, 8192)
	protocolCorpusRequireBoundedRuleParse(t, fixture.wire(), redfishCorpusRule, redfishDirect)
	fixture.target += "a"
	redfishTestReject(t, fixture.wire())
	fixture = redfishTestFixtures()[0]
	fixture.headers = append(fixture.headers, "X-Pad: ")
	fixture.headers[2] += strings.Repeat("x", 16384-len(fixture.wire()))
	wire := fixture.wire()
	require.Len(t, wire, 16384)
	protocolCorpusRequireBoundedRuleParse(t, wire, redfishCorpusRule, redfishDirect)
	reader := newProtocolCorpusBoundedReader(append(bytes.Clone(wire), 0))
	_, err := parser.ParseBinary(reader, redfishCorpusRule, redfishDirect)
	require.ErrorContains(t, err, "16384-byte implementation profile")
	require.Equal(t, 16385, reader.Len())
	redfishTestReject(t, append(bytes.Clone(wire), 0))
	for _, fixture := range redfishTestFixtures()[2:] {
		_, err := parser.ParseBinaryWithConfig(newProtocolCorpusBoundedReader(fixture.wire()), redfishCorpusRule, map[string]any{"httpBodyLimit": 1}, redfishDirect)
		require.ErrorContains(t, err, "configured limit")
		node, err := parser.ParseBinaryWithConfig(newProtocolCorpusBoundedReader(fixture.wire()), redfishCorpusRule, map[string]any{"httpBodyLimit": 1}, redfishCarrier)
		require.NoError(t, err)
		protocolCorpusRequireValue(t, node, "Unparsed Redfish Service Root Request", fixture.wire())
		require.Nil(t, protocolCorpusFindNode(node, "Method"))
		node = protocolCorpusRequireBoundedRuleParse(t, fixture.wire(), redfishCorpusRule, redfishDirect)
		redfishTestFields(t, node, fixture, 0)
	}
}

func TestProtocolCorpusRedfishImportsAndHeldReader(t *testing.T) {
	fixture := redfishTestFixtures()[3]
	for offset := 0; offset < 8; offset++ {
		for _, entry := range []string{redfishDirect, redfishCarrier} {
			prefix, pad := "", ""
			if offset != 0 {
				prefix = fmt.Sprintf("    Prefix: uint8,%dbit\n", offset)
				pad = fmt.Sprintf("    Padding: uint8,%dbit\n", 8-offset)
			}
			wire := fixture.wire()
			root := fcoeTestInline(t, fmt.Sprintf(`Package:
  Envelope:
    operator: |
      if %d > 0 { this.ProcessSubNode("Prefix") }
      this.GetSubNode("Request").SetMaxLength(%d)
      this.ProcessSubNode("Request")
      this.ProcessSubNode("Suffix")
      if %d > 0 { this.ProcessSubNode("Padding") }
%s    Request: "import:application-layer/redfish.yaml;node:%s"
    Suffix: uint8
%s`, offset, len(wire), offset, prefix, entry, pad))
			var fields []snaTestField
			if offset != 0 {
				fields = append(fields, snaBit("Prefix", uint8(1<<offset-1), uint64(offset)))
			}
			fields = append(fields, snaRaw("Request", wire), snaU8("Suffix", 0x5a))
			if offset != 0 {
				fields = append(fields, snaBit("Padding", 0, uint64(8-offset)))
			}
			input := snaEncode(fields)
			root.Cfg.SetItem(base.CfgLength, uint64(len(input))*8)
			reader := base.NewBitReader(bytes.NewReader(input))
			require.NoError(t, reader.Backup())
			require.NoError(t, root.ParseSubNode(reader, "Envelope"))
			node := base.GetNodeByPath(root, "@Envelope")
			redfishTestFields(t, protocolCorpusFindNode(node, "Request"), fixture, uint64(offset))
			miopTestField(t, node, "Suffix", uint8(0x5a), uint64(offset+len(wire)*8), uint64(offset+(len(wire)+1)*8))
			require.Equal(t, input, NodeToBytes(node))
			require.NoError(t, reader.Recovery())
			replay, err := reader.ReadBits(uint64(len(input)) * 8)
			require.NoError(t, err)
			require.Equal(t, input, replay)
			require.ErrorContains(t, reader.Recovery(), "no backup")
		}
	}
	for _, valid := range []bool{true, false} {
		for _, rollback := range []bool{false, true} {
			wire := fixture.wire()
			if !valid {
				wire = bytes.Replace(wire, []byte("odata-version: 4.0"), []byte("odata-version: 3.0"), 1)
			}
			reader := base.NewBitReader(bytes.NewReader(append(append([]byte{0xa5}, wire...), 0x5a)))
			_, err := reader.ReadBits(8)
			require.NoError(t, err)
			require.NoError(t, reader.Backup())
			root, err := base.ParseRule("application-layer/redfish.yaml")
			require.NoError(t, err)
			root.Cfg.SetItem(base.CfgLength, uint64(len(wire))*8)
			require.NoError(t, root.ParseSubNode(reader, redfishCarrier))
			node := base.GetNodeByPath(root, "@"+redfishCarrier)
			require.Equal(t, wire, NodeToBytes(node))
			if valid {
				redfishTestFields(t, node, fixture, 0)
			} else {
				protocolCorpusRequireValue(t, node, "Unparsed Redfish Service Root Request", wire)
				require.Nil(t, protocolCorpusFindNode(node, "Method"))
			}
			if rollback {
				require.NoError(t, reader.Recovery())
				replay, err := reader.ReadBits(uint64(len(wire)) * 8)
				require.NoError(t, err)
				require.Equal(t, wire, replay)
			} else {
				require.NoError(t, reader.PopBackup())
			}
			suffix, err := reader.ReadBits(8)
			require.NoError(t, err)
			require.Equal(t, []byte{0x5a}, suffix)
			require.ErrorContains(t, reader.Recovery(), "no backup")
		}
	}
}

func TestProtocolCorpusRedfishPhysicalTruncationAndConcurrentIsolation(t *testing.T) {
	wire := redfishTestFixtures()[3].wire()
	for _, entry := range []string{redfishDirect, redfishCarrier} {
		for _, cut := range []int{1, 20, len(wire) - 1} {
			root, err := base.ParseRule("application-layer/redfish.yaml")
			require.NoError(t, err)
			root.Cfg.SetItem(base.CfgLength, uint64(len(wire))*8)
			reader := base.NewBitReader(bytes.NewReader(wire[:cut]))
			require.NoError(t, reader.Backup())
			require.Error(t, root.ParseSubNode(reader, entry))
			require.NoError(t, reader.Recovery())
			replay, err := reader.ReadBits(uint64(cut) * 8)
			require.NoError(t, err)
			require.Equal(t, wire[:cut], replay)
			require.ErrorContains(t, reader.Recovery(), "no backup")
			_, err = reader.ReadBits(8)
			require.ErrorIs(t, err, io.EOF)
		}
	}
	var wait sync.WaitGroup
	errors := make(chan error, 12)
	for i := 0; i < 12; i++ {
		wait.Add(1)
		go func(i int) {
			defer wait.Done()
			wire := redfishTestFixtures()[i%4].wire()
			valid := i%3 != 0
			if !valid {
				wire = append(wire, 0)
			}
			node, err := parser.ParseBinary(newProtocolCorpusBoundedReader(wire), redfishCorpusRule, redfishCarrier)
			if err == nil {
				_, err = node.Result()
			}
			if err == nil && (!bytes.Equal(wire, NodeToBytes(node)) || (protocolCorpusFindNode(node, "Method") != nil) != valid || (protocolCorpusFindNode(node, "Unparsed Redfish Service Root Request") != nil) == valid) {
				err = fmt.Errorf("Redfish context %d leaked trial state", i)
			}
			errors <- err
		}(i)
	}
	wait.Wait()
	close(errors)
	for err := range errors {
		require.NoError(t, err)
	}
}
