package bin_parser

import (
	"bytes"
	"crypto/sha256"
	"encoding/binary"
	"encoding/hex"
	"fmt"
	"hash/crc32"
	"io"
	"strings"
	"sync"
	"testing"

	"github.com/stretchr/testify/require"
	"github.com/yaklang/yaklang/common/bin-parser/parser"
	"github.com/yaklang/yaklang/common/bin-parser/parser/base"
	"github.com/yaklang/yaklang/common/bin-parser/parser/stream_parser"
	yaml "github.com/yaklang/yaklang/common/utils/orderedyaml"
)

type fcoeTestFixture struct {
	name, literal, frameSHA string
}

// Independent literals, not generated by the corpus recipe or parser. CRC
// numeric values were independently computed with Python zlib.crc32 and the
// first complete 64-byte frame was verified by Wireshark (CRC Status: Good).
// The first six are positive. The final original companion record is retained
// byte-for-byte as an unsupported negative, not a complete optional-header frame.
var fcoeTestFixtures = []fcoeTestFixture{
	{"basic", "000000000000000000000000002e0401020300040506ff380000070000001234ffff00000000deadbeef4a1916e142000000", "8ecebda57b3455b408e795ba0879c8ea2e4711f92f6a11349b71319176a8bca8"},
	{"empty", "000000000000000000000000002e800102030004050600380000070000001234ffff000000007e1a47b142000000", "e02d4b80ac6e14999845cc02724f4a0c0cefe8d6b1c586692c88a7bb04c99fa9"},
	{"network", "000000000000000000000000002e0401020300040506ff380000072000001234ffff0000000000112233445566778899aabbccddeeff01020304643e522d42000000", "3cdfd3c596e6d24d3b7dbda7479a296f477da8b3eb1d725dc4b9744d81dc837e"},
	{"fill1", "000000000000000000000000002e0401020300040506ff380001070000001234ffff00000000aabbcc7f30b2407742000000", "b1585ab4d6222fcdce7609b0a8904ceb270a274a50aacf9948481c1375db7bb1"},
	{"fill2", "000000000000000000000000002e0401020300040506ff380002070000001234ffff00000000aabb12343d996fda42000000", "db3c137270769c23f53b89a06b52525eede6a180d0e97b42a45223b2b44a5534"},
	{"vft-network-fill3", "000000000000000000000000002e5003a247091122330401020300040506ff380003072000001234ffff0000000000112233445566778899aabbccddeeff1011121314a1a2a379b87e9a42000000", "b741383b0cf467760aa4233781e9d28e9a82b66e1496f1d6c281dbd30d868497"},
	{"unknown-optional", "000000000000000000000000002e0401020300040506ff380000073100001234ffff00000000000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f6d6da71e42000000", "56a690f1f4fa8e8290c3884ee2dadf290340cec903bc7a4b70e0985ba438e71d"},
}

func fcoeTestHex(t testing.TB, literal string) []byte {
	t.Helper()
	wire, err := hex.DecodeString(literal)
	require.NoError(t, err)
	return wire
}

func fcoeTestEthernet(pdu []byte) []byte {
	return append([]byte{0x0e, 0xfc, 0, 1, 2, 3, 0x0e, 0xfc, 0, 4, 5, 6, 0x89, 6}, pdu...)
}

func fcoeTestInfo(t testing.TB, node *base.Node, name string, expected any) {
	t.Helper()
	info, ok := node.Cfg.GetItem("additionInfo").(map[string]any)
	require.True(t, ok, node.Name)
	require.Equal(t, expected, info[name], name)
}

func fcoeTestField(t *testing.T, node *base.Node, name, typ string, expected any, start, end uint64) *base.Node {
	t.Helper()
	field := protocolCorpusFindNode(node, name)
	require.NotNil(t, field, name)
	require.Equal(t, typ, field.Cfg.GetString(base.CfgType), name)
	require.Equal(t, [2]uint64{start, end}, stream_parser.GetNodeResultPos(field), name)
	result, err := field.Result()
	require.NoError(t, err)
	require.Same(t, field, result.Origin)
	protocolCorpusRequireValue(t, node, name, expected)
	switch typ {
	case "uint8":
		require.IsType(t, uint8(0), result.Value, name)
	case "uint16":
		require.IsType(t, uint16(0), result.Value, name)
	case "uint32":
		require.IsType(t, uint32(0), result.Value, name)
	case "raw":
		require.IsType(t, []byte{}, result.Value, name)
	}
	return field
}

func fcoeTestInnerRoot(t *testing.T, root *base.Node) *base.Node {
	t.Helper()
	field := protocolCorpusFindNode(root, "R_CTL")
	require.NotNil(t, field)
	return field.Cfg.GetItem(base.CfgParent).(*base.Node).Cfg.GetItem(base.CfgParent).(*base.Node)
}

func fcoeTestOuterRoot(t *testing.T, root *base.Node) *base.Node {
	t.Helper()
	field := protocolCorpusFindNode(root, "SOF")
	require.NotNil(t, field)
	return field.Cfg.GetItem(base.CfgParent).(*base.Node)
}

func fcoeTestTree(t *testing.T, root *base.Node, wire []byte, bitOffset uint64) {
	t.Helper()
	position := bitOffset
	var walk func(*base.Node)
	walk = func(n *base.Node) {
		if stream_parser.NodeHasResult(n) {
			span := stream_parser.GetNodeResultPos(n)
			require.Equal(t, position, span[0], n.Name)
			require.Greater(t, span[1], span[0], n.Name)
			position = span[1]
			value, err := n.Result()
			require.NoError(t, err)
			require.Same(t, n, value.Origin)
			return
		}
		for _, child := range n.Children {
			require.Same(t, n, child.Cfg.GetItem(base.CfgParent), child.Name)
			// Imports get an independent rule context, but all children must
			// still share the exact output buffer and writer, not copied data.
			require.Same(t, n.Ctx.GetItem("buffer"), child.Ctx.GetItem("buffer"))
			require.Same(t, n.Ctx.GetItem("writer"), child.Ctx.GetItem("writer"))
			walk(child)
		}
	}
	walk(root)
	require.Equal(t, bitOffset+uint64(len(wire))*8, position)
	require.Equal(t, uint64(len(wire))*8, stream_parser.CalcNodeConsumedLength(root))
	_, err := root.Result()
	require.NoError(t, err)
	if bitOffset%8 == 0 {
		// NodeToBytes intentionally includes the shared-buffer prefix.
		require.Equal(t, wire, NodeToBytes(root)[bitOffset/8:bitOffset/8+uint64(len(wire))])
	}
	require.Nil(t, protocolCorpusFindNode(root, "Frame Check Probe"))
	require.Nil(t, protocolCorpusFindNode(root, "FibreChannelPeekByte"))
}

func fcoeTestInnerFields(t *testing.T, root *base.Node, fc []byte, offset uint64, eof int, sofContext ...int) {
	t.Helper()
	node := fcoeTestInnerRoot(t, root)
	prefix := 0
	if fc[0] == 0x50 {
		prefix = 8
		fcoeTestField(t, node, "VFT R_CTL", "uint8", uint64(0x50), offset, offset+8)
		fcoeTestField(t, node, "VFT Version", "uint8", uint64(0), offset+8, offset+10)
		fcoeTestField(t, node, "VFT Type", "uint8", uint64(0), offset+10, offset+14)
		fcoeTestField(t, node, "VFT Version Reserved", "uint8", uint64(fc[1]&3), offset+14, offset+16)
		fcoeTestField(t, node, "VFT Priority", "uint8", uint64(fc[2]>>5), offset+16, offset+19)
		fcoeTestField(t, node, "VF_ID", "uint16", uint64((binary.BigEndian.Uint16(fc[2:4])>>1)&0xfff), offset+19, offset+31)
		fcoeTestField(t, node, "VFT ID Reserved", "uint8", uint64(fc[3]&1), offset+31, offset+32)
		fcoeTestField(t, node, "VFT Hop Count", "uint8", uint64(fc[4]), offset+32, offset+40)
		fcoeTestField(t, node, "VFT Reserved", "raw", fc[5:8], offset+40, offset+64)
	} else {
		require.Nil(t, protocolCorpusFindNode(node, "VFT Header"))
	}
	h := fc[prefix:]
	start := offset + uint64(prefix)*8
	for _, field := range []struct {
		name, typ string
		from, to  int
	}{
		{"R_CTL", "uint8", 0, 1}, {"D_ID", "uint32", 1, 4}, {"CS_CTL", "uint8", 4, 5},
		{"S_ID", "uint32", 5, 8}, {"FC Type", "uint8", 8, 9}, {"F_CTL", "uint32", 9, 12},
		{"SEQ_ID", "uint8", 12, 13}, {"DF_CTL", "uint8", 13, 14}, {"SEQ_CNT", "uint16", 14, 16},
		{"OX_ID", "uint16", 16, 18}, {"RX_ID", "uint16", 18, 20}, {"Parameter", "uint32", 20, 24},
	} {
		var value uint64
		for _, b := range h[field.from:field.to] {
			value = value<<8 | uint64(b)
		}
		fcoeTestField(t, node, field.name, field.typ, value, start+uint64(field.from)*8, start+uint64(field.to)*8)
	}
	fctl := uint32(h[9])<<16 | uint32(h[10])<<8 | uint32(h[11])
	known := h[13] == 0 || h[13] == 0x20
	require.True(t, known, "only implemented optional-header layouts can succeed")
	sof := -1
	if len(sofContext) != 0 {
		sof = sofContext[0]
	}
	ack := sof == 0x28 || sof == 0x29 || sof == 0x2d || sof == 0x31 || sof == 0x35 || sof == 0x39
	fillSeparated := known && (eof == 0x42 || (eof == 0x41 && ack)) && fctl&0x080000 != 0
	fill := 0
	if fillSeparated {
		fill = int(h[11] & 3)
	}
	dataStart := prefix + 24
	if h[13] == 0x20 {
		fcoeTestField(t, node, "Network Destination", "raw", fc[dataStart:dataStart+8], offset+uint64(dataStart)*8, offset+uint64(dataStart+8)*8)
		fcoeTestField(t, node, "Network Source", "raw", fc[dataStart+8:dataStart+16], offset+uint64(dataStart+8)*8, offset+uint64(dataStart+16)*8)
		dataStart += 16
	} else {
		require.Nil(t, protocolCorpusFindNode(node, "Network Header"))
	}
	name := "FC Data"
	dataEnd := len(fc) - fill
	if dataEnd > dataStart {
		fcoeTestField(t, node, name, "raw", fc[dataStart:dataEnd], offset+uint64(dataStart)*8, offset+uint64(dataEnd)*8)
	} else {
		require.Nil(t, protocolCorpusFindNode(node, name))
	}
	if fill > 0 {
		fcoeTestField(t, node, "Fill Bytes", "raw", fc[dataEnd:], offset+uint64(dataEnd)*8, offset+uint64(len(fc))*8)
	} else {
		require.Nil(t, protocolCorpusFindNode(node, "Fill Bytes"))
	}
	fcoeTestInfo(t, node, "VFT Present", prefix != 0)
	fcoeTestInfo(t, node, "Optional Headers Decoded", known)
	fcoeTestInfo(t, node, "Declared Fill Count", int(h[11]&3))
	fcoeTestInfo(t, node, "Fill Separated", fillSeparated)
	fcoeTestInfo(t, node, "Fill Length", fill)
	fcoeTestInfo(t, node, "EOF Context Available", eof >= 0)
	fcoeTestInfo(t, node, "SOF Context Available", sof >= 0)
	fcoeTestInfo(t, node, "Body Semantics Decoded", false)
	fcoeTestInfo(t, node, "Session State Validated", false)
	fcoeTestInfo(t, node, "Exchange Responder", fctl&0x800000 != 0)
	fcoeTestInfo(t, node, "Sequence Context (Responder-sent)", fctl&0x400000 != 0)
	fcoeTestTree(t, node, fc, offset)
}

func fcoeTestOuterFields(t *testing.T, root *base.Node, pdu []byte, offset uint64, trailer int) {
	t.Helper()
	node := fcoeTestOuterRoot(t, root)
	fcEnd := len(pdu) - 8 - trailer
	fcoeTestField(t, node, "FCoE Version", "uint8", uint64(0), offset, offset+4)
	fcoeTestField(t, node, "FCoE Version Reserved", "uint8", uint64(pdu[0]&15), offset+4, offset+8)
	fcoeTestField(t, node, "FCoE Header Reserved", "raw", pdu[1:13], offset+8, offset+104)
	fcoeTestField(t, node, "SOF", "uint8", uint64(pdu[13]), offset+104, offset+112)
	fcoeTestInnerFields(t, node, pdu[14:fcEnd], offset+112, int(pdu[fcEnd+4]), int(pdu[13]))
	crc := fcoeTestField(t, node, "FC CRC32", "uint32", uint64(binary.LittleEndian.Uint32(pdu[fcEnd:])), offset+uint64(fcEnd)*8, offset+uint64(fcEnd+4)*8)
	require.Equal(t, "little", crc.Cfg.GetString(base.CfgEndian))
	fcoeTestField(t, node, "EOF", "uint8", uint64(pdu[fcEnd+4]), offset+uint64(fcEnd+4)*8, offset+uint64(fcEnd+5)*8)
	fcoeTestField(t, node, "FCoE Trailer Reserved", "raw", pdu[fcEnd+5:fcEnd+8], offset+uint64(fcEnd+5)*8, offset+uint64(fcEnd+8)*8)
	if trailer > 0 {
		fcoeTestField(t, node, "Ethernet FCS", "raw", pdu[len(pdu)-trailer:], offset+uint64(len(pdu)-trailer)*8, offset+uint64(len(pdu))*8)
	}
	fcoeTestInfo(t, node, "FC CRC32 Verified", true)
	fcoeTestInfo(t, node, "FC Region Length", len(pdu)-22-trailer)
	fcoeTestInfo(t, node, "Ethernet FCS Verified", false)
	fcoeTestInfo(t, node, "Trailer Length", trailer)
	fcoeTestInfo(t, node, "Frame Content Declared Invalid", pdu[fcEnd+4] == 0x49)
	fcoeTestInfo(t, node, "Frame Aborted", pdu[fcEnd+4] == 0x50)
	fcoeTestInfo(t, node, "Session State Validated", false)
	fcoeTestTree(t, node, pdu, offset)
}

func TestProtocolCorpusFCoEFieldsAndPublicPaths(t *testing.T) {
	for _, fixture := range fcoeTestFixtures {
		pdu := fcoeTestHex(t, fixture.literal)
		frame := fcoeTestEthernet(pdu)
		require.Equal(t, fixture.frameSHA, fmt.Sprintf("%x", sha256.Sum256(frame)))
		if fixture.name == "unknown-optional" {
			fcoeTestUnsupportedLayout(t, pdu)
			continue
		}
		for _, path := range []struct {
			rule, entry string
			wire        []byte
			offset      uint64
		}{
			{"fcoe", "FCoE", pdu, 0}, {"fcoe", "FCoECarrier", pdu, 0}, {"ethernet", "Ethernet", frame, 112},
		} {
			t.Run(fixture.name+"/"+path.entry, func(t *testing.T) {
				node := protocolCorpusRequireBoundedRuleParse(t, path.wire, path.rule, path.entry)
				fcoeTestOuterFields(t, node, pdu, path.offset, 0)
				require.Nil(t, protocolCorpusFindNode(node, "Unparsed FCoE Payload"))
			})
		}
		for _, entry := range []string{"FibreChannel", "FibreChannelCarrier"} {
			for _, eof := range []int{-1, 0x42} {
				t.Run(fmt.Sprintf("%s/%s/%d", fixture.name, entry, eof), func(t *testing.T) {
					var config map[string]any
					if eof >= 0 {
						config = map[string]any{"fibreChannelEOF": eof}
					}
					fc := pdu[14 : len(pdu)-8]
					node := protocolCorpusRequireBoundedRuleParseWithConfig(t, fc, "fibre_channel", entry, config)
					fcoeTestInnerFields(t, node, fc, 0, eof)
				})
			}
		}
	}
}

func TestProtocolCorpusFCoEOriginalEveryRecord(t *testing.T) {
	expected := fcoeTestHex(t, "020000000002020000000001890600000000000000000000000000000100000000000000000000000000000000000000000000000000")
	for _, name := range []string{"fcoe", "fibre-channel"} {
		frames := protocolCorpusAuditPackets(t, "testdata/protocol-corpus/captures/generated-pr5023/pr5023-gen-"+name+".pcap")
		require.Len(t, frames, 1)
		for _, frame := range frames {
			require.Equal(t, expected, frame)
			require.Len(t, frame[28:46], 18)
			require.Equal(t, uint32(0x884979ac), crc32.ChecksumIEEE(frame[28:46]))
			_, err := parser.ParseBinary(newProtocolCorpusBoundedReader(frame[14:]), "fcoe", "FCoE")
			require.ErrorContains(t, err, "fcoe: incomplete minimum frame")
			_, err = parser.ParseBinary(newProtocolCorpusBoundedReader(frame[28:46]), "fibre_channel", "FibreChannel")
			require.ErrorContains(t, err, "fc: incomplete fixed header")
			for _, path := range []struct {
				rule, entry, raw string
				wire             []byte
				offset           uint64
			}{
				{"fcoe", "FCoECarrier", "Unparsed FCoE Payload", frame[14:], 0},
				{"ethernet", "Ethernet", "Unparsed FCoE Payload", frame, 112},
				{"fibre_channel", "FibreChannelCarrier", "Unparsed Fibre Channel Payload", frame[28:46], 0},
			} {
				node := protocolCorpusRequireBoundedRuleParse(t, path.wire, path.rule, path.entry)
				fcoeTestField(t, node, path.raw, "raw", path.wire[path.offset/8:], path.offset, uint64(len(path.wire))*8)
				require.Nil(t, protocolCorpusFindNode(node, "R_CTL"))
				require.Nil(t, protocolCorpusFindNode(node, "FC CRC32"))
			}
		}
	}
}

func fcoeTestWrapFC(fc []byte, eof byte) []byte {
	pdu := append(make([]byte, 13), 0x2e)
	pdu = append(pdu, fc...)
	pdu = binary.LittleEndian.AppendUint32(pdu, crc32.ChecksumIEEE(fc))
	return append(pdu, eof, 0, 0, 0)
}

func fcoeTestRawFallback(t *testing.T, wire []byte, rule, entry, name string) {
	t.Helper()
	node := protocolCorpusRequireBoundedRuleParse(t, wire, rule, entry)
	fcoeTestField(t, node, name, "raw", wire, 0, uint64(len(wire))*8)
	require.Nil(t, protocolCorpusFindNode(node, "R_CTL"))
	require.Nil(t, protocolCorpusFindNode(node, "FC CRC32"))
	require.Equal(t, wire, NodeToBytes(node))
}

func fcoeTestUnsupportedLayout(t *testing.T, pdu []byte) {
	t.Helper()
	fc := pdu[14 : len(pdu)-8]
	_, err := parser.ParseBinary(newProtocolCorpusBoundedReader(pdu), "fcoe", "FCoE")
	require.ErrorContains(t, err, "fc: unsupported optional-header layout")
	_, err = parser.ParseBinary(newProtocolCorpusBoundedReader(fc), "fibre_channel", "FibreChannel")
	require.ErrorContains(t, err, "fc: unsupported optional-header layout")
	fcoeTestRawFallback(t, pdu, "fcoe", "FCoECarrier", "Unparsed FCoE Payload")
	fcoeTestRawFallback(t, fc, "fibre_channel", "FibreChannelCarrier", "Unparsed Fibre Channel Payload")
	frame := fcoeTestEthernet(pdu)
	node := protocolCorpusRequireBoundedRuleParse(t, frame, "ethernet", "Ethernet")
	fcoeTestField(t, node, "Unparsed FCoE Payload", "raw", pdu, 112, uint64(len(frame))*8)
	require.Nil(t, protocolCorpusFindNode(node, "R_CTL"))
	require.Nil(t, protocolCorpusFindNode(node, "FC CRC32"))
	require.Equal(t, frame, NodeToBytes(node))
}

func TestProtocolCorpusFCoEUnsupportedOptionalLayouts(t *testing.T) {
	first := fcoeTestHex(t, fcoeTestFixtures[0].literal)
	// Supply more than enough bytes for legacy NH16 + AH32 + DH64. Refusal
	// is the explicit implementation profile, not an assumption that every
	// unimplemented layout has an invalid length or a decoded body.
	fc := append(bytes.Clone(first[14:38]), bytes.Repeat([]byte{0x5a}, 128)...)
	for dfctl := 0; dfctl <= 255; dfctl++ {
		if dfctl == 0 || dfctl == 0x20 {
			continue
		}
		fc[13] = byte(dfctl)
		_, err := parser.ParseBinary(newProtocolCorpusBoundedReader(fc), "fibre_channel", "FibreChannel")
		require.ErrorContains(t, err, "fc: unsupported optional-header layout", dfctl)
		fcoeTestRawFallback(t, fc, "fibre_channel", "FibreChannelCarrier", "Unparsed Fibre Channel Payload")
	}
	for _, dfctl := range []byte{1, 2, 3, 0x10, 0x30, 0x31, 0x40, 0x80, 0xff} {
		fc[13] = dfctl
		fcoeTestUnsupportedLayout(t, fcoeTestWrapFC(fc, 0x42))
	}
}

func TestProtocolCorpusFCoEAllShortPrefixes(t *testing.T) {
	for _, fixture := range fcoeTestFixtures {
		pdu := fcoeTestHex(t, fixture.literal)
		for cut := 0; cut < len(pdu); cut++ {
			_, err := parser.ParseBinary(newProtocolCorpusBoundedReader(pdu[:cut]), "fcoe", "FCoE")
			require.Errorf(t, err, "%s cut %d", fixture.name, cut)
			if cut > 0 {
				fcoeTestRawFallback(t, pdu[:cut], "fcoe", "FCoECarrier", "Unparsed FCoE Payload")
			}
		}
		// Bare FC has no total-length field. An aligned shorter Data Field
		// can be a different complete frame, so explicitly check both outcomes.
		fc := pdu[14 : len(pdu)-8]
		minimum := 24
		if fc[0] == 0x50 {
			minimum += 8
		}
		h := fc[minimum-24:]
		if h[13] == 0x20 {
			minimum += 16
		}
		for cut := 0; cut < len(fc); cut++ {
			node, err := parser.ParseBinary(newProtocolCorpusBoundedReader(fc[:cut]), "fibre_channel", "FibreChannel")
			valid := cut >= minimum && cut%4 == 0 && (h[13] == 0 || h[13] == 0x20)
			if valid {
				require.NoError(t, err, "%s FC prefix %d", fixture.name, cut)
				fcoeTestInnerFields(t, node, fc[:cut], 0, -1)
			} else {
				require.Errorf(t, err, "%s FC prefix %d", fixture.name, cut)
				if cut > 0 {
					fcoeTestRawFallback(t, fc[:cut], "fibre_channel", "FibreChannelCarrier", "Unparsed Fibre Channel Payload")
				}
			}
		}
	}
}

func TestProtocolCorpusFCoECRCAndMalformedGeometry(t *testing.T) {
	pdu := fcoeTestHex(t, fcoeTestFixtures[0].literal)
	// Every single-bit change in the complete FC region and stored CRC is
	// detected. Header/trailer reserved bytes are deliberately outside CRC.
	for index := 14; index < len(pdu)-4; index++ {
		for bit := byte(1); bit != 0; bit <<= 1 {
			bad := bytes.Clone(pdu)
			bad[index] ^= bit
			_, err := parser.ParseBinary(newProtocolCorpusBoundedReader(bad), "fcoe", "FCoE")
			require.ErrorContains(t, err, "FC CRC32 mismatch", "byte %d bit %d", index, bit)
			if bit == 1 {
				fcoeTestRawFallback(t, bad, "fcoe", "FCoECarrier", "Unparsed FCoE Payload")
			}
		}
	}
	for _, tc := range []struct {
		name string
		edit func([]byte) []byte
		want string
	}{
		{"version", func(b []byte) []byte { b[0] = 0x10; return b }, "unsupported version"},
		{"sof", func(b []byte) []byte { b[13] = 0; return b }, "unknown SOF"},
		{"eof", func(b []byte) []byte { b[len(b)-4] = 0; return b }, "unknown EOF"},
		{"alignment", func(b []byte) []byte { return append(b, 0) }, "not word-aligned"},
		{"undeclared-fcs", func(b []byte) []byte { return append(b, 0, 0, 0, 0) }, "CRC32 mismatch"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			bad := tc.edit(bytes.Clone(pdu))
			_, err := parser.ParseBinary(newProtocolCorpusBoundedReader(bad), "fcoe", "FCoE")
			require.ErrorContains(t, err, tc.want)
			fcoeTestRawFallback(t, bad, "fcoe", "FCoECarrier", "Unparsed FCoE Payload")
		})
	}
	fc := bytes.Clone(pdu[14 : len(pdu)-8])
	for _, first := range []byte{0x50, 0x51, 0x52, 0x5f} {
		bad := bytes.Clone(fc)
		bad[0] = first
		_, err := parser.ParseBinary(newProtocolCorpusBoundedReader(bad), "fibre_channel", "FibreChannel")
		require.Error(t, err)
		fcoeTestRawFallback(t, fcoeTestWrapFC(bad, 0x42), "fcoe", "FCoECarrier", "Unparsed FCoE Payload")
	}
	vft := fcoeTestHex(t, fcoeTestFixtures[5].literal)
	for _, mutation := range []struct {
		index int
		value byte
	}{{15, 0x40}, {15, 4}, {22, 0x50}, {22, 0x51}} {
		bad := bytes.Clone(vft[14 : len(vft)-8])
		bad[mutation.index-14] = mutation.value
		_, err := parser.ParseBinary(newProtocolCorpusBoundedReader(bad), "fibre_channel", "FibreChannel")
		require.ErrorContains(t, err, "unsupported")
		fcoeTestRawFallback(t, fcoeTestWrapFC(bad, 0x42), "fcoe", "FCoECarrier", "Unparsed FCoE Payload")
	}
}

func TestProtocolCorpusFCoEExternalFramingAndIgnoredReserved(t *testing.T) {
	pdu := fcoeTestHex(t, fcoeTestFixtures[0].literal)
	// Nonzero reserved byte 1 is modern reserved data, not a request to
	// auto-detect the obsolete two-byte FCoE format.
	pdu[0], pdu[1], pdu[12] = 0x0f, 0xa5, 0x5a
	copy(pdu[len(pdu)-3:], []byte{1, 2, 3})
	for _, path := range []struct{ rule, entry string }{{"fcoe", "FCoE"}, {"fcoe", "FCoECarrier"}, {"ethernet", "Ethernet"}} {
		for _, trailer := range []int{0, 4} {
			wire := bytes.Clone(pdu)
			if trailer != 0 {
				wire = append(wire, 0xde, 0xad, 0xbe, 0xef)
			}
			input, offset := wire, uint64(0)
			if path.rule == "ethernet" {
				input, offset = fcoeTestEthernet(wire), 112
			}
			node := protocolCorpusRequireBoundedRuleParseWithConfig(t, input, path.rule, path.entry, map[string]any{"fcoeTrailerLength": trailer})
			fcoeTestOuterFields(t, node, wire, offset, trailer)
			fcoeTestInfo(t, fcoeTestOuterRoot(t, node), "Trailer Length Explicit", true)
		}
	}
	for _, invalid := range []any{-1, 1, 3, 5, 0.5, "4", true, nil} {
		_, err := parser.ParseBinaryWithConfig(newProtocolCorpusBoundedReader(pdu), "fcoe", map[string]any{"fcoeTrailerLength": invalid}, "FCoE")
		require.Error(t, err, invalid)
	}
	for _, target := range []struct{ rule, entry string }{{"fcoe", "FCoE"}, {"fcoe", "FCoECarrier"}, {"fibre_channel", "FibreChannel"}, {"fibre_channel", "FibreChannelCarrier"}} {
		_, err := parser.ParseBinary(bytes.NewReader(pdu), target.rule, target.entry)
		require.ErrorContains(t, err, "explicit")
		_, err = parser.ParseBinary(newProtocolCorpusBoundedReader(nil), target.rule, target.entry)
		require.Error(t, err)
		root, err := base.ParseRule(target.rule + ".yaml")
		require.NoError(t, err)
		root.Cfg.SetItem(base.CfgLength, uint64(len(pdu)*8-1))
		err = root.ParseSubNode(base.NewBitReader(bytes.NewReader(pdu)), target.entry)
		require.ErrorContains(t, err, "byte-sized")
	}
}

func TestProtocolCorpusFCoEFillAndEOFContext(t *testing.T) {
	pdu := fcoeTestHex(t, fcoeTestFixtures[3].literal)
	fc := bytes.Clone(pdu[14 : len(pdu)-8])
	for _, eof := range []byte{0x41, 0x42, 0x49, 0x50} {
		for _, endSequence := range []bool{false, true} {
			wire := bytes.Clone(fc)
			if !endSequence {
				wire[9] &^= 8
			}
			pdu := fcoeTestWrapFC(wire, eof)
			node := protocolCorpusRequireBoundedRuleParse(t, pdu, "fcoe", "FCoE")
			fcoeTestOuterFields(t, node, pdu, 0, 0)
			fcoeTestInfo(t, fcoeTestOuterRoot(t, node), "Frame Content Declared Invalid", eof == 0x49)
			fcoeTestInfo(t, fcoeTestOuterRoot(t, node), "Frame Aborted", eof == 0x50)
		}
	}
	// Without the receive context required for fill interpretation, even a
	// header-only frame with low F_CTL bits remains a factual header parse.
	for _, dfctl := range []byte{0, 0x31} {
		for _, eof := range []int{-1, 0x41, 0x42, 0x50} {
			for _, endSequence := range []bool{false, true} {
				wire := bytes.Clone(fc[:24])
				wire[13] = dfctl
				if !endSequence {
					wire[9] &^= 8
				}
				config := map[string]any{}
				if eof >= 0 {
					config["fibreChannelEOF"] = eof
				}
				node, err := parser.ParseBinaryWithConfig(newProtocolCorpusBoundedReader(wire), "fibre_channel", config, "FibreChannel")
				if dfctl == 0x31 {
					require.ErrorContains(t, err, "unsupported optional-header layout")
					fcoeTestRawFallback(t, wire, "fibre_channel", "FibreChannelCarrier", "Unparsed Fibre Channel Payload")
				} else if eof == 0x42 && endSequence {
					require.ErrorContains(t, err, "fill count exceeds Data Field")
				} else {
					require.NoError(t, err)
					fcoeTestInnerFields(t, node, wire, 0, eof)
				}
			}
		}
	}
	// Fill must not be borrowed from the required Network Header.
	network := fcoeTestHex(t, fcoeTestFixtures[2].literal)
	short := bytes.Clone(network[14 : 14+40])
	short[11] = 1
	_, err := parser.ParseBinaryWithConfig(newProtocolCorpusBoundedReader(short), "fibre_channel", map[string]any{"fibreChannelEOF": 0x42}, "FibreChannel")
	require.ErrorContains(t, err, "incomplete Network Header")
	for _, invalid := range []any{0, 0x43, 0x100, "66", 65.5, true} {
		_, err := parser.ParseBinaryWithConfig(newProtocolCorpusBoundedReader(fc), "fibre_channel", map[string]any{"fibreChannelEOF": invalid}, "FibreChannel")
		require.Error(t, err, invalid)
	}
	// Version-sensitive bits are not treated as universally reserved.
	fc[9] |= 2
	fc[10] |= 0xc0
	node := protocolCorpusRequireBoundedRuleParse(t, fc, "fibre_channel", "FibreChannel")
	fcoeTestInnerFields(t, node, fc, 0, -1)
	for _, contextBits := range []byte{0, 0x40, 0x80, 0xc0} {
		wire := bytes.Clone(fc)
		wire[9] = (wire[9] & 0x3f) | contextBits
		node := protocolCorpusRequireBoundedRuleParse(t, wire, "fibre_channel", "FibreChannel")
		inner := fcoeTestInnerRoot(t, node)
		fcoeTestInfo(t, inner, "Exchange Responder", contextBits&0x80 != 0)
		fcoeTestInfo(t, inner, "Sequence Context (Responder-sent)", contextBits&0x40 != 0)
		require.NotContains(t, inner.Cfg.GetItem("additionInfo").(map[string]any), "Sequence Responder")
		fcoeTestInnerFields(t, node, wire, 0, -1)
	}
}

func TestProtocolCorpusFCoEAcknowledgedTerminalFill(t *testing.T) {
	// Independent regression: changing only SOFi3 -> SOFi2 and EOFt -> EOFn
	// cannot change the FC data/fill or its CRC. Linux fc_exch_setup_hdr emits
	// this combination for END_SEQ in classes which require a BLS ACK.
	original := fcoeTestHex(t, fcoeTestFixtures[3].literal)
	regression := bytes.Clone(original)
	regression[13], regression[len(regression)-4] = 0x2d, 0x41
	require.Equal(t, original[14:len(original)-4], regression[14:len(regression)-4])
	for _, path := range []struct {
		rule, entry string
		wire        []byte
		offset      uint64
	}{
		{"fcoe", "FCoE", regression, 0}, {"fcoe", "FCoECarrier", regression, 0},
		{"ethernet", "Ethernet", fcoeTestEthernet(regression), 112},
	} {
		node := protocolCorpusRequireBoundedRuleParseWithConfig(t, path.wire, path.rule, path.entry,
			map[string]any{"fibreChannelSOF": 0x2e, "fibreChannelEOF": 0x50})
		fcoeTestOuterFields(t, node, regression, path.offset, 0)
		fcoeTestField(t, node, "FC Data", "raw", []byte{0xaa, 0xbb, 0xcc}, path.offset+304, path.offset+328)
		fcoeTestField(t, node, "Fill Bytes", "raw", []byte{0x7f}, path.offset+328, path.offset+336)
	}
	// Check every supported bare-FC SOF and EOF, not a blanket END_SEQ or EOFn rule.
	// The class-3 codes must retain the trailing byte under EOFn; invalid,
	// abort and other terminal delimiters never acquire fill semantics here.
	for _, sof := range []struct {
		value byte
		ack   bool
	}{{0x28, true}, {0x29, true}, {0x2d, true}, {0x2e, false}, {0x31, true}, {0x35, true}, {0x36, false}, {0x39, true}} {
		for _, eof := range []byte{0x41, 0x42, 0x44, 0x46, 0x49, 0x4e, 0x4f, 0x50} {
			for _, endSequence := range []bool{false, true} {
				fc := bytes.Clone(original[14 : len(original)-8])
				if !endSequence {
					fc[9] &^= 8
				}
				node := protocolCorpusRequireBoundedRuleParseWithConfig(t, fc, "fibre_channel", "FibreChannel",
					map[string]any{"fibreChannelSOF": int(sof.value), "fibreChannelEOF": int(eof)})
				fcoeTestInnerFields(t, node, fc, 0, int(eof), int(sof.value))
				wantFill := endSequence && (eof == 0x42 || (eof == 0x41 && sof.ack))
				require.Equal(t, wantFill, protocolCorpusFindNode(node, "Fill Bytes") != nil,
					"SOF=%02x EOF=%02x END_SEQ=%v", sof.value, eof, endSequence)
				if (sof.value == 0x28 || sof.value == 0x2d || sof.value == 0x35 || sof.value == 0x2e || sof.value == 0x36) &&
					(eof == 0x41 || eof == 0x42 || eof == 0x49 || eof == 0x50) {
					wire := fcoeTestWrapFC(fc, eof)
					wire[13] = sof.value
					outer := protocolCorpusRequireBoundedRuleParse(t, wire, "fcoe", "FCoE")
					fcoeTestOuterFields(t, outer, wire, 0, 0)
					require.Equal(t, wantFill, protocolCorpusFindNode(outer, "Fill Bytes") != nil)
				}
			}
		}
	}
	// Bare FC requires explicit SOF for EOFn; both carrier and direct paths
	// preserve the same values, spans and caller-supplied context.
	for _, fixture := range []int{3, 4, 5, 6} {
		pdu := fcoeTestHex(t, fcoeTestFixtures[fixture].literal)
		fc := pdu[14 : len(pdu)-8]
		for _, entry := range []string{"FibreChannel", "FibreChannelCarrier"} {
			for _, sof := range []int{-1, 0x2d, 0x35, 0x2e} {
				config := map[string]any{"fibreChannelEOF": 0x41}
				if sof >= 0 {
					config["fibreChannelSOF"] = sof
				}
				if fixture == 6 {
					node, err := parser.ParseBinaryWithConfig(newProtocolCorpusBoundedReader(fc), "fibre_channel", config, entry)
					if entry == "FibreChannel" {
						require.ErrorContains(t, err, "unsupported optional-header layout")
					} else {
						require.NoError(t, err)
						fcoeTestField(t, node, "Unparsed Fibre Channel Payload", "raw", fc, 0, uint64(len(fc))*8)
						require.Nil(t, protocolCorpusFindNode(node, "R_CTL"))
						require.Equal(t, fc, NodeToBytes(node))
					}
					continue
				}
				node := protocolCorpusRequireBoundedRuleParseWithConfig(t, fc, "fibre_channel", entry, config)
				fcoeTestInnerFields(t, node, fc, 0, 0x41, sof)
			}
		}
	}
	fc := original[14 : len(original)-8]
	for _, invalid := range []any{nil, 0, 0x27, 0x100, "45", 45.5, true} {
		_, err := parser.ParseBinaryWithConfig(newProtocolCorpusBoundedReader(fc), "fibre_channel",
			map[string]any{"fibreChannelEOF": 0x41, "fibreChannelSOF": invalid}, "FibreChannel")
		require.ErrorContains(t, err, "unknown external SOF", invalid)
	}
	for _, eof := range []int{-1, 0x41, 0x50} {
		config := map[string]any{"fibreChannelSOF": 0x2d}
		if eof >= 0 {
			config["fibreChannelEOF"] = eof
		}
		// A declared byte of fill without any Data Field is malformed only
		// once the applicable normal terminal context has been established.
		node, err := parser.ParseBinaryWithConfig(newProtocolCorpusBoundedReader(fc[:24]), "fibre_channel", config, "FibreChannel")
		if eof == 0x41 {
			require.ErrorContains(t, err, "fill count exceeds Data Field")
		} else {
			require.NoError(t, err)
			fcoeTestInnerFields(t, node, fc[:24], 0, eof, 0x2d)
		}
	}
	// The acknowledged terminal case cannot borrow a byte from an incomplete
	// Network Header, and its carrier must remove all partially decoded fields.
	network := fcoeTestHex(t, fcoeTestFixtures[2].literal)
	short := bytes.Clone(network[14 : 14+40])
	short[11] = 1
	pdu := fcoeTestWrapFC(short, 0x41)
	pdu[13] = 0x2d
	_, err := parser.ParseBinary(newProtocolCorpusBoundedReader(pdu), "fcoe", "FCoE")
	require.ErrorContains(t, err, "incomplete Network Header")
	fcoeTestRawFallback(t, pdu, "fcoe", "FCoECarrier", "Unparsed FCoE Payload")
}

func TestProtocolCorpusFCoEDelimiterProfile(t *testing.T) {
	// FC-BB-5 Rev 2.00 section 7.7 tables 22/23, not the broader general FC
	// encapsulation enum or the older UNH tutorial's draft-revision table.
	original := fcoeTestHex(t, fcoeTestFixtures[0].literal)
	for _, field := range []struct {
		name    string
		offset  int
		allowed map[byte]bool
	}{
		{"SOF", 13, map[byte]bool{0x28: true, 0x2d: true, 0x35: true, 0x2e: true, 0x36: true}},
		{"EOF", len(original) - 4, map[byte]bool{0x41: true, 0x42: true, 0x49: true, 0x50: true}},
	} {
		for value := 0; value <= 255; value++ {
			wire := bytes.Clone(original)
			wire[field.offset] = byte(value)
			// The delimiter is outside the protected FC bytes: these failures
			// must be profile failures, not manufactured CRC failures.
			require.Equal(t, original[14:len(original)-4], wire[14:len(wire)-4])
			node, err := parser.ParseBinary(newProtocolCorpusBoundedReader(wire), "fcoe", "FCoE")
			if field.allowed[byte(value)] {
				require.NoError(t, err, field.name, value)
				fcoeTestOuterFields(t, node, wire, 0, 0)
			} else {
				require.ErrorContains(t, err, "unknown "+field.name+" delimiter", field.name, value)
				fcoeTestRawFallback(t, wire, "fcoe", "FCoECarrier", "Unparsed FCoE Payload")
			}
		}
	}
}

func TestProtocolCorpusFCoECompanionEveryRecord(t *testing.T) {
	frames := protocolCorpusAuditPackets(t, "testdata/protocol-corpus/captures/generated-validated/gen-fcoe-valid.pcap")
	require.Len(t, frames, len(fcoeTestFixtures))
	for index, frame := range frames {
		pdu := fcoeTestHex(t, fcoeTestFixtures[index].literal)
		require.Equal(t, fcoeTestEthernet(pdu), frame)
		if index == 6 {
			// Preserve this exact record as an unsupported negative: its 32B
			// Data Field cannot fit legacy NH16 + AH32 + DH16 at DF_CTL=31.
			fcoeTestUnsupportedLayout(t, pdu)
			continue
		}
		for _, path := range []struct {
			rule, entry string
			wire        []byte
			offset      uint64
		}{
			{"fcoe", "FCoE", pdu, 0}, {"fcoe", "FCoECarrier", pdu, 0}, {"ethernet", "Ethernet", frame, 112},
		} {
			node := protocolCorpusRequireBoundedRuleParse(t, path.wire, path.rule, path.entry)
			fcoeTestOuterFields(t, node, pdu, path.offset, 0)
		}
		fc := frame[28 : len(frame)-8]
		node := protocolCorpusRequireBoundedRuleParse(t, fc, "fibre_channel", "FibreChannel")
		fcoeTestInnerFields(t, node, fc, 0, -1)
	}
}

func fcoeTestInline(t *testing.T, source string) *base.Node {
	t.Helper()
	var document yaml.MapSlice
	require.NoError(t, yaml.Unmarshal([]byte(source), &document))
	root, err := base.NewNodeTree(document)
	require.NoError(t, err)
	return root
}

func TestProtocolCorpusFCoECRCIndependentVector(t *testing.T) {
	root := fcoeTestInline(t, `
endian: big
Package:
  CRC:
    operator: |
      data = this.ProcessSubNode("Data").Value
      if fcoeCRC32IEEE(data) != 0xcbf43926 { panic("incorrect independent CRC32 vector") }
      if fcoeCRC32IEEE(data[:0]) != 0 { panic("incorrect empty CRC32 vector") }
    Data: raw,9
`)
	reader := bytes.NewReader([]byte("123456789"))
	root.Cfg.SetItem(base.CfgLength, uint64(72))
	require.NoError(t, root.ParseSubNode(base.NewBitReader(reader), "CRC"))
	require.Zero(t, reader.Len())
}

func TestProtocolCorpusFCoEGlobalBitOffsetsAndTransactions(t *testing.T) {
	valid := fcoeTestHex(t, fcoeTestFixtures[5].literal)
	for offset := uint64(0); offset < 8; offset++ {
		for _, outcome := range []string{"valid", "ack-terminal", "bad-crc", "unsupported-inner", "unsupported-layout"} {
			t.Run(fmt.Sprintf("%d/%s", offset, outcome), func(t *testing.T) {
				pdu := bytes.Clone(valid)
				if outcome == "ack-terminal" {
					pdu[13], pdu[len(pdu)-4] = 0x2d, 0x41
				} else if outcome == "bad-crc" {
					pdu[len(pdu)-8] ^= 1
				} else if outcome == "unsupported-inner" {
					fc := bytes.Clone(pdu[14 : len(pdu)-8])
					fc[8] = 0x51
					pdu = fcoeTestWrapFC(fc, 0x42)
				} else if outcome == "unsupported-layout" {
					fc := bytes.Clone(pdu[14 : len(pdu)-8])
					fc[8+13] = 0x31
					pdu = fcoeTestWrapFC(fc, 0x42)
				}
				var packed bytes.Buffer
				writer := base.NewBitWriter(&packed)
				if offset > 0 {
					require.NoError(t, writer.WriteBits([]byte{0x55}, offset))
				}
				require.NoError(t, writer.WriteBits(pdu, uint64(len(pdu))*8))
				require.NoError(t, writer.WriteBits([]byte{0xd3}, 8))
				if offset > 0 {
					require.NoError(t, writer.WriteBits([]byte{0}, 8-offset))
				}
				root := fcoeTestInline(t, fmt.Sprintf(`
endian: big
Package:
  Wrapped:
    operator: |
      if %d > 0 { this.ProcessSubNode("Prefix") }
      this.GetSubNode("Frame").SetMaxLength(%d)
      this.ProcessSubNode("Frame")
      this.ProcessSubNode("Sentinel")
      if %d > 0 { this.ProcessSubNode("Padding") }
    Prefix: uint8,%dbit
    Frame: "import:fcoe.yaml;node:FCoECarrier"
    Sentinel: uint8
    Padding: uint8,%dbit
`, offset, len(pdu), offset, offset, 8-offset))
				root.Cfg.SetItem(base.CfgLength, uint64(packed.Len())*8)
				root.Ctx.SetItem("fibreChannelEOF", 0x41) // The enclosing wire's EOF must win.
				root.Ctx.SetItem("fibreChannelSOF", 0x2e) // The enclosing wire's class must win too.
				reader := base.NewBitReader(bytes.NewReader(packed.Bytes()))
				require.NoError(t, root.ParseSubNode(reader, "Wrapped"))
				wrapped := base.GetNodeByPath(root, "@Wrapped")
				frame := protocolCorpusFindNode(wrapped, "Frame")
				require.NotNil(t, frame)
				if outcome == "valid" || outcome == "ack-terminal" {
					fcoeTestOuterFields(t, frame, pdu, offset, 0)
				} else {
					fcoeTestField(t, frame, "Unparsed FCoE Payload", "raw", pdu, offset, offset+uint64(len(pdu))*8)
					require.Nil(t, protocolCorpusFindNode(frame, "R_CTL"))
					require.Nil(t, protocolCorpusFindNode(frame, "SOF"))
				}
				fcoeTestField(t, wrapped, "Sentinel", "uint8", uint64(0xd3), offset+uint64(len(pdu))*8, offset+uint64(len(pdu)+1)*8)
				require.Equal(t, 0x41, root.Ctx.GetItem("fibreChannelEOF"))
				require.Equal(t, 0x2e, root.Ctx.GetItem("fibreChannelSOF"))
				require.False(t, root.Ctx.Has("FC EOF"))
				require.False(t, root.Ctx.Has("FC SOF"))
				require.ErrorContains(t, reader.Recovery(), "no backup")
				require.ErrorContains(t, reader.PopBackup(), "no backup")
				require.Equal(t, packed.Bytes(), NodeToBytes(wrapped))
				_, err := reader.ReadBits(8)
				require.ErrorIs(t, err, io.EOF)
			})
		}
	}
}

func TestProtocolCorpusFCoEShortPhysicalReader(t *testing.T) {
	valid := fcoeTestHex(t, fcoeTestFixtures[5].literal)
	for _, target := range []struct {
		rule, entry string
		wire        []byte
	}{
		{"fcoe", "FCoECarrier", valid}, {"fibre_channel", "FibreChannelCarrier", valid[14 : len(valid)-8]},
	} {
		for available := 0; available < len(target.wire); available++ {
			root, err := base.ParseRule(target.rule + ".yaml")
			require.NoError(t, err)
			root.Cfg.SetItem(base.CfgLength, uint64(len(target.wire))*8)
			reader := base.NewBitReader(bytes.NewReader(target.wire[:available]))
			err = root.ParseSubNode(reader, target.entry)
			require.Error(t, err, available)
			carrier := base.GetNodeByPath(root, "@"+target.entry)
			require.Nil(t, protocolCorpusFindNode(carrier, "SOF"))
			require.Nil(t, protocolCorpusFindNode(carrier, "R_CTL"))
			require.Nil(t, protocolCorpusFindNode(carrier, "FC CRC32"))
			require.ErrorContains(t, reader.Recovery(), "no backup")
			require.ErrorContains(t, reader.PopBackup(), "no backup")
		}
	}
}

func TestProtocolCorpusFCoETaggedPublicPaths(t *testing.T) {
	for _, fixture := range fcoeTestFixtures {
		for _, trailer := range []int{0, 4} {
			pdu := fcoeTestHex(t, fixture.literal)
			if trailer != 0 {
				pdu = append(pdu, 0xde, 0xad, 0xbe, 0xef)
			}
			for _, tag := range [][]byte{
				{0x81, 0, 0xb0, 0x7b, 0x89, 6},
				{0x88, 0xa8, 0xb0, 0x7b, 0x89, 6},
				{0x88, 0xa8, 0xb0, 0x7b, 0x81, 0, 0x20, 0x42, 0x89, 6},
			} {
				frame := append(bytes.Clone(fcoeTestEthernet(nil)[:12]), tag...)
				offset := uint64(len(frame)) * 8
				frame = append(frame, pdu...)
				config := map[string]any{"fcoeTrailerLength": trailer}
				node := protocolCorpusRequireBoundedRuleParseWithConfig(t, frame, "ethernet", "Ethernet", config)
				if fixture.name == "unknown-optional" {
					fcoeTestField(t, node, "Unparsed FCoE Payload", "raw", pdu, offset, uint64(len(frame))*8)
					require.Nil(t, protocolCorpusFindNode(node, "R_CTL"))
					require.Equal(t, frame, NodeToBytes(node))
				} else {
					fcoeTestOuterFields(t, node, pdu, offset, trailer)
				}
				frame[int(offset/8)+len(pdu)-8-trailer] ^= 1
				node = protocolCorpusRequireBoundedRuleParseWithConfig(t, frame, "ethernet", "Ethernet", config)
				fcoeTestField(t, node, "Unparsed FCoE Payload", "raw", frame[offset/8:], offset, uint64(len(frame))*8)
				require.Nil(t, protocolCorpusFindNode(node, "R_CTL"))
			}
		}
	}
}

func TestProtocolCorpusFCoEStructuredGenerationUnsupported(t *testing.T) {
	input := map[string]any{"Version Byte": map[string]any{"FCoE Version": uint8(0)}, "SOF": uint8(0x2e), "EOF": uint8(0x42), "FC CRC32": uint32(0xe116194a)}
	for _, target := range []struct{ rule, entry string }{{"fcoe", "FCoE"}, {"fcoe", "FCoECarrier"}, {"fibre_channel", "FibreChannel"}, {"fibre_channel", "FibreChannelCarrier"}} {
		_, err := parser.GenerateBinary(input, target.rule, target.entry)
		require.ErrorContains(t, err, "explicit")
	}
}

func TestProtocolCorpusFCoEResourceProfiles(t *testing.T) {
	fixture := fcoeTestHex(t, fcoeTestFixtures[0].literal)
	baseFrame := append(bytes.Clone(fixture[14:38]), bytes.Repeat([]byte{0x5a}, 2112)...)
	for _, prefix := range [][]byte{nil, {0x50, 0, 0, 2, 1, 0, 0, 0}} {
		fc := append(bytes.Clone(prefix), baseFrame...)
		pdu := fcoeTestWrapFC(fc, 0x42)
		pdu = append(pdu, 1, 2, 3, 4)
		node := protocolCorpusRequireBoundedRuleParseWithConfig(t, pdu, "fcoe", "FCoE", map[string]any{"fcoeTrailerLength": 4})
		fcoeTestOuterFields(t, node, pdu, 0, 4)
		count := 0
		var walk func(*base.Node)
		walk = func(n *base.Node) {
			count++
			for _, child := range n.Children {
				walk(child)
			}
		}
		walk(node)
		require.Less(t, count, 100, "raw payload length must not grow the field tree")
		oversized := append(bytes.Clone(fc), 0, 0, 0, 0)
		_, err := parser.ParseBinary(newProtocolCorpusBoundedReader(oversized), "fibre_channel", "FibreChannel")
		require.ErrorContains(t, err, "profile")
		fcoeTestRawFallback(t, fcoeTestWrapFC(oversized, 0x42), "fcoe", "FCoECarrier", "Unparsed FCoE Payload")
	}
	// Above-profile advertised lengths fail before even the first physical byte.
	for _, tc := range []struct {
		rule, entry string
		size        int
	}{{"fcoe", "FCoE", 2171}, {"fibre_channel", "FibreChannel", 2145}} {
		root, err := base.ParseRule(tc.rule + ".yaml")
		require.NoError(t, err)
		root.Cfg.SetItem(base.CfgLength, uint64(tc.size)*8)
		err = root.ParseSubNode(base.NewBitReader(bytes.NewReader(nil)), tc.entry)
		require.ErrorContains(t, err, "profile")
	}
}

func TestProtocolCorpusFCoEParallelIsolation(t *testing.T) {
	var group sync.WaitGroup
	errors := make(chan error, 48)
	for index := 0; index < 48; index++ {
		index := index
		pdu := fcoeTestHex(t, fcoeTestFixtures[index%len(fcoeTestFixtures)].literal)
		unsupported := index%len(fcoeTestFixtures) == 6
		group.Add(1)
		go func() {
			defer group.Done()
			entry := "FCoE"
			var config map[string]any
			if index%2 == 0 {
				entry = "FCoECarrier"
			}
			if index%3 == 0 {
				pdu = append(pdu, byte(index), 0, 0, 0)
				config = map[string]any{"fcoeTrailerLength": 4}
			}
			node, err := parser.ParseBinaryWithConfig(newProtocolCorpusBoundedReader(pdu), "fcoe", config, entry)
			if unsupported && entry == "FCoE" {
				if err != nil && strings.Contains(err.Error(), "unsupported optional-header layout") {
					errors <- nil
				} else {
					errors <- fmt.Errorf("unexpected unsupported record outcome %d: %v", index, err)
				}
				return
			}
			if err == nil && unsupported && (protocolCorpusFindNode(node, "Unparsed FCoE Payload") == nil || protocolCorpusFindNode(node, "R_CTL") != nil) {
				err = fmt.Errorf("incomplete unsupported record rollback %d", index)
			}
			if err == nil && !unsupported && protocolCorpusFindNode(node, "FC CRC32") == nil {
				err = fmt.Errorf("missing parsed CRC at record %d", index)
			}
			if err == nil && !bytes.Equal(pdu, NodeToBytes(node)) {
				err = fmt.Errorf("cross-record bytes at record %d", index)
			}
			if err == nil {
				_, err = node.Result()
			}
			errors <- err
		}()
	}
	group.Wait()
	close(errors)
	for err := range errors {
		require.NoError(t, err)
	}
}
