package bin_parser

// ProtocolInfo describes one dissector in the YAML rule set.
type ProtocolInfo struct {
	Name       string
	Layer      string
	RuleFile   string
	EntryNode  string
	Status     string
	Notes      string
	SampleFrom string
}

const (
	statusStable  = "stable"
	statusPartial = "partial"
	statusNew     = "new"
)

// ProtocolCatalog is the protocol coverage list for the Wireshark-like
// binary parser. Status is "stable" when existing tests already lock
// behavior, "new" for dissectors added in this work, and "partial" when
// only a subset of PDUs/fields is decoded.
var ProtocolCatalog = []ProtocolInfo{
	{Name: "Ethernet", Layer: "L2", RuleFile: "ethernet.yaml", Status: statusStable, SampleFrom: "existing ethernet fixtures"},
	{Name: "IEEE 802.1Q", Layer: "L2", RuleFile: "ieee_802_1q.yaml", Status: statusNew, SampleFrom: "gopacket Dot1Q (Wireshark-compatible)"},
	{Name: "ARP", Layer: "L2", RuleFile: "address_resolution_protocol.yaml", Status: statusStable, SampleFrom: "existing ethernet fixtures"},
	{Name: "PPP", Layer: "L2", RuleFile: "ppp.yaml", Status: statusStable, SampleFrom: "existing PPP/GRE fixtures"},
	{Name: "LCP", Layer: "L2", RuleFile: "link_control_protocol.yaml", Status: statusStable},
	{Name: "PAP", Layer: "L2", RuleFile: "password_authentication_protocol.yaml", Status: statusStable},
	{Name: "CHAP", Layer: "L2", RuleFile: "challenge_handshake_authentication_protocol.yaml", Status: statusStable},
	{Name: "EAPOL", Layer: "L2", RuleFile: "eapol.yaml", Status: statusNew, Notes: "802.1X Start/Logoff/EAP-Packet/Key", SampleFrom: "Wireshark wpa-Induction.pcap frame 87 (via gopacket)"},
	{Name: "IPv4", Layer: "L3", RuleFile: "internet_protocol.yaml", Status: statusStable, SampleFrom: "existing ethernet fixtures"},
	{Name: "IPv6", Layer: "L3", RuleFile: "internet_protocol_version_6.yaml", Status: statusStable, SampleFrom: "existing ethernet fixtures"},
	{Name: "ICMP", Layer: "L3", RuleFile: "internet_control_message_protocol.yaml", Status: statusNew, Notes: "echo, dest-unreach, time-exceeded, redirect, timestamp"},
	{Name: "ICMPv6", Layer: "L3", RuleFile: "internet_control_message_protocol_v6.yaml", Status: statusNew, Notes: "echo/NS/NA/RS/RA"},
	{Name: "GRE", Layer: "L3", RuleFile: "generic_routing_encapsulation.yaml", Status: statusStable},
	{Name: "TCP", Layer: "L4", RuleFile: "transmission_control_protocol.yaml", Status: statusStable},
	{Name: "UDP", Layer: "L4", RuleFile: "user_datagram_protocol.yaml", Status: statusStable},
	{Name: "DNS", Layer: "L7", RuleFile: "application-layer/dns.yaml", Status: statusStable, SampleFrom: "existing ethernet fixtures"},
	{Name: "HTTP", Layer: "L7", RuleFile: "application-layer/http.yaml", Status: statusNew, Notes: "request/response + CONNECT + WPAD", SampleFrom: "existing ethernet fixtures"},
	{Name: "TLS", Layer: "L7", RuleFile: "application-layer/tls.yaml", Status: statusNew, Notes: "record 20-24 + ClientHello + extensions; Payload for app-data", SampleFrom: "gopacket tls_test.go (scapy-ssl_tls pcap)"},
	{Name: "DHCP", Layer: "L7", RuleFile: "application-layer/dhcp.yaml", Status: statusNew, SampleFrom: "gopacket DHCPv4 (RFC 2131)"},
	{Name: "NTP", Layer: "L7", RuleFile: "application-layer/ntp.yaml", Status: statusNew, SampleFrom: "Wireshark SampleCaptures NTP_sync.pcap (via gopacket testdata)"},
	{Name: "SNMP", Layer: "L7", RuleFile: "application-layer/snmp.yaml", Status: statusNew, Notes: "SNMPv1/v2c Get/Set + varbind SEQUENCE", SampleFrom: "RFC 1157 GetRequest"},
	{Name: "SSH", Layer: "L7", RuleFile: "application-layer/ssh.yaml", Status: statusNew, Notes: "identification + binary packet", SampleFrom: "RFC 4253"},
	{Name: "FTP", Layer: "L7", RuleFile: "application-layer/ftp.yaml", Status: statusNew, Notes: "reply + commands", SampleFrom: "RFC 959"},
	{Name: "SMTP", Layer: "L7", RuleFile: "application-layer/smtp.yaml", Status: statusNew, Notes: "reply + commands", SampleFrom: "RFC 5321"},
	{Name: "Redis", Layer: "L7", RuleFile: "application-layer/redis.yaml", Status: statusNew, Notes: "RESP arrays/bulk/simple", SampleFrom: "Redis RESP PING"},
	{Name: "MQTT", Layer: "L7", RuleFile: "application-layer/mqtt.yaml", Status: statusNew, Notes: "CONNECT/CONNACK + 1/2-byte remaining length", SampleFrom: "MQTT 3.1.1 CONNECT"},
	{Name: "SOCKS5", Layer: "L7", RuleFile: "application-layer/socks5.yaml", Status: statusStable, SampleFrom: "existing socks5 fixtures"},
	{Name: "LDAP", Layer: "L7", RuleFile: "application-layer/ldap.yaml", Status: statusNew, Notes: "SEQUENCE + bind/unbind/search"},
	{Name: "NTLM", Layer: "L7", RuleFile: "application-layer/ntlm.yaml", Status: statusNew, Notes: "see NTLMSSP type 1/2/3"},
	{Name: "MSRdp", Layer: "L7", RuleFile: "application-layer/msrdp.yaml", Status: statusNew, Notes: "TPKT + X224 CR/CC + Cookie/Negotiation"},
	{Name: "IIOP", Layer: "L7", RuleFile: "application-layer/iiop.yaml", Status: statusNew, SampleFrom: "GIOP 1.2 LocateRequest NameService"},
	{Name: "T3", Layer: "L7", RuleFile: "application-layer/t3.yaml", Status: statusNew, SampleFrom: "T3 hello 12.2.1 AS/HL + IDENTIFY header"},
	{Name: "PPTP", Layer: "L7", RuleFile: "application-layer/pptp.yaml", Status: statusNew, SampleFrom: "RFC 2637 SCCRQ"},
	{Name: "BER", Layer: "L7", RuleFile: "application-layer/ber.yaml", Status: statusNew, SampleFrom: "X.690 INTEGER"},
	{Name: "SMB2", Layer: "L7", RuleFile: "application-layer/smb2.yaml", Status: statusNew, Notes: "header + NEGOTIATE + SESSION_SETUP", SampleFrom: "[MS-SMB2] 2.2.1/2.2.3/2.2.4/2.2.5"},
	{Name: "SMB", Layer: "L7", RuleFile: "application-layer/smb.yaml", Status: statusNew, Notes: "NEGOTIATE/AndX/CLOSE/TRANSACTION", SampleFrom: "[MS-CIFS] 2.2.3.1/2.2.4.52"},
	{Name: "NBT SS", Layer: "L4", RuleFile: "application-layer/nbss.yaml", Status: statusNew, Notes: "session message wrapping SMB/SMB2", SampleFrom: "RFC 1002"},
	{Name: "MySQL", Layer: "L7", RuleFile: "application-layer/mysql.yaml", Status: statusNew, Notes: "HandshakeV10 including plugin data/name + OK/ERR/COM", SampleFrom: "MySQL HandshakeV10 internals doc"},
	{Name: "NTLMSSP", Layer: "L7", RuleFile: "application-layer/ntlm.yaml", Status: statusNew, Notes: "signature + type 1/2/3 dispatcher", SampleFrom: "[MS-NLMP] 2.2.1"},
	{Name: "Kerberos", Layer: "L7", RuleFile: "application-layer/kerberos.yaml", Status: statusNew, Notes: "APPLICATION tags AS/TGS/AP/ERROR, TCP record", SampleFrom: "RFC 4120"},
	{Name: "PostgreSQL", Layer: "L7", RuleFile: "application-layer/postgresql.yaml", Status: statusNew, Notes: "startup/SSL/cancel + typed messages", SampleFrom: "PostgreSQL protocol 3.0"},
	{Name: "MSSQL TDS", Layer: "L7", RuleFile: "application-layer/tds.yaml", Status: statusNew, Notes: "TDS header PRELOGIN/LOGIN7/BATCH/RESPONSE", SampleFrom: "[MS-TDS] 2.2.1"},
	{Name: "AJP", Layer: "L7", RuleFile: "application-layer/ajp.yaml", Status: statusNew, Notes: "AJP13 magic 0x1234/AB, CPING/FORWARD", SampleFrom: "Apache AJP13"},
	{Name: "SPNEGO", Layer: "L7", RuleFile: "application-layer/spnego.yaml", Status: statusNew, Notes: "GSS-API 0x60 + OID", SampleFrom: "RFC 4178"},
	{Name: "NetNTLMv2", Layer: "L7", RuleFile: "application-layer/ntlm.yaml", Status: statusNew, Notes: "NTProofStr + client challenge blob", SampleFrom: "[MS-NLMP] 3.3.2"},
	{Name: "Kerberos PAC", Layer: "L7", RuleFile: "application-layer/kerberos.yaml", Status: statusNew, Notes: "PAC_INFO_BUFFER list", SampleFrom: "[MS-PAC] 2.3"},
	{Name: "HTTP/2", Layer: "L7", RuleFile: "application-layer/http2.yaml", Status: statusNew, Notes: "preface + DATA/SETTINGS list/PING/GOAWAY/WINDOW_UPDATE", SampleFrom: "RFC 9113"},
	{Name: "WebSocket", Layer: "L7", RuleFile: "application-layer/websocket.yaml", Status: statusNew, Notes: "RFC 6455 frame", SampleFrom: "RFC 6455 §5.7 Hello + close 1000"},
	{Name: "QUIC", Layer: "L4", RuleFile: "application-layer/quic.yaml", Status: statusNew, Notes: "long/short header + CID", SampleFrom: "RFC 9001 A.2/A.3 Initial DCID/SCID"},
	{Name: "RADIUS", Layer: "L7", RuleFile: "application-layer/radius.yaml", Status: statusNew, Notes: "RFC 2865 header + attribute list", SampleFrom: "gopacket radius_test.go (Wireshark radtest.pcap)"},
	{Name: "Oracle TNS", Layer: "L7", RuleFile: "application-layer/tns.yaml", Status: statusNew, Notes: "TNS packet header types 1-15", SampleFrom: "Oracle TNS"},
	{Name: "TNS", Layer: "L7", RuleFile: "application-layer/tns.yaml", Status: statusNew, Notes: "alias of Oracle TNS", SampleFrom: "Oracle TNS"},
	{Name: "DCE/RPC", Layer: "L7", RuleFile: "application-layer/dcerpc.yaml", Status: statusNew, Notes: "v5 header + bind/request", SampleFrom: "[MS-RPCE] 2.2.2.6"},
	{Name: "MSRPC", Layer: "L7", RuleFile: "application-layer/dcerpc.yaml", Status: statusNew, Notes: "same as DCE/RPC", SampleFrom: "[MS-RPCE]"},
	{Name: "MSRPC EPM", Layer: "L7", RuleFile: "application-layer/dcerpc.yaml", Status: statusNew, Notes: "bind UUID + request opnum", SampleFrom: "[MS-RPCE] epmapper"},
	{Name: "SAMR", Layer: "L7", RuleFile: "application-layer/dcerpc.yaml", Status: statusNew, Notes: "DCE/RPC bind UUID", SampleFrom: "[MS-SAMR]"},
	{Name: "LSARPC", Layer: "L7", RuleFile: "application-layer/dcerpc.yaml", Status: statusNew, Notes: "DCE/RPC bind UUID", SampleFrom: "[MS-LSAT]"},
	{Name: "NETLOGON", Layer: "L7", RuleFile: "application-layer/dcerpc.yaml", Status: statusNew, Notes: "DCE/RPC bind UUID", SampleFrom: "[MS-NRPC]"},
	{Name: "DRSUAPI", Layer: "L7", RuleFile: "application-layer/dcerpc.yaml", Status: statusNew, Notes: "DCE/RPC bind UUID", SampleFrom: "[MS-DRSR]"},
	{Name: "SRVSVC", Layer: "L7", RuleFile: "application-layer/dcerpc.yaml", Status: statusNew, Notes: "DCE/RPC bind UUID", SampleFrom: "[MS-SRVS]"},
	{Name: "SVCCTL", Layer: "L7", RuleFile: "application-layer/dcerpc.yaml", Status: statusNew, Notes: "DCE/RPC bind UUID", SampleFrom: "[MS-SCMR]"},
	{Name: "WINREG", Layer: "L7", RuleFile: "application-layer/dcerpc.yaml", Status: statusNew, Notes: "DCE/RPC bind UUID", SampleFrom: "[MS-RRP]"},
	{Name: "WMI", Layer: "L7", RuleFile: "application-layer/dcerpc.yaml", Status: statusNew, Notes: "DCOM/WMI via DCE/RPC header", SampleFrom: "[MS-WMI]"},
	{Name: "DCOM", Layer: "L7", RuleFile: "application-layer/dcerpc.yaml", Status: statusNew, Notes: "DCOM via DCE/RPC header", SampleFrom: "[MS-DCOM]"},
	{Name: "PsExec/SMB-svcctl", Layer: "L7", RuleFile: "application-layer/dcerpc.yaml", Status: statusNew, Notes: "SVCCTL OpenSCManagerW opnum 15", SampleFrom: "[MS-SCMR] 3.1.4"},
	{Name: "Java serialization", Layer: "L7", RuleFile: "application-layer/java_ser.yaml", Status: statusNew, Notes: "STREAM_MAGIC ACED v5 + TC type", SampleFrom: "Java Object Serialization Spec"},
	{Name: "SMB3", Layer: "L7", RuleFile: "application-layer/smb3.yaml", Status: statusNew, Notes: "transform \\xfdSMB", SampleFrom: "[MS-SMB2] 2.2.41"},
	{Name: "NBNS", Layer: "L7", RuleFile: "application-layer/nbns.yaml", Status: statusNew, Notes: "NetBIOS name service header", SampleFrom: "RFC 1002"},
	{Name: "NBT NS", Layer: "L4", RuleFile: "application-layer/nbns.yaml", Status: statusNew, Notes: "same as NBNS", SampleFrom: "RFC 1002"},
	{Name: "NetBIOS", Layer: "L4", RuleFile: "application-layer/nbss.yaml", Status: statusNew, Notes: "session + name service", SampleFrom: "RFC 1001/1002"},
	{Name: "LLMNR response", Layer: "L7", RuleFile: "application-layer/nbns.yaml", Status: statusNew, Notes: "LLMNR is DNS-shaped on UDP 5355", SampleFrom: "RFC 4795"},
	{Name: "NBT-NS response", Layer: "L7", RuleFile: "application-layer/nbns.yaml", Status: statusNew, Notes: "NBNS query/response", SampleFrom: "RFC 1002"},
	{Name: "JA3/JA4", Layer: "L7", RuleFile: "application-layer/tls_hello.yaml", Status: statusNew, Notes: "ClientHello cipher suites + extensions for fingerprint", SampleFrom: "TLS ClientHello"},
	{Name: "WPAD proxy", Layer: "L7", RuleFile: "application-layer/http.yaml", Status: statusNew, Notes: "HTTP GET /wpad.dat", SampleFrom: "WPAD"},
	{Name: "Yakit proxy framing", Layer: "L7", RuleFile: "application-layer/http.yaml", Status: statusNew, Notes: "HTTP CONNECT framing", SampleFrom: "Yakit HTTP CONNECT"},
	{Name: "LLC", Layer: "L2", RuleFile: "llc.yaml", Status: statusNew, SampleFrom: "IEEE 802.3 + STP BPDU (gopacket)"},
	{Name: "IEEE 802.1ad QinQ", Layer: "L2", RuleFile: "ieee_802_1ad.yaml", Status: statusNew, SampleFrom: "EtherType 0x88a8"},
	{Name: "PPPoE Discovery", Layer: "L2", RuleFile: "pppoe.yaml", Status: statusNew, SampleFrom: "RFC 2516 PADI/PADO tags"},
	{Name: "STP", Layer: "L2", RuleFile: "stp.yaml", Status: statusNew, SampleFrom: "gopacket STP BPDU"},
	{Name: "LLDP", Layer: "L2", RuleFile: "lldp.yaml", Status: statusNew, SampleFrom: "gopacket Siemens LLDP"},
	{Name: "CDP", Layer: "L2", RuleFile: "cdp.yaml", Status: statusNew, SampleFrom: "Wireshark SampleCaptures/cdp.pcap"},
	{Name: "Loopback", Layer: "L2", RuleFile: "loopback.yaml", Status: statusNew, SampleFrom: "EtherType 0x9000"},
	{Name: "Linux SLL", Layer: "L2", RuleFile: "linux_sll.yaml", Status: statusNew, SampleFrom: "DLT_LINUX_SLL"},
	{Name: "IEEE 802.11", Layer: "L2", RuleFile: "ieee_802_11.yaml", Status: statusNew, SampleFrom: "Dot11 + RSN IE"},
	{Name: "IGMP", Layer: "L3", RuleFile: "igmp.yaml", Status: statusNew, SampleFrom: "gopacket IGMPv1 report"},
	{Name: "IPsec AH", Layer: "L3", RuleFile: "ipsec.yaml", Status: statusNew, SampleFrom: "RFC 4302"},
	{Name: "MPLS", Layer: "L3", RuleFile: "mpls.yaml", Status: statusNew, SampleFrom: "gopacket MPLS stack"},
	{Name: "VXLAN", Layer: "L3", RuleFile: "vxlan.yaml", Status: statusNew, SampleFrom: "gopacket RFC 7348 VNI 255"},
	{Name: "L2TP", Layer: "L4", RuleFile: "l2tp.yaml", Status: statusNew, SampleFrom: "RFC 2661"},
	{Name: "OpenVPN", Layer: "L4", RuleFile: "openvpn.yaml", Status: statusNew, SampleFrom: "opcode header"},
	{Name: "WireGuard", Layer: "L4", RuleFile: "wireguard.yaml", Status: statusNew, SampleFrom: "handshake initiation Sender + response Receiver"},
	{Name: "IKEv2", Layer: "L4", RuleFile: "ike.yaml", Status: statusNew, SampleFrom: "RFC 7296 header"},
	{Name: "OSPF", Layer: "L3", RuleFile: "ospf.yaml", Status: statusNew, SampleFrom: "gopacket OSPFv2 Hello"},
	{Name: "BGP", Layer: "L4", RuleFile: "bgp.yaml", Status: statusNew, SampleFrom: "RFC 4271 keepalive"},
	{Name: "RIP", Layer: "L4", RuleFile: "rip.yaml", Status: statusNew, SampleFrom: "RFC 2453"},
	{Name: "EIGRP", Layer: "L3", RuleFile: "eigrp.yaml", Status: statusNew, SampleFrom: "IP proto 88"},
	{Name: "VRRP", Layer: "L3", RuleFile: "vrrp.yaml", Status: statusNew, SampleFrom: "gopacket VRRPv2"},
	{Name: "HSRP", Layer: "L4", RuleFile: "hsrp.yaml", Status: statusNew, SampleFrom: "UDP/1985 hello"},
	{Name: "SCTP", Layer: "L4", RuleFile: "sctp.yaml", Status: statusNew, SampleFrom: "RFC 4960"},
	{Name: "NBT DG", Layer: "L4", RuleFile: "nbt_dg.yaml", Status: statusNew, SampleFrom: "RFC 1002"},
	{Name: "DHCPv6", Layer: "L7", RuleFile: "dhcpv6.yaml", Status: statusNew, SampleFrom: "RFC 8415 Solicit"},
	{Name: "TFTP", Layer: "L7", RuleFile: "tftp.yaml", Status: statusNew, SampleFrom: "RFC 1350 RRQ"},
	{Name: "Syslog", Layer: "L7", RuleFile: "syslog.yaml", Status: statusNew, SampleFrom: "RFC 5424 PRI"},
	{Name: "STUN", Layer: "L7", RuleFile: "stun.yaml", Status: statusNew, SampleFrom: "RFC 5389 Binding"},
	{Name: "SIP", Layer: "L7", RuleFile: "sip.yaml", Status: statusNew, SampleFrom: "RFC 3261 REGISTER"},
	{Name: "RTP", Layer: "L7", RuleFile: "rtp.yaml", Status: statusNew, SampleFrom: "RFC 3550"},
	{Name: "SOCKS4", Layer: "L7", RuleFile: "socks4.yaml", Status: statusNew, SampleFrom: "SOCKS4 CONNECT"},
	{Name: "Telnet", Layer: "L7", RuleFile: "telnet.yaml", Status: statusNew, SampleFrom: "RFC 854 IAC"},
	{Name: "POP3", Layer: "L7", RuleFile: "pop3.yaml", Status: statusNew, SampleFrom: "RFC 1939 +OK"},
	{Name: "IMAP", Layer: "L7", RuleFile: "imap.yaml", Status: statusNew, SampleFrom: "RFC 3501"},
	{Name: "VNC/RFB", Layer: "L7", RuleFile: "vnc.yaml", Status: statusNew, SampleFrom: "RFB 003.008"},
	{Name: "MongoDB", Layer: "L7", RuleFile: "mongodb.yaml", Status: statusNew, SampleFrom: "OP_MSG"},
	{Name: "Memcached", Layer: "L7", RuleFile: "memcached.yaml", Status: statusNew, SampleFrom: "binary protocol"},
	{Name: "AMQP", Layer: "L7", RuleFile: "amqp.yaml", Status: statusNew, SampleFrom: "AMQP 0-9-1 header"},
	{Name: "Kafka", Layer: "L7", RuleFile: "kafka.yaml", Status: statusNew, SampleFrom: "Metadata v0 Client ID + topic Name"},
	{Name: "JSON-RPC", Layer: "L7", RuleFile: "jsonrpc.yaml", Status: statusNew, SampleFrom: "JSON-RPC 2.0 ping"},
	{Name: "TACACS+", Layer: "L7", RuleFile: "tacacs.yaml", Status: statusNew, SampleFrom: "TACACS+ header"},
	{Name: "DTLS", Layer: "L7", RuleFile: "dtls.yaml", Status: statusNew, SampleFrom: "DTLS 1.2 record"},
	{Name: "ONC RPC", Layer: "L7", RuleFile: "onc_rpc.yaml", Status: statusNew, SampleFrom: "RFC 5531 CALL"},
	{Name: "IPMI", Layer: "L7", RuleFile: "ipmi.yaml", Status: statusNew, SampleFrom: "RMCP"},
	{Name: "BitTorrent", Layer: "L7", RuleFile: "bittorrent.yaml", Status: statusNew, SampleFrom: "handshake"},
	{Name: "FastCGI", Layer: "L7", RuleFile: "fastcgi.yaml", Status: statusNew, SampleFrom: "FCGI BEGIN_REQUEST"},
	{Name: "JDWP", Layer: "L7", RuleFile: "jdwp.yaml", Status: statusNew, SampleFrom: "JDWP-Handshake"},
	{Name: "PHP serialize", Layer: "L7", RuleFile: "php_ser.yaml", Status: statusNew, SampleFrom: "i:1;"},
	{Name: "Python pickle", Layer: "L7", RuleFile: "pickle.yaml", Status: statusNew, SampleFrom: "PROTO 2"},
	{Name: "RMI/JRMP", Layer: "L7", RuleFile: "rmi.yaml", Status: statusNew, SampleFrom: "JRMI"},
	{Name: "Thrift", Layer: "L7", RuleFile: "thrift.yaml", Status: statusNew, SampleFrom: "binary protocol"},
	{Name: "Protobuf", Layer: "L7", RuleFile: "protobuf.yaml", Status: statusNew, SampleFrom: "encoding field1=150 + string testing"},
	{Name: "Zabbix agent", Layer: "L7", RuleFile: "zabbix.yaml", Status: statusNew, SampleFrom: "ZBXD"},
	{Name: "Hessian2", Layer: "L7", RuleFile: "hessian.yaml", Status: statusNew, SampleFrom: "H 2.0"},
	{Name: "Rsync daemon", Layer: "L7", RuleFile: "rsync.yaml", Status: statusNew, SampleFrom: "@RSYNCD"},
	{Name: "RTSP", Layer: "L7", RuleFile: "rtsp.yaml", Status: statusNew, SampleFrom: "RFC 2326 OPTIONS"},
	{Name: "RTMP", Layer: "L7", RuleFile: "rtmp.yaml", Status: statusNew, SampleFrom: "Adobe RTMP Set Chunk Size + AMF0 connect"},
	{Name: "FTP-DATA", Layer: "L7", RuleFile: "ftp_data.yaml", Status: statusNew, SampleFrom: "TCP/20 payload"},
	{Name: "Jenkins remoting", Layer: "L7", RuleFile: "jenkins.yaml", Status: statusNew, SampleFrom: "Protocol:HTTP11"},
	{Name: "SaltStack", Layer: "L7", RuleFile: "salt.yaml", Status: statusNew, SampleFrom: "ZMTP greeting NULL + ping frame"},
	{Name: ".NET Remoting", Layer: "L7", RuleFile: "net_remoting.yaml", Status: statusNew, SampleFrom: ".NET preamble"},

	// Multi-entry rule files need an explicit entry node. These registrations
	// make the sample-validated formats discoverable without requiring callers
	// to know an internal YAML node name.
	{Name: "BOOTP", Layer: "L7", RuleFile: "application-layer/bootp.yaml", EntryNode: "BOOTP", Status: statusNew, SampleFrom: "pinned Wireshark DHCP capture"},
	{Name: "IEEE 802.11 Radiotap", Layer: "L2", RuleFile: "application-layer/extended_protocols.yaml", EntryNode: "RadioTapHeader", Status: statusNew, SampleFrom: "pinned tcpdump Radiotap capture"},
	{Name: "AFP", Layer: "L7", RuleFile: "application-layer/extended_protocols.yaml", EntryNode: "AFP", Status: statusNew, SampleFrom: "pinned upstream capture"},
	{Name: "ActiveMQ OpenWire", Layer: "L7", RuleFile: "application-layer/extended_protocols.yaml", EntryNode: "ActiveMQOpenWire", Status: statusNew, SampleFrom: "pinned upstream capture"},
	{Name: "BACnet", Layer: "L7", RuleFile: "application-layer/extended_protocols.yaml", EntryNode: "BACnetIP", Status: statusNew, SampleFrom: "pinned upstream capture"},
	{Name: "BFD", Layer: "L7", RuleFile: "application-layer/extended_protocols.yaml", EntryNode: "BFD", Status: statusNew, SampleFrom: "pinned upstream capture"},
	{Name: "Beckhoff ADS", Layer: "L7", RuleFile: "application-layer/extended_protocols.yaml", EntryNode: "BeckhoffADS", Status: statusNew, SampleFrom: "pinned upstream capture"},
	{Name: "CAN/ISO-TP", Layer: "L7", RuleFile: "application-layer/extended_protocols.yaml", EntryNode: "CANEthernet", Status: statusNew, SampleFrom: "pinned upstream capture"},
	{Name: "Cassandra CQL", Layer: "L7", RuleFile: "application-layer/extended_protocols.yaml", EntryNode: "CassandraCQL", Status: statusNew, SampleFrom: "pinned upstream capture"},
	{Name: "Ceph", Layer: "L7", RuleFile: "application-layer/extended_protocols.yaml", EntryNode: "CephConnect", Status: statusNew, SampleFrom: "pinned upstream capture"},
	{Name: "Citrix ICA", Layer: "L7", RuleFile: "application-layer/extended_protocols.yaml", EntryNode: "CitrixICA", Status: statusNew, SampleFrom: "pinned upstream capture"},
	{Name: "Collectd", Layer: "L7", RuleFile: "application-layer/extended_protocols.yaml", EntryNode: "Collectd", Status: statusNew, SampleFrom: "pinned upstream capture"},
	{Name: "DB2 DRDA", Layer: "L7", RuleFile: "application-layer/extended_protocols.yaml", EntryNode: "DRDA", Status: statusNew, SampleFrom: "pinned upstream capture"},
	{Name: "DLMS/COSEM", Layer: "L7", RuleFile: "application-layer/extended_protocols.yaml", EntryNode: "DLMSHDLC", Status: statusNew, SampleFrom: "pinned upstream capture"},
	{Name: "DNP3", Layer: "L7", RuleFile: "application-layer/extended_protocols.yaml", EntryNode: "DNP3", Status: statusNew, SampleFrom: "pinned upstream capture"},
	{Name: "Diameter", Layer: "L7", RuleFile: "application-layer/extended_protocols.yaml", EntryNode: "Diameter", Status: statusNew, SampleFrom: "pinned upstream capture"},
	{Name: "EtherNet/IP CIP", Layer: "L7", RuleFile: "application-layer/extended_protocols.yaml", EntryNode: "EtherNetIPCIPIO", Status: statusNew, SampleFrom: "pinned upstream capture"},
	{Name: "FIX", Layer: "L7", RuleFile: "application-layer/extended_protocols.yaml", EntryNode: "FIX", Status: statusNew, SampleFrom: "pinned upstream capture"},
	{Name: "GLBP", Layer: "L7", RuleFile: "application-layer/extended_protocols.yaml", EntryNode: "GLBP", Status: statusNew, SampleFrom: "pinned upstream capture"},
	{Name: "GTP Prime", Layer: "L7", RuleFile: "application-layer/extended_protocols.yaml", EntryNode: "GTPPrime", Status: statusNew, SampleFrom: "pinned upstream capture"},
	{Name: "GTP-C", Layer: "L7", RuleFile: "application-layer/extended_protocols.yaml", EntryNode: "GTPv2", Status: statusNew, SampleFrom: "pinned upstream capture"},
	{Name: "GTP-U", Layer: "L7", RuleFile: "application-layer/extended_protocols.yaml", EntryNode: "GTPv1", Status: statusNew, SampleFrom: "pinned upstream capture"},
	{Name: "Git daemon", Layer: "L7", RuleFile: "application-layer/extended_protocols.yaml", EntryNode: "GitDaemon", Status: statusNew, SampleFrom: "pinned upstream capture"},
	{Name: "Gnutella", Layer: "L7", RuleFile: "application-layer/extended_protocols.yaml", EntryNode: "Gnutella", Status: statusNew, SampleFrom: "pinned upstream capture"},
	{Name: "H.323", Layer: "L7", RuleFile: "application-layer/extended_protocols.yaml", EntryNode: "H323", Status: statusNew, SampleFrom: "pinned upstream capture"},
	{Name: "Hart-IP", Layer: "L7", RuleFile: "application-layer/extended_protocols.yaml", EntryNode: "HartIP", Status: statusNew, SampleFrom: "pinned upstream capture"},
	{Name: "IEC 60870-5-104", Layer: "L7", RuleFile: "application-layer/extended_protocols.yaml", EntryNode: "IEC104", Status: statusNew, SampleFrom: "pinned upstream capture"},
	{Name: "IPP", Layer: "L7", RuleFile: "application-layer/extended_protocols.yaml", EntryNode: "IPP", Status: statusNew, SampleFrom: "pinned upstream capture"},
	{Name: "IRC", Layer: "L7", RuleFile: "application-layer/extended_protocols.yaml", EntryNode: "IRC", Status: statusNew, SampleFrom: "pinned upstream capture"},
	{Name: "KNX/IP", Layer: "L7", RuleFile: "application-layer/extended_protocols.yaml", EntryNode: "KNXIP", Status: statusNew, SampleFrom: "pinned upstream capture"},
	{Name: "LDP", Layer: "L7", RuleFile: "application-layer/extended_protocols.yaml", EntryNode: "LDP", Status: statusNew, SampleFrom: "pinned upstream capture"},
	{Name: "MELSEC", Layer: "L7", RuleFile: "application-layer/extended_protocols.yaml", EntryNode: "MELSEC", Status: statusNew, SampleFrom: "pinned upstream capture"},
	{Name: "MGCP", Layer: "L7", RuleFile: "application-layer/extended_protocols.yaml", EntryNode: "MGCP", Status: statusNew, SampleFrom: "pinned upstream capture"},
	{Name: "MPEG-TS", Layer: "L7", RuleFile: "application-layer/extended_protocols.yaml", EntryNode: "MPEGTransportStream", Status: statusNew, SampleFrom: "pinned upstream capture"},
	{Name: "Modbus TCP", Layer: "L7", RuleFile: "application-layer/extended_protocols.yaml", EntryNode: "ModbusTCP", Status: statusNew, SampleFrom: "pinned upstream capture"},
	{Name: "NATS", Layer: "L7", RuleFile: "application-layer/extended_protocols.yaml", EntryNode: "NATS", Status: statusNew, SampleFrom: "pinned upstream capture"},
	{Name: "NNTP", Layer: "L7", RuleFile: "application-layer/extended_protocols.yaml", EntryNode: "NNTP", Status: statusNew, SampleFrom: "pinned upstream capture"},
	{Name: "NetFlow v9", Layer: "L7", RuleFile: "application-layer/extended_protocols.yaml", EntryNode: "NetFlowV9", Status: statusNew, SampleFrom: "pinned upstream capture"},
	{Name: "OPC UA", Layer: "L7", RuleFile: "application-layer/extended_protocols.yaml", EntryNode: "OPCUAHello", Status: statusNew, SampleFrom: "pinned upstream capture"},
	{Name: "Omron FINS", Layer: "L7", RuleFile: "application-layer/extended_protocols.yaml", EntryNode: "OmronFINS", Status: statusNew, SampleFrom: "pinned upstream capture"},
	{Name: "PFCP", Layer: "L7", RuleFile: "application-layer/extended_protocols.yaml", EntryNode: "PFCP", Status: statusNew, SampleFrom: "pinned upstream capture"},
	{Name: "PIM", Layer: "L3", RuleFile: "application-layer/extended_protocols.yaml", EntryNode: "PIM", Status: statusNew, SampleFrom: "pinned upstream capture"},
	{Name: "RSH", Layer: "L7", RuleFile: "application-layer/extended_protocols.yaml", EntryNode: "RSH", Status: statusNew, SampleFrom: "pinned upstream capture"},
	{Name: "S7comm", Layer: "L7", RuleFile: "application-layer/extended_protocols.yaml", EntryNode: "S7comm", Status: statusNew, SampleFrom: "pinned upstream capture"},
	{Name: "S7comm-plus", Layer: "L7", RuleFile: "application-layer/extended_protocols.yaml", EntryNode: "S7commPlus", Status: statusNew, SampleFrom: "pinned upstream capture"},
	{Name: "SCCP/Skinny", Layer: "L7", RuleFile: "application-layer/extended_protocols.yaml", EntryNode: "Skinny", Status: statusNew, SampleFrom: "pinned upstream capture"},
	{Name: "SMPP", Layer: "L7", RuleFile: "application-layer/extended_protocols.yaml", EntryNode: "SMPPBind", Status: statusNew, SampleFrom: "pinned upstream capture"},
	{Name: "SRVLOC/SLP", Layer: "L7", RuleFile: "application-layer/extended_protocols.yaml", EntryNode: "SLPv2", Status: statusNew, SampleFrom: "pinned upstream capture"},
	{Name: "STOMP", Layer: "L7", RuleFile: "application-layer/extended_protocols.yaml", EntryNode: "STOMP", Status: statusNew, SampleFrom: "pinned upstream capture"},
	{Name: "Teredo", Layer: "L7", RuleFile: "application-layer/extended_protocols.yaml", EntryNode: "TeredoAuthentication", Status: statusNew, SampleFrom: "pinned upstream capture"},
	{Name: "XDMCP", Layer: "L7", RuleFile: "application-layer/extended_protocols.yaml", EntryNode: "XDMCP", Status: statusNew, SampleFrom: "pinned upstream capture"},
	{Name: "sFlow", Layer: "L7", RuleFile: "application-layer/extended_protocols.yaml", EntryNode: "SFlowV5", Status: statusNew, SampleFrom: "pinned upstream capture"},

	{Name: "6in4", Layer: "L3", RuleFile: "internet_protocol.yaml", EntryNode: "Internet Protocol", Status: statusNew, Notes: "IPv4 protocol 41 envelope and complete inner IPv6 packet", SampleFrom: "pinned upstream capture"},
	{Name: "AnyDesk", Layer: "L7", RuleFile: "application-layer/tls.yaml", Status: statusPartial, Notes: "TLS outer format", SampleFrom: "pinned upstream capture"},
	{Name: "DingTalk", Layer: "L7", RuleFile: "application-layer/tls.yaml", Status: statusPartial, Notes: "TLS outer format", SampleFrom: "pinned upstream capture"},
	{Name: "DoH", Layer: "L7", RuleFile: "application-layer/tls.yaml", Status: statusPartial, Notes: "TLS outer format", SampleFrom: "pinned upstream capture"},
	{Name: "DoQ", Layer: "L7", RuleFile: "application-layer/quic.yaml", EntryNode: "QUIC", Status: statusPartial, Notes: "QUIC outer format", SampleFrom: "pinned upstream capture"},
	{Name: "DoT", Layer: "L7", RuleFile: "application-layer/tls.yaml", Status: statusPartial, Notes: "TLS outer format", SampleFrom: "pinned upstream capture"},
	{Name: "Elasticsearch", Layer: "L7", RuleFile: "application-layer/elasticsearch.yaml", EntryNode: "Elasticsearch", Status: statusNew, SampleFrom: "pinned upstream capture"},
	{Name: "FTPS", Layer: "L7", RuleFile: "application-layer/ftp.yaml", EntryNode: "FTPAuthTLS", Status: statusNew, Notes: "explicit AUTH TLS negotiation command", SampleFrom: "pinned upstream capture"},
	{Name: "HTTP Proxy CONNECT", Layer: "L7", RuleFile: "application-layer/http.yaml", EntryNode: "HTTP", Status: statusNew, SampleFrom: "pinned upstream capture"},
	{Name: "HTTP/3", Layer: "L7", RuleFile: "application-layer/quic.yaml", EntryNode: "QUIC", Status: statusPartial, Notes: "QUIC outer format", SampleFrom: "pinned upstream capture"},
	{Name: "IEC 61850 MMS", Layer: "L7", RuleFile: "application-layer/mms.yaml", EntryNode: "MMSPDU", Status: statusPartial, Notes: "capture-backed initiate request/response, confirmed request/error/response, and conclude PDUs; capability bit strings remain explicit raw bytes", SampleFrom: "pinned upstream capture"},
	{Name: "IKEv1", Layer: "L4", RuleFile: "ike.yaml", EntryNode: "IKE", Status: statusNew, SampleFrom: "pinned upstream capture"},
	{Name: "IIOP/GIOP", Layer: "L7", RuleFile: "application-layer/iiop.yaml", EntryNode: "GIOP", Status: statusNew, SampleFrom: "pinned upstream capture"},
	{Name: "IMAPS", Layer: "L7", RuleFile: "application-layer/tls.yaml", Status: statusPartial, Notes: "TLS outer format", SampleFrom: "pinned upstream capture"},
	{Name: "IPsec ESP", Layer: "L3", RuleFile: "ipsec.yaml", EntryNode: "ESP", Status: statusStable, Notes: "SPI, sequence, and encrypted payload", SampleFrom: "pinned upstream capture"},
	{Name: "NFS", Layer: "L7", RuleFile: "onc_rpc.yaml", EntryNode: "ONCRPC", Status: statusNew, SampleFrom: "pinned upstream capture"},
	{Name: "OCSP", Layer: "L7", RuleFile: "application-layer/ocsp.yaml", EntryNode: "OCSPRequest", Status: statusNew, Notes: "DER request and certificate identifier", SampleFrom: "pinned upstream capture"},
	{Name: "PTP", Layer: "L7", RuleFile: "ptp.yaml", EntryNode: "PTP", Status: statusNew, SampleFrom: "pinned upstream capture"},
	{Name: "Profinet IO", Layer: "L7", RuleFile: "application-layer/profinet_io.yaml", EntryNode: "ProfinetIOReadImplicit", Status: statusNew, Notes: "DCE/RPC v4 Read Implicit request", SampleFrom: "pinned upstream capture"},
	{Name: "RDP", Layer: "L7", RuleFile: "application-layer/msrdp.yaml", EntryNode: "RDPConnectionRequest", Status: statusNew, SampleFrom: "pinned upstream capture"},
	{Name: "RTCP", Layer: "L7", RuleFile: "rtp.yaml", EntryNode: "RTCP", Status: statusNew, SampleFrom: "pinned upstream capture"},
	{Name: "SMTPS", Layer: "L7", RuleFile: "application-layer/tls.yaml", Status: statusPartial, Notes: "TLS outer format", SampleFrom: "pinned upstream capture"},
	{Name: "SOAP", Layer: "L7", RuleFile: "application-layer/http.yaml", EntryNode: "HTTP", Status: statusPartial, Notes: "HTTP outer format", SampleFrom: "pinned upstream capture"},
	{Name: "SSDP", Layer: "L7", RuleFile: "application-layer/upnp.yaml", EntryNode: "UPnPSSDPNotify", Status: statusPartial, Notes: "NOTIFY start line and required discovery headers", SampleFrom: "pinned upstream capture"},
	{Name: "T.38", Layer: "L7", RuleFile: "application-layer/extended_protocols.yaml", EntryNode: "SDPT38Advertisement", Status: statusPartial, Notes: "SDP announcement fields", SampleFrom: "pinned upstream capture"},
	{Name: "TeamViewer", Layer: "L7", RuleFile: "application-layer/teamviewer.yaml", EntryNode: "TeamViewerRecord", Status: statusPartial, Notes: "bounded 0x1724 and 0x1130 record framing; payload remains opaque", SampleFrom: "pinned upstream capture"},
	{Name: "UPnP", Layer: "L7", RuleFile: "application-layer/upnp.yaml", EntryNode: "UPnPSSDPNotify", Status: statusNew, Notes: "SSDP NOTIFY discovery fields", SampleFrom: "pinned upstream capture"},
	{Name: "WeChat/MicroMsg", Layer: "L7", RuleFile: "application-layer/tls.yaml", Status: statusPartial, Notes: "TLS outer format", SampleFrom: "pinned upstream capture"},
	{Name: "WebDAV", Layer: "L7", RuleFile: "application-layer/http.yaml", EntryNode: "HTTP", Status: statusPartial, Notes: "HTTP outer format", SampleFrom: "pinned upstream capture"},
	{Name: "mDNS", Layer: "L7", RuleFile: "application-layer/dns.yaml", EntryNode: "DNS", Status: statusNew, SampleFrom: "pinned upstream capture"},

	{Name: "ANSI C12.22", Layer: "L7", RuleFile: "application-layer/extended_protocols.yaml", EntryNode: "C1222Message", Status: statusNew, SampleFrom: "pinned upstream capture"},
	{Name: "CoAP", Layer: "L7", RuleFile: "application-layer/extended_protocols.yaml", EntryNode: "CoAP", Status: statusNew, SampleFrom: "pinned upstream capture"},
	{Name: "DLEP", Layer: "L7", RuleFile: "application-layer/extended_protocols.yaml", EntryNode: "DLEPSignal", Status: statusNew, SampleFrom: "pinned upstream capture"},
	{Name: "IPX", Layer: "L3", RuleFile: "application-layer/extended_protocols.yaml", EntryNode: "IPX", Status: statusNew, SampleFrom: "pinned upstream capture"},
	{Name: "NAT-PMP", Layer: "L7", RuleFile: "application-layer/extended_protocols.yaml", EntryNode: "NATPMPPublicAddressRequest", Status: statusNew, SampleFrom: "pinned upstream capture"},
	{Name: "SOME/IP", Layer: "L7", RuleFile: "application-layer/extended_protocols.yaml", EntryNode: "SOMEIP", Status: statusNew, SampleFrom: "pinned upstream capture"},
	{Name: "USB HID report", Layer: "L7", RuleFile: "application-layer/extended_protocols.yaml", EntryNode: "USBHIDReport", Status: statusPartial, SampleFrom: "pinned upstream capture"},
}
