package bin_parser

import (
	"bytes"
	"encoding/binary"
	"encoding/hex"
	"fmt"
	"io"
	"testing"

	"github.com/stretchr/testify/require"
	"github.com/yaklang/yaklang/common/bin-parser/parser"
	"github.com/yaklang/yaklang/common/bin-parser/parser/base"
	"github.com/yaklang/yaklang/common/bin-parser/parser/stream_parser"
)

// Primary format oracle: Linux v6.12 struct elapaarp (packed, 28 bytes),
// __aarp_send_query, aarp_send_reply and aarp_send_probe. The fixture is an
// independent wire encoding, not a captured Linux exchange or DDP dataset.
// https://github.com/torvalds/linux/blob/v6.12/include/linux/atalk.h
// https://github.com/torvalds/linux/blob/v6.12/net/appletalk/aarp.c
var aarpCorpusBodies = []string{
	"0001809b060400010200000000010012342a00000000000000123456",
	"0001809b06040002020000000002001234560200000000010012342a",
	"0001809b060400030200000000010023456700000000000000234567",
}

func aarpCorpusBody(t *testing.T, index int) []byte {
	t.Helper()
	wire, err := hex.DecodeString(aarpCorpusBodies[index])
	require.NoError(t, err)
	require.Len(t, wire, 28)
	return wire
}

func aarpCorpusRequireFields(t *testing.T, node *base.Node, body []byte, offset int) {
	t.Helper()
	for _, field := range []struct {
		name       string
		start, end int
		raw        bool
	}{
		{"Hardware Type", 0, 2, false}, {"Protocol Type", 2, 4, false},
		{"Hardware Length", 4, 5, false}, {"Protocol Length", 5, 6, false}, {"Function", 6, 8, false},
		{"Source Hardware Address", 8, 14, true}, {"Source Protocol Reserved", 14, 15, false},
		{"Source Network", 15, 17, false}, {"Source Node", 17, 18, false},
		{"Destination Hardware Address", 18, 24, true}, {"Destination Protocol Reserved", 24, 25, false},
		{"Destination Network", 25, 27, false}, {"Destination Node", 27, 28, false},
	} {
		var value any
		switch {
		case field.raw:
			value = body[field.start:field.end]
		case field.end-field.start == 2:
			value = uint64(binary.BigEndian.Uint16(body[field.start:field.end]))
		default:
			value = uint64(body[field.start])
		}
		protocolCorpusRequireValue(t, node, field.name, value)
		leaf := protocolCorpusFindNode(node, field.name)
		require.Equal(t, [2]uint64{uint64(offset+field.start) * 8, uint64(offset+field.end) * 8}, stream_parser.GetNodeResultPos(leaf), field.name)
	}
}

func aarpCorpusEthernet(body []byte, snap bool) []byte {
	header := []byte{9, 0, 7, 255, 255, 255, 2, 0, 0, 0, 0, 1, 0x80, 0xf3}
	if snap {
		binary.BigEndian.PutUint16(header[12:], uint16(8+len(body)))
		header = append(header, 0xaa, 0xaa, 3, 0, 0, 0, 0x80, 0xf3)
	}
	return append(header, body...)
}

func TestProtocolCorpusAARPCompanionEveryRecord(t *testing.T) {
	frames := protocolCorpusAuditPackets(t, "testdata/protocol-corpus/captures/generated-validated/gen-aarp-valid.pcap")
	require.Len(t, frames, 3)
	for index, frame := range frames {
		t.Run(fmt.Sprint(index+1), func(t *testing.T) {
			body := aarpCorpusBody(t, index)
			require.Len(t, frame, 60)
			require.Equal(t, []byte{0, 36, 0xaa, 0xaa, 3, 0, 0, 0, 0x80, 0xf3}, frame[12:22])
			require.Equal(t, body, frame[22:50])
			require.Equal(t, make([]byte, 10), frame[50:])
			require.Equal(t, body[8:14], frame[6:12])
			if index == 1 {
				require.Equal(t, body[18:24], frame[:6]) // Reply is unicast.
			} else {
				require.Equal(t, []byte{9, 0, 7, 255, 255, 255}, frame[:6])
				require.Equal(t, make([]byte, 6), body[18:24])
			}
			if index == 2 {
				require.Equal(t, body[14:18], body[24:28]) // Probe uses the proposed address twice.
			}
			for _, entry := range []struct {
				rule, name string
				wire       []byte
				offset     int
			}{
				{"aarp", "AARP", body, 0},
				{"llc", "LLC", frame[14:50], 8},
				{"ethernet", "Ethernet", frame, 22},
			} {
				node := protocolCorpusRequireBoundedRuleParse(t, entry.wire, entry.rule, entry.name)
				aarpCorpusRequireFields(t, node, body, entry.offset)
				require.Nil(t, protocolCorpusFindNode(node, "AARP Payload"))
				if entry.rule == "ethernet" {
					protocolCorpusRequireValue(t, node, "Frame Trailer", frame[50:])
				}
			}
			// The EtherType 80f3 carrier is a separate synthetic variant; it is
			// not the LLC/SNAP format generated by Linux's aarp.c send functions.
			etherII := append(aarpCorpusEthernet(body, false), bytes.Repeat([]byte{0xa5}, 18)...)
			node := protocolCorpusRequireBoundedRuleParse(t, etherII, "ethernet", "Ethernet")
			aarpCorpusRequireFields(t, node, body, 14)
			protocolCorpusRequireValue(t, node, "AARP Link Trailer", etherII[42:])
		})
	}
}

func aarpCorpusRequireFallback(t *testing.T, body []byte) {
	t.Helper()
	for _, snap := range []bool{false, true} {
		frame := aarpCorpusEthernet(body, snap)
		if len(body) == 0 {
			// No candidate or raw body exists. Reject the empty carrier rather
			// than inventing a successfully parsed zero-byte AARP message.
			_, err := parser.ParseBinary(newProtocolCorpusBoundedReader(frame), "ethernet", "Ethernet")
			require.ErrorContains(t, err, "aarp: empty carrier has no message")
			continue
		}
		node := protocolCorpusRequireBoundedRuleParse(t, frame, "ethernet", "Ethernet")
		require.Nil(t, protocolCorpusFindNode(node, "Function"), "failed AARP probe must not retain fields")
		if len(body) > 0 {
			protocolCorpusRequireValue(t, node, "AARP Payload", body)
			start := uint64(14)
			if snap {
				start = 22
			}
			require.Equal(t, [2]uint64{start * 8, uint64(len(frame)) * 8}, stream_parser.GetNodeResultPos(protocolCorpusFindNode(node, "AARP Payload")))
		}
	}
}

func TestProtocolCorpusAARPOriginalNegativeAndLengths(t *testing.T) {
	frames := protocolCorpusAuditPackets(t, "testdata/protocol-corpus/captures/generated-pr5023/pr5023-gen-aarp.pcap")
	require.Len(t, frames, 1)
	require.Len(t, frames[0], 40)
	require.Equal(t, []byte{0x80, 0xf3, 0, 1, 8, 0, 6, 7}, frames[0][12:20])
	_, err := parser.ParseBinary(newProtocolCorpusBoundedReader(frames[0][14:]), "aarp", "AARP")
	require.ErrorContains(t, err, "aarp: Ethernet AppleTalk message length must be 28 bytes")
	node := protocolCorpusRequireBoundedRuleParse(t, frames[0], "ethernet", "Ethernet")
	protocolCorpusRequireValue(t, node, "AARP Payload", frames[0][14:])
	require.Nil(t, protocolCorpusFindNode(node, "Function"))
	for index := range aarpCorpusBodies {
		body := aarpCorpusBody(t, index)
		for end := 0; end < len(body); end++ {
			_, err := parser.ParseBinary(newProtocolCorpusBoundedReader(body[:end]), "aarp", "AARP")
			require.ErrorContains(t, err, "28 bytes", "function %d prefix %d", index+1, end)
			aarpCorpusRequireFallback(t, body[:end])
		}
		for _, length := range []int{29, 56, 65536} {
			wire := append(append([]byte(nil), body...), make([]byte, length-28)...)
			_, err := parser.ParseBinary(newProtocolCorpusBoundedReader(wire), "aarp", "AARP")
			require.ErrorContains(t, err, "28 bytes")
		}
		_, err := parser.ParseBinary(bytes.NewBuffer(body), "aarp", "AARP")
		require.ErrorContains(t, err, "explicit message boundary required")
	}
}

func TestProtocolCorpusAARPInvalidFieldsAndDispatch(t *testing.T) {
	body := aarpCorpusBody(t, 1)
	for _, field := range []struct {
		offset int
		values []byte
	}{
		{0, []byte{1, 255}}, {1, []byte{0, 2, 255}},
		{2, []byte{0, 8, 255}}, {3, []byte{0, 0xf3, 255}},
		{4, []byte{0, 5, 7, 255}}, {5, []byte{0, 3, 5, 7, 255}},
		{6, []byte{1, 255}}, {7, []byte{0, 4, 255}},
		{14, []byte{1, 255}}, {24, []byte{1, 255}},
	} {
		for _, value := range field.values {
			wire := append([]byte(nil), body...)
			wire[field.offset] = value
			_, err := parser.ParseBinary(newProtocolCorpusBoundedReader(wire), "aarp", "AARP")
			require.ErrorContains(t, err, "aarp:", "offset %d value %d", field.offset, value)
			aarpCorpusRequireFallback(t, wire)
		}
	}
	// The address fields are wire values, not proof of current node ownership.
	// Exercise every byte of both MACs, both big-endian networks and node IDs.
	variant := append([]byte(nil), body...)
	copy(variant[8:14], []byte{2, 0x13, 0x25, 0x37, 0x49, 0x5b})
	copy(variant[18:24], []byte{2, 0x68, 0x7a, 0x8c, 0x9e, 0xb0})
	copy(variant[15:18], []byte{0x12, 0x34, 0x56})
	copy(variant[25:28], []byte{0xab, 0xcd, 0xef})
	aarpCorpusRequireFields(t, protocolCorpusRequireBoundedRuleParse(t, variant, "aarp", "AARP"), variant, 0)
	for _, snap := range []bool{false, true} {
		frame := aarpCorpusEthernet(variant, snap)
		offset := 14
		if snap {
			offset = 22
			aarpCorpusRequireFields(t, protocolCorpusRequireBoundedRuleParse(t, frame[14:], "llc", "LLC"), variant, 8)
		}
		aarpCorpusRequireFields(t, protocolCorpusRequireBoundedRuleParse(t, frame, "ethernet", "Ethernet"), variant, offset)
		// A carrier may preserve following link bytes, but must not claim a
		// second address-resolution message merely from a matching prefix.
		joined := aarpCorpusEthernet(append(append([]byte(nil), variant...), body...), snap)
		node := protocolCorpusRequireBoundedRuleParse(t, joined, "ethernet", "Ethernet")
		aarpCorpusRequireFields(t, node, variant, offset)
		protocolCorpusRequireValue(t, node, "AARP Link Trailer", body)
	}
	for _, mutation := range []struct {
		offset int
		value  byte
	}{
		{14, 0xab}, {15, 0xab}, {16, 0x13}, {17, 1}, {18, 1}, {19, 1}, {21, 0xf2},
	} {
		frame := aarpCorpusEthernet(body, true)
		frame[mutation.offset] = mutation.value
		node := protocolCorpusRequireBoundedRuleParse(t, frame, "ethernet", "Ethernet")
		require.Nil(t, protocolCorpusFindNode(node, "Function"), "noncanonical SNAP at byte %d", mutation.offset)
		if mutation.offset == 14 {
			protocolCorpusRequireValue(t, node, "LLC Payload", frame[17:])
		} else {
			protocolCorpusRequireValue(t, node, "SNAP Payload", body)
		}
	}
}

func TestProtocolCorpusAARPConcurrentIsolation(t *testing.T) {
	for index := 0; index < 12; index++ {
		t.Run(fmt.Sprint(index), func(t *testing.T) {
			t.Parallel()
			body := aarpCorpusBody(t, index%3)
			// Failed probes with a nonzero reserved byte must not change the
			// next input's field tree, canonical-SNAP marker or read position.
			invalid := append([]byte(nil), body...)
			invalid[24] = byte(index + 1)
			aarpCorpusRequireFallback(t, invalid)
			frame := aarpCorpusEthernet(body, index%2 == 0)
			offset := 14
			if index%2 == 0 {
				offset = 22
			}
			aarpCorpusRequireFields(t, protocolCorpusRequireBoundedRuleParse(t, frame, "ethernet", "Ethernet"), body, offset)
		})
	}
}

func TestProtocolCorpusAARPCarrierTransactions(t *testing.T) {
	body := aarpCorpusBody(t, 1)
	invalid := bytes.Clone(body)
	invalid[24] = 1 // Fail late, after source and destination MAC fields.
	for _, snap := range []bool{false, true} {
		for _, sample := range []struct {
			name    string
			payload []byte
			valid   bool
		}{
			{"success", body, true},
			{"trailer", append(bytes.Clone(body), 0xa5, 0x5a), true},
			{"invalid-reserved", invalid, false},
			{"short-first-byte", body[:1], false},
			{"short-final-byte", body[:27], false},
		} {
			t.Run(fmt.Sprintf("snap=%t/%s", snap, sample.name), func(t *testing.T) {
				wire := aarpCorpusEthernet(sample.payload, snap)
				root, err := base.ParseRule("ethernet.yaml")
				require.NoError(t, err)
				root.Cfg.SetItem(base.CfgLength, uint64(len(wire))*8)
				reader := bytes.NewReader(wire)
				bitReader := base.NewBitReader(reader)
				require.NoError(t, root.ParseSubNode(bitReader, "Ethernet"))
				parsed := base.GetNodeByPath(root, "@Ethernet")
				require.NotNil(t, parsed)
				require.Equal(t, wire, NodeToBytes(parsed))
				if sample.valid {
					offset := 14
					if snap {
						offset = 22
					}
					aarpCorpusRequireFields(t, parsed, body, offset)
					if len(sample.payload) > 28 {
						protocolCorpusRequireValue(t, parsed, "AARP Link Trailer", sample.payload[28:])
					}
				} else {
					protocolCorpusRequireValue(t, parsed, "AARP Payload", sample.payload)
					require.Nil(t, protocolCorpusFindNode(parsed, "Function"))
				}
				// Holding the actual reader exposes a forgotten successful Save
				// or a failed probe that did not fully discard its replay state.
				require.Zero(t, reader.Len())
				require.ErrorContains(t, bitReader.Recovery(), "no backup")
				require.ErrorContains(t, bitReader.PopBackup(), "no backup")
				_, err = bitReader.ReadBits(8)
				require.ErrorIs(t, err, io.EOF)
			})
		}
	}
}
