package bin_parser

import (
	"bytes"
	"crypto/sha256"
	"encoding/binary"
	"encoding/hex"
	"fmt"
	"io"
	"os"
	"sync"
	"testing"

	"github.com/stretchr/testify/require"
	"github.com/yaklang/yaklang/common/bin-parser/parser"
	"github.com/yaklang/yaklang/common/bin-parser/parser/base"
)

const xtpTestRule = "transport-layer.xtp"

// Independent fixed wire values, not generated by the decoder. CHECK is the
// Internet checksum of each packet except data-header-check (header only).
// These are packet structures, not claims of valid associations or outcomes.
var xtpTestFixtures = []struct{ name, hex string }{
	{"data-empty", "800102030405060700000020000000004d811234010203040102030405060708"},
	{"data-odd", "8001020304050607000000200000000523b512340102030401020304050607086162636465"},
	{"data-btag", "8001020304050607000100200000000b49a61234010203040102030405060708112233445566778878797a"},
	{"data-header-check", "800102030405060740000020000000050d7c12340102030401020304050607086162636465"},
	{"cntl", "80010203040506070000002100000014a8bd12340102030401020304050607080102030405060708111213141516171821222324"},
	{"first-ipv4", "8001020304050607000000220000002d4ccd123401020304010203040506070800102401c0000202c00002010b7e9ca500180401000005dc000186a000000fa000030d4000001f4048454c4c4f"},
	{"first-null-btag", "80010203040506070001002200000019cfff123401020304010203040506070800082400000000000008040000000000112233445566778844"},
	{"tcntl", "800102030405060700000025000000289287123401020304010203040506070801020304050607081112131415161718212223240000000081828384858687880008040000000000"},
	{"jcntl", "80010203040506070800002700000048717a1234010203040102030405060708010203040506070811121314151617182122232400000000818283848586878800102401c0000202c00002010b7e9ca500180401000005dc000186a000000fa000030d4000001f40"},
	{"diag", "80010203040506070000002800000013004a123401020304010203040506070800000001000000016e6f206c697374656e6572"},
}

func xtpTestWire(t *testing.T, index int) []byte {
	t.Helper()
	wire, err := hex.DecodeString(xtpTestFixtures[index].hex)
	require.NoError(t, err)
	return wire
}

func xtpTestParse(t *testing.T, wire []byte, entry string) *base.Node {
	t.Helper()
	return protocolCorpusRequireBoundedRuleParse(t, wire, xtpTestRule, entry)
}

func xtpTestMessage(t *testing.T, n *base.Node) *base.Node {
	t.Helper()
	key := protocolCorpusFindNode(n, "Key")
	require.NotNil(t, key)
	return key.Cfg.GetItem(base.CfgParent).(*base.Node)
}

func xtpTestInfo(t *testing.T, n *base.Node, wire []byte) {
	t.Helper()
	info := xtpTestMessage(t, n).Cfg.GetItem("additionInfo").(map[string]any)
	require.Equal(t, "XTP 4.0 bounded DATA/CNTL/FIRST/TCNTL/JCNTL/DIAG structural fields", info["Profile"])
	require.Equal(t, true, info["Checksum Valid"])
	require.Equal(t, wire[0]&0x80 != 0, info["Returned Key"])
	require.Equal(t, wire[8]&0x40 == 0, info["Payload Checksum Verified"])
	length := len(wire)
	if wire[8]&0x40 != 0 {
		length = 32
	}
	require.Equal(t, length, info["Checksum Covered Bytes"])
	for _, key := range []string{"Reserved Values Validated", "Service Semantics Decoded", "Data Semantics Decoded", "Session State Validated", "Acknowledgment State Validated", "Multicast Membership Validated"} {
		require.Equal(t, false, info[key], key)
	}
}

func TestProtocolCorpusXTPFields(t *testing.T) {
	for i, fixture := range xtpTestFixtures {
		for _, entry := range []string{"XTP", "XTPCarrier"} {
			t.Run(fixture.name+"/"+entry, func(t *testing.T) {
				wire := xtpTestWire(t, i)
				n := xtpTestParse(t, wire, entry)
				require.Equal(t, wire, NodeToBytes(n))
				megacoTestTree(t, xtpTestMessage(t, n), 0, uint64(len(wire))*8)
				xtpTestInfo(t, n, wire)
				for _, f := range []struct {
					name, typ         string
					start, end, value uint64
				}{
					{"Key", "uint64", 0, 64, 0x8001020304050607}, {"Version", "uint8", 88, 91, 1}, {"Packet Format", "uint8", 91, 96, uint64(wire[11] & 31)},
					{"Data Length", "uint32", 96, 128, uint64(len(wire) - 32)}, {"Checksum", "uint16", 128, 144, uint64(binary.BigEndian.Uint16(wire[16:]))},
					{"Sort", "uint16", 144, 160, 0x1234}, {"Synchronization", "uint32", 160, 192, 0x01020304}, {"Sequence", "uint64", 192, 256, 0x0102030405060708},
					{"NOCHECK", "uint8", 65, 66, uint64((wire[8] >> 6) & 1)}, {"BTAG", "uint8", 79, 80, uint64(wire[9] & 1)},
				} {
					latTestField(t, n, f.name, f.typ, f.start, f.end, f.value)
				}
			})
		}
	}
	n := xtpTestParse(t, xtpTestWire(t, 4), "XTP")
	latTestField(t, n, "Receive Sequence", "uint64", 256, 320, uint64(0x0102030405060708))
	latTestField(t, n, "Allocation", "uint64", 320, 384, uint64(0x1112131415161718))
	// ECHO follows all eight ALLOC bytes, unlike the historical display typo.
	latTestField(t, n, "Echo", "uint32", 384, 416, uint64(0x21222324))
	n = xtpTestParse(t, xtpTestWire(t, 5), "XTP")
	latTestField(t, n, "Address Length", "uint16", 256, 272, uint64(16))
	latTestField(t, n, "Destination IPv4", "raw", 288, 320, []byte{192, 0, 2, 2})
	latTestField(t, n, "Source IPv4", "raw", 320, 352, []byte{192, 0, 2, 1})
	latTestField(t, n, "Destination Port", "uint16", 352, 368, uint64(2942))
	latTestField(t, n, "Source Port", "uint16", 368, 384, uint64(40101))
	latTestField(t, n, "Maximum Data", "uint32", 416, 448, uint64(1500))
	latTestField(t, n, "Incoming Rate", "uint32", 448, 480, uint64(100000))
	latTestField(t, n, "Outgoing Burst", "uint32", 544, 576, uint64(8000))
	latTestField(t, n, "Data", "raw", 576, 616, []byte("HELLO"))
	n = xtpTestParse(t, xtpTestWire(t, 6), "XTP")
	latTestField(t, n, "Traffic Length", "uint16", 320, 336, uint64(8))
	latTestField(t, n, "Byte Tag", "uint64", 384, 448, uint64(0x1122334455667788))
	latTestField(t, n, "Data", "raw", 448, 456, []byte("D"))
	n = xtpTestParse(t, xtpTestWire(t, 7), "XTP")
	latTestField(t, n, "Echo", "uint32", 384, 416, uint64(0x21222324))
	latTestField(t, n, "Control Reserved", "uint32", 416, 448, uint64(0))
	latTestField(t, n, "Exchange Key", "uint64", 448, 512, uint64(0x8182838485868788))
	n = xtpTestParse(t, xtpTestWire(t, 8), "XTP")
	latTestField(t, n, "Address Length", "uint16", 512, 528, uint64(16))
	latTestField(t, n, "Traffic Length", "uint16", 640, 656, uint64(24))
	n = xtpTestParse(t, xtpTestWire(t, 9), "XTP")
	latTestField(t, n, "Diagnostic Code", "uint32", 256, 288, uint64(1))
	latTestField(t, n, "Diagnostic Value", "uint32", 288, 320, uint64(1))
	latTestField(t, n, "Diagnostic Message", "raw", 320, 408, []byte("no listener"))
}

// Test-only recomputation for mutated boundary cases. Golden positives above
// remain fixed literals, and the native checksum has independent known vectors.
func xtpTestRecheck(wire []byte) {
	binary.BigEndian.PutUint32(wire[12:16], uint32(len(wire)-32))
	wire[16], wire[17] = 0, 0
	end := len(wire)
	if wire[8]&0x40 != 0 {
		end = 32
	}
	var sum uint64
	for i := 0; i < end; i++ {
		if i%2 == 0 {
			sum += uint64(wire[i]) * 256
		} else {
			sum += uint64(wire[i])
		}
	}
	for sum > 65535 {
		sum = sum/65536 + sum%65536
	}
	binary.BigEndian.PutUint16(wire[16:18], uint16(65535-sum))
}

func xtpTestReject(t *testing.T, wire []byte, contains string) {
	t.Helper()
	_, err := parser.ParseBinary(newProtocolCorpusBoundedReader(wire), xtpTestRule, "XTP")
	require.ErrorContains(t, err, contains)
	if len(wire) == 0 {
		return
	}
	n := xtpTestParse(t, wire, "XTPCarrier")
	require.Equal(t, wire, NodeToBytes(n))
	latTestField(t, n, "Unparsed XTP Payload", "raw", 0, uint64(len(wire))*8, wire)
	require.Nil(t, protocolCorpusFindNode(n, "Key"))
}

func TestProtocolCorpusXTPPrefixesAndNegatives(t *testing.T) {
	for i, f := range xtpTestFixtures {
		wire := xtpTestWire(t, i)
		for cut := 0; cut < len(wire); cut++ {
			t.Run(fmt.Sprintf("%s/prefix%d", f.name, cut), func(t *testing.T) { xtpTestReject(t, wire[:cut], "xtp:") })
		}
	}
	for version := 0; version < 8; version++ {
		if version == 1 {
			continue
		}
		wire := xtpTestWire(t, 0)
		wire[11] = byte(version << 5)
		xtpTestRecheck(wire)
		xtpTestReject(t, wire, "unsupported version")
	}
	for format := 0; format < 32; format++ {
		if format == 0 || format == 1 || format == 2 || format == 5 || format == 7 || format == 8 {
			continue
		}
		wire := xtpTestWire(t, 0)
		wire[11] = byte(32 + format)
		xtpTestRecheck(wire)
		xtpTestReject(t, wire, "unsupported packet format")
	}
	for _, tc := range []struct {
		index  int
		mutate func([]byte) []byte
		err    string
	}{
		{1, func(b []byte) []byte { b[31] ^= 1; return b }, "checksum"},
		{1, func(b []byte) []byte { b[len(b)-1] ^= 1; return b }, "checksum"},
		{3, func(b []byte) []byte { b[31] ^= 1; return b }, "checksum"},
		{1, func(b []byte) []byte { b[15]--; return b }, "DLEN"},
		{1, func(b []byte) []byte {
			for i := 12; i < 16; i++ {
				b[i] = 255
			}
			return b
		}, "DLEN"},
		{2, func(b []byte) []byte { b = b[:39]; xtpTestRecheck(b); return b }, "BTAG"},
		{4, func(b []byte) []byte { b = append(b, 0); xtpTestRecheck(b); return b }, "trailing"},
		{4, func(b []byte) []byte { b = b[:51]; xtpTestRecheck(b); return b }, "truncated Common Control"},
		{5, func(b []byte) []byte { b[33] = 15; xtpTestRecheck(b); return b }, "address length"},
		{5, func(b []byte) []byte { b[35] = 6; xtpTestRecheck(b); return b }, "unsupported address"},
		{5, func(b []byte) []byte { b[49] = 23; xtpTestRecheck(b); return b }, "traffic length"},
		{5, func(b []byte) []byte { b[51] = 128; xtpTestRecheck(b); return b }, "unsupported traffic"},
		{5, func(b []byte) []byte { b = b[:71]; xtpTestRecheck(b); return b }, "truncated Traffic"},
		{6, func(b []byte) []byte { b[33] = 16; xtpTestRecheck(b); return b }, "null address length"},
		{6, func(b []byte) []byte { b[41] = 7; xtpTestRecheck(b); return b }, "null traffic length"},
		{6, func(b []byte) []byte { b = b[:55]; xtpTestRecheck(b); return b }, "BTAG"},
		{7, func(b []byte) []byte { b = append(b, 0); xtpTestRecheck(b); return b }, "trailing"},
		{8, func(b []byte) []byte { b = append(b, 0); xtpTestRecheck(b); return b }, "trailing"},
		{9, func(b []byte) []byte { b = b[:39]; xtpTestRecheck(b); return b }, "diagnostic"},
	} {
		xtpTestReject(t, tc.mutate(xtpTestWire(t, tc.index)), tc.err)
	}
	// NOCHECK does not promise body integrity, and unknown flag/reserved/service
	// values do not gain made-up connection-state validation.
	wire := xtpTestWire(t, 3)
	wire[len(wire)-1] ^= 1
	n := xtpTestParse(t, wire, "XTP")
	xtpTestInfo(t, n, wire)
	require.Equal(t, wire, NodeToBytes(n))
	wire = xtpTestWire(t, 7)
	wire[8] |= 0x80
	wire[10] = 0xa5
	wire[52] = 0xff
	wire[66] = 255
	wire[68] = 0xff
	xtpTestRecheck(wire)
	n = xtpTestParse(t, wire, "XTP")
	xtpTestInfo(t, n, wire)
	require.Equal(t, wire, NodeToBytes(n))
}

func TestProtocolCorpusXTPAllOriginalRecords(t *testing.T) {
	path := "testdata/protocol-corpus/captures/generated-pr5023/pr5023-gen-xtp.pcap"
	data, err := os.ReadFile(path)
	require.NoError(t, err)
	require.Equal(t, "ebf6e31d3fd6f95e9ff1a58bbaffe7437ac3110d6efe4d3184be5be19ab9d3cb", fmt.Sprintf("%x", sha256.Sum256(data)))
	frames := protocolCorpusAuditPackets(t, path)
	require.Len(t, frames, 1)
	for _, frame := range frames {
		require.Len(t, frame, 66)
		require.Equal(t, byte(0x45), frame[14])
		require.Equal(t, uint16(52), binary.BigEndian.Uint16(frame[16:18]))
		require.Equal(t, byte(36), frame[23])
		wire := frame[34:66]
		require.Equal(t, make([]byte, 32), wire)
		xtpTestReject(t, wire, "unsupported version 0")
		fixedVersion := bytes.Clone(wire)
		fixedVersion[11] = 0x20
		xtpTestReject(t, fixedVersion, "checksum")
		n := protocolCorpusRequireBoundedRuleParse(t, frame, "ethernet", "Ethernet")
		require.Equal(t, frame, NodeToBytes(n))
	}
}

func TestProtocolCorpusXTPCompanionRecords(t *testing.T) {
	const path = "testdata/protocol-corpus/captures/generated-validated/gen-xtp-valid.pcap"
	data, err := os.ReadFile(path)
	require.NoError(t, err)
	require.Equal(t, "7142ebdfecd609198e17bbbc04b73c009a04396504a99eda600b9e257a1a224d", fmt.Sprintf("%x", sha256.Sum256(data)))
	frames := protocolCorpusAuditPackets(t, path)
	require.Len(t, frames, len(xtpTestFixtures))
	for i, frame := range frames {
		require.GreaterOrEqual(t, len(frame), 34)
		require.Equal(t, byte(0x45), frame[14])
		require.Equal(t, byte(36), frame[23])
		require.Equal(t, len(frame)-14, int(binary.BigEndian.Uint16(frame[16:18])))
		require.Zero(t, binary.BigEndian.Uint16(frame[20:22])&0x3fff)
		wire := frame[34:]
		require.Equal(t, xtpTestWire(t, i), wire)
		for _, entry := range []string{"XTP", "XTPCarrier"} {
			n := xtpTestParse(t, wire, entry)
			require.Equal(t, wire, NodeToBytes(n))
			xtpTestInfo(t, n, wire)
			megacoTestTree(t, xtpTestMessage(t, n), 0, uint64(len(wire))*8)
			protocolCorpusRequireValue(t, n, "Version", uint64(1))
			protocolCorpusRequireValue(t, n, "Packet Format", uint64(wire[11]&31))
		}
	}
}

func TestProtocolCorpusXTPResourcesAndIsolation(t *testing.T) {
	wire := append(xtpTestWire(t, 0), bytes.Repeat([]byte{0xa5}, 65535-32)...)
	xtpTestRecheck(wire)
	n := xtpTestParse(t, wire, "XTP")
	require.Equal(t, wire, NodeToBytes(n))
	tooLong := bytes.NewReader(append(bytes.Clone(wire), 0))
	_, err := parser.ParseBinary(&giopCarrierTestBitReader{Reader: tooLong, bits: uint64(65536) * 8}, xtpTestRule, "XTP")
	require.ErrorContains(t, err, "boundary")
	require.Equal(t, 65536, tooLong.Len())
	for _, entry := range []string{"XTP", "XTPCarrier"} {
		_, err := parser.ParseBinary(bytes.NewReader(wire), xtpTestRule, entry)
		require.ErrorContains(t, err, "explicit")
		_, err = parser.GenerateBinary(map[string]any{}, xtpTestRule, entry)
		require.Error(t, err)
		for extra := uint64(1); extra < 8; extra++ {
			r := &giopCarrierTestBitReader{Reader: bytes.NewReader(append(xtpTestWire(t, 0), 0)), bits: 256 + extra}
			_, err = parser.ParseBinary(r, xtpTestRule, entry)
			require.ErrorContains(t, err, "byte")
			require.Equal(t, 33, r.Len())
		}
	}
	var wg sync.WaitGroup
	for i := 0; i < 20; i++ {
		wg.Add(1)
		go func(i int) {
			defer wg.Done()
			wire := xtpTestWire(t, i%len(xtpTestFixtures))
			n := xtpTestParse(t, wire, "XTPCarrier")
			xtpTestInfo(t, n, wire)
			require.Equal(t, wire, NodeToBytes(n))
		}(i)
	}
	wg.Wait()
}

func TestProtocolCorpusXTPImportedHeldReader(t *testing.T) {
	for _, index := range []int{0, 1, 2, 5, 6, 7, 8, 9} {
		for offset := uint64(0); offset < 8; offset++ {
			for _, valid := range []bool{false, true} {
				t.Run(fmt.Sprintf("%s/%d/%t", xtpTestFixtures[index].name, offset, valid), func(t *testing.T) {
					wire := xtpTestWire(t, index)
					if !valid {
						wire[len(wire)-1] ^= 1
					}
					var packed bytes.Buffer
					w := base.NewBitWriter(&packed)
					if offset > 0 {
						require.NoError(t, w.WriteBits([]byte{0x55}, offset))
					}
					require.NoError(t, w.WriteBits(wire, uint64(len(wire))*8))
					require.NoError(t, w.WriteBits([]byte{0xd3}, 8))
					if offset > 0 {
						require.NoError(t, w.WriteBits([]byte{0}, 8-offset))
					}
					root := latTestInline(t, fmt.Sprintf(`Package:
  Envelope:
    operator: |
      if %d > 0 { this.ProcessSubNode("Prefix") }
      this.GetSubNode("Message").SetMaxLength(%d)
      this.ProcessSubNode("Message")
      this.ProcessSubNode("Sentinel")
      if %d > 0 { this.ProcessSubNode("Padding") }
    Prefix: uint8,%dbit
    Message: "import:transport-layer/xtp.yaml;node:XTPCarrier"
    Sentinel: uint8
    Padding: uint8,%dbit
`, offset, len(wire), offset, offset, 8-offset))
					root.Cfg.SetItem(base.CfgLength, uint64(packed.Len())*8)
					r := base.NewBitReader(bytes.NewReader(packed.Bytes()))
					require.NoError(t, r.Backup())
					require.NoError(t, root.ParseSubNode(r, "Envelope"))
					n := base.GetNodeByPath(root, "@Envelope")
					message := protocolCorpusFindNode(n, "Message")
					if valid {
						megacoTestTree(t, xtpTestMessage(t, message), offset, offset+uint64(len(wire))*8)
						xtpTestInfo(t, message, wire)
						latTestField(t, message, "Key", "uint64", offset, offset+64, uint64(0x8001020304050607))
						latTestField(t, message, "Version", "uint8", offset+88, offset+91, uint64(1))
					} else {
						latTestField(t, message, "Unparsed XTP Payload", "raw", offset, offset+uint64(len(wire))*8, wire)
						require.Nil(t, protocolCorpusFindNode(message, "Key"))
					}
					protocolCorpusRequireValue(t, n, "Sentinel", uint64(0xd3))
					require.Equal(t, packed.Bytes(), NodeToBytes(n))
					require.NoError(t, r.Recovery())
					replay, err := r.ReadBits(uint64(packed.Len()) * 8)
					require.NoError(t, err)
					require.Equal(t, packed.Bytes(), replay)
					require.ErrorContains(t, r.Recovery(), "no backup")
					_, err = r.ReadBits(8)
					require.ErrorIs(t, err, io.EOF)
				})
			}
		}
	}
}

func TestProtocolCorpusXTPPhysicalTruncation(t *testing.T) {
	wire := xtpTestWire(t, 5)
	for _, entry := range []string{"XTP", "XTPCarrier"} {
		for cut := 0; cut < len(wire); cut++ {
			root, err := base.ParseRule("transport-layer/xtp.yaml")
			require.NoError(t, err)
			root.Cfg.SetItem(base.CfgLength, uint64(len(wire))*8)
			r := base.NewBitReader(bytes.NewReader(wire[:cut]))
			require.NoError(t, r.Backup())
			require.Error(t, root.ParseSubNode(r, entry))
			require.NoError(t, r.Recovery())
			if cut > 0 {
				got, err := r.ReadBits(uint64(cut) * 8)
				require.NoError(t, err)
				require.Equal(t, wire[:cut], got)
			}
			require.ErrorContains(t, r.PopBackup(), "no backup")
		}
	}
}

func TestProtocolCorpusXTPNonByteImportBoundary(t *testing.T) {
	for offset := uint64(0); offset < 8; offset++ {
		for extra := uint64(1); extra < 8; extra++ {
			wire := xtpTestWire(t, 0)
			var packed, before bytes.Buffer
			writer, expected := base.NewBitWriter(&packed), base.NewBitWriter(&before)
			if offset > 0 {
				require.NoError(t, writer.WriteBits([]byte{0x55}, offset))
				require.NoError(t, expected.WriteBits([]byte{0x55}, offset))
			}
			require.NoError(t, writer.WriteBits(wire, 256))
			require.NoError(t, writer.WriteBits([]byte{0x55}, extra))
			require.NoError(t, writer.WriteBits([]byte{0xd3}, 8))
			if padding := (8 - (offset+extra)%8) % 8; padding > 0 {
				require.NoError(t, writer.WriteBits([]byte{0}, padding))
			}
			root := latTestInline(t, fmt.Sprintf(`Package:
  Wrapped:
    operator: |
      if %d > 0 { this.ProcessSubNode("Prefix") }
      this.ProcessSubNode("Message")
      this.ProcessSubNode("Sentinel")
    Prefix: uint8,%dbit
    Message:
      import: transport-layer/xtp.yaml
      node: XTPCarrier
      length: %d
    Sentinel: uint8
`, offset, offset, 256+extra))
			root.Cfg.SetItem(base.CfgLength, uint64(packed.Len())*8)
			r := base.NewBitReader(bytes.NewReader(packed.Bytes()))
			err := root.ParseSubNode(r, "Wrapped")
			require.ErrorContains(t, err, "xtp: carrier requires a byte boundary")
			n := base.GetNodeByPath(root, "@Wrapped")
			for _, name := range []string{"Key", "Unparsed XTP Payload", "Sentinel"} {
				require.Nil(t, protocolCorpusFindNode(n, name))
			}
			require.Equal(t, offset, root.Ctx.GetUint64("pointer"))
			require.Equal(t, before.Bytes(), root.Ctx.GetItem("buffer").(*bytes.Buffer).Bytes())
			require.Equal(t, expected.Snapshot(), root.Ctx.GetItem("writer").(*base.BitWriter).Snapshot())
			got, err := r.ReadBits(256)
			require.NoError(t, err)
			require.Equal(t, wire, got)
			_, err = r.ReadBits(extra)
			require.NoError(t, err)
			got, err = r.ReadBits(8)
			require.NoError(t, err)
			require.Equal(t, []byte{0xd3}, got)
			require.ErrorContains(t, r.PopBackup(), "no backup")
		}
	}
}
