package bin_parser

import (
	"bytes"
	"crypto/sha256"
	"encoding/binary"
	"encoding/hex"
	"fmt"
	"io"
	"os"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
	"github.com/yaklang/yaklang/common/bin-parser/parser"
	"github.com/yaklang/yaklang/common/bin-parser/parser/base"
	"github.com/yaklang/yaklang/common/bin-parser/parser/stream_parser"
	yaml "github.com/yaklang/yaklang/common/utils/orderedyaml"
)

const redfishSSDPCorpusRule = "application-layer.redfish_ssdp"
const redfishSSDPTestTarget = "urn:dmtf-org:service:redfish-rest:1"
const redfishSSDPTestUUID = "92384634-2938-2342-8820-489239905423"

// Independently assembled text messages from DSP0266 1.23.1 section 12.4,
// UDA 2.0 section 1.3.2 and the backwards-compatible UDA 1.0 notifications.
// They are literal wire data, not generated by the rule being tested.
func redfishSSDPTestFixtures() []struct{ name, kind, wire string } {
	return []struct{ name, kind, wire string }{
		{"multicast-search", "Search Request", "M-SEARCH * HTTP/1.1\r\nHOST: 239.255.255.250:1900\r\nMAN: \"ssdp:discover\"\r\nST: urn:dmtf-org:service:redfish-rest:1\r\nMX: 2\r\n\r\n"},
		{"search-response", "Search Response", "HTTP/1.1 200 OK\r\nCACHE-CONTROL: max-age=1800\r\nST: urn:dmtf-org:service:redfish-rest:1\r\nUSN: uuid:92384634-2938-2342-8820-489239905423::urn:dmtf-org:service:redfish-rest:1\r\nAL: https://192.0.2.50/redfish/v1/\r\nEXT:\r\n\r\n"},
		{"alive", "Notification", "NOTIFY * HTTP/1.1\r\nHOST: 239.255.255.250:1900\r\nCACHE-CONTROL: max-age=1800\r\nLOCATION: http://192.0.2.50/description.xml\r\nNT: urn:dmtf-org:service:redfish-rest:1\r\nNTS: ssdp:alive\r\nSERVER: SampleOS/1.0 UPnP/1.0 Discovery/1.0\r\nUSN: uuid:92384634-2938-2342-8820-489239905423::urn:dmtf-org:service:redfish-rest:1\r\n\r\n"},
		{"byebye", "Notification", "NOTIFY * HTTP/1.1\r\nHOST: 239.255.255.250:1900\r\nNT: urn:dmtf-org:service:redfish-rest:1\r\nNTS: ssdp:byebye\r\nUSN: uuid:92384634-2938-2342-8820-489239905423::urn:dmtf-org:service:redfish-rest:1\r\n\r\n"},
		{"unicast-search", "Search Request", "M-SEARCH * HTTP/1.1\r\nHOST: 192.0.2.50:1901\r\nMAN: \"ssdp:discover\"\r\nST: urn:dmtf-org:service:redfish-rest:1\r\n\r\n"},
		{"response-minor", "Search Response", "HTTP/1.1 200 OK\r\ncache-control:\tmax-age = 3600\r\nst: urn:dmtf-org:service:redfish-rest:1:23\r\nusn: uuid:92384634-2938-2342-8820-489239905423::urn:dmtf-org:service:redfish-rest:1:23\r\nal: https://[2001:db8::50]:8443/redfish/v1/\r\next:\t\r\nsample.example.com: first\r\nsample.example.com: second\r\n\r\n"},
	}
}

func redfishSSDPTestMessage(t *testing.T, node *base.Node) *base.Node {
	t.Helper()
	var found *base.Node
	var walk func(*base.Node)
	walk = func(n *base.Node) {
		if info, ok := n.Cfg.GetItem("additionInfo").(map[string]any); ok && info["Redfish Specific Target"] == true {
			found = n
			return
		}
		for _, child := range n.Children {
			walk(child)
		}
	}
	walk(node)
	require.NotNil(t, found)
	return found
}

func TestProtocolCorpusRedfishSSDPFields(t *testing.T) {
	for _, fixture := range redfishSSDPTestFixtures() {
		for _, entry := range []string{"RedfishSSDP", "RedfishSSDPCarrier"} {
			t.Run(fixture.name+"/"+entry, func(t *testing.T) {
				node := protocolCorpusRequireBoundedRuleParse(t, []byte(fixture.wire), redfishSSDPCorpusRule, entry)
				require.Equal(t, []byte(fixture.wire), NodeToBytes(node))
				message := redfishSSDPTestMessage(t, node)
				info := message.Cfg.GetItem("additionInfo").(map[string]any)
				require.Equal(t, fixture.kind, info["Message Kind"])
				require.Equal(t, false, info["Redfish REST Validated"])
				require.Equal(t, false, info["Remote UUID Equality Validated"])
				require.Equal(t, false, info["UPnP Capability Profile Validated"])
				require.Equal(t, false, info["Transport Context Validated"])
				require.EqualValues(t, 1, info["Service Major Version"])
				redfishSSDPTestFields(t, message, fixture.wire, 0)
				if fixture.name == "response-minor" {
					require.Equal(t, redfishSSDPTestTarget+":23", info["Service Target"])
					require.EqualValues(t, 23, info["Service Minor Version"])
					require.Equal(t, true, info["Service Minor Present"])
					require.Equal(t, "2001:db8::50", info["al URL"].(map[string]any)["hostname"])
				} else {
					require.Equal(t, redfishSSDPTestTarget, info["Service Target"])
					require.EqualValues(t, 0, info["Service Minor Version"])
					require.Equal(t, false, info["Service Minor Present"])
				}
				if fixture.kind != "Search Request" {
					require.Equal(t, redfishSSDPTestUUID, info["Service UUID"])
				}
				switch fixture.name {
				case "multicast-search":
					require.EqualValues(t, 2, info["Maximum Wait Seconds"])
					require.Equal(t, true, info["Host Is Standard Multicast"])
				case "unicast-search":
					require.NotContains(t, info, "Maximum Wait Seconds")
					require.Equal(t, false, info["Host Is Standard Multicast"])
				case "search-response", "alive":
					require.EqualValues(t, 1800, info["Maximum Age Seconds"])
				case "response-minor":
					require.EqualValues(t, 3600, info["Maximum Age Seconds"])
				case "byebye":
					require.NotContains(t, info, "Maximum Age Seconds")
				}
				if fixture.name == "alive" || fixture.name == "byebye" {
					require.Equal(t, "ssdp:"+fixture.name, info["Notification Subtype"])
				}
				if fixture.kind == "Search Response" {
					url := info["al URL"].(map[string]any)
					require.Equal(t, "https", url["scheme"])
					require.Equal(t, "/redfish/v1/", url["path"])
					require.Equal(t, "/redfish/v1/", url["escaped_path"])
					require.Equal(t, "", url["raw_query"])
				}
			})
		}
	}
}

// The independent text tokenizer is only an expected-value oracle. It does not
// call the rule, HTTP, or SSDP code to calculate field values or global spans.
func redfishSSDPTestFields(t *testing.T, message *base.Node, wire string, bitOffset uint64) {
	t.Helper()
	lines := strings.Split(wire, "\r\n")
	lineName := "Request Line"
	fieldNames := []string{"Method", "Target", "Version"}
	if strings.HasPrefix(wire, "HTTP/") {
		lineName = "Response Line"
		fieldNames = []string{"Version", "Status", "Reason"}
	}
	position := 0
	line := protocolCorpusFindNode(message, lineName)
	require.NotNil(t, line)
	check := func(node *base.Node, expected string, delimiter int) {
		t.Helper()
		require.NotNil(t, node)
		require.Equal(t, "string", node.Cfg.GetString(base.CfgType))
		require.Equal(t, [2]uint64{bitOffset + uint64(position)*8, bitOffset + uint64(position+len(expected))*8}, stream_parser.GetNodeResultPos(node), node.Name)
		require.Equal(t, uint64(len(expected)+delimiter)*8, stream_parser.CalcNodeConsumedLength(node))
		result, err := node.Result()
		require.NoError(t, err)
		require.Same(t, node, result.Origin)
		require.IsType(t, "", result.Value)
		require.Equal(t, expected, result.Value)
		position += len(expected) + delimiter
	}
	for index, value := range strings.SplitN(lines[0], " ", 3) {
		delim := 1
		if index == 2 {
			delim = 2
		}
		check(protocolCorpusFindNode(line, fieldNames[index]), value, delim)
	}
	headers := protocolCorpusFindNode(message, "Headers")
	require.NotNil(t, headers)
	require.Len(t, headers.Children, len(lines)-3)
	require.EqualValues(t, len(lines)-3, headers.Cfg.GetItem("additionInfo").(map[string]any)["Count"])
	for index, text := range lines[1 : len(lines)-2] {
		parts := strings.SplitN(text, ":", 2)
		require.Len(t, parts, 2)
		header := headers.Children[index]
		check(protocolCorpusFindNode(header, "Name"), parts[0], 1)
		check(protocolCorpusFindNode(header, "Value"), parts[1], 2)
		info := header.Cfg.GetItem("additionInfo").(map[string]any)
		require.Equal(t, strings.ToLower(parts[0]), info["Normalized Name"])
		require.Equal(t, strings.Trim(parts[1], " \t"), info["Normalized Value"])
	}
	end := protocolCorpusFindNode(message, "Message End")
	require.Equal(t, "uint16", end.Cfg.GetString(base.CfgType))
	require.Equal(t, [2]uint64{bitOffset + uint64(position)*8, bitOffset + uint64(position+2)*8}, stream_parser.GetNodeResultPos(end))
	result, err := end.Result()
	require.NoError(t, err)
	require.Equal(t, uint16(0x0d0a), result.Value)
	require.Same(t, end, result.Origin)
	require.Equal(t, len(wire), position+2)
	require.Equal(t, uint64(len(wire))*8, stream_parser.CalcNodeConsumedLength(message))
	var walk func(*base.Node)
	walk = func(n *base.Node) {
		for _, child := range n.Children {
			require.Same(t, n, child.Cfg.GetItem(base.CfgParent))
			require.Same(t, n.Ctx.GetItem("buffer"), child.Ctx.GetItem("buffer"))
			require.Same(t, n.Ctx.GetItem("writer"), child.Ctx.GetItem("writer"))
			walk(child)
		}
	}
	walk(message)
}

func redfishSSDPTestRaw(t *testing.T, wire []byte) {
	t.Helper()
	node := protocolCorpusRequireBoundedRuleParse(t, wire, redfishSSDPCorpusRule, "RedfishSSDPCarrier")
	raw := protocolCorpusFindNode(node, "Unparsed Redfish SSDP Payload")
	require.NotNil(t, raw)
	require.Equal(t, "raw", raw.Cfg.GetString(base.CfgType))
	require.Equal(t, [2]uint64{0, uint64(len(wire)) * 8}, stream_parser.GetNodeResultPos(raw))
	value, err := raw.Result()
	require.NoError(t, err)
	require.Same(t, raw, value.Origin)
	require.Equal(t, wire, value.Value)
	require.Nil(t, protocolCorpusFindNode(node, "Method"))
	require.Nil(t, protocolCorpusFindNode(node, "Status"))
	require.Nil(t, protocolCorpusFindNode(node, "Headers"))
	require.Equal(t, wire, NodeToBytes(node))
}

func TestProtocolCorpusRedfishSSDPOriginalEveryRecord(t *testing.T) {
	const path = "captures/generated-pr5023/pr5023-gen-redfish-ssdp.pcap"
	data, err := os.ReadFile("testdata/protocol-corpus/" + path)
	require.NoError(t, err)
	digest := sha256.Sum256(data)
	require.Equal(t, "7125fdb142473fb130fa3ec35d9517a17500309651cd55509ce6962c44dc2eac", hex.EncodeToString(digest[:]))
	frames := protocolCorpusAuditPackets(t, "testdata/protocol-corpus/"+path)
	require.Len(t, frames, 1)
	for index, frame := range frames {
		t.Run(fmt.Sprint(index+1), func(t *testing.T) {
			require.Len(t, frame, 158)
			require.Equal(t, byte(64), frame[22], "retain original TTL; a SHOULD is not a wire rejection")
			wire := frame[42:]
			require.Equal(t, strings.Replace(redfishSSDPTestFixtures()[0].wire, "redfish-rest", "redfish", 1), string(wire))
			_, err := parser.ParseBinary(newProtocolCorpusBoundedReader(wire), redfishSSDPCorpusRule, "RedfishSSDP")
			require.ErrorContains(t, err, "unsupported Redfish service target")
			redfishSSDPTestRaw(t, wire)
		})
	}
}

func TestProtocolCorpusRedfishSSDPCompanionEveryRecord(t *testing.T) {
	const path = "testdata/protocol-corpus/captures/generated-validated/gen-redfish-ssdp-valid.pcap"
	data, err := os.ReadFile(path)
	require.NoError(t, err)
	digest := sha256.Sum256(data)
	require.Equal(t, "51ff9ea07c8b1af57831a5380d2eeee1093e8a7c750e9ce577702359cfd8a9d5", hex.EncodeToString(digest[:]))
	frames := protocolCorpusAuditPackets(t, path)
	fixtures := redfishSSDPTestFixtures()
	require.Len(t, frames, len(fixtures))
	for index, frame := range frames {
		t.Run(fixtures[index].name, func(t *testing.T) {
			require.Equal(t, []byte{8, 0}, frame[12:14])
			require.Equal(t, byte(0x45), frame[14])
			require.Equal(t, byte(17), frame[23])
			require.EqualValues(t, len(frame)-14, binary.BigEndian.Uint16(frame[16:18]))
			require.EqualValues(t, len(frame)-34, binary.BigEndian.Uint16(frame[38:40]))
			require.Equal(t, fixtures[index].wire, string(frame[42:]))
			for _, entry := range []string{"RedfishSSDP", "RedfishSSDPCarrier"} {
				node := protocolCorpusRequireBoundedRuleParse(t, frame[42:], redfishSSDPCorpusRule, entry)
				redfishSSDPTestFields(t, redfishSSDPTestMessage(t, node), fixtures[index].wire, 0)
				require.Equal(t, frame[42:], NodeToBytes(node))
			}
		})
	}
}

func redfishSSDPTestAddHeader(wire, header string) string {
	return strings.TrimSuffix(wire, "\r\n") + header + "\r\n\r\n"
}

func TestProtocolCorpusRedfishSSDPSupportedVariations(t *testing.T) {
	fixtures := redfishSSDPTestFixtures()
	query, response, alive := fixtures[0].wire, fixtures[1].wire, fixtures[2].wire
	cases := []string{
		strings.Replace(query, "MX: 2", "MX: 60", 1), // The recommended <=5 is not a SHALL.
		strings.Replace(query, "HOST:", "hOsT:", 1),
		strings.Replace(query, "239.255.255.250:1900", "239.255.255.250", 1),
		strings.Replace(query, "239.255.255.250:1900", "[ff02::c]:1900", 1),
		strings.Replace(query, "239.255.255.250:1900", "[FF05::C]", 1),
		strings.Replace(query, "239.255.255.250:1900", "[ff02:0:0:0:0:0:0:c]:01900", 1),
		strings.Replace(alive, "max-age=1800", "max-age=0", 1), // UDA notification recommendation only.
		strings.Replace(response, "max-age=1800", "opaque=\"a,b\", MAX-AGE = 4294967295", 1),
		redfishSSDPTestAddHeader(query, "CONTENT-LENGTH: 000"),
		redfishSSDPTestAddHeader(response, "LOCATION: http://example.test/description.xml?name=a%20b"),
		redfishSSDPTestAddHeader(query, "x.example.test:\tvalue\t"),
		redfishSSDPTestAddHeader(query, "x.example.test: \x80\xff"),
	}
	for index, wire := range cases {
		t.Run(fmt.Sprint(index), func(t *testing.T) {
			node := protocolCorpusRequireBoundedRuleParse(t, []byte(wire), redfishSSDPCorpusRule, "RedfishSSDP")
			redfishSSDPTestFields(t, redfishSSDPTestMessage(t, node), wire, 0)
		})
	}
}

func TestProtocolCorpusRedfishSSDPNegatives(t *testing.T) {
	f := redfishSSDPTestFixtures()
	q, r, a, b := f[0].wire, f[1].wire, f[2].wire, f[3].wire
	cases := []struct{ name, wire, reason string }{
		{"old-target", strings.Replace(q, "redfish-rest", "redfish", 1), "unsupported Redfish service target"},
		{"generic-target", strings.Replace(q, redfishSSDPTestTarget, "ssdp:all", 1), "unsupported Redfish service target"},
		{"root-target", strings.Replace(q, redfishSSDPTestTarget, "upnp:rootdevice", 1), "unsupported Redfish service target"},
		{"wrong-major", strings.Replace(q, redfishSSDPTestTarget, strings.TrimSuffix(redfishSSDPTestTarget, "1")+"2", 1), "unsupported Redfish service target"},
		{"wrong-method", strings.Replace(q, "M-SEARCH", "GET", 1), "unsupported method"},
		{"wrong-path", strings.Replace(q, " * ", " / ", 1), "asterisk"},
		{"wrong-version", strings.Replace(q, "HTTP/1.1", "HTTP/1.0", 1), "version"},
		{"wrong-status", strings.Replace(r, "200 OK", "201 OK", 1), "status"},
		{"wrong-reason", strings.Replace(r, "200 OK", "200 Fine", 1), "reason"},
		{"body", q + "x", "body or trailing"},
		{"double-message", q + q, "body or trailing"},
		{"content-length", redfishSSDPTestAddHeader(q, "Content-Length: 1"), "body length"},
		{"transfer", redfishSSDPTestAddHeader(q, "Transfer-Encoding: chunked"), "transfer framing"},
		{"blank-transfer", redfishSSDPTestAddHeader(q, "Transfer-Encoding:"), "transfer framing"},
		{"namespace", strings.Replace(q, "\"ssdp:discover\"", "ssdp:discover", 1), "namespace"},
		{"namespace-case", strings.Replace(q, "ssdp:discover", "SSDP:DISCOVER", 1), "namespace"},
		{"no-mx", strings.Replace(q, "MX: 2\r\n", "", 1), "requires MX"},
		{"no-mx-expanded-ipv6", strings.ReplaceAll(strings.Replace(q, "MX: 2\r\n", "", 1), "239.255.255.250:1900", "[ff02:0:0:0:0:0:0:c]:01900"), "requires MX"},
		{"mx-zero", strings.Replace(q, "MX: 2", "MX: 0", 1), "positive"},
		{"mx-overflow", strings.Replace(q, "MX: 2", "MX: 4294967296", 1), "decimal exceeds"},
		{"mx-negative", strings.Replace(q, "MX: 2", "MX: -1", 1), "invalid decimal"},
		{"mx-empty", strings.Replace(q, "MX: 2", "MX:", 1), "empty decimal"},
		{"minor-zero", strings.Replace(q, redfishSSDPTestTarget, redfishSSDPTestTarget+":0", 1), "minor version"},
		{"minor-overflow", strings.Replace(q, redfishSSDPTestTarget, redfishSSDPTestTarget+":4294967296", 1), "decimal exceeds"},
		{"bad-host-port", strings.Replace(q, "239.255.255.250:1900", "example.test:65536", 1), "HOST authority"},
		{"wrong-multicast-port", strings.Replace(q, "239.255.255.250:1900", "239.255.255.250:1901", 1), "multicast HOST port"},
		{"bad-host-path", strings.Replace(q, "239.255.255.250:1900", "example.test/path", 1), "HOST authority"},
		{"bad-host-user", strings.Replace(q, "239.255.255.250:1900", "user@example.test", 1), "HOST authority"},
		{"bad-header-token", redfishSSDPTestAddHeader(q, "bad name: value"), "header name"},
		{"empty-header-name", redfishSSDPTestAddHeader(q, ": value"), "header name"},
		{"bad-header-ctl", redfishSSDPTestAddHeader(q, "X: \x00"), "header value"},
		{"bad-header-del", redfishSSDPTestAddHeader(q, "X: \x7f"), "header value"},
		{"folded", redfishSSDPTestAddHeader(q, " continuation: value"), "header name"},
		{"response-age", strings.Replace(r, "max-age=1800", "max-age=1799", 1), "below 1800"},
		{"response-age-duplicate", strings.Replace(r, "max-age=1800", "max-age=1800, max-age=1800", 1), "ambiguous max-age"},
		{"response-age-missing", strings.Replace(r, "max-age=1800", "opaque=0", 1), "missing max-age"},
		{"response-cache-quote", strings.Replace(r, "max-age=1800", "max-age=1800, opaque=\"unclosed", 1), "malformed cache"},
		{"response-ext", strings.Replace(r, "EXT:\r\n", "EXT: value\r\n", 1), "EXT must be empty"},
		{"response-uuid", strings.Replace(r, redfishSSDPTestUUID, "not-a-canonical-uuid", 1), "USN UUID"},
		{"response-uuid-char", strings.Replace(r, redfishSSDPTestUUID, "g2384634-2938-2342-8820-489239905423", 1), "USN UUID"},
		{"response-usn-mismatch", strings.Replace(r, "::"+redfishSSDPTestTarget, "::"+redfishSSDPTestTarget+":2", 1), "does not match"},
		{"update-unsupported", strings.Replace(a, "ssdp:alive", "ssdp:update", 1), "unsupported notification subtype"},
		{"notify-unicast", strings.Replace(b, "239.255.255.250:1900", "192.0.2.50:1900", 1), "notification multicast"},
		{"alive-empty-server", strings.Replace(a, "SampleOS/1.0 UPnP/1.0 Discovery/1.0", "", 1), "empty SERVER"},
		{"query-notify-fields", redfishSSDPTestAddHeader(q, "NT: "+redfishSSDPTestTarget), "notification fields"},
		{"response-search-fields", redfishSSDPTestAddHeader(r, "MX: 2"), "request fields"},
		{"notify-search-fields", redfishSSDPTestAddHeader(b, "ST: "+redfishSSDPTestTarget), "search fields"},
	}
	for _, url := range []string{"/redfish/v1/", "ftp://example.test/", "http://", "http://u@example.test/", "https://example.test/#fragment", "http://[garbage]/", "http://example.test:99999/", "http://example.test/a b", "http://example.test/a\\b", "http://example.test/?q=%xy", "http://example.test/?q=a b", "http://example.test/<x>"} {
		cases = append(cases, struct{ name, wire, reason string }{"url/" + url, strings.Replace(r, "https://192.0.2.50/redfish/v1/", url, 1), "invalid absolute HTTP(S) URL"})
	}
	for _, fixture := range f[:4] {
		lines := strings.Split(fixture.wire, "\r\n")
		for _, header := range lines[1 : len(lines)-2] {
			name := strings.SplitN(header, ":", 2)[0]
			cases = append(cases, struct{ name, wire, reason string }{fixture.name + "/duplicate/" + name, redfishSSDPTestAddHeader(fixture.wire, strings.ToLower(name)+header[len(name):]), "duplicate singleton header"})
			cases = append(cases, struct{ name, wire, reason string }{fixture.name + "/missing/" + name, strings.Replace(fixture.wire, header+"\r\n", "", 1), ""})
		}
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			_, err := parser.ParseBinary(newProtocolCorpusBoundedReader([]byte(tc.wire)), redfishSSDPCorpusRule, "RedfishSSDP")
			require.Error(t, err)
			if tc.reason != "" {
				require.ErrorContains(t, err, tc.reason)
			}
			redfishSSDPTestRaw(t, []byte(tc.wire))
		})
	}
}

func redfishSSDPTestInline(t *testing.T, source string) *base.Node {
	t.Helper()
	var document yaml.MapSlice
	require.NoError(t, yaml.Unmarshal([]byte(source), &document))
	root, err := base.NewNodeTree(document)
	require.NoError(t, err)
	return root
}

func TestProtocolCorpusRedfishSSDPGlobalOffsetsTransactions(t *testing.T) {
	for offset := uint64(0); offset < 8; offset++ {
		for _, bad := range []bool{false, true} {
			t.Run(fmt.Sprintf("%d/%t", offset, bad), func(t *testing.T) {
				wire := redfishSSDPTestFixtures()[1].wire
				if bad {
					wire = strings.Replace(wire, "EXT:", "EXT: not-empty", 1)
				}
				var packed bytes.Buffer
				writer := base.NewBitWriter(&packed)
				if offset > 0 {
					require.NoError(t, writer.WriteBits([]byte{0x55}, offset))
				}
				require.NoError(t, writer.WriteBits([]byte(wire), uint64(len(wire))*8))
				require.NoError(t, writer.WriteBits([]byte{0xd3}, 8))
				if offset > 0 {
					require.NoError(t, writer.WriteBits([]byte{0}, 8-offset))
				}
				root := redfishSSDPTestInline(t, fmt.Sprintf(`
endian: big
Package:
  Wrapped:
    operator: |
      if %d > 0 { this.ProcessSubNode("Prefix") }
      this.GetSubNode("Frame").SetMaxLength(%d)
      this.ProcessSubNode("Frame")
      this.ProcessSubNode("Sentinel")
      if %d > 0 { this.ProcessSubNode("Padding") }
    Prefix: uint8,%dbit
    Frame: "import:application-layer/redfish_ssdp.yaml;node:RedfishSSDPCarrier"
    Sentinel: uint8
    Padding: uint8,%dbit
`, offset, len(wire), offset, offset, 8-offset))
				root.Cfg.SetItem(base.CfgLength, uint64(packed.Len())*8)
				root.Ctx.SetItem("redfish-test-marker", "outer")
				reader := base.NewBitReader(bytes.NewReader(packed.Bytes()))
				require.NoError(t, root.ParseSubNode(reader, "Wrapped"))
				wrapped := base.GetNodeByPath(root, "@Wrapped")
				if !bad {
					redfishSSDPTestFields(t, redfishSSDPTestMessage(t, wrapped), wire, offset)
				} else {
					raw := protocolCorpusFindNode(wrapped, "Unparsed Redfish SSDP Payload")
					require.NotNil(t, raw)
					require.Equal(t, [2]uint64{offset, offset + uint64(len(wire))*8}, stream_parser.GetNodeResultPos(raw))
					value, err := raw.Result()
					require.NoError(t, err)
					require.Equal(t, []byte(wire), value.Value)
					require.Nil(t, protocolCorpusFindNode(wrapped, "Status"))
					require.Nil(t, protocolCorpusFindNode(wrapped, "Headers"))
				}
				sentinel := protocolCorpusFindNode(wrapped, "Sentinel")
				require.Equal(t, [2]uint64{offset + uint64(len(wire))*8, offset + uint64(len(wire)+1)*8}, stream_parser.GetNodeResultPos(sentinel))
				protocolCorpusRequireValue(t, wrapped, "Sentinel", uint64(0xd3))
				require.Equal(t, "outer", root.Ctx.GetItem("redfish-test-marker"))
				require.ErrorContains(t, reader.Recovery(), "no backup")
				require.ErrorContains(t, reader.PopBackup(), "no backup")
				require.Equal(t, packed.Bytes(), NodeToBytes(wrapped))
				_, err := reader.ReadBits(8)
				require.ErrorIs(t, err, io.EOF)
			})
		}
	}
}

func TestProtocolCorpusRedfishSSDPShortPrefixes(t *testing.T) {
	for _, fixture := range redfishSSDPTestFixtures() {
		t.Run(fixture.name, func(t *testing.T) {
			for length := 0; length < len(fixture.wire); length++ {
				wire := []byte(fixture.wire[:length])
				_, err := parser.ParseBinary(newProtocolCorpusBoundedReader(wire), redfishSSDPCorpusRule, "RedfishSSDP")
				require.Error(t, err, "prefix %d", length)
				if length > 0 {
					redfishSSDPTestRaw(t, wire)
				}
			}
		})
	}
}

func TestProtocolCorpusRedfishSSDPShortPhysicalReaders(t *testing.T) {
	wire := []byte(redfishSSDPTestFixtures()[0].wire)
	for length := 0; length < len(wire); length++ {
		root, err := base.ParseRule("application-layer/redfish_ssdp.yaml")
		require.NoError(t, err)
		root.Cfg.SetItem(base.CfgLength, uint64(len(wire))*8)
		reader := base.NewBitReader(bytes.NewReader(wire[:length]))
		err = root.ParseSubNode(reader, "RedfishSSDPCarrier")
		require.Error(t, err, "available %d", length)
		carrier := base.GetNodeByPath(root, "@RedfishSSDPCarrier")
		require.Nil(t, protocolCorpusFindNode(carrier, "Method"))
		require.Nil(t, protocolCorpusFindNode(carrier, "Headers"))
		require.ErrorContains(t, reader.Recovery(), "no backup")
		require.ErrorContains(t, reader.PopBackup(), "no backup")
	}
}

func TestProtocolCorpusRedfishSSDPBoundariesAndGeneration(t *testing.T) {
	wire := []byte(redfishSSDPTestFixtures()[0].wire)
	for _, entry := range []string{"RedfishSSDP", "RedfishSSDPCarrier"} {
		_, err := parser.ParseBinary(bytes.NewReader(wire), redfishSSDPCorpusRule, entry)
		require.ErrorContains(t, err, "explicit")
		_, err = parser.GenerateBinary(map[string]any{"Method": "M-SEARCH"}, redfishSSDPCorpusRule, entry)
		require.ErrorContains(t, err, "explicit")
		_, err = parser.ParseBinary(newProtocolCorpusBoundedReader(nil), redfishSSDPCorpusRule, entry)
		require.Error(t, err)
		for extra := uint64(1); extra < 8; extra++ {
			root, err := base.ParseRule("application-layer/redfish_ssdp.yaml")
			require.NoError(t, err)
			root.Cfg.SetItem(base.CfgLength, uint64(len(wire))*8+extra)
			reader := bytes.NewReader(append(bytes.Clone(wire), 0))
			err = root.ParseSubNode(base.NewBitReader(reader), entry)
			require.ErrorContains(t, err, "explicit byte boundary")
			require.Equal(t, len(wire)+1, reader.Len(), "reject before reads")
		}
	}
	root, err := base.ParseRule("application-layer/redfish_ssdp.yaml")
	require.NoError(t, err)
	root.Cfg.SetItem(base.CfgLength, uint64(16385)*8)
	reader := bytes.NewReader([]byte{0x55})
	err = root.ParseSubNode(base.NewBitReader(reader), "RedfishSSDP")
	require.ErrorContains(t, err, "16384-byte parser profile")
	require.Equal(t, 1, reader.Len())
}

func TestProtocolCorpusRedfishSSDPResourceProfiles(t *testing.T) {
	query := redfishSSDPTestFixtures()[0].wire
	// Construct exact limits using independent complete extension header lines.
	maxBytes := query
	for len(maxBytes) < 16384 {
		length := 16384 - len(maxBytes)
		if length > 1024 {
			length = 1024
		}
		require.GreaterOrEqual(t, length, 5)
		maxBytes = redfishSSDPTestAddHeader(maxBytes, "X: "+strings.Repeat("v", length-5))
	}
	require.Len(t, maxBytes, 16384)
	maxCount := query
	for index := 0; index < 60; index++ {
		maxCount = redfishSSDPTestAddHeader(maxCount, "X: v")
	}
	maxName := redfishSSDPTestAddHeader(query, strings.Repeat("X", 64)+": v")
	maxHeader := redfishSSDPTestAddHeader(query, "X: "+strings.Repeat("v", 1019))
	for name, wire := range map[string]string{"message-bytes": maxBytes, "header-count": maxCount, "header-name": maxName, "header-bytes": maxHeader} {
		t.Run(name, func(t *testing.T) {
			node := protocolCorpusRequireBoundedRuleParse(t, []byte(wire), redfishSSDPCorpusRule, "RedfishSSDP")
			redfishSSDPTestFields(t, redfishSSDPTestMessage(t, node), wire, 0)
			count := 0
			var walk func(*base.Node)
			walk = func(n *base.Node) {
				count++
				for _, child := range n.Children {
					walk(child)
				}
			}
			walk(node)
			require.Less(t, count, 225, "tree grows with bounded headers, not individual bytes")
		})
	}
	for name, wire := range map[string]string{
		"message-bytes": maxBytes + "x",
		"header-count":  redfishSSDPTestAddHeader(maxCount, "X: v"),
		"header-name":   redfishSSDPTestAddHeader(query, strings.Repeat("X", 65)+": v"),
		"header-bytes":  redfishSSDPTestAddHeader(query, "X: "+strings.Repeat("v", 1020)),
	} {
		t.Run("over-"+name, func(t *testing.T) {
			_, err := parser.ParseBinary(newProtocolCorpusBoundedReader([]byte(wire)), redfishSSDPCorpusRule, "RedfishSSDP")
			require.Error(t, err)
			redfishSSDPTestRaw(t, []byte(wire))
		})
	}
}

func TestProtocolCorpusRedfishSSDPParallelIsolation(t *testing.T) {
	for index := 0; index < 24; index++ {
		index := index
		t.Run(fmt.Sprint(index), func(t *testing.T) {
			t.Parallel()
			fixture := redfishSSDPTestFixtures()[index%6]
			wire := fixture.wire
			if index%4 == 0 {
				wire = strings.ReplaceAll(wire, "redfish-rest", "redfish")
				redfishSSDPTestRaw(t, []byte(wire))
				return
			}
			entry := "RedfishSSDP"
			if index%2 == 0 {
				entry = "RedfishSSDPCarrier"
			}
			node := protocolCorpusRequireBoundedRuleParseWithConfig(t, []byte(wire), redfishSSDPCorpusRule, entry, map[string]any{"redfish-test-marker": index})
			message := redfishSSDPTestMessage(t, node)
			require.Equal(t, index, message.Ctx.GetItem("redfish-test-marker"))
			redfishSSDPTestFields(t, message, wire, 0)
			require.Equal(t, []byte(wire), NodeToBytes(node))
		})
	}
}
