package bin_parser

// RoadmapItem is one protocol we intend the YAML dissector tree to cover.
// Sources:
//   - wireshark: present in Wireshark dissectors
//   - colasoft: advertised by Colasoft Capsa (科来, 1800+ proto / 731 decoded)
//   - private: vendor / national / unpublished framing that Capsa-class tools
//     still identify (QQ family, 国内安全设备, ICS 厂商私有等)
type RoadmapItem struct {
	Name     string
	Family   string
	Sources  []string
	Status   string
	Priority string
	Notes    string
}

const (
	srcWireshark = "wireshark"
	srcColasoft  = "colasoft"
	srcPrivate   = "private"

	stDone    = "done"
	stPartial = "partial"
	stTodo    = "todo"

	priP0 = "P0" // pentest / yaklang 核心流量
	priP1 = "P1" // 企业网常见
	priP2 = "P2" // ICS / 运营商 / 存储
	priP3 = "P3" // 国产 IM / P2P / 厂商私有（科来强项）
	priP4 = "P4" // Wireshark 长尾
)

func src(ss ...string) []string { return ss }

// ProtocolRoadmap is the full support backlog. Implemented dissectors are
// marked done/partial and must stay in sync with ProtocolCatalog.
var ProtocolRoadmap = []RoadmapItem{
	// --- L2 / 链路 ---
	{Name: "Ethernet II", Family: "link", Sources: src(srcWireshark, srcColasoft), Status: stDone, Priority: priP0},
	{Name: "Ethernet 802.2", Family: "link", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP1},
	{Name: "Ethernet 802.3", Family: "link", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP1},
	{Name: "Ethernet SNAP", Family: "link", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP1},
	{Name: "IEEE 802.1Q", Family: "link", Sources: src(srcWireshark, srcColasoft), Status: stDone, Priority: priP0},
	{Name: "IEEE 802.1ad QinQ", Family: "link", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP1},
	{Name: "ARP", Family: "link", Sources: src(srcWireshark, srcColasoft), Status: stDone, Priority: priP0},
	{Name: "RARP", Family: "link", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP2},
	{Name: "PPP", Family: "link", Sources: src(srcWireshark, srcColasoft), Status: stDone, Priority: priP1},
	{Name: "PPPoE Discovery", Family: "link", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP1},
	{Name: "PPPoE Session", Family: "link", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP1},
	{Name: "LCP", Family: "link", Sources: src(srcWireshark, srcColasoft), Status: stDone, Priority: priP1},
	{Name: "PAP", Family: "link", Sources: src(srcWireshark, srcColasoft), Status: stDone, Priority: priP1},
	{Name: "CHAP", Family: "link", Sources: src(srcWireshark, srcColasoft), Status: stDone, Priority: priP1},
	{Name: "EAPOL", Family: "link", Sources: src(srcWireshark, srcColasoft), Status: stPartial, Priority: priP1},
	{Name: "EAP", Family: "link", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP1},
	{Name: "STP", Family: "link", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP1},
	{Name: "RSTP", Family: "link", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP1},
	{Name: "MSTP", Family: "link", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP2},
	{Name: "LLDP", Family: "link", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP1},
	{Name: "CDP", Family: "link", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP1},
	{Name: "LACP", Family: "link", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP2},
	{Name: "MACSec", Family: "link", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "ISL", Family: "link", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "LLC", Family: "link", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP2},
	{Name: "SNAP", Family: "link", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP2},
	{Name: "Loopback", Family: "link", Sources: src(srcWireshark), Status: stTodo, Priority: priP1},
	{Name: "Linux SLL", Family: "link", Sources: src(srcWireshark), Status: stTodo, Priority: priP1},
	{Name: "Linux SLL2", Family: "link", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "IEEE 802.11", Family: "link", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP1},
	{Name: "IEEE 802.11 Radiotap", Family: "link", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "WEP", Family: "link", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP2},
	{Name: "WPA/RSN", Family: "link", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP1},
	{Name: "FCoE", Family: "link", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP2},
	{Name: "Fibre Channel", Family: "link", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP2},
	{Name: "HomePlug AV", Family: "link", Sources: src(srcWireshark), Status: stTodo, Priority: priP4},
	{Name: "IEEE 802.1AB", Family: "link", Sources: src(srcWireshark), Status: stTodo, Priority: priP4},
	{Name: "IEEE 802.1X", Family: "link", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP1},
	{Name: "IEEE 802.1ah PBB", Family: "link", Sources: src(srcWireshark), Status: stTodo, Priority: priP4},
	{Name: "IEEE 802.3 Slow Protocols", Family: "link", Sources: src(srcWireshark), Status: stTodo, Priority: priP4},
	{Name: "MRP-MMRP", Family: "link", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "MRP-MVRP", Family: "link", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "MRP-MSRP", Family: "link", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "EOAM", Family: "link", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "CFM", Family: "link", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "E-LMI", Family: "link", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "VNTAG", Family: "link", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "TRILL", Family: "link", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "SPB", Family: "link", Sources: src(srcWireshark), Status: stTodo, Priority: priP4},

	// --- L3 / 网络与路由 ---
	{Name: "IPv4", Family: "internet", Sources: src(srcWireshark, srcColasoft), Status: stDone, Priority: priP0},
	{Name: "IPv6", Family: "internet", Sources: src(srcWireshark, srcColasoft), Status: stDone, Priority: priP0},
	{Name: "IPv6 Hop-by-Hop", Family: "internet", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP2},
	{Name: "IPv6 Routing Header", Family: "internet", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP2},
	{Name: "IPv6 Fragment", Family: "internet", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP2},
	{Name: "IPv6 Destination Options", Family: "internet", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP2},
	{Name: "ICMP", Family: "internet", Sources: src(srcWireshark, srcColasoft), Status: stDone, Priority: priP0, Notes: "echo/unreach/time-exceeded/redirect/timestamp"},
	{Name: "ICMPv6", Family: "internet", Sources: src(srcWireshark, srcColasoft), Status: stDone, Priority: priP0, Notes: "echo/NS/NA/RS/RA"},
	{Name: "ICMPv6 NDP", Family: "internet", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP1},
	{Name: "ICMPv6 MLD", Family: "internet", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "IGMP", Family: "internet", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP1},
	{Name: "GRE", Family: "internet", Sources: src(srcWireshark, srcColasoft), Status: stDone, Priority: priP1},
	{Name: "IPIP", Family: "internet", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP2},
	{Name: "IPsec AH", Family: "internet", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP1},
	{Name: "IPsec ESP", Family: "internet", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP1},
	{Name: "IPcomp", Family: "internet", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "MPLS", Family: "internet", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP1},
	{Name: "MPLS PW", Family: "internet", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "VXLAN", Family: "internet", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP1},
	{Name: "Geneve", Family: "internet", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "NVGRE", Family: "internet", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "STT", Family: "internet", Sources: src(srcWireshark), Status: stTodo, Priority: priP4},
	{Name: "GTP-C", Family: "internet", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP2},
	{Name: "GTP-U", Family: "internet", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP2},
	{Name: "GTPv2", Family: "internet", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP2},
	{Name: "Mobile IP", Family: "internet", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "MIPv6", Family: "internet", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "L2TP", Family: "internet", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP1},
	{Name: "L2F", Family: "internet", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "PPTP", Family: "internet", Sources: src(srcWireshark, srcColasoft), Status: stPartial, Priority: priP1},
	{Name: "SSTP", Family: "internet", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "OpenVPN", Family: "internet", Sources: src(srcWireshark, srcPrivate), Status: stTodo, Priority: priP1},
	{Name: "WireGuard", Family: "internet", Sources: src(srcWireshark), Status: stTodo, Priority: priP1},
	{Name: "IKEv1", Family: "internet", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP1},
	{Name: "IKEv2", Family: "internet", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP1},
	{Name: "NAT-T", Family: "internet", Sources: src(srcWireshark), Status: stTodo, Priority: priP1},
	{Name: "Teredo", Family: "internet", Sources: src(srcWireshark), Status: stTodo, Priority: priP4},
	{Name: "6in4", Family: "internet", Sources: src(srcWireshark), Status: stTodo, Priority: priP4},
	{Name: "6to4", Family: "internet", Sources: src(srcWireshark), Status: stTodo, Priority: priP4},
	{Name: "ISATAP", Family: "internet", Sources: src(srcWireshark), Status: stTodo, Priority: priP4},

	{Name: "OSPF", Family: "routing", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP1},
	{Name: "OSPFv3", Family: "routing", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "BGP", Family: "routing", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP1},
	{Name: "RIP", Family: "routing", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP1},
	{Name: "RIPng", Family: "routing", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP2},
	{Name: "EIGRP", Family: "routing", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP1},
	{Name: "IS-IS", Family: "routing", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP2},
	{Name: "IGRP", Family: "routing", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "EGP", Family: "routing", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "VRRP", Family: "routing", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP1},
	{Name: "HSRP", Family: "routing", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP1},
	{Name: "GLBP", Family: "routing", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "CARP", Family: "routing", Sources: src(srcWireshark), Status: stTodo, Priority: priP4},
	{Name: "PIM", Family: "routing", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP2},
	{Name: "DVMRP", Family: "routing", Sources: src(srcWireshark), Status: stTodo, Priority: priP4},
	{Name: "MSDP", Family: "routing", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "LDP", Family: "routing", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "RSVP", Family: "routing", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP2},
	{Name: "BFD", Family: "routing", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "LACP-marker", Family: "routing", Sources: src(srcWireshark), Status: stTodo, Priority: priP4},
	{Name: "NHRP", Family: "routing", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "DMVPN", Family: "routing", Sources: src(srcWireshark, srcPrivate), Status: stTodo, Priority: priP2},
	{Name: "OLSR", Family: "routing", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "Babel", Family: "routing", Sources: src(srcWireshark), Status: stTodo, Priority: priP4},

	// --- L4 ---
	{Name: "TCP", Family: "transport", Sources: src(srcWireshark, srcColasoft), Status: stDone, Priority: priP0},
	{Name: "UDP", Family: "transport", Sources: src(srcWireshark, srcColasoft), Status: stDone, Priority: priP0},
	{Name: "SCTP", Family: "transport", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP1},
	{Name: "DCCP", Family: "transport", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "UDP-Lite", Family: "transport", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "QUIC", Family: "transport", Sources: src(srcWireshark), Status: stDone, Priority: priP0, Notes: "long/short header + CID + Initial token"},
	{Name: "NetBIOS", Family: "transport", Sources: src(srcWireshark, srcColasoft), Status: stDone, Priority: priP0, Notes: "NBSS + NBNS"},
	{Name: "NBT NS", Family: "transport", Sources: src(srcWireshark, srcColasoft), Status: stDone, Priority: priP0, Notes: "NBNS questions/answers"},
	{Name: "NBT DG", Family: "transport", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP1},
	{Name: "NBT SS", Family: "transport", Sources: src(srcWireshark, srcColasoft), Status: stDone, Priority: priP0, Notes: "session message + SMB/SMB2 payload"},

	// --- 名称 / 配置 ---
	{Name: "DNS", Family: "name-config", Sources: src(srcWireshark, srcColasoft), Status: stDone, Priority: priP0},
	{Name: "mDNS", Family: "name-config", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP1},
	{Name: "LLMNR", Family: "name-config", Sources: src(srcWireshark), Status: stTodo, Priority: priP1},
	{Name: "NBNS", Family: "name-config", Sources: src(srcWireshark, srcColasoft), Status: stDone, Priority: priP0, Notes: "questions + answers"},
	{Name: "DoT", Family: "name-config", Sources: src(srcWireshark), Status: stTodo, Priority: priP1},
	{Name: "DoH", Family: "name-config", Sources: src(srcWireshark), Status: stTodo, Priority: priP1},
	{Name: "DoQ", Family: "name-config", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "DHCP", Family: "name-config", Sources: src(srcWireshark, srcColasoft), Status: stDone, Priority: priP0},
	{Name: "DHCPv6", Family: "name-config", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP1},
	{Name: "BOOTP", Family: "name-config", Sources: src(srcWireshark, srcColasoft), Status: stPartial, Priority: priP1, Notes: "folded into DHCP"},
	{Name: "NTP", Family: "name-config", Sources: src(srcWireshark, srcColasoft), Status: stDone, Priority: priP1},
	{Name: "SNTP", Family: "name-config", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP2},
	{Name: "PTP", Family: "name-config", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP2},
	{Name: "WINS", Family: "name-config", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP2},
	{Name: "WINS-Replication", Family: "name-config", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "SSDP", Family: "name-config", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP1},
	{Name: "UPnP", Family: "name-config", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP1},
	{Name: "WS-Discovery", Family: "name-config", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "Bonjour", Family: "name-config", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP2},

	// --- Web / TLS ---
	{Name: "HTTP", Family: "web", Sources: src(srcWireshark, srcColasoft), Status: stDone, Priority: priP0, Notes: "request/response + CONNECT + WPAD"},
	{Name: "HTTP/2", Family: "web", Sources: src(srcWireshark), Status: stDone, Priority: priP0, Notes: "preface + DATA/SETTINGS/PING/GOAWAY/WINDOW_UPDATE"},
	{Name: "HTTP/3", Family: "web", Sources: src(srcWireshark), Status: stTodo, Priority: priP1},
	{Name: "WebSocket", Family: "web", Sources: src(srcWireshark), Status: stDone, Priority: priP0, Notes: "RFC 6455 frame"},
	{Name: "SPDY", Family: "web", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "TLS", Family: "web", Sources: src(srcWireshark, srcColasoft), Status: stPartial, Priority: priP0, Notes: "record layer + ClientHello"},
	{Name: "SSL", Family: "web", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP1},
	{Name: "DTLS", Family: "web", Sources: src(srcWireshark), Status: stTodo, Priority: priP1},
	{Name: "JA3/JA4", Family: "web", Sources: src(srcPrivate), Status: stDone, Priority: priP0, Notes: "ClientHello cipher suites"},
	{Name: "gRPC", Family: "web", Sources: src(srcWireshark), Status: stTodo, Priority: priP1},
	{Name: "SOAP", Family: "web", Sources: src(srcWireshark), Status: stTodo, Priority: priP1},
	{Name: "XML-RPC", Family: "web", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "JSON-RPC", Family: "web", Sources: src(srcPrivate), Status: stTodo, Priority: priP1},
	{Name: "WebDAV", Family: "web", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "OCSP", Family: "web", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "ACMEv2", Family: "web", Sources: src(srcPrivate), Status: stTodo, Priority: priP4},

	// --- 邮件 ---
	{Name: "SMTP", Family: "mail", Sources: src(srcWireshark, srcColasoft), Status: stDone, Priority: priP0, Notes: "reply + EHLO/MAIL/RCPT/DATA/AUTH"},
	{Name: "SMTPS", Family: "mail", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP1},
	{Name: "POP3", Family: "mail", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP1},
	{Name: "POP3S", Family: "mail", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP2},
	{Name: "IMAP", Family: "mail", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP1},
	{Name: "IMAPS", Family: "mail", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP2},
	{Name: "NNTP", Family: "mail", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "LMTP", Family: "mail", Sources: src(srcWireshark), Status: stTodo, Priority: priP4},
	{Name: "Submission", Family: "mail", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},

	// --- 文件 / 打印 / 远程文件系统 ---
	{Name: "FTP", Family: "file", Sources: src(srcWireshark, srcColasoft), Status: stDone, Priority: priP0, Notes: "reply + USER/PASS/RETR/STOR"},
	{Name: "FTP-DATA", Family: "file", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP1},
	{Name: "FTPS", Family: "file", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "TFTP", Family: "file", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP1},
	{Name: "SFTP", Family: "file", Sources: src(srcWireshark), Status: stTodo, Priority: priP1},
	{Name: "SCP", Family: "file", Sources: src(srcPrivate), Status: stTodo, Priority: priP2},
	{Name: "NFS", Family: "file", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP1},
	{Name: "RPC", Family: "file", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP1},
	{Name: "Portmap/Rpcbind", Family: "file", Sources: src(srcWireshark), Status: stTodo, Priority: priP1},
	{Name: "Mount", Family: "file", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "SMB", Family: "file", Sources: src(srcWireshark, srcColasoft), Status: stDone, Priority: priP0, Notes: "NEGOTIATE/AndX/CLOSE/TRANSACTION/TRANS2"},
	{Name: "SMB2", Family: "file", Sources: src(srcWireshark, srcColasoft), Status: stDone, Priority: priP0, Notes: "NEGOTIATE/SESSION_SETUP/TREE/CREATE/READ/WRITE/CLOSE/IOCTL"},
	{Name: "SMB3", Family: "file", Sources: src(srcWireshark), Status: stDone, Priority: priP0, Notes: "transform \\xfdSMB + session/nonce"},
	{Name: "CIFS", Family: "file", Sources: src(srcWireshark, srcColasoft), Status: stDone, Priority: priP0, Notes: "see SMB"},
	{Name: "SMB-Direct", Family: "file", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "AFP", Family: "file", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP2},
	{Name: "NCP", Family: "file", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "IPP", Family: "file", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "LPD", Family: "file", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "Rsync", Family: "file", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP2},
	{Name: "9P", Family: "file", Sources: src(srcWireshark), Status: stTodo, Priority: priP4},

	// --- 目录 / 认证 ---
	{Name: "LDAP", Family: "auth", Sources: src(srcWireshark, srcColasoft), Status: stDone, Priority: priP0, Notes: "SEQUENCE + bind/unbind/search tags"},
	{Name: "LDAPS", Family: "auth", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP1},
	{Name: "CLDAP", Family: "auth", Sources: src(srcWireshark), Status: stTodo, Priority: priP1},
	{Name: "Kerberos", Family: "auth", Sources: src(srcWireshark, srcColasoft), Status: stDone, Priority: priP0, Notes: "APPLICATION tags AS/TGS/AP/ERROR + TCP record"},
	{Name: "NTLM", Family: "auth", Sources: src(srcWireshark, srcColasoft), Status: stDone, Priority: priP0, Notes: "see NTLMSSP type 1/2/3"},
	{Name: "NTLMSSP", Family: "auth", Sources: src(srcWireshark), Status: stDone, Priority: priP0, Notes: "type 1/2/3 fields + SMB2/SPNEGO hook"},
	{Name: "SPNEGO", Family: "auth", Sources: src(srcWireshark), Status: stDone, Priority: priP0, Notes: "GSS-API 0x60 + OID + NegToken"},
	{Name: "GSS-API", Family: "auth", Sources: src(srcWireshark), Status: stTodo, Priority: priP1},
	{Name: "RADIUS", Family: "auth", Sources: src(srcWireshark, srcColasoft), Status: stDone, Priority: priP0, Notes: "RFC 2865 header + attributes blob"},
	{Name: "TACACS+", Family: "auth", Sources: src(srcWireshark), Status: stTodo, Priority: priP1},
	{Name: "Diameter", Family: "auth", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "OAuth/OIDC wire", Family: "auth", Sources: src(srcPrivate), Status: stTodo, Priority: priP2},
	{Name: "SAML", Family: "auth", Sources: src(srcPrivate), Status: stTodo, Priority: priP2},
	{Name: "SOCKS4", Family: "auth", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP1},
	{Name: "SOCKS5", Family: "auth", Sources: src(srcWireshark, srcColasoft), Status: stDone, Priority: priP0},
	{Name: "HTTP Proxy CONNECT", Family: "auth", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP1},

	// --- 远程访问 / 终端 ---
	{Name: "SSH", Family: "remote", Sources: src(srcWireshark, srcColasoft), Status: stDone, Priority: priP0, Notes: "banner + binary packet/KEXINIT"},
	{Name: "Telnet", Family: "remote", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP1},
	{Name: "Rlogin", Family: "remote", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "RSH", Family: "remote", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "RDP", Family: "remote", Sources: src(srcWireshark, srcColasoft), Status: stPartial, Priority: priP0, Notes: "TPKT on 3389 + X224/Negotiation"},
	{Name: "CREDSSP", Family: "remote", Sources: src(srcWireshark), Status: stTodo, Priority: priP1},
	{Name: "VNC/RFB", Family: "remote", Sources: src(srcWireshark), Status: stTodo, Priority: priP1},
	{Name: "X11", Family: "remote", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "Citrix ICA", Family: "remote", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP2},
	{Name: "TeamViewer", Family: "remote", Sources: src(srcPrivate, srcColasoft), Status: stTodo, Priority: priP3},
	{Name: "AnyDesk", Family: "remote", Sources: src(srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "Sunlogin/Oray", Family: "remote", Sources: src(srcPrivate, srcColasoft), Status: stTodo, Priority: priP3},
	{Name: "ToDesk", Family: "remote", Sources: src(srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "RustDesk", Family: "remote", Sources: src(srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "PCAnywhere", Family: "remote", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "WinRM", Family: "remote", Sources: src(srcWireshark), Status: stTodo, Priority: priP1},
	{Name: "PsExec/SMB-svcctl", Family: "remote", Sources: src(srcPrivate), Status: stPartial, Priority: priP0, Notes: "SVCCTL via DCE/RPC opnum"},

	// --- 数据库 ---
	{Name: "MySQL", Family: "database", Sources: src(srcWireshark, srcColasoft), Status: stDone, Priority: priP0, Notes: "HandshakeV10/OK/ERR/EOF/COM_QUERY"},
	{Name: "MariaDB", Family: "database", Sources: src(srcWireshark), Status: stTodo, Priority: priP1},
	{Name: "PostgreSQL", Family: "database", Sources: src(srcWireshark, srcColasoft), Status: stDone, Priority: priP0, Notes: "startup/SSL/query/auth/error/ready"},
	{Name: "MSSQL TDS", Family: "database", Sources: src(srcWireshark, srcColasoft), Status: stDone, Priority: priP0, Notes: "header + PRELOGIN tokens/LOGIN7/BATCH"},
	{Name: "Oracle TNS", Family: "database", Sources: src(srcWireshark, srcColasoft), Status: stDone, Priority: priP0, Notes: "header types 1-15 + CONNECT data"},
	{Name: "MongoDB", Family: "database", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP1},
	{Name: "Redis", Family: "database", Sources: src(srcWireshark, srcColasoft), Status: stDone, Priority: priP0},
	{Name: "Memcached", Family: "database", Sources: src(srcWireshark), Status: stTodo, Priority: priP1},
	{Name: "Elasticsearch", Family: "database", Sources: src(srcPrivate), Status: stTodo, Priority: priP1},
	{Name: "Cassandra CQL", Family: "database", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "CouchDB", Family: "database", Sources: src(srcPrivate), Status: stTodo, Priority: priP4},
	{Name: "HBase", Family: "database", Sources: src(srcPrivate), Status: stTodo, Priority: priP2},
	{Name: "ClickHouse", Family: "database", Sources: src(srcPrivate), Status: stTodo, Priority: priP2},
	{Name: "InfluxDB", Family: "database", Sources: src(srcPrivate), Status: stTodo, Priority: priP4},
	{Name: "DB2 DRDA", Family: "database", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "Sybase TDS", Family: "database", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "Informix", Family: "database", Sources: src(srcWireshark), Status: stTodo, Priority: priP4},
	{Name: "SQLite over net", Family: "database", Sources: src(srcPrivate), Status: stTodo, Priority: priP4},
	{Name: "ETCD", Family: "database", Sources: src(srcPrivate), Status: stTodo, Priority: priP2},
	{Name: "ZooKeeper", Family: "database", Sources: src(srcPrivate), Status: stTodo, Priority: priP2},

	// --- 消息队列 / RPC ---
	{Name: "AMQP", Family: "mq-rpc", Sources: src(srcWireshark), Status: stTodo, Priority: priP1},
	{Name: "MQTT", Family: "mq-rpc", Sources: src(srcWireshark, srcColasoft), Status: stDone, Priority: priP0, Notes: "CONNECT/CONNACK/PUBLISH/SUBSCRIBE/PING"},
	{Name: "MQTT-SN", Family: "mq-rpc", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "Kafka", Family: "mq-rpc", Sources: src(srcWireshark), Status: stTodo, Priority: priP1},
	{Name: "RocketMQ", Family: "mq-rpc", Sources: src(srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "RabbitMQ", Family: "mq-rpc", Sources: src(srcWireshark), Status: stTodo, Priority: priP1},
	{Name: "ActiveMQ OpenWire", Family: "mq-rpc", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "STOMP", Family: "mq-rpc", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "NATS", Family: "mq-rpc", Sources: src(srcPrivate), Status: stTodo, Priority: priP2},
	{Name: "NSQ", Family: "mq-rpc", Sources: src(srcPrivate), Status: stTodo, Priority: priP4},
	{Name: "Pulsar", Family: "mq-rpc", Sources: src(srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "IBM MQ", Family: "mq-rpc", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "TIBCO Rendezvous", Family: "mq-rpc", Sources: src(srcWireshark), Status: stTodo, Priority: priP4},
	{Name: "Thrift", Family: "mq-rpc", Sources: src(srcWireshark), Status: stTodo, Priority: priP1},
	{Name: "Protobuf", Family: "mq-rpc", Sources: src(srcWireshark), Status: stTodo, Priority: priP1},
	{Name: "Cap'n Proto", Family: "mq-rpc", Sources: src(srcPrivate), Status: stTodo, Priority: priP4},
	{Name: "Hessian", Family: "mq-rpc", Sources: src(srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "Dubbo", Family: "mq-rpc", Sources: src(srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "SofaRPC", Family: "mq-rpc", Sources: src(srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "gRPC-Web", Family: "mq-rpc", Sources: src(srcPrivate), Status: stTodo, Priority: priP2},
	{Name: "JSON-RPC 2.0", Family: "mq-rpc", Sources: src(srcPrivate), Status: stTodo, Priority: priP1},
	{Name: "ONC RPC", Family: "mq-rpc", Sources: src(srcWireshark), Status: stTodo, Priority: priP1},
	{Name: "DCE/RPC", Family: "mq-rpc", Sources: src(srcWireshark, srcColasoft), Status: stDone, Priority: priP0, Notes: "bind/bind_ack/request/response/fault"},
	{Name: "MSRPC", Family: "mq-rpc", Sources: src(srcWireshark, srcColasoft), Status: stDone, Priority: priP0, Notes: "same as DCE/RPC"},
	{Name: "IIOP/GIOP", Family: "mq-rpc", Sources: src(srcWireshark, srcColasoft), Status: stPartial, Priority: priP1},
	{Name: "T3", Family: "mq-rpc", Sources: src(srcPrivate, srcColasoft), Status: stPartial, Priority: priP1},
	{Name: "RMI/JRMP", Family: "mq-rpc", Sources: src(srcWireshark), Status: stTodo, Priority: priP1},
	{Name: "JNDI", Family: "mq-rpc", Sources: src(srcPrivate), Status: stTodo, Priority: priP1},
	{Name: "BER", Family: "mq-rpc", Sources: src(srcWireshark), Status: stPartial, Priority: priP1},
	{Name: "DER", Family: "mq-rpc", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "ASN.1", Family: "mq-rpc", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},

	// --- 管理 / 监控 ---
	{Name: "SNMP", Family: "mgmt", Sources: src(srcWireshark, srcColasoft), Status: stDone, Priority: priP0, Notes: "v1/v2c Get/Set + varbind SEQUENCE"},
	{Name: "SNMPv3", Family: "mgmt", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP1},
	{Name: "Syslog", Family: "mgmt", Sources: src(srcWireshark), Status: stTodo, Priority: priP1},
	{Name: "NetFlow v5", Family: "mgmt", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "NetFlow v9", Family: "mgmt", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "IPFIX", Family: "mgmt", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "sFlow", Family: "mgmt", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "ICMP Timestamp", Family: "mgmt", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "CWMP/TR-069", Family: "mgmt", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "NETCONF", Family: "mgmt", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "RESTCONF", Family: "mgmt", Sources: src(srcPrivate), Status: stTodo, Priority: priP2},
	{Name: "gNMI", Family: "mgmt", Sources: src(srcPrivate), Status: stTodo, Priority: priP4},
	{Name: "IPMI", Family: "mgmt", Sources: src(srcWireshark), Status: stTodo, Priority: priP1},
	{Name: "Redfish", Family: "mgmt", Sources: src(srcPrivate), Status: stTodo, Priority: priP2},
	{Name: "Collectd", Family: "mgmt", Sources: src(srcWireshark), Status: stTodo, Priority: priP4},
	{Name: "Zabbix", Family: "mgmt", Sources: src(srcPrivate), Status: stTodo, Priority: priP2},
	{Name: "Nagios NSCA", Family: "mgmt", Sources: src(srcPrivate), Status: stTodo, Priority: priP4},
	{Name: "Prometheus exposition", Family: "mgmt", Sources: src(srcPrivate), Status: stTodo, Priority: priP2},
	{Name: "Graphite", Family: "mgmt", Sources: src(srcPrivate), Status: stTodo, Priority: priP4},
	{Name: "StatsD", Family: "mgmt", Sources: src(srcPrivate), Status: stTodo, Priority: priP4},

	// --- VoIP / 媒体 ---
	{Name: "SIP", Family: "voip", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP1},
	{Name: "SDP", Family: "voip", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP1},
	{Name: "RTP", Family: "voip", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP1},
	{Name: "RTCP", Family: "voip", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP1},
	{Name: "RTSP", Family: "voip", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP1},
	{Name: "H.323", Family: "voip", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP2},
	{Name: "H.225", Family: "voip", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP2},
	{Name: "H.245", Family: "voip", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "Q.931", Family: "voip", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP2},
	{Name: "MGCP", Family: "voip", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP2},
	{Name: "Megaco/H.248", Family: "voip", Sources: src(srcWireshark), Status: stTodo, Priority: priP4},
	{Name: "SCCP/Skinny", Family: "voip", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "IAX2", Family: "voip", Sources: src(srcWireshark), Status: stTodo, Priority: priP4},
	{Name: "T.38", Family: "voip", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "WebRTC", Family: "voip", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP1},
	{Name: "STUN", Family: "voip", Sources: src(srcWireshark), Status: stTodo, Priority: priP1},
	{Name: "TURN", Family: "voip", Sources: src(srcWireshark), Status: stTodo, Priority: priP1},
	{Name: "ICE", Family: "voip", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "SRTP", Family: "voip", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "HLS", Family: "voip", Sources: src(srcPrivate), Status: stTodo, Priority: priP4},
	{Name: "RTMP", Family: "voip", Sources: src(srcWireshark), Status: stTodo, Priority: priP1},
	{Name: "RTMPE", Family: "voip", Sources: src(srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "MPEG-TS", Family: "voip", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},

	// --- Microsoft 全家桶 ---
	{Name: "MSRPC EPM", Family: "microsoft", Sources: src(srcWireshark), Status: stPartial, Priority: priP0, Notes: "DCE/RPC bind UUID"},
	{Name: "SAMR", Family: "microsoft", Sources: src(srcWireshark), Status: stPartial, Priority: priP0, Notes: "DCE/RPC bind UUID"},
	{Name: "LSARPC", Family: "microsoft", Sources: src(srcWireshark), Status: stPartial, Priority: priP0, Notes: "DCE/RPC bind UUID"},
	{Name: "NETLOGON", Family: "microsoft", Sources: src(srcWireshark), Status: stPartial, Priority: priP0, Notes: "DCE/RPC bind UUID"},
	{Name: "DRSUAPI", Family: "microsoft", Sources: src(srcWireshark), Status: stPartial, Priority: priP0, Notes: "DCE/RPC bind UUID"},
	{Name: "SRVSVC", Family: "microsoft", Sources: src(srcWireshark), Status: stPartial, Priority: priP0, Notes: "DCE/RPC bind UUID"},
	{Name: "WKSSVC", Family: "microsoft", Sources: src(srcWireshark), Status: stTodo, Priority: priP1},
	{Name: "SVCCTL", Family: "microsoft", Sources: src(srcWireshark), Status: stPartial, Priority: priP0, Notes: "DCE/RPC bind UUID"},
	{Name: "WINREG", Family: "microsoft", Sources: src(srcWireshark), Status: stPartial, Priority: priP0, Notes: "DCE/RPC bind UUID"},
	{Name: "SPOOLSS", Family: "microsoft", Sources: src(srcWireshark), Status: stTodo, Priority: priP1},
	{Name: "ATSVC", Family: "microsoft", Sources: src(srcWireshark), Status: stTodo, Priority: priP1},
	{Name: "RPRN", Family: "microsoft", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "OXABREF/NSPI", Family: "microsoft", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "MAPI", Family: "microsoft", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "Exchange EWS", Family: "microsoft", Sources: src(srcPrivate), Status: stTodo, Priority: priP2},
	{Name: "ADWS", Family: "microsoft", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "WMI", Family: "microsoft", Sources: src(srcWireshark), Status: stPartial, Priority: priP0, Notes: "DCOM/WMI via DCE/RPC"},
	{Name: "DCOM", Family: "microsoft", Sources: src(srcWireshark), Status: stPartial, Priority: priP0, Notes: "DCOM via DCE/RPC"},
	{Name: "IObjectExporter", Family: "microsoft", Sources: src(srcWireshark), Status: stTodo, Priority: priP1},
	{Name: "MS-WSP", Family: "microsoft", Sources: src(srcWireshark), Status: stTodo, Priority: priP4},
	{Name: "MS-FASP", Family: "microsoft", Sources: src(srcWireshark), Status: stTodo, Priority: priP4},
	{Name: "LLMNR-MDNS collision", Family: "microsoft", Sources: src(srcPrivate), Status: stTodo, Priority: priP1},
	{Name: "WPAD", Family: "microsoft", Sources: src(srcPrivate), Status: stTodo, Priority: priP1},

	// --- ICS / SCADA / 工业以太网（科来 + Wireshark 都强） ---
	{Name: "Modbus TCP", Family: "ics", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP2},
	{Name: "Modbus RTU/ASCII", Family: "ics", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP2},
	{Name: "S7comm", Family: "ics", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP2},
	{Name: "S7comm-plus", Family: "ics", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "COTP", Family: "ics", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "TPKT", Family: "ics", Sources: src(srcWireshark), Status: stPartial, Priority: priP1, Notes: "RDP/ISO path"},
	{Name: "DNP3", Family: "ics", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP2},
	{Name: "IEC 60870-5-104", Family: "ics", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP2},
	{Name: "IEC 60870-5-101", Family: "ics", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "IEC 61850 MMS", Family: "ics", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "IEC 61850 GOOSE", Family: "ics", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "IEC 61850 SV", Family: "ics", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "OPC UA", Family: "ics", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "OPC DA", Family: "ics", Sources: src(srcPrivate), Status: stTodo, Priority: priP2},
	{Name: "BACnet", Family: "ics", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP2},
	{Name: "EtherNet/IP CIP", Family: "ics", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP2},
	{Name: "Profinet IO", Family: "ics", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP2},
	{Name: "Profinet DCP", Family: "ics", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "PROFIBUS", Family: "ics", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "EtherCAT", Family: "ics", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP2},
	{Name: "Powerlink", Family: "ics", Sources: src(srcWireshark), Status: stTodo, Priority: priP4},
	{Name: "SERCOS III", Family: "ics", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "CC-Link IE", Family: "ics", Sources: src(srcWireshark, srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "MELSEC", Family: "ics", Sources: src(srcPrivate, srcColasoft), Status: stTodo, Priority: priP3},
	{Name: "Omron FINS", Family: "ics", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP2},
	{Name: "GE SRTP", Family: "ics", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "Beckhoff ADS", Family: "ics", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "CODESYS", Family: "ics", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "Hart-IP", Family: "ics", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "FF HSE", Family: "ics", Sources: src(srcWireshark), Status: stTodo, Priority: priP4},
	{Name: "LonTalk", Family: "ics", Sources: src(srcWireshark), Status: stTodo, Priority: priP4},
	{Name: "KNX/IP", Family: "ics", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "DALI", Family: "ics", Sources: src(srcPrivate), Status: stTodo, Priority: priP4},
	{Name: "CAN/ISO-TP", Family: "ics", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "J1939", Family: "ics", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "UDS", Family: "ics", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "DoIP", Family: "ics", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "VARAN", Family: "ics", Sources: src(srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "AES50", Family: "ics", Sources: src(srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "Zigbee", Family: "ics", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "Z-Wave", Family: "ics", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "LoRaWAN", Family: "ics", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "DLMS/COSEM", Family: "ics", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "IEC 62056", Family: "ics", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "M-Bus", Family: "ics", Sources: src(srcWireshark), Status: stTodo, Priority: priP4},
	{Name: "DALI-2", Family: "ics", Sources: src(srcPrivate), Status: stTodo, Priority: priP4},

	// --- 国产 IM / P2P / 应用识别（科来强项，Wireshark 往往没有） ---
	{Name: "QQ", Family: "cn-app", Sources: src(srcColasoft, srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "QQ Login", Family: "cn-app", Sources: src(srcColasoft, srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "QQ KeepAlive", Family: "cn-app", Sources: src(srcColasoft, srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "QQ Message", Family: "cn-app", Sources: src(srcColasoft, srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "WeChat/MicroMsg", Family: "cn-app", Sources: src(srcPrivate, srcColasoft), Status: stTodo, Priority: priP3},
	{Name: "WeChat MMTLS", Family: "cn-app", Sources: src(srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "DingTalk", Family: "cn-app", Sources: src(srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "Feishu/Lark", Family: "cn-app", Sources: src(srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "WeCom", Family: "cn-app", Sources: src(srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "TIM", Family: "cn-app", Sources: src(srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "YY", Family: "cn-app", Sources: src(srcColasoft, srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "NetEase POPO", Family: "cn-app", Sources: src(srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "AliWangWang", Family: "cn-app", Sources: src(srcColasoft, srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "Fetion", Family: "cn-app", Sources: src(srcColasoft, srcPrivate), Status: stTodo, Priority: priP4},
	{Name: "BaiduHi", Family: "cn-app", Sources: src(srcColasoft, srcPrivate), Status: stTodo, Priority: priP4},
	{Name: "MSNMS", Family: "cn-app", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "Yahoo Messenger", Family: "cn-app", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "IRC", Family: "cn-app", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP2},
	{Name: "XMPP", Family: "cn-app", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP2},
	{Name: "BitTorrent", Family: "cn-app", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP1},
	{Name: "eMule/ED2K", Family: "cn-app", Sources: src(srcColasoft, srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "Thunder/Xunlei", Family: "cn-app", Sources: src(srcColasoft, srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "PPLive", Family: "cn-app", Sources: src(srcColasoft, srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "PPStream", Family: "cn-app", Sources: src(srcColasoft, srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "Qvod", Family: "cn-app", Sources: src(srcColasoft, srcPrivate), Status: stTodo, Priority: priP4},
	{Name: "Funshion", Family: "cn-app", Sources: src(srcColasoft, srcPrivate), Status: stTodo, Priority: priP4},
	{Name: "SoulSeek", Family: "cn-app", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "Gnutella", Family: "cn-app", Sources: src(srcWireshark), Status: stTodo, Priority: priP4},
	{Name: "BaiduNetdisk", Family: "cn-app", Sources: src(srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "AliyunDrive", Family: "cn-app", Sources: src(srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "Quark", Family: "cn-app", Sources: src(srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "iQIYI P2P", Family: "cn-app", Sources: src(srcPrivate, srcColasoft), Status: stTodo, Priority: priP3},
	{Name: "Youku P2P", Family: "cn-app", Sources: src(srcPrivate, srcColasoft), Status: stTodo, Priority: priP3},
	{Name: "Bilibili P2P", Family: "cn-app", Sources: src(srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "Douyin/TikTok", Family: "cn-app", Sources: src(srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "Kuaishou", Family: "cn-app", Sources: src(srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "Kugou", Family: "cn-app", Sources: src(srcColasoft, srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "Kuwo", Family: "cn-app", Sources: src(srcColasoft, srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "Netease Cloud Music", Family: "cn-app", Sources: src(srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "QQ Music", Family: "cn-app", Sources: src(srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "Alipay", Family: "cn-app", Sources: src(srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "WeChat Pay", Family: "cn-app", Sources: src(srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "UnionPay", Family: "cn-app", Sources: src(srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "Taobao", Family: "cn-app", Sources: src(srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "JD", Family: "cn-app", Sources: src(srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "Meituan", Family: "cn-app", Sources: src(srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "DiDi", Family: "cn-app", Sources: src(srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "Pinduoduo", Family: "cn-app", Sources: src(srcPrivate), Status: stTodo, Priority: priP3},

	// --- 国产厂商 / 安全设备私有（科来会认，Wireshark 基本没有） ---
	{Name: "Huawei NCA", Family: "cn-vendor", Sources: src(srcPrivate, srcColasoft), Status: stTodo, Priority: priP3},
	{Name: "Huawei SSL VPN", Family: "cn-vendor", Sources: src(srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "Huawei NHRP+", Family: "cn-vendor", Sources: src(srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "H3C", Family: "cn-vendor", Sources: src(srcPrivate, srcColasoft), Status: stTodo, Priority: priP3},
	{Name: "H3C IRF", Family: "cn-vendor", Sources: src(srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "Sangfor SSL VPN", Family: "cn-vendor", Sources: src(srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "Sangfor aTrust", Family: "cn-vendor", Sources: src(srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "Sangfor AF", Family: "cn-vendor", Sources: src(srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "QiAnXin Tianqing", Family: "cn-vendor", Sources: src(srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "QiAnXin NGFW", Family: "cn-vendor", Sources: src(srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "360 Tianji", Family: "cn-vendor", Sources: src(srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "360 Safe", Family: "cn-vendor", Sources: src(srcPrivate, srcColasoft), Status: stTodo, Priority: priP3},
	{Name: "Hillstone", Family: "cn-vendor", Sources: src(srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "Topsec", Family: "cn-vendor", Sources: src(srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "Venustech", Family: "cn-vendor", Sources: src(srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "Leadsec", Family: "cn-vendor", Sources: src(srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "DPTech", Family: "cn-vendor", Sources: src(srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "NSFOCUS", Family: "cn-vendor", Sources: src(srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "Venus NTA", Family: "cn-vendor", Sources: src(srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "Ruijie", Family: "cn-vendor", Sources: src(srcPrivate, srcColasoft), Status: stTodo, Priority: priP3},
	{Name: "Maipu", Family: "cn-vendor", Sources: src(srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "ZTE", Family: "cn-vendor", Sources: src(srcPrivate, srcColasoft), Status: stTodo, Priority: priP3},
	{Name: "Fiberhome", Family: "cn-vendor", Sources: src(srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "Dahua", Family: "cn-vendor", Sources: src(srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "Hikvision ISAPI", Family: "cn-vendor", Sources: src(srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "Hikvision SDK", Family: "cn-vendor", Sources: src(srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "Uniview", Family: "cn-vendor", Sources: src(srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "GB28181", Family: "cn-vendor", Sources: src(srcPrivate, srcColasoft), Status: stTodo, Priority: priP2},
	{Name: "ONVIF", Family: "cn-vendor", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "RTSP-over-GB", Family: "cn-vendor", Sources: src(srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "WPS Office sync", Family: "cn-vendor", Sources: src(srcPrivate), Status: stTodo, Priority: priP4},
	{Name: "Kingsoft", Family: "cn-vendor", Sources: src(srcPrivate), Status: stTodo, Priority: priP4},
	{Name: "Yakit MITM magic", Family: "cn-vendor", Sources: src(srcPrivate), Status: stDone, Priority: priP0, Notes: "HTTP CONNECT intercept"},

	// --- 运营商 / 短信网关 / 国内规范 ---
	{Name: "CMPP", Family: "carrier", Sources: src(srcPrivate, srcColasoft), Status: stTodo, Priority: priP3, Notes: "中国移动短信"},
	{Name: "SGIP", Family: "carrier", Sources: src(srcPrivate, srcColasoft), Status: stTodo, Priority: priP3, Notes: "中国联通短信"},
	{Name: "SMGP", Family: "carrier", Sources: src(srcPrivate, srcColasoft), Status: stTodo, Priority: priP3, Notes: "中国电信短信"},
	{Name: "SMPP", Family: "carrier", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "UCP/EMI", Family: "carrier", Sources: src(srcWireshark), Status: stTodo, Priority: priP4},
	{Name: "Diameter Cx/Dx", Family: "carrier", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "SIP IMS", Family: "carrier", Sources: src(srcWireshark, srcPrivate), Status: stTodo, Priority: priP2},
	{Name: "RADIUS accounting CN", Family: "carrier", Sources: src(srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "Portal/WebAuth", Family: "carrier", Sources: src(srcPrivate, srcColasoft), Status: stTodo, Priority: priP3},
	{Name: "PPPoE+BRAS", Family: "carrier", Sources: src(srcPrivate), Status: stTodo, Priority: priP2},
	{Name: "DOCSIS", Family: "carrier", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "PacketCable", Family: "carrier", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "3GPP S1AP", Family: "carrier", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "3GPP NGAP", Family: "carrier", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "3GPP NAS", Family: "carrier", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "3GPP M2AP", Family: "carrier", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "3GPP M3AP", Family: "carrier", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "PFCP", Family: "carrier", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "GTP Prime", Family: "carrier", Sources: src(srcWireshark), Status: stTodo, Priority: priP4},

	// --- 游戏（科来列表里大量存在） ---
	{Name: "WoW", Family: "game", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "Quake", Family: "game", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "Quake2", Family: "game", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "Quake3", Family: "game", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "Steam", Family: "game", Sources: src(srcWireshark), Status: stTodo, Priority: priP4},
	{Name: "Xbox Live", Family: "game", Sources: src(srcWireshark), Status: stTodo, Priority: priP4},
	{Name: "PlayStation", Family: "game", Sources: src(srcPrivate), Status: stTodo, Priority: priP4},
	{Name: "Tencent Games", Family: "game", Sources: src(srcPrivate, srcColasoft), Status: stTodo, Priority: priP3},
	{Name: "NetEase Games", Family: "game", Sources: src(srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "miHoYo/HoYoverse", Family: "game", Sources: src(srcPrivate), Status: stTodo, Priority: priP3},

	// --- 存储 ---
	{Name: "iSCSI", Family: "storage", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "NBD", Family: "storage", Sources: src(srcWireshark), Status: stTodo, Priority: priP4},
	{Name: "AoE", Family: "storage", Sources: src(srcWireshark), Status: stTodo, Priority: priP4},
	{Name: "FCP", Family: "storage", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP2},
	{Name: "NVMe-oF", Family: "storage", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "Ceph", Family: "storage", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "Gluster", Family: "storage", Sources: src(srcPrivate), Status: stTodo, Priority: priP4},
	{Name: "MinIO/S3", Family: "storage", Sources: src(srcPrivate), Status: stTodo, Priority: priP1},
	{Name: "NFS4.1/4.2", Family: "storage", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "SMB3 multichannel", Family: "storage", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},

	// --- 其它常见 pentest ---
	{Name: "RMI", Family: "pentest", Sources: src(srcWireshark), Status: stTodo, Priority: priP1},
	{Name: "JMX", Family: "pentest", Sources: src(srcPrivate), Status: stTodo, Priority: priP1},
	{Name: "JDWP", Family: "pentest", Sources: src(srcPrivate), Status: stTodo, Priority: priP1},
	{Name: "FastCGI", Family: "pentest", Sources: src(srcWireshark), Status: stTodo, Priority: priP1},
	{Name: "AJP", Family: "pentest", Sources: src(srcWireshark), Status: stDone, Priority: priP0, Notes: "AJP13 CPING/CPONG/FORWARD/SEND_HEADERS"},
	{Name: "IIOP Locate", Family: "pentest", Sources: src(srcWireshark), Status: stPartial, Priority: priP1},
	{Name: "Memcache binary", Family: "pentest", Sources: src(srcWireshark), Status: stTodo, Priority: priP1},
	{Name: "Docker API", Family: "pentest", Sources: src(srcPrivate), Status: stTodo, Priority: priP1},
	{Name: "Kubernetes API", Family: "pentest", Sources: src(srcPrivate), Status: stTodo, Priority: priP1},
	{Name: "etcd raft", Family: "pentest", Sources: src(srcPrivate), Status: stTodo, Priority: priP2},
	{Name: "Consul", Family: "pentest", Sources: src(srcPrivate), Status: stTodo, Priority: priP2},
	{Name: "Vault", Family: "pentest", Sources: src(srcPrivate), Status: stTodo, Priority: priP2},
	{Name: "Elasticsearch transport", Family: "pentest", Sources: src(srcPrivate), Status: stTodo, Priority: priP1},
	{Name: "Solr", Family: "pentest", Sources: src(srcPrivate), Status: stTodo, Priority: priP2},
	{Name: "Jenkins remoting", Family: "pentest", Sources: src(srcPrivate), Status: stTodo, Priority: priP1},
	{Name: "Redis Sentinel/Cluster", Family: "pentest", Sources: src(srcPrivate), Status: stTodo, Priority: priP1},
	{Name: "Zabbix agent", Family: "pentest", Sources: src(srcPrivate), Status: stTodo, Priority: priP1},
	{Name: "Nagios NRPE", Family: "pentest", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "Checkmk", Family: "pentest", Sources: src(srcPrivate), Status: stTodo, Priority: priP4},
	{Name: "VMware SOAP", Family: "pentest", Sources: src(srcPrivate), Status: stTodo, Priority: priP1},
	{Name: "VMware AFD", Family: "pentest", Sources: src(srcPrivate), Status: stTodo, Priority: priP2},
	{Name: "ESXi hostd", Family: "pentest", Sources: src(srcPrivate), Status: stTodo, Priority: priP2},
	{Name: "vSphere NBDSSL", Family: "pentest", Sources: src(srcPrivate), Status: stTodo, Priority: priP2},
	{Name: "Xen API", Family: "pentest", Sources: src(srcPrivate), Status: stTodo, Priority: priP4},
	{Name: "Libvirt", Family: "pentest", Sources: src(srcPrivate), Status: stTodo, Priority: priP2},
	{Name: "QEMU QMP", Family: "pentest", Sources: src(srcPrivate), Status: stTodo, Priority: priP2},
	{Name: "IPMI RMCP+", Family: "pentest", Sources: src(srcWireshark), Status: stTodo, Priority: priP1},
	{Name: "Redfish SSDP", Family: "pentest", Sources: src(srcPrivate), Status: stTodo, Priority: priP2},
	{Name: "WS-Man", Family: "pentest", Sources: src(srcWireshark), Status: stTodo, Priority: priP1},
	{Name: "WinRM HTTP", Family: "pentest", Sources: src(srcPrivate), Status: stTodo, Priority: priP1},
	{Name: "PowerShell PSRP", Family: "pentest", Sources: src(srcPrivate), Status: stTodo, Priority: priP1},
	{Name: "WCF", Family: "pentest", Sources: src(srcPrivate), Status: stTodo, Priority: priP2},
	{Name: ".NET Remoting", Family: "pentest", Sources: src(srcPrivate), Status: stTodo, Priority: priP1},
	{Name: "Java serialization", Family: "pentest", Sources: src(srcPrivate), Status: stDone, Priority: priP0, Notes: "STREAM_MAGIC ACED v5 + TC type"},
	{Name: "Hessian2", Family: "pentest", Sources: src(srcPrivate), Status: stTodo, Priority: priP1},
	{Name: "Kryo", Family: "pentest", Sources: src(srcPrivate), Status: stTodo, Priority: priP2},
	{Name: "PHP serialize", Family: "pentest", Sources: src(srcPrivate), Status: stTodo, Priority: priP1},
	{Name: "Python pickle", Family: "pentest", Sources: src(srcPrivate), Status: stTodo, Priority: priP1},
	{Name: "Ruby Marshal", Family: "pentest", Sources: src(srcPrivate), Status: stTodo, Priority: priP2},
	{Name: "AMF0/AMF3", Family: "pentest", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "Burlap", Family: "pentest", Sources: src(srcPrivate), Status: stTodo, Priority: priP4},
	{Name: "IIOP over SSL", Family: "pentest", Sources: src(srcPrivate), Status: stTodo, Priority: priP2},
	{Name: "JDWP handshake", Family: "pentest", Sources: src(srcPrivate), Status: stTodo, Priority: priP1},
	{Name: "Rsync daemon", Family: "pentest", Sources: src(srcWireshark), Status: stTodo, Priority: priP1},
	{Name: "Git daemon", Family: "pentest", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "SVN", Family: "pentest", Sources: src(srcWireshark), Status: stTodo, Priority: priP4},
	{Name: "Mercurial", Family: "pentest", Sources: src(srcPrivate), Status: stTodo, Priority: priP4},
	{Name: "Docker Registry", Family: "pentest", Sources: src(srcPrivate), Status: stTodo, Priority: priP1},
	{Name: "OCI distribution", Family: "pentest", Sources: src(srcPrivate), Status: stTodo, Priority: priP2},
	{Name: "gRPC reflection", Family: "pentest", Sources: src(srcPrivate), Status: stTodo, Priority: priP1},
	{Name: "Consul RPC", Family: "pentest", Sources: src(srcPrivate), Status: stTodo, Priority: priP2},
	{Name: "Nomad", Family: "pentest", Sources: src(srcPrivate), Status: stTodo, Priority: priP4},
	{Name: "SaltStack", Family: "pentest", Sources: src(srcPrivate), Status: stTodo, Priority: priP1},
	{Name: "Ansible", Family: "pentest", Sources: src(srcPrivate), Status: stTodo, Priority: priP2},
	{Name: "Puppet", Family: "pentest", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "Chef", Family: "pentest", Sources: src(srcPrivate), Status: stTodo, Priority: priP4},
	{Name: "LDAP paged/SASL", Family: "pentest", Sources: src(srcWireshark), Status: stTodo, Priority: priP1},
	{Name: "Kerberos PAC", Family: "pentest", Sources: src(srcWireshark), Status: stDone, Priority: priP0, Notes: "PAC_INFO_BUFFER list"},
	{Name: "AS-REP / TGS", Family: "pentest", Sources: src(srcWireshark), Status: stDone, Priority: priP0, Notes: "see Kerberos tags"},
	{Name: "NTLM v1/v2", Family: "pentest", Sources: src(srcWireshark), Status: stDone, Priority: priP0, Notes: "see NTLMSSP"},
	{Name: "NetNTLMv2", Family: "pentest", Sources: src(srcPrivate), Status: stDone, Priority: priP0, Notes: "NTProofStr + client challenge"},
	{Name: "LLMNR poison", Family: "pentest", Sources: src(srcPrivate), Status: stDone, Priority: priP0, Notes: "LLMNR questions/answers on UDP 5355"},
	{Name: "NBT-NS poison", Family: "pentest", Sources: src(srcPrivate), Status: stDone, Priority: priP0, Notes: "NBNS questions/answers on UDP 137"},
	{Name: "DHCPv6 spoof", Family: "pentest", Sources: src(srcPrivate), Status: stTodo, Priority: priP1},
	{Name: "WPAD proxy", Family: "pentest", Sources: src(srcPrivate), Status: stDone, Priority: priP0, Notes: "HTTP GET /wpad.dat"},
	{Name: "IPv6 RA", Family: "pentest", Sources: src(srcWireshark), Status: stTodo, Priority: priP1},

	// --- 支付 / 金融私有 ---
	{Name: "ISO 8583", Family: "finance", Sources: src(srcWireshark, srcPrivate), Status: stTodo, Priority: priP2},
	{Name: "FIX", Family: "finance", Sources: src(srcWireshark), Status: stTodo, Priority: priP2},
	{Name: "SWIFT", Family: "finance", Sources: src(srcPrivate), Status: stTodo, Priority: priP2},
	{Name: "UnionPay CUPS", Family: "finance", Sources: src(srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "PBOC", Family: "finance", Sources: src(srcPrivate), Status: stTodo, Priority: priP3},
	{Name: "Alipay mtop", Family: "finance", Sources: src(srcPrivate), Status: stTodo, Priority: priP3},

	// --- 长尾但科来 PDF 点名的 ---
	{Name: "XDMCP", Family: "longtail", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "XOT", Family: "longtail", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "XYPLEX", Family: "longtail", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "TZSP", Family: "longtail", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "TIPC", Family: "longtail", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "SAMETIME", Family: "longtail", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "SEBEK", Family: "longtail", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "SIGCOMP", Family: "longtail", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "SliMP3", Family: "longtail", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "SMUX", Family: "longtail", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "SRVLOC/SLP", Family: "longtail", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP2},
	{Name: "TNS", Family: "longtail", Sources: src(srcWireshark, srcColasoft), Status: stDone, Priority: priP0, Notes: "Oracle TNS header + CONNECT data"},
	{Name: "TPNCP", Family: "longtail", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "ULP", Family: "longtail", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "WASSP", Family: "longtail", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "WTLS", Family: "longtail", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "ZEP", Family: "longtail", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "AllJoyn", Family: "longtail", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "Roofnet", Family: "longtail", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "ROHC", Family: "longtail", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "TDMoE", Family: "longtail", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "TELKONET", Family: "longtail", Sources: src(srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "WAI", Family: "longtail", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP3, Notes: "WAPI 中国无线"},
	{Name: "WAPI", Family: "longtail", Sources: src(srcPrivate, srcColasoft), Status: stTodo, Priority: priP3},
	{Name: "WSMP", Family: "longtail", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "swIPe", Family: "longtail", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "XTP", Family: "longtail", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "VINES", Family: "longtail", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "IPX", Family: "longtail", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "SPX", Family: "longtail", Sources: src(srcWireshark), Status: stTodo, Priority: priP4},
	{Name: "AppleTalk", Family: "longtail", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "AARP", Family: "longtail", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "DECnet", Family: "longtail", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "SNA", Family: "longtail", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "NetBEUI", Family: "longtail", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "LAT", Family: "longtail", Sources: src(srcWireshark), Status: stTodo, Priority: priP4},
	{Name: "MOP", Family: "longtail", Sources: src(srcWireshark), Status: stTodo, Priority: priP4},
	{Name: "PUP", Family: "longtail", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "XNS", Family: "longtail", Sources: src(srcWireshark, srcColasoft), Status: stTodo, Priority: priP4},
	{Name: "CHAOS", Family: "longtail", Sources: src(srcWireshark), Status: stTodo, Priority: priP4},
}

func RoadmapStats() (total, done, partial, todo int) {
	total = len(ProtocolRoadmap)
	for _, item := range ProtocolRoadmap {
		switch item.Status {
		case stDone:
			done++
		case stPartial:
			partial++
		default:
			todo++
		}
	}
	return
}
