package core

const TypeCaseByte = "byte"
const TypeCaseLong = "long"
const TypeCaseShort = "short"
const TypeCaseInt = "int"
const TypeCaseChar = "char"
const TypeCaseFloat = "float"
const TypeCaseDouble = "double"
const (
	ADD  = "add"
	INC  = "inc"
	New  = "new"
	NEQ  = "!="
	EQ   = "=="
	LT   = "<"
	GTE  = ">="
	GT   = ">"
	NE   = "!="
	LTE  = "<="
	SUB  = "-"
	REM  = "%"
	DIV  = "/"
	MUL  = "*"
	AND  = "&"
	OR   = "|"
	XOR  = "^"
	SHL  = "<<"
	SHR  = ">>"
	USHR = ">>>"

	LOGICAL_AND = "&&"
	LOGICAL_OR  = "||"
)
