package airaghttp

import (
	"fmt"
	"os"
	"strings"

	"github.com/yaklang/yaklang/common/ai/aispec"
	"github.com/yaklang/yaklang/common/utils"
	"gopkg.in/yaml.v2"
)

// AIServiceConfig AI 服务配置 (一个具体模型的接入参数)
// api_key 非空视为"已配置"; 否则回退内置默认模型 (见 buildAIEngineOptions).
type AIServiceConfig struct {
	Type   string `yaml:"type"`
	Model  string `yaml:"model"`
	APIKey string `yaml:"api_key"`
	Domain string `yaml:"domain"`
}

// IsConfigured 以 api_key 是否填写判断该模型是否已配置好
func (a AIServiceConfig) IsConfigured() bool {
	return strings.TrimSpace(a.APIKey) != ""
}

// SpecOptions 转换为 aispec 选项列表 (用于构造该模型的 callback)
func (a AIServiceConfig) SpecOptions() []aispec.AIConfigOption {
	opts := make([]aispec.AIConfigOption, 0, 3)
	if a.Model != "" {
		opts = append(opts, aispec.WithModel(a.Model))
	}
	if a.APIKey != "" {
		opts = append(opts, aispec.WithAPIKey(a.APIKey))
	}
	if a.Domain != "" {
		opts = append(opts, aispec.WithDomain(a.Domain))
	}
	return opts
}

// RAGServerConfig RAG HTTP 服务的完整配置
// 可由 rag-server.yaml 加载, 也可由命令行参数覆盖.
type RAGServerConfig struct {
	// HTTP 监听配置
	Host        string `yaml:"host"`
	Port        int    `yaml:"port"`
	RoutePrefix string `yaml:"route_prefix"`

	// 认证: 空 = 不认证; 非空 = 要求 Authorization: Bearer <token>
	AuthToken string `yaml:"auth_token"`

	// 并发与超时控制
	Concurrent   int `yaml:"concurrent"`
	Timeout      int `yaml:"timeout"`
	MaxIteration int `yaml:"max_iteration"`

	// 回答语言偏好
	Language string `yaml:"language"`

	// 知识库来源
	// Collections 为空时使用 profile DB 内全部已存在集合.
	Collections []string `yaml:"collections"`
	// RagFiles 启动时导入的本地 .rag 文件.
	RagFiles []string `yaml:"rag_files"`

	// AI 高质模型配置 (质量优先通道)
	// 配置好(api_key 非空)则关键推理使用该模型; 未配置则回退轻量模型.
	AI AIServiceConfig `yaml:"ai"`

	// AILightweight 轻量模型配置 (速度优先通道: 搜索/记忆/压缩等高频调用, 省成本)
	// 配置好(api_key 非空)则速度优先使用该小尺寸模型; 未配置则回退内置 memfit-light-free.
	AILightweight AIServiceConfig `yaml:"ai_lightweight"`

	// ServeFrontend 是否在根路径 serve 内置只读搜索前端页面 (默认 true)
	ServeFrontend bool `yaml:"serve_frontend"`

	// Debug 调试模式 (打印 prompt/event)
	Debug bool `yaml:"debug"`
}

// NewDefaultConfig 返回默认配置
// 关键词: rag-server default config, port 9093
func NewDefaultConfig() *RAGServerConfig {
	return &RAGServerConfig{
		Host:         "0.0.0.0",
		Port:         9093,
		RoutePrefix:  "/api/rag-server",
		AuthToken:    "",
		Concurrent:   3,
		Timeout:      180,
		MaxIteration: 1,
		Language:     "zh",
		Collections:  nil,
		RagFiles:     nil,
		AI: AIServiceConfig{
			Type:   "aibalance",
			Model:  "",
			APIKey: "",
			Domain: "",
		},
		AILightweight: AIServiceConfig{
			Type:   "aibalance",
			Model:  "",
			APIKey: "",
			Domain: "",
		},
		ServeFrontend: true,
	}
}

// LightweightModelName 未配置自定义 AI 时使用的默认轻量模型 (aibalance)
// 关键词: lightweight default model, memfit-light-free, fallback standard
const LightweightModelName = "memfit-light-free"

// LoadConfigFromFile 从 yaml 文件加载配置 (缺省字段以默认值兜底)
// 关键词: rag-server.yaml load, yaml.Unmarshal, default fallback
func LoadConfigFromFile(path string) (*RAGServerConfig, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, utils.Errorf("read config file failed: %v", err)
	}

	cfg := NewDefaultConfig()
	if err := yaml.Unmarshal(raw, cfg); err != nil {
		return nil, utils.Errorf("parse config yaml failed: %v", err)
	}
	cfg.fillDefaults()
	return cfg, nil
}

// GenerateConfigTemplate 生成带注释的 rag-server 配置模板字符串.
// 注释引导用户填写 APIKey 等关键项, 默认值与 NewDefaultConfig 保持一致.
// 关键词: gen-config template, set apikey, commented yaml
func GenerateConfigTemplate() string {
	c := NewDefaultConfig()
	return fmt.Sprintf(`# rag-server.yaml - RAG Knowledge Base HTTP Server configuration
# Generated by: yak rag-server --gen-config <file>
# Edit this file (especially the AI api_key), then start with:
#   yak rag-server --config <file>

# ---------- HTTP listen ----------
host: %q
port: %d
route_prefix: %q

# ---------- Auth ----------
# Bearer token. empty = no auth; non-empty = require "Authorization: Bearer <token>"
auth_token: %q

# ---------- Concurrency & timeout ----------
concurrent: %d        # max simultaneous chat (SSE) requests
timeout: %d          # per chat request timeout in seconds
max_iteration: %d      # ReAct max iterations

# ---------- Answer language ----------
language: %q          # zh or en

# ---------- Knowledge sources ----------
# collections: leave empty ([]) to use ALL existing collections in the profile DB
collections: []
# rag_files: local .rag files to import on startup
rag_files: []

# ---------- AI service ----------
# Two independent channels (override defaults to tune cost & quality):
#   'ai'            = HIGH-QUALITY model, used by the quality-priority channel
#                     (key reasoning / final answer).
#   'ai_lightweight'= SMALL/light model, used by the speed-priority channel
#                     (search / memory / compression, called frequently).
# For each block: fill api_key (and model) to enable it; leave api_key EMPTY to
# fall back to the built-in lightweight model (%s via aibalance, needs no key).
# >>>>>> SET YOUR API KEY BELOW <<<<<<
ai:
  type: %q
  model: ""             # e.g. memfit-qwen3.7-max
  api_key: ""           # <-- high-quality model API key (empty = use lightweight)
  domain: ""
ai_lightweight:
  type: %q
  model: ""             # e.g. memfit-light-free
  api_key: ""           # <-- small/light model API key (empty = use built-in light model)
  domain: ""

# ---------- Web UI ----------
# serve the built-in read-only search page at the root path
serve_frontend: %t

# ---------- Debug ----------
debug: false
`,
		c.Host, c.Port, c.RoutePrefix,
		c.AuthToken,
		c.Concurrent, c.Timeout, c.MaxIteration,
		c.Language,
		LightweightModelName,
		c.AI.Type,
		c.AILightweight.Type,
		c.ServeFrontend,
	)
}

// SaveConfigTemplateToFile 将配置模板写入文件; 默认拒绝覆盖已存在文件
// 关键词: write config template, gen-config, avoid overwrite
func SaveConfigTemplateToFile(path string, overwrite bool) error {
	if strings.TrimSpace(path) == "" {
		return utils.Error("config file path is empty")
	}
	if !overwrite {
		if _, err := os.Stat(path); err == nil {
			return utils.Errorf("file already exists: %s (use --gen-config-force to overwrite)", path)
		}
	}
	if err := os.WriteFile(path, []byte(GenerateConfigTemplate()), 0o644); err != nil {
		return utils.Errorf("write config template failed: %v", err)
	}
	return nil
}

// fillDefaults 为关键字段补齐默认值, 避免 yaml 缺省导致非法监听等问题
func (c *RAGServerConfig) fillDefaults() {
	if c.Host == "" {
		c.Host = "0.0.0.0"
	}
	if c.Port <= 0 {
		c.Port = 9093
	}
	if c.RoutePrefix == "" {
		c.RoutePrefix = "/api/rag-server"
	}
	if c.Concurrent <= 0 {
		c.Concurrent = 3
	}
	if c.Timeout <= 0 {
		c.Timeout = 180
	}
	if c.MaxIteration <= 0 {
		c.MaxIteration = 1
	}
	if c.Language == "" {
		c.Language = "zh"
	}
	if c.AI.Type == "" {
		c.AI.Type = "aibalance"
	}
	if c.AILightweight.Type == "" {
		c.AILightweight.Type = "aibalance"
	}
}

// IsAIConfigured 判断高质模型是否配置好 (以 api_key 为准).
// 已配置则质量优先通道使用该模型; 未配置则回退到轻量模型.
// 关键词: high-quality ai configured, api_key, fallback lightweight
func (c *RAGServerConfig) IsAIConfigured() bool {
	return c.AI.IsConfigured()
}

// IsLightweightAIConfigured 判断轻量模型是否单独配置好.
// 未配置则速度优先通道回退到内置 memfit-light-free.
// 关键词: lightweight ai configured, speed priority, cost saving
func (c *RAGServerConfig) IsLightweightAIConfigured() bool {
	return c.AILightweight.IsConfigured()
}

// AISpecOptions 高质模型的 aispec 选项列表
func (c *RAGServerConfig) AISpecOptions() []aispec.AIConfigOption {
	return c.AI.SpecOptions()
}

// LightweightAISpecOptions 轻量模型的 aispec 选项列表
func (c *RAGServerConfig) LightweightAISpecOptions() []aispec.AIConfigOption {
	return c.AILightweight.SpecOptions()
}

// Option 配置覆盖项, 主要用于命令行参数覆盖 yaml 配置
type Option func(*RAGServerConfig)

func WithHost(host string) Option {
	return func(c *RAGServerConfig) {
		if host != "" {
			c.Host = host
		}
	}
}

func WithPort(port int) Option {
	return func(c *RAGServerConfig) {
		if port > 0 {
			c.Port = port
		}
	}
}

func WithRoutePrefix(prefix string) Option {
	return func(c *RAGServerConfig) {
		if prefix != "" {
			c.RoutePrefix = prefix
		}
	}
}

func WithAuthToken(token string) Option {
	return func(c *RAGServerConfig) {
		if token != "" {
			c.AuthToken = token
		}
	}
}

func WithConcurrent(n int) Option {
	return func(c *RAGServerConfig) {
		if n > 0 {
			c.Concurrent = n
		}
	}
}

func WithTimeout(sec int) Option {
	return func(c *RAGServerConfig) {
		if sec > 0 {
			c.Timeout = sec
		}
	}
}

func WithMaxIteration(n int) Option {
	return func(c *RAGServerConfig) {
		if n > 0 {
			c.MaxIteration = n
		}
	}
}

func WithLanguage(lang string) Option {
	return func(c *RAGServerConfig) {
		if lang != "" {
			c.Language = lang
		}
	}
}

func WithCollections(names ...string) Option {
	return func(c *RAGServerConfig) {
		if len(names) > 0 {
			c.Collections = names
		}
	}
}

func WithRagFiles(files ...string) Option {
	return func(c *RAGServerConfig) {
		if len(files) > 0 {
			c.RagFiles = files
		}
	}
}

func WithAIService(typ, model, apiKey, domain string) Option {
	return func(c *RAGServerConfig) {
		if typ != "" {
			c.AI.Type = typ
		}
		if model != "" {
			c.AI.Model = model
		}
		if apiKey != "" {
			c.AI.APIKey = apiKey
		}
		if domain != "" {
			c.AI.Domain = domain
		}
	}
}

func WithLightweightAIService(typ, model, apiKey, domain string) Option {
	return func(c *RAGServerConfig) {
		if typ != "" {
			c.AILightweight.Type = typ
		}
		if model != "" {
			c.AILightweight.Model = model
		}
		if apiKey != "" {
			c.AILightweight.APIKey = apiKey
		}
		if domain != "" {
			c.AILightweight.Domain = domain
		}
	}
}

func WithDebug(debug bool) Option {
	return func(c *RAGServerConfig) {
		c.Debug = debug
	}
}

func WithServeFrontend(enable bool) Option {
	return func(c *RAGServerConfig) {
		c.ServeFrontend = enable
	}
}
