package syntaxflow_scan

import "github.com/yaklang/yaklang/common/yak/ssaapi/ssaconfig"

var Exports = map[string]any{
	"StartScan":                    StartScan,
	"ScanProject":                  ScanProject,
	"ScanProjectFromJSON":          ScanProjectFromJSON,
	"ResumeScan":                   ResumeScan,
	"GetScanStatus":                GetScanStatus,
	"stageCollect":                 StageCollect,
	"stageInspect":                 StageInspect,
	"stageReview":                  StageReview,
	"stageAnalyze":                 StageAnalyze,
	"stageName":                    func(s string) string { return ProductStage(s).DisplayName() },
	"SourceMode":                   SourceMode,
	"StructMode":                   StructMode,
	"SSAMode":                      SSAMode,
	"withMode":                     WithMode,
	"withStageCallback":            WithStageCallback,
	"withScanProcessCallback":      WithProcessCallback,
	"withProcessRuleDetail":        WithProcessRuleDetail,
	"withScanResultCallback":       WithScanResultCallback,
	"withScanPrograms":             withPrograms,
	"withCompiledSource":           WithCompiledSource,
	"withScanSourceFiles":          WithSourceFiles,
	"withScanSourceDir":            WithSourceDir,
	"withScanQueryTargets":         WithQueryTargets,
	"withScanConcurrency":          ssaconfig.WithScanConcurrency,
	"withScanRuleTimeout":          ssaconfig.WithScanRuleTimeout,
	"withScanRuleWorkLimit":        ssaconfig.WithScanRuleWorkLimit,
	"withScanRuleWorkLimitDefault": ssaconfig.WithScanRuleWorkLimitDefault,
	"withReporter":                 WithReporter,
	"withRuleInput":                ssaconfig.WithRuleInput,
	"withRuleInputRaw":             ssaconfig.WithRuleInputRaw,
	"withRuleFilter":               ssaconfig.WithRuleFilter,
	"withRuleFilterTag":            ssaconfig.WithRuleFilterTag,
	"withRuleFilterMode":           ssaconfig.WithRuleFilterMode,
	"withRuleFilterKeyword":        ssaconfig.WithRuleFilterKeyword,
	"withRuleFilterGroupNames":     ssaconfig.WithRuleFilterGroupNames,
	"withRuleFilterLibRuleKind":    ssaconfig.WithRuleFilterLibRuleKind,
}
