name: Bug Report / Bug 报告
description: Submit a bug report to help us improve / 提交一个 bug 帮助我们改进产品
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        感谢您花时间填写这个 bug 报告！请尽可能详细地填写以下信息，这将帮助我们更快地解决问题。
        Thank you for taking the time to fill out this bug report! Please provide as much detail as possible to help us resolve the issue quickly.

  - type: input
    id: version
    attributes:
      label: Version / 版本号
      description: What version are you using? / 您正在使用的版本是什么？
      placeholder: e.g. / 例如：v1.0.0
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description / Bug 描述
      description: Please describe the issue in detail / 请详细描述您遇到的问题
      placeholder: A clear and concise description of the bug / 清晰简洁地描述 bug 是什么
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce / 复现步骤
      description: How can we reproduce this issue? / 如何复现这个问题？
      placeholder: |
        1. Go to '...' / 进入 '...'
        2. Click on '....' / 点击 '....'
        3. Scroll down to '....' / 滚动到 '....'
        4. See error / 出现错误
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior / 期望行为
      description: What did you expect to happen? / 清晰简洁地描述您期望发生的情况
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment / 运行环境
      description: Select your operating environment (multiple choices allowed) / 选择运行环境（可多选）
      multiple: true
      options:
        - Windows
        - macOS
        - Linux
        - iOS
        - Android
        - Others / 其他
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs / 相关日志
      description: Please paste any relevant error logs here / 如果有相关的错误日志，请在此粘贴
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context / 补充信息
      description: Add any other context about the problem here / 添加任何其他有关问题的上下文信息
