blank_issues_enabled: false
contact_links:
  - name: Docs (yaklang.com or yaklang.io)
    url: https://www.yaklang.com/docs/intro/
    about: Please check the documentation first, it may have the answer.
