// Code generated by yak embed-fs-hash DO NOT EDIT.
// nolint: golint
package consts

// ExistedBuildInAIToolEmbedFSHash contains the SHA256 hash of the embedded AI tool filesystem.
// This hash is used to verify the integrity of AI-related tools and configurations embedded in the binary.
// These tools include AI-powered analysis engines and machine learning models for security testing.
const ExistedBuildInAIToolEmbedFSHash string = "bb119469e47774ae43ede1106586f529e53be794a84130a8fa801eeef2f4e985"
