// Code generated by yak embed-fs-hash DO NOT EDIT.
// nolint: golint
package consts

// ExistedBuildInAIToolEmbedFSHash contains the SHA256 hash of the embedded AI tool filesystem.
// This hash is used to verify the integrity of AI-related tools and configurations embedded in the binary.
// These tools include AI-powered analysis engines and machine learning models for security testing.
const ExistedBuildInAIToolEmbedFSHash string = "fc46f724332d2499614ae5aea2bbf9d65c2a1f24feb6bec917457dbebb419da1"
