// Code generated by yak embed-fs-hash DO NOT EDIT.
// nolint: golint
package consts

// ExistedBuildInForgeEmbedFSHash contains the SHA256 hash of the embedded build-in forge filesystem.
// This hash is used to verify the integrity of the built-in forge templates and resources.
// The forge system provides templates for code generation and vulnerability testing scenarios.
const ExistedBuildInForgeEmbedFSHash string = "efdcab4543caf22d25233cae562833bf9c53ea00198f310d22735e2dcb1adf06"
