// Code generated by go run common/yak/cmd/yak.go embed-fs-hash --override --all DO NOT EDIT.
// nolint: golint
package consts

// ExistedCorePluginEmbedFSHash contains the SHA256 hash of the embedded core plugin filesystem.
// This hash is used to verify the integrity of core plugins and detect changes in the plugin bundle.
// The hash is automatically generated during the build process and should not be manually modified.
const ExistedCorePluginEmbedFSHash string = "6a911014bf1e9c6bc68f3a522a1259434b9d597d1d94700b4b76745c181c18dd"

// ExistedSyntaxFlowEmbedFSHash contains the SHA256 hash of the embedded SyntaxFlow filesystem.
// This hash is used to verify the integrity of SyntaxFlow rules and templates embedded in the binary.
// The hash is automatically calculated from the SyntaxFlow rule files during compilation.
const ExistedSyntaxFlowEmbedFSHash string = "e6c6c4486214b1965467b4898363b40dea1782fa0ef5ddb0959a56b88722e9af"

// ExistedBuildInForgeEmbedFSHash contains the SHA256 hash of the embedded build-in forge filesystem.
// This hash is used to verify the integrity of the built-in forge templates and resources.
// The forge system provides templates for code generation and vulnerability testing scenarios.
const ExistedBuildInForgeEmbedFSHash string = "b2ec7cdc764a95537c74ff6ae82d8c9c34ad5a8c520a2b710bc08b3c2c6312eb"

// ExistedBuildInAIToolEmbedFSHash contains the SHA256 hash of the embedded AI tool filesystem.
// This hash is used to verify the integrity of AI-related tools and configurations embedded in the binary.
// These tools include AI-powered analysis engines and machine learning models for security testing.
const ExistedBuildInAIToolEmbedFSHash string = "d868c3e552647934861c370a8ef5382f57683595cd2229aad4faa04788b24f7b"
