// Code generated by go run common/yak/cmd/yak.go embed-fs-hash --override --all DO NOT EDIT.
// nolint: golint
package consts

// ExistedCorePluginEmbedFSHash contains the SHA256 hash of the embedded core plugin filesystem.
// This hash is used to verify the integrity of core plugins and detect changes in the plugin bundle.
// The hash is automatically generated during the build process and should not be manually modified.
const ExistedCorePluginEmbedFSHash string = "3ac540d3a0c554511596ebb3135c426d69f27b93ec22fa1510b6972457c300a9"

// ExistedSyntaxFlowEmbedFSHash contains the SHA256 hash of the embedded SyntaxFlow filesystem.
// This hash is used to verify the integrity of SyntaxFlow rules and templates embedded in the binary.
// The hash is automatically calculated from the SyntaxFlow rule files during compilation.
const ExistedSyntaxFlowEmbedFSHash string = "a1f732aee6dd83f58ef6db24da75b3ea6fb6d71637d04f6d922546fb73a744c7"

// ExistedBuildInForgeEmbedFSHash contains the SHA256 hash of the embedded build-in forge filesystem.
// This hash is used to verify the integrity of the built-in forge templates and resources.
// The forge system provides templates for code generation and vulnerability testing scenarios.
const ExistedBuildInForgeEmbedFSHash string = "05e084d3799804bc65812146943c1a06a60763ba50dfdc2985cd1824986552d7"

// ExistedBuildInAIToolEmbedFSHash contains the SHA256 hash of the embedded AI tool filesystem.
// This hash is used to verify the integrity of AI-related tools and configurations embedded in the binary.
// These tools include AI-powered analysis engines and machine learning models for security testing.
const ExistedBuildInAIToolEmbedFSHash string = "b0b4e49210bb301c6fc020912d305ba69e9e54d3e0706a03a149b5c2f6d0286b"
