// Code generated by go run common/yak/cmd/yak.go embed-fs-hash --override --all DO NOT EDIT.
// nolint: golint
package consts

// ExistedCorePluginEmbedFSHash contains the SHA256 hash of the embedded core plugin filesystem.
// This hash is used to verify the integrity of core plugins and detect changes in the plugin bundle.
// The hash is automatically generated during the build process and should not be manually modified.
const ExistedCorePluginEmbedFSHash string = "677d98ff13ffdad64a146454d9b76aa4f8b466e5bdb66572169f9e26733284f9"

// ExistedSyntaxFlowEmbedFSHash contains the SHA256 hash of the embedded SyntaxFlow filesystem.
// This hash is used to verify the integrity of SyntaxFlow rules and templates embedded in the binary.
// The hash is automatically calculated from the SyntaxFlow rule files during compilation.
const ExistedSyntaxFlowEmbedFSHash string = "81fc9d049fd31a691f2a84dcc8794ffde3d6a6f4090414cad3c19b95ec729611"

// ExistedBuildInForgeEmbedFSHash contains the SHA256 hash of the embedded build-in forge filesystem.
// This hash is used to verify the integrity of the built-in forge templates and resources.
// The forge system provides templates for code generation and vulnerability testing scenarios.
const ExistedBuildInForgeEmbedFSHash string = "aefcf10f612cdf9667148651f2f4535d018ce43e81d26399d3cf4a063684d3e9"

// ExistedBuildInAIToolEmbedFSHash contains the SHA256 hash of the embedded AI tool filesystem.
// This hash is used to verify the integrity of AI-related tools and configurations embedded in the binary.
// These tools include AI-powered analysis engines and machine learning models for security testing.
const ExistedBuildInAIToolEmbedFSHash string = "945e829dde556f419b4070c8a57c7d31848fd533a24117c9d6db464921fa4314"
