// Code generated by go run common/yak/cmd/yak.go embed-fs-hash --override --all DO NOT EDIT.
// nolint: golint
package consts

// ExistedCorePluginEmbedFSHash contains the SHA256 hash of the embedded core plugin filesystem.
// This hash is used to verify the integrity of core plugins and detect changes in the plugin bundle.
// The hash is automatically generated during the build process and should not be manually modified.
const ExistedCorePluginEmbedFSHash string = "7bf8710653a37f88c3b1f42401cb2c9b13709ca0c081f878da24d6d1367f0ea7"

// ExistedSyntaxFlowEmbedFSHash contains the SHA256 hash of the embedded SyntaxFlow filesystem.
// This hash is used to verify the integrity of SyntaxFlow rules and templates embedded in the binary.
// The hash is automatically calculated from the SyntaxFlow rule files during compilation.
const ExistedSyntaxFlowEmbedFSHash string = "58ea23d2833a700dc844e2ec5f99e5026465d176f15efdb8b93e267ecc350133"

// ExistedBuildInForgeEmbedFSHash contains the SHA256 hash of the embedded build-in forge filesystem.
// This hash is used to verify the integrity of the built-in forge templates and resources.
// The forge system provides templates for code generation and vulnerability testing scenarios.
const ExistedBuildInForgeEmbedFSHash string = "e31843a480aa678ee4a756bb348857d4e43252579eb62af15be3eb46ddd2b7fe"

// ExistedBuildInAIToolEmbedFSHash contains the SHA256 hash of the embedded AI tool filesystem.
// This hash is used to verify the integrity of AI-related tools and configurations embedded in the binary.
// These tools include AI-powered analysis engines and machine learning models for security testing.
const ExistedBuildInAIToolEmbedFSHash string = "dd6fb759f6f5019a38d270363dc863152ddf542be196398e8e57bbd2e93001b7"
