package yakast

import (
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"

	"github.com/yaklang/yaklang/common/yak/antlr4yak/yakfmt"
	"github.com/yaklang/yaklang/common/yak/antlr4yak/yakvm"
)

func TestFormatterCacheResetsWithCompiler(t *testing.T) {
	compiler := NewYakCompiler()
	for _, source := range []string{"a=1", "a=2;f=func(x){return x+1}", "a=f\"汉字 ${1+2}\""} {
		if !compiler.Compiler(source) {
			t.Fatal(compiler.GetErrors())
		}
		expected, err := yakfmt.Format(source)
		if err != nil {
			t.Fatal(err)
		}
		expected = expected[:len(expected)-1]
		for i := 0; i < 3; i++ {
			if got := compiler.GetFormattedCode(); got != expected {
				t.Fatalf("stale format cache: %q, expected %q", got, expected)
			}
		}
	}
	if compiler.Compiler("a=") {
		t.Fatal("invalid source compiled")
	}
	if got := compiler.GetFormattedCode(); got != "" {
		t.Fatal("failed parse reused previous format", got)
	}
}

func TestFormatterLazyCompilerAndIncludeIsolation(t *testing.T) {
	included := filepath.Join(t.TempDir(), "included.yak")
	if err := os.WriteFile(included, []byte("fromInclude = 7"), 0600); err != nil {
		t.Fatal(err)
	}
	source := "include " + strconv.Quote(included) + ";f=func(a){return a+fromInclude}"
	c := NewYakCompiler()
	if !c.Compiler(source) {
		t.Fatal(c.GetErrors())
	}
	if c.formatReady || c.formattedCode != "" {
		t.Fatal("compilation eagerly formatted source")
	}
	// Formatting must not reopen includes, alter generated code, or replace
	// the root input with an included program's input.
	if err := os.Remove(included); err != nil {
		t.Fatal(err)
	}
	codes := append([]*yakvm.Code(nil), c.GetOpcodes()...)
	symtbl, sourcePointer := c.currentSymtbl, c.sourceCodePointer
	want, err := yakfmt.Format(source)
	if err != nil {
		t.Fatal(err)
	}
	for i := 0; i < 3; i++ {
		if got := c.GetFormattedCode(); got != strings.TrimSuffix(want, "\n") {
			t.Fatalf("root format changed after include: %q", got)
		}
	}
	if !c.formatReady || c.currentSymtbl != symtbl || c.sourceCodePointer != sourcePointer || len(codes) != len(c.GetOpcodes()) {
		t.Fatal("formatting changed compiler state")
	}
	for i, code := range codes {
		if c.GetOpcodes()[i] != code {
			t.Fatal("formatting regenerated bytecode")
		}
	}
}
