package scannode

import "strings"

const (
	legionCommandStream  = "LEGION_COMMANDS"
	legionHIDSPrefix     = "legion.hids"
	legionRealtimePrefix = "legion.realtime"

	legionCommandDispatch                             = "job.dispatch"
	legionCommandCancel                               = "job.cancel"
	legionCommandCapabilityApply                      = "capability.apply"
	legionCommandHIDSResponseActionExecute            = "hids.response_action.execute"
	legionCommandHIDSDesiredSpecDryRun                = "hids.desired_spec.dry_run"
	legionCommandHIDSCurrentStateCollect              = "hids.current_state.collect"
	legionCommandHIDSFileEvidenceCollect              = "hids.file_evidence.collect"
	legionCommandSSARuleSyncExport                    = "ssa.rule_sync.export"
	legionCommandAISessionBind                        = "ai.session.bind"
	legionCommandAISessionInput                       = "ai.session.input"
	legionCommandAISessionAppend                      = "ai.session.context.append"
	legionCommandAISessionCancel                      = "ai.session.cancel"
	legionCommandAISessionClose                       = "ai.session.close"
	legionCommandAISessionTitleUpdate                 = "ai.session.title.update"
	legionCommandAISessionDelete                      = "ai.session.delete"
	legionCommandAILogsCheckpointsExport              = "ai.logs.checkpoints.export"
	legionCommandAIProviderModelsList                 = "ai.provider.models.list"
	legionCommandAIProviderHealthCheck                = "ai.provider.health_check"
	legionCommandAIFocusQuery                         = "ai.focus.query"
	legionCommandAIMaterialsRandomQuery               = "ai.materials.random.query"
	legionCommandAIGlobalConfigGet                    = "ai.global_config.get"
	legionCommandAIGlobalConfigSet                    = "ai.global_config.set"
	legionCommandAIMCPServersList                     = "ai.mcp_servers.list"
	legionCommandAIMCPServerCreate                    = "ai.mcp_server.create"
	legionCommandAIMCPServerUpdate                    = "ai.mcp_server.update"
	legionCommandAIMCPServerDelete                    = "ai.mcp_server.delete"
	legionCommandAILocalModelsList                    = "ai.local_models.list"
	legionCommandAILlamaServerReady                   = "ai.local_model.llama_server.ready"
	legionCommandAILlamaServerInstall                 = "ai.local_model.llama_server.install"
	legionCommandAILocalModelCreate                   = "ai.local_model.create"
	legionCommandAILocalModelUpdate                   = "ai.local_model.update"
	legionCommandAILocalModelDelete                   = "ai.local_model.delete"
	legionCommandAILocalModelStart                    = "ai.local_model.start"
	legionCommandAILocalModelStop                     = "ai.local_model.stop"
	legionCommandAILocalModelDownload                 = "ai.local_model.download"
	legionCommandAILocalModelOperationCancel          = "ai.local_model.operation.cancel"
	legionCommandAILocalModelsClear                   = "ai.local_models.clear"
	legionCommandAIForgesList                         = "ai.forges.list"
	legionCommandAIForgeCreate                        = "ai.forge.create"
	legionCommandAIForgeUpdate                        = "ai.forge.update"
	legionCommandAIForgeDelete                        = "ai.forge.delete"
	legionCommandAIForgeExport                        = "ai.forge.export"
	legionCommandAIForgeImport                        = "ai.forge.import"
	legionCommandAIToolsList                          = "ai.tools.list"
	legionCommandAIToolCreate                         = "ai.tool.create"
	legionCommandAIToolUpdate                         = "ai.tool.update"
	legionCommandAIToolMetadataGenerate               = "ai.tool.metadata.generate"
	legionCommandAIToolsFavoriteToggle                = "ai.tools.favorite.toggle"
	legionCommandAIToolsDelete                        = "ai.tools.delete"
	legionCommandAIKnowledgeBasesList                 = "ai.knowledge_bases.list"
	legionCommandAIKnowledgeBaseCreate                = "ai.knowledge_base.create"
	legionCommandAIKnowledgeBaseImport                = "ai.knowledge_base.import"
	legionCommandAIKnowledgeBaseUpdate                = "ai.knowledge_base.update"
	legionCommandAIKnowledgeBaseDelete                = "ai.knowledge_base.delete"
	legionCommandAIKnowledgeBaseExport                = "ai.knowledge_base.export"
	legionCommandAIKnowledgeBaseEntriesSearch         = "ai.knowledge_base_entries.search"
	legionCommandAIKnowledgeBaseQueryByAI             = "ai.knowledge_base.query_by_ai"
	legionCommandAIKnowledgeBaseQueryByAICancel       = "ai.knowledge_base.query_by_ai.cancel"
	legionCommandAIKnowledgeBaseQuestionIndexGenerate = "ai.knowledge_base.question_index.generate"
	legionCommandAIKnowledgeBaseQuestionIndexCancel   = "ai.knowledge_base.question_index.generate.cancel"
	legionCommandAIKnowledgeBaseEntryCreate           = "ai.knowledge_base_entry.create"
	legionCommandAIKnowledgeBaseEntryUpdate           = "ai.knowledge_base_entry.update"
	legionCommandAIKnowledgeBaseEntryDelete           = "ai.knowledge_base_entry.delete"
	legionCommandAIKnowledgeBaseVectorIndexBuild      = "ai.knowledge_base.vector_index.build"
	legionCommandAIKnowledgeBaseEntryVectorIndexBuild = "ai.knowledge_base_entry.vector_index.build"
	legionCommandAIMemoryEntityCreate                 = "ai.memory_entity.create"
	legionCommandAIMemoryEntityGet                    = "ai.memory_entity.get"
	legionCommandAIMemoryEntitiesQuery                = "ai.memory_entities.query"
	legionCommandAIMemoryEntityUpdate                 = "ai.memory_entity.update"
	legionCommandAIMemoryEntitiesDelete               = "ai.memory_entities.delete"
	legionCommandAIMemoryEntityTagsCount              = "ai.memory_entity_tags.count"
	legionCommandAIHTTPFlowsQuery                     = "ai.http_flows.query"
	legionCommandAIRisksQuery                         = "ai.risks.query"

	legionEventClaimed                                    = "job.claimed"
	legionEventStarted                                    = "job.started"
	legionEventProgress                                   = "job.progressed"
	legionEventAsset                                      = "job.asset"
	legionEventRisk                                       = "job.risk"
	legionEventReport                                     = "job.report"
	legionEventArtifactReady                              = "job.artifact_ready"
	legionEventSucceeded                                  = "job.succeeded"
	legionEventFailed                                     = "job.failed"
	legionEventCancelled                                  = "job.cancelled"
	legionEventCapabilityStatus                           = "capability.status"
	legionEventCapabilityAlert                            = "capability.alert"
	legionEventCapabilityFailed                           = "capability.failed"
	legionEventHIDSObservation                            = "hids.observation"
	legionEventHIDSResponseActionResult                   = "hids.response_action.result"
	legionEventHIDSDesiredSpecDryRunResult                = "hids.desired_spec.dry_run.result"
	legionEventSSARuleSyncReady                           = "ssa.rule_sync.ready"
	legionEventSSARuleSyncFailed                          = "ssa.rule_sync.failed"
	legionEventAISessionReady                             = "ai.session.ready"
	legionEventAISessionEvent                             = "ai.session.event"
	legionEventAISessionDone                              = "ai.session.done"
	legionEventAISessionFailed                            = "ai.session.failed"
	legionEventAISessionCancelled                         = "ai.session.cancelled"
	legionEventAISessionTitleUpdated                      = "ai.session.title.updated"
	legionEventAISessionTitleUpdateFailed                 = "ai.session.title.update.failed"
	legionEventAISessionDeleteCompleted                   = "ai.session.delete.completed"
	legionEventAISessionDeleteFailed                      = "ai.session.delete.failed"
	legionEventAILogsCheckpointsExported                  = "ai.logs.checkpoints.exported"
	legionEventAILogsCheckpointsExportFailed              = "ai.logs.checkpoints.export.failed"
	legionEventAIProviderModelsListed                     = "ai.provider.models.listed"
	legionEventAIProviderModelsFailed                     = "ai.provider.models.failed"
	legionEventAIProviderHealthCheckCompleted             = "ai.provider.health_check.completed"
	legionEventAIProviderHealthCheckFailed                = "ai.provider.health_check.failed"
	legionEventAIFocusQueried                             = "ai.focus.queried"
	legionEventAIFocusQueryFailed                         = "ai.focus.query.failed"
	legionEventAIMaterialsRandomQueried                   = "ai.materials.random.queried"
	legionEventAIMaterialsRandomQueryFailed               = "ai.materials.random.query.failed"
	legionEventAIGlobalConfigFetched                      = "ai.global_config.fetched"
	legionEventAIGlobalConfigFetchFailed                  = "ai.global_config.fetch.failed"
	legionEventAIGlobalConfigUpdated                      = "ai.global_config.updated"
	legionEventAIGlobalConfigUpdateFailed                 = "ai.global_config.update.failed"
	legionEventAIMCPServersListed                         = "ai.mcp_servers.listed"
	legionEventAIMCPServersListFailed                     = "ai.mcp_servers.list.failed"
	legionEventAIMCPServerCreated                         = "ai.mcp_server.created"
	legionEventAIMCPServerCreateFailed                    = "ai.mcp_server.create.failed"
	legionEventAIMCPServerUpdated                         = "ai.mcp_server.updated"
	legionEventAIMCPServerUpdateFailed                    = "ai.mcp_server.update.failed"
	legionEventAIMCPServerDeleted                         = "ai.mcp_server.deleted"
	legionEventAIMCPServerDeleteFailed                    = "ai.mcp_server.delete.failed"
	legionEventAILocalModelsListed                        = "ai.local_models.listed"
	legionEventAILocalModelsListFailed                    = "ai.local_models.list.failed"
	legionEventAILlamaServerReadyChecked                  = "ai.local_model.llama_server.ready.checked"
	legionEventAILlamaServerReadyCheckFailed              = "ai.local_model.llama_server.ready.failed"
	legionEventAILlamaServerInstalled                     = "ai.local_model.llama_server.installed"
	legionEventAILlamaServerInstallFailed                 = "ai.local_model.llama_server.install.failed"
	legionEventAILocalModelCreated                        = "ai.local_model.created"
	legionEventAILocalModelCreateFailed                   = "ai.local_model.create.failed"
	legionEventAILocalModelUpdated                        = "ai.local_model.updated"
	legionEventAILocalModelUpdateFailed                   = "ai.local_model.update.failed"
	legionEventAILocalModelDeleted                        = "ai.local_model.deleted"
	legionEventAILocalModelDeleteFailed                   = "ai.local_model.delete.failed"
	legionEventAILocalModelStarted                        = "ai.local_model.started"
	legionEventAILocalModelStartFailed                    = "ai.local_model.start.failed"
	legionEventAILocalModelStopped                        = "ai.local_model.stopped"
	legionEventAILocalModelStopFailed                     = "ai.local_model.stop.failed"
	legionEventAILocalModelDownloaded                     = "ai.local_model.downloaded"
	legionEventAILocalModelDownloadFailed                 = "ai.local_model.download.failed"
	legionEventAILocalModelOperationAccepted              = "ai.local_model.operation.accepted"
	legionEventAILocalModelOperationProgressed            = "ai.local_model.operation.progressed"
	legionEventAILocalModelOperationCompleted             = "ai.local_model.operation.completed"
	legionEventAILocalModelOperationCancelled             = "ai.local_model.operation.cancelled"
	legionEventAILocalModelOperationFailed                = "ai.local_model.operation.failed"
	legionEventAILocalModelsCleared                       = "ai.local_models.cleared"
	legionEventAILocalModelsClearFailed                   = "ai.local_models.clear.failed"
	legionEventAIForgesListed                             = "ai.forges.listed"
	legionEventAIForgesListFailed                         = "ai.forges.list.failed"
	legionEventAIForgeCreated                             = "ai.forge.created"
	legionEventAIForgeCreateFailed                        = "ai.forge.create.failed"
	legionEventAIForgeUpdated                             = "ai.forge.updated"
	legionEventAIForgeUpdateFailed                        = "ai.forge.update.failed"
	legionEventAIForgeDeleted                             = "ai.forge.deleted"
	legionEventAIForgeDeleteFailed                        = "ai.forge.delete.failed"
	legionEventAIForgeExportProgressed                    = "ai.forge.export.progressed"
	legionEventAIForgeExported                            = "ai.forge.exported"
	legionEventAIForgeExportFailed                        = "ai.forge.export.failed"
	legionEventAIForgeImportProgressed                    = "ai.forge.import.progressed"
	legionEventAIForgeImported                            = "ai.forge.imported"
	legionEventAIForgeImportFailed                        = "ai.forge.import.failed"
	legionEventAIToolsListed                              = "ai.tools.listed"
	legionEventAIToolsListFailed                          = "ai.tools.list.failed"
	legionEventAIToolCreated                              = "ai.tool.created"
	legionEventAIToolCreateFailed                         = "ai.tool.create.failed"
	legionEventAIToolUpdated                              = "ai.tool.updated"
	legionEventAIToolUpdateFailed                         = "ai.tool.update.failed"
	legionEventAIToolMetadataGenerated                    = "ai.tool.metadata.generated"
	legionEventAIToolMetadataGenerateFailed               = "ai.tool.metadata.generate.failed"
	legionEventAIToolsFavoriteToggled                     = "ai.tools.favorite.toggled"
	legionEventAIToolsFavoriteToggleFailed                = "ai.tools.favorite.toggle.failed"
	legionEventAIToolsDeleted                             = "ai.tools.deleted"
	legionEventAIToolsDeleteFailed                        = "ai.tools.delete.failed"
	legionEventAIKnowledgeBasesListed                     = "ai.knowledge_bases.listed"
	legionEventAIKnowledgeBasesListFailed                 = "ai.knowledge_bases.list.failed"
	legionEventAIKnowledgeBaseCreated                     = "ai.knowledge_base.created"
	legionEventAIKnowledgeBaseCreateFailed                = "ai.knowledge_base.create.failed"
	legionEventAIKnowledgeBaseImported                    = "ai.knowledge_base.imported"
	legionEventAIKnowledgeBaseImportFailed                = "ai.knowledge_base.import.failed"
	legionEventAIKnowledgeBaseUpdated                     = "ai.knowledge_base.updated"
	legionEventAIKnowledgeBaseUpdateFailed                = "ai.knowledge_base.update.failed"
	legionEventAIKnowledgeBaseDeleted                     = "ai.knowledge_base.deleted"
	legionEventAIKnowledgeBaseDeleteFailed                = "ai.knowledge_base.delete.failed"
	legionEventAIKnowledgeBaseExported                    = "ai.knowledge_base.exported"
	legionEventAIKnowledgeBaseExportFailed                = "ai.knowledge_base.export.failed"
	legionEventAIKnowledgeBaseEntriesSearched             = "ai.knowledge_base_entries.searched"
	legionEventAIKnowledgeBaseEntriesSearchFailed         = "ai.knowledge_base_entries.search.failed"
	legionEventAIKnowledgeBaseQueryByAIChunk              = "ai.knowledge_base.query_by_ai.chunk"
	legionEventAIKnowledgeBaseQueryByAICompleted          = "ai.knowledge_base.query_by_ai.completed"
	legionEventAIKnowledgeBaseQueryByAIFailed             = "ai.knowledge_base.query_by_ai.failed"
	legionEventAIKnowledgeBaseQuestionIndexProgress       = "ai.knowledge_base.question_index.progress"
	legionEventAIKnowledgeBaseQuestionIndexCompleted      = "ai.knowledge_base.question_index.completed"
	legionEventAIKnowledgeBaseQuestionIndexFailed         = "ai.knowledge_base.question_index.failed"
	legionEventAIKnowledgeBaseEntryCreated                = "ai.knowledge_base_entry.created"
	legionEventAIKnowledgeBaseEntryCreateFailed           = "ai.knowledge_base_entry.create.failed"
	legionEventAIKnowledgeBaseEntryUpdated                = "ai.knowledge_base_entry.updated"
	legionEventAIKnowledgeBaseEntryUpdateFailed           = "ai.knowledge_base_entry.update.failed"
	legionEventAIKnowledgeBaseEntryDeleted                = "ai.knowledge_base_entry.deleted"
	legionEventAIKnowledgeBaseEntryDeleteFailed           = "ai.knowledge_base_entry.delete.failed"
	legionEventAIKnowledgeBaseVectorIndexBuilt            = "ai.knowledge_base.vector_index.built"
	legionEventAIKnowledgeBaseVectorIndexBuildFailed      = "ai.knowledge_base.vector_index.build.failed"
	legionEventAIKnowledgeBaseEntryVectorIndexBuilt       = "ai.knowledge_base_entry.vector_index.built"
	legionEventAIKnowledgeBaseEntryVectorIndexBuildFailed = "ai.knowledge_base_entry.vector_index.build.failed"
	legionEventAIMemoryEntityCreated                      = "ai.memory_entity.created"
	legionEventAIMemoryEntityCreateFailed                 = "ai.memory_entity.create.failed"
	legionEventAIMemoryEntityFetched                      = "ai.memory_entity.fetched"
	legionEventAIMemoryEntityFetchFailed                  = "ai.memory_entity.fetch.failed"
	legionEventAIMemoryEntitiesQueried                    = "ai.memory_entities.queried"
	legionEventAIMemoryEntitiesQueryFailed                = "ai.memory_entities.query.failed"
	legionEventAIMemoryEntityUpdated                      = "ai.memory_entity.updated"
	legionEventAIMemoryEntityUpdateFailed                 = "ai.memory_entity.update.failed"
	legionEventAIMemoryEntitiesDeleted                    = "ai.memory_entities.deleted"
	legionEventAIMemoryEntitiesDeleteFailed               = "ai.memory_entities.delete.failed"
	legionEventAIMemoryEntityTagsCounted                  = "ai.memory_entity_tags.counted"
	legionEventAIMemoryEntityTagsCountFailed              = "ai.memory_entity_tags.count.failed"
	legionEventAIHTTPFlowsQueried                         = "ai.http_flows.queried"
	legionEventAIHTTPFlowsQueryFailed                     = "ai.http_flows.query.failed"
	legionEventAIRisksQueried                             = "ai.risks.queried"
	legionEventAIRisksQueryFailed                         = "ai.risks.query.failed"

	legionAssetKindTCPOpenPort        = "tcp_open_port"
	legionAssetKindServiceFingerprint = "service_fingerprint"
	legionArtifactKindSSAResultV1     = "ssa_result_v1"

	legionRiskKindVulnerability = "vulnerability"
	legionRiskKindWeakPassword  = "weak_password"
	legionRiskKindSecurityRisk  = "security_risk"

	legionReportKindScan = "scan_report"
)

const legionRealtimeHIDSDesiredSpecDryRunResultPrefix = legionRealtimePrefix + ".hids.desired_spec_dry_run.result"

func commandSubjectWildcard(base string) string {
	return trimSubject(base) + ".>"
}

func jobEventSubject(prefix, eventType string) string {
	return trimSubject(prefix) + "." + strings.TrimPrefix(eventType, ".")
}

func capabilityEventSubject(prefix, eventType string) string {
	normalizedEventType := strings.TrimPrefix(strings.TrimSpace(eventType), ".")
	if normalizedEventType == legionEventHIDSObservation {
		return legionHIDSPrefix + ".observation"
	}
	if normalizedEventType == legionEventHIDSResponseActionResult {
		return legionHIDSPrefix + ".response_action.result"
	}
	return jobEventSubject(prefix, normalizedEventType)
}

func hidsDesiredSpecDryRunResultSubject(commandID string) string {
	commandID = strings.TrimSpace(commandID)
	if commandID == "" {
		return legionRealtimeHIDSDesiredSpecDryRunResultPrefix
	}
	return legionRealtimeHIDSDesiredSpecDryRunResultPrefix + "." + commandID
}

func trimSubject(value string) string {
	return strings.TrimSuffix(strings.TrimSpace(value), ".")
}
