//go:build !irify_exclude

// Code generated by embedfs/generate; DO NOT EDIT.

package sfdb

import (
	"embed"

	"github.com/yaklang/yaklang/common/utils/embedfs"
)

//go:embed "rule_versions.json.embed.gz"
var ruleVersionFSStorage embed.FS

var ruleVersionFS = embedfs.New(ruleVersionFSStorage)
