// Package assets holds the embedded runtime archives (libyak.a, libgc.a), crt
// objects, static system libraries (libc.a, libgcc.a, libgcc_eh.a), and the
// extra cgo C static libraries (extdeps/: libpcap.a, libm.a, libresolv.a, ...)
// that make the ssa2llvm binary self-contained: when ssa2llvm compiles a yak
// script it links these in-process via lld (see github.com/yaklang/go-llvm)
// instead of shelling out to clang/llc or reading artifacts from the host.
//
// The asset bytes are populated by scripts/build_runtime_embed.sh and embedded
// via go:embed (embed_assets.go). manifest_generated.go (also generated by the
// script) records their SHA256 for the compile-cache key. Build ssa2llvm only
// after running scripts/build_runtime_embed.sh so the embedded files exist.
package assets

import (
	"fmt"
	"os"
	"path/filepath"
)

// Manifest records the SHA256 of each embedded asset. It is populated by
// manifest_generated.go (generated by build_runtime_embed.sh) and used as a
// compile-cache key so cache validity is independent of the host toolchain.
type Manifest struct {
	Libyak   string
	Libgc    string
	Crt1     string
	Crti     string
	Crtn     string
	CrtBegin string
	CrtEnd   string
	Libc     string
	Libgcc   string
	LibgccEh string
}

// ReleasedPaths holds the absolute paths of assets written to the work dir by
// ReleaseTo.
type ReleasedPaths struct {
	Libyak   string
	Libgc    string
	Crt1     string
	Crti     string
	Crtn     string
	CrtBegin string
	CrtEnd   string
	Libc     string
	Libgcc   string
	LibgccEh string
	// ExtDeps are the released extra cgo C static libraries (libpcap.a, libm.a,
	// ...), in stable manifest order. They are linked inside the lld group.
	ExtDeps []string
}

// ExtDep is one extra cgo C static library embedded under extdeps/. The set is
// variable (depends on SSA2LLVM_EMBED_MODULES), so extdeps/ is embedded as a
// directory and enumerated at release time; extdepManifest lists which members
// to link plus their SHA256 (cache key + integrity), generated alongside
// EmbeddedManifest by build_runtime_embed.sh.
type ExtDep struct {
	Name string // file name within extdeps/, e.g. "libpcap.a"
	Sha  string // SHA256 of the file
}

// EmbeddedAvailable, EmbeddedManifest, embeddedLibyak ... embeddedLibgccEh,
// embeddedExtDeps, and extdepManifest are declared in embed_assets.go /
// manifest_generated.go (both generated/populated by build_runtime_embed.sh).

// HasEmbeddedRuntime reports whether the embedded runtime archives are
// available in this build.
func HasEmbeddedRuntime() bool { return EmbeddedAvailable }

// ExtdepManifest returns the embedded extra cgo C static libraries to link
// (name + SHA256), in stable order.
func ExtdepManifest() []ExtDep { return extdepManifest }

func writeAsset(dir, name string, data []byte) (string, error) {
	if len(data) == 0 {
		return "", fmt.Errorf("embedded asset %q is empty; run scripts/build_runtime_embed.sh before building ssa2llvm", name)
	}
	p := filepath.Join(dir, name)
	if err := os.WriteFile(p, data, 0o644); err != nil {
		return "", fmt.Errorf("release embedded asset %q: %w", name, err)
	}
	return p, nil
}

// ReleaseTo writes all embedded runtime assets into dir and returns their
// absolute paths. dir should be the compile work dir (the caller owns its
// cleanup).
func ReleaseTo(dir string) (ReleasedPaths, error) {
	if !EmbeddedAvailable {
		return ReleasedPaths{}, fmt.Errorf("embedded runtime not available: run scripts/build_runtime_embed.sh before building ssa2llvm")
	}
	var rp ReleasedPaths
	var err error
	if rp.Libyak, err = writeAsset(dir, "libyak.a", embeddedLibyak); err != nil {
		return rp, err
	}
	if rp.Libgc, err = writeAsset(dir, "libgc.a", embeddedLibgc); err != nil {
		return rp, err
	}
	if rp.Crt1, err = writeAsset(dir, "crt1.o", embeddedCrt1); err != nil {
		return rp, err
	}
	if rp.Crti, err = writeAsset(dir, "crti.o", embeddedCrti); err != nil {
		return rp, err
	}
	if rp.Crtn, err = writeAsset(dir, "crtn.o", embeddedCrtn); err != nil {
		return rp, err
	}
	if rp.CrtBegin, err = writeAsset(dir, "crtbegin.o", embeddedCrtBegin); err != nil {
		return rp, err
	}
	if rp.CrtEnd, err = writeAsset(dir, "crtend.o", embeddedCrtEnd); err != nil {
		return rp, err
	}
	if rp.Libc, err = writeAsset(dir, "libc.a", embeddedLibc); err != nil {
		return rp, err
	}
	if rp.Libgcc, err = writeAsset(dir, "libgcc.a", embeddedLibgcc); err != nil {
		return rp, err
	}
	if rp.LibgccEh, err = writeAsset(dir, "libgcc_eh.a", embeddedLibgccEh); err != nil {
		return rp, err
	}
	// Release the extra cgo C static libraries (variable set) for heavy modules
	// (e.g. libpcap.a for poc). extdepManifest is generated in stable order.
	for _, ed := range extdepManifest {
		data, rerr := embeddedExtDeps.ReadFile("extdeps/" + ed.Name)
		if rerr != nil {
			return rp, fmt.Errorf("release embedded extdep %q: %w", ed.Name, rerr)
		}
		p, werr := writeAsset(dir, ed.Name, data)
		if werr != nil {
			return rp, werr
		}
		rp.ExtDeps = append(rp.ExtDeps, p)
	}
	return rp, nil
}
