keys:
  - key: "your-api-key"
    allowed_models: ["model1", "model2"]
models:
  - name: "model1"
    providers:
      - model_name: "gemini-2.0-flash-001"
        type_name: "openai"
        domain_or_url: "http://api.ai.yaklang.com"
        no_https: true
        api_key: "sk-yak-yyds"