keys:
  - key: "your-api-key"
    allowed_models:
      - "model1"
      - "model2"
models:
  - name: "model1"
    providers:
      - model_name: "gemini-2.0-flash"
        type_name: "openai"
        domain_or_url: "http://api.a1i.yaklang.io/v1/chat/completions"
        no_https: true
        api_key: "sk-yak-yyds" 