package crawler

var Exports = map[string]interface{}{
	"Start":               StartCrawler,
	"basicAuth":           WithBasicAuth,
	"bodySize":            WithBodySize,
	"concurrent":          WithConcurrent,
	"connectTimeout":      WithConnectTimeout,
	"timeout":             WithConnectTimeout,
	"verifyCertificate":   WithVerifyCertificate,
	"httpsToHttpFallback": WithHTTPSFallback,
	"domainExclude":       WithDomainBlackList,
	"domainInclude":       WithDomainWhiteList,
	"cookie":              WithFixedCookie,
	"forbiddenFromParent": WithForbiddenFromParent,
	"disallowSuffix":      WithDisallowSuffix,
	"header":              WithHeader,
	"urlExtractor":        WithUrlExtractor,
	"maxDepth":            WithMaxDepth,
	"maxRedirect":         WithMaxRedirectTimes,
	"maxRequest":          WithMaxRequestCount,
	"maxRetry":            WithMaxRetry,
	"maxUrls":             WithMaxUrlCount,
	"proxy":               WithProxy,
	"responseTimeout":     WithResponseTimeout,
	"urlRegexpExclude":    WithUrlRegexpBlackList,
	"urlRegexpInclude":    WithUrlRegexpWhiteList,
	"userAgent":           WithUserAgent,
	"ua":                  WithUserAgent,
	"autoLogin":           WithAutoLogin,
	"jsParser":            WithJSParser,
	"onUrlFound":          WithOnUrlFound,
	"RequestsFromFlow":    HandleRequestResult,

	// AI assisted JS / HTML path extraction
	"aiJSExtract":      WithAIJSExtract,
	"aiJSMaxTokens":    WithAIJS_MaxTokens,
	"aiJSChunkBytes":   WithAIJS_ChunkBytes,
	"aiJSOverlapBytes": WithAIJS_OverlapBytes,
	"aiJSContextBytes": WithAIJS_ContextBytes,
	"aiJSConcurrency":  WithAIJS_Concurrency,
	"aiJSSkipBelow":    WithAIJS_SkipBelowBytes,
	"aiJSAIOptions":    WithAIJS_AIOptions,
}
