#!/usr/bin/env bash
go-bindata -pkg dicts -o ./common/dicts/bindata.go dataex/dicts/...

go-bindata -pkg bindata -o ./common/bindata/bindata.go data/...
go-bindata -pkg ruledata -o ./server/dbm/rules/ruledata/ruledata.go server/dbm/rules/notification-rules/...
