#!/bin/sh -e

echo "Start to Test SSAAPI"
go test -count=1 -timeout 10m ./common/yak/ssaapi/...

echo "Start to Test Syntaxflow rule"
go test -count=1 -timeout 60s -skip "TestBuildInRule_Verify_DEBUG" ./common/syntaxflow/...

echo "SSA URL"
go test -count=1 -timeout 1m -run ^TestSFURl$ github.com/yaklang/yaklang/common/yak/yakurl

echo "Start to Test SSA-Analyze"
# SSA plugin rule/option
go test -count=1 -timeout 20s ./common/yak/static_analyzer/test/...
# StaticAnalyze
go test -count=1 -timeout 20s -run TestAnalyzeMustPASS* ./common/coreplugin
# SSA UTIL
go test -count=1 -timeout 20s ./common/yak/ssa/...
# yak ssa
go test -count=1 -timeout 20s ./common/yak/yak2ssa/test/...
# Test Java Syntax
go test -count=1 -timeout 10s ./common/yak/java/...
# Test php syntax
go test -count=1 -timeout 30s ./common/yak/php/...
# Test Js Syntax
go test -count=1 -timeout 60s ./common/yak/JS2ssa/...
# Test Go syntax
go test -count=1 -timeout 20s ./common/yak/go2ssa/...

echo "syntaxflow and language grpc"
go test -count=1 -timeout 5m -run TestGRPCMUSTPASS_SyntaxFlow* ./common/yakgrpc/...
go test -count=1 -timeout 5m -run TestGRPCMUSTPASS_LANGUAGE* ./common/yakgrpc/...
