// Package crawlerx
// @Author bcy2007  2023/7/12 16:56
package crawlerx

var CrawlerXExports = map[string]interface{}{
	"StartCrawler":   StartCrawler,
	"PageScreenShot": NewPageScreenShot,
	"OutputResult":   OutputData,

	"browserInfo":       WithBrowserInfo,
	"saveToDB":          WithSaveToDB,
	"runtimeId":         WithRuntimeID,
	"maxUrl":            WithMaxUrl,
	"maxDepth":          WithMaxDepth,
	"concurrent":        WithConcurrent,
	"blacklist":         WithBlackList,
	"whitelist":         WithWhiteList,
	"pageTimeout":       WithPageTimeout,
	"fullTimeout":       WithFullTimeout,
	"extraWaitLoadTime": WithExtraWaitLoadTime,
	"formFill":          WithFormFill,
	"fileInput":         WithFileInput,
	"headers":           WithHeaders,
	"rawHeaders":        WithHeaderInfo,
	"cookies":           WithCookies,
	"rawCookie":         WithCookieInfo,
	"scanRangeLevel":    WithScanRangeLevel,
	"scanRepeatLevel":   WithScanRepeatLevel,
	"ignoreQueryName":   WithIgnoreQueryName,
	"sensitiveWords":    WithSensitiveWords,
	"leakless":          WithLeakless,
	"localStorage":      WithLocalStorage,
	"sessionStorage":    WithSessionStorage,
	"invalidSuffix":     WithInvalidSuffix,
	"stealth":           WithStealth,
	"runtimeID":         WithRuntimeID,
	"evalJs":            WithEvalJs,
	"jsResultSend":      WithJsResultSave,
	"vue":               WithVue,
	"response":          WithResponse,
	"sourceType":        WithSourceType,
	"fromPlugin":        WithFromPlugin,
	"urlCheck":          WithUrlCheck,
	"aiInputUrl":        WithAIInputUrl,
	"aiInputInfo":       WithAIInputInf,

	"loginUsername": WithLoginUsername,
	"loginPassword": WithLoginPassword,
	"aiDomain":      WithAIDomain,
	"aiKey":         WithAiKey,

	"UnLimitRepeat":      unlimited,
	"LowRepeatLevel":     lowLevel,
	"MediumRepeatLevel":  midLevel,
	"HighRepeatLevel":    highLevel,
	"ExtremeRepeatLevel": extremeLevel,

	"AllDomainScan":       mainDomain,
	"SubMenuScan":         subDomain,
	"UnlimitedDomainScan": unlimitedDomain,
	"BoardDomain":         boardDomain,
}
