// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: attach_api.proto

package ypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AttachApi_AttachCombinedOutput_FullMethodName   = "/ypb.AttachApi/AttachCombinedOutput"
	AttachApi_SaveTextToTemporalFile_FullMethodName = "/ypb.AttachApi/SaveTextToTemporalFile"
)

// AttachApiClient is the client API for AttachApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AttachApiClient interface {
	// 接入标准输出和标准错误流
	AttachCombinedOutput(ctx context.Context, in *AttachCombinedOutputRequest, opts ...grpc.CallOption) (AttachApi_AttachCombinedOutputClient, error)
	SaveTextToTemporalFile(ctx context.Context, in *SaveTextToTemporalFileRequest, opts ...grpc.CallOption) (*SaveTextToTemporalFileResponse, error)
}

type attachApiClient struct {
	cc grpc.ClientConnInterface
}

func NewAttachApiClient(cc grpc.ClientConnInterface) AttachApiClient {
	return &attachApiClient{cc}
}

func (c *attachApiClient) AttachCombinedOutput(ctx context.Context, in *AttachCombinedOutputRequest, opts ...grpc.CallOption) (AttachApi_AttachCombinedOutputClient, error) {
	stream, err := c.cc.NewStream(ctx, &AttachApi_ServiceDesc.Streams[0], AttachApi_AttachCombinedOutput_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &attachApiAttachCombinedOutputClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AttachApi_AttachCombinedOutputClient interface {
	Recv() (*ExecResult, error)
	grpc.ClientStream
}

type attachApiAttachCombinedOutputClient struct {
	grpc.ClientStream
}

func (x *attachApiAttachCombinedOutputClient) Recv() (*ExecResult, error) {
	m := new(ExecResult)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *attachApiClient) SaveTextToTemporalFile(ctx context.Context, in *SaveTextToTemporalFileRequest, opts ...grpc.CallOption) (*SaveTextToTemporalFileResponse, error) {
	out := new(SaveTextToTemporalFileResponse)
	err := c.cc.Invoke(ctx, AttachApi_SaveTextToTemporalFile_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AttachApiServer is the server API for AttachApi service.
// All implementations must embed UnimplementedAttachApiServer
// for forward compatibility
type AttachApiServer interface {
	// 接入标准输出和标准错误流
	AttachCombinedOutput(*AttachCombinedOutputRequest, AttachApi_AttachCombinedOutputServer) error
	SaveTextToTemporalFile(context.Context, *SaveTextToTemporalFileRequest) (*SaveTextToTemporalFileResponse, error)
	mustEmbedUnimplementedAttachApiServer()
}

// UnimplementedAttachApiServer must be embedded to have forward compatible implementations.
type UnimplementedAttachApiServer struct {
}

func (UnimplementedAttachApiServer) AttachCombinedOutput(*AttachCombinedOutputRequest, AttachApi_AttachCombinedOutputServer) error {
	return status.Errorf(codes.Unimplemented, "method AttachCombinedOutput not implemented")
}
func (UnimplementedAttachApiServer) SaveTextToTemporalFile(context.Context, *SaveTextToTemporalFileRequest) (*SaveTextToTemporalFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveTextToTemporalFile not implemented")
}
func (UnimplementedAttachApiServer) mustEmbedUnimplementedAttachApiServer() {}

// UnsafeAttachApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AttachApiServer will
// result in compilation errors.
type UnsafeAttachApiServer interface {
	mustEmbedUnimplementedAttachApiServer()
}

func RegisterAttachApiServer(s grpc.ServiceRegistrar, srv AttachApiServer) {
	s.RegisterService(&AttachApi_ServiceDesc, srv)
}

func _AttachApi_AttachCombinedOutput_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AttachCombinedOutputRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AttachApiServer).AttachCombinedOutput(m, &attachApiAttachCombinedOutputServer{stream})
}

type AttachApi_AttachCombinedOutputServer interface {
	Send(*ExecResult) error
	grpc.ServerStream
}

type attachApiAttachCombinedOutputServer struct {
	grpc.ServerStream
}

func (x *attachApiAttachCombinedOutputServer) Send(m *ExecResult) error {
	return x.ServerStream.SendMsg(m)
}

func _AttachApi_SaveTextToTemporalFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveTextToTemporalFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttachApiServer).SaveTextToTemporalFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttachApi_SaveTextToTemporalFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttachApiServer).SaveTextToTemporalFile(ctx, req.(*SaveTextToTemporalFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AttachApi_ServiceDesc is the grpc.ServiceDesc for AttachApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AttachApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ypb.AttachApi",
	HandlerType: (*AttachApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveTextToTemporalFile",
			Handler:    _AttachApi_SaveTextToTemporalFile_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AttachCombinedOutput",
			Handler:       _AttachApi_AttachCombinedOutput_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "attach_api.proto",
}
