// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: license_api.proto

package ypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	LicenseApi_GetLicense_FullMethodName   = "/ypb.LicenseApi/GetLicense"
	LicenseApi_CheckLicense_FullMethodName = "/ypb.LicenseApi/CheckLicense"
)

// LicenseApiClient is the client API for LicenseApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LicenseApiClient interface {
	// license
	GetLicense(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetLicenseResponse, error)
	CheckLicense(ctx context.Context, in *CheckLicenseRequest, opts ...grpc.CallOption) (*Empty, error)
}

type licenseApiClient struct {
	cc grpc.ClientConnInterface
}

func NewLicenseApiClient(cc grpc.ClientConnInterface) LicenseApiClient {
	return &licenseApiClient{cc}
}

func (c *licenseApiClient) GetLicense(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetLicenseResponse, error) {
	out := new(GetLicenseResponse)
	err := c.cc.Invoke(ctx, LicenseApi_GetLicense_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *licenseApiClient) CheckLicense(ctx context.Context, in *CheckLicenseRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, LicenseApi_CheckLicense_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LicenseApiServer is the server API for LicenseApi service.
// All implementations must embed UnimplementedLicenseApiServer
// for forward compatibility
type LicenseApiServer interface {
	// license
	GetLicense(context.Context, *Empty) (*GetLicenseResponse, error)
	CheckLicense(context.Context, *CheckLicenseRequest) (*Empty, error)
	mustEmbedUnimplementedLicenseApiServer()
}

// UnimplementedLicenseApiServer must be embedded to have forward compatible implementations.
type UnimplementedLicenseApiServer struct {
}

func (UnimplementedLicenseApiServer) GetLicense(context.Context, *Empty) (*GetLicenseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLicense not implemented")
}
func (UnimplementedLicenseApiServer) CheckLicense(context.Context, *CheckLicenseRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckLicense not implemented")
}
func (UnimplementedLicenseApiServer) mustEmbedUnimplementedLicenseApiServer() {}

// UnsafeLicenseApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LicenseApiServer will
// result in compilation errors.
type UnsafeLicenseApiServer interface {
	mustEmbedUnimplementedLicenseApiServer()
}

func RegisterLicenseApiServer(s grpc.ServiceRegistrar, srv LicenseApiServer) {
	s.RegisterService(&LicenseApi_ServiceDesc, srv)
}

func _LicenseApi_GetLicense_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LicenseApiServer).GetLicense(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LicenseApi_GetLicense_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LicenseApiServer).GetLicense(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _LicenseApi_CheckLicense_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckLicenseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LicenseApiServer).CheckLicense(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LicenseApi_CheckLicense_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LicenseApiServer).CheckLicense(ctx, req.(*CheckLicenseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LicenseApi_ServiceDesc is the grpc.ServiceDesc for LicenseApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LicenseApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ypb.LicenseApi",
	HandlerType: (*LicenseApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLicense",
			Handler:    _LicenseApi_GetLicense_Handler,
		},
		{
			MethodName: "CheckLicense",
			Handler:    _LicenseApi_CheckLicense_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "license_api.proto",
}
