// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: payloads_api.proto

package ypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PayloadsApi_QueryPayload_FullMethodName         = "/ypb.PayloadsApi/QueryPayload"
	PayloadsApi_DeletePayloadByGroup_FullMethodName = "/ypb.PayloadsApi/DeletePayloadByGroup"
	PayloadsApi_DeletePayload_FullMethodName        = "/ypb.PayloadsApi/DeletePayload"
	PayloadsApi_SavePayload_FullMethodName          = "/ypb.PayloadsApi/SavePayload"
	PayloadsApi_SavePayloadStream_FullMethodName    = "/ypb.PayloadsApi/SavePayloadStream"
	PayloadsApi_GetAllPayloadGroup_FullMethodName   = "/ypb.PayloadsApi/GetAllPayloadGroup"
	PayloadsApi_UpdatePayload_FullMethodName        = "/ypb.PayloadsApi/UpdatePayload"
	PayloadsApi_GetAllPayload_FullMethodName        = "/ypb.PayloadsApi/GetAllPayload"
)

// PayloadsApiClient is the client API for PayloadsApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PayloadsApiClient interface {
	// Payload 相关接口
	QueryPayload(ctx context.Context, in *QueryPayloadRequest, opts ...grpc.CallOption) (*QueryPayloadResponse, error)
	DeletePayloadByGroup(ctx context.Context, in *DeletePayloadByGroupRequest, opts ...grpc.CallOption) (*Empty, error)
	DeletePayload(ctx context.Context, in *DeletePayloadRequest, opts ...grpc.CallOption) (*Empty, error)
	SavePayload(ctx context.Context, in *SavePayloadRequest, opts ...grpc.CallOption) (*Empty, error)
	SavePayloadStream(ctx context.Context, in *SavePayloadRequest, opts ...grpc.CallOption) (PayloadsApi_SavePayloadStreamClient, error)
	GetAllPayloadGroup(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetAllPayloadGroupResponse, error)
	UpdatePayload(ctx context.Context, in *UpdatePayloadRequest, opts ...grpc.CallOption) (*Empty, error)
	GetAllPayload(ctx context.Context, in *GetAllPayloadRequest, opts ...grpc.CallOption) (*GetAllPayloadResponse, error)
}

type payloadsApiClient struct {
	cc grpc.ClientConnInterface
}

func NewPayloadsApiClient(cc grpc.ClientConnInterface) PayloadsApiClient {
	return &payloadsApiClient{cc}
}

func (c *payloadsApiClient) QueryPayload(ctx context.Context, in *QueryPayloadRequest, opts ...grpc.CallOption) (*QueryPayloadResponse, error) {
	out := new(QueryPayloadResponse)
	err := c.cc.Invoke(ctx, PayloadsApi_QueryPayload_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payloadsApiClient) DeletePayloadByGroup(ctx context.Context, in *DeletePayloadByGroupRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, PayloadsApi_DeletePayloadByGroup_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payloadsApiClient) DeletePayload(ctx context.Context, in *DeletePayloadRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, PayloadsApi_DeletePayload_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payloadsApiClient) SavePayload(ctx context.Context, in *SavePayloadRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, PayloadsApi_SavePayload_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payloadsApiClient) SavePayloadStream(ctx context.Context, in *SavePayloadRequest, opts ...grpc.CallOption) (PayloadsApi_SavePayloadStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &PayloadsApi_ServiceDesc.Streams[0], PayloadsApi_SavePayloadStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &payloadsApiSavePayloadStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PayloadsApi_SavePayloadStreamClient interface {
	Recv() (*SavePayloadProgress, error)
	grpc.ClientStream
}

type payloadsApiSavePayloadStreamClient struct {
	grpc.ClientStream
}

func (x *payloadsApiSavePayloadStreamClient) Recv() (*SavePayloadProgress, error) {
	m := new(SavePayloadProgress)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *payloadsApiClient) GetAllPayloadGroup(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*GetAllPayloadGroupResponse, error) {
	out := new(GetAllPayloadGroupResponse)
	err := c.cc.Invoke(ctx, PayloadsApi_GetAllPayloadGroup_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payloadsApiClient) UpdatePayload(ctx context.Context, in *UpdatePayloadRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, PayloadsApi_UpdatePayload_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payloadsApiClient) GetAllPayload(ctx context.Context, in *GetAllPayloadRequest, opts ...grpc.CallOption) (*GetAllPayloadResponse, error) {
	out := new(GetAllPayloadResponse)
	err := c.cc.Invoke(ctx, PayloadsApi_GetAllPayload_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PayloadsApiServer is the server API for PayloadsApi service.
// All implementations must embed UnimplementedPayloadsApiServer
// for forward compatibility
type PayloadsApiServer interface {
	// Payload 相关接口
	QueryPayload(context.Context, *QueryPayloadRequest) (*QueryPayloadResponse, error)
	DeletePayloadByGroup(context.Context, *DeletePayloadByGroupRequest) (*Empty, error)
	DeletePayload(context.Context, *DeletePayloadRequest) (*Empty, error)
	SavePayload(context.Context, *SavePayloadRequest) (*Empty, error)
	SavePayloadStream(*SavePayloadRequest, PayloadsApi_SavePayloadStreamServer) error
	GetAllPayloadGroup(context.Context, *Empty) (*GetAllPayloadGroupResponse, error)
	UpdatePayload(context.Context, *UpdatePayloadRequest) (*Empty, error)
	GetAllPayload(context.Context, *GetAllPayloadRequest) (*GetAllPayloadResponse, error)
	mustEmbedUnimplementedPayloadsApiServer()
}

// UnimplementedPayloadsApiServer must be embedded to have forward compatible implementations.
type UnimplementedPayloadsApiServer struct {
}

func (UnimplementedPayloadsApiServer) QueryPayload(context.Context, *QueryPayloadRequest) (*QueryPayloadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryPayload not implemented")
}
func (UnimplementedPayloadsApiServer) DeletePayloadByGroup(context.Context, *DeletePayloadByGroupRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePayloadByGroup not implemented")
}
func (UnimplementedPayloadsApiServer) DeletePayload(context.Context, *DeletePayloadRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePayload not implemented")
}
func (UnimplementedPayloadsApiServer) SavePayload(context.Context, *SavePayloadRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SavePayload not implemented")
}
func (UnimplementedPayloadsApiServer) SavePayloadStream(*SavePayloadRequest, PayloadsApi_SavePayloadStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method SavePayloadStream not implemented")
}
func (UnimplementedPayloadsApiServer) GetAllPayloadGroup(context.Context, *Empty) (*GetAllPayloadGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllPayloadGroup not implemented")
}
func (UnimplementedPayloadsApiServer) UpdatePayload(context.Context, *UpdatePayloadRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePayload not implemented")
}
func (UnimplementedPayloadsApiServer) GetAllPayload(context.Context, *GetAllPayloadRequest) (*GetAllPayloadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllPayload not implemented")
}
func (UnimplementedPayloadsApiServer) mustEmbedUnimplementedPayloadsApiServer() {}

// UnsafePayloadsApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PayloadsApiServer will
// result in compilation errors.
type UnsafePayloadsApiServer interface {
	mustEmbedUnimplementedPayloadsApiServer()
}

func RegisterPayloadsApiServer(s grpc.ServiceRegistrar, srv PayloadsApiServer) {
	s.RegisterService(&PayloadsApi_ServiceDesc, srv)
}

func _PayloadsApi_QueryPayload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPayloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayloadsApiServer).QueryPayload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PayloadsApi_QueryPayload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayloadsApiServer).QueryPayload(ctx, req.(*QueryPayloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PayloadsApi_DeletePayloadByGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePayloadByGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayloadsApiServer).DeletePayloadByGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PayloadsApi_DeletePayloadByGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayloadsApiServer).DeletePayloadByGroup(ctx, req.(*DeletePayloadByGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PayloadsApi_DeletePayload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePayloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayloadsApiServer).DeletePayload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PayloadsApi_DeletePayload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayloadsApiServer).DeletePayload(ctx, req.(*DeletePayloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PayloadsApi_SavePayload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SavePayloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayloadsApiServer).SavePayload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PayloadsApi_SavePayload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayloadsApiServer).SavePayload(ctx, req.(*SavePayloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PayloadsApi_SavePayloadStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SavePayloadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PayloadsApiServer).SavePayloadStream(m, &payloadsApiSavePayloadStreamServer{stream})
}

type PayloadsApi_SavePayloadStreamServer interface {
	Send(*SavePayloadProgress) error
	grpc.ServerStream
}

type payloadsApiSavePayloadStreamServer struct {
	grpc.ServerStream
}

func (x *payloadsApiSavePayloadStreamServer) Send(m *SavePayloadProgress) error {
	return x.ServerStream.SendMsg(m)
}

func _PayloadsApi_GetAllPayloadGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayloadsApiServer).GetAllPayloadGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PayloadsApi_GetAllPayloadGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayloadsApiServer).GetAllPayloadGroup(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PayloadsApi_UpdatePayload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePayloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayloadsApiServer).UpdatePayload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PayloadsApi_UpdatePayload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayloadsApiServer).UpdatePayload(ctx, req.(*UpdatePayloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PayloadsApi_GetAllPayload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllPayloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayloadsApiServer).GetAllPayload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PayloadsApi_GetAllPayload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayloadsApiServer).GetAllPayload(ctx, req.(*GetAllPayloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PayloadsApi_ServiceDesc is the grpc.ServiceDesc for PayloadsApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PayloadsApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ypb.PayloadsApi",
	HandlerType: (*PayloadsApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryPayload",
			Handler:    _PayloadsApi_QueryPayload_Handler,
		},
		{
			MethodName: "DeletePayloadByGroup",
			Handler:    _PayloadsApi_DeletePayloadByGroup_Handler,
		},
		{
			MethodName: "DeletePayload",
			Handler:    _PayloadsApi_DeletePayload_Handler,
		},
		{
			MethodName: "SavePayload",
			Handler:    _PayloadsApi_SavePayload_Handler,
		},
		{
			MethodName: "GetAllPayloadGroup",
			Handler:    _PayloadsApi_GetAllPayloadGroup_Handler,
		},
		{
			MethodName: "UpdatePayload",
			Handler:    _PayloadsApi_UpdatePayload_Handler,
		},
		{
			MethodName: "GetAllPayload",
			Handler:    _PayloadsApi_GetAllPayload_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SavePayloadStream",
			Handler:       _PayloadsApi_SavePayloadStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "payloads_api.proto",
}
