// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: yak_shell_api.proto

package ypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type YaklangShellRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Input string `protobuf:"bytes,1,opt,name=Input,proto3" json:"Input,omitempty"`
}

func (x *YaklangShellRequest) Reset() {
	*x = YaklangShellRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yak_shell_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *YaklangShellRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YaklangShellRequest) ProtoMessage() {}

func (x *YaklangShellRequest) ProtoReflect() protoreflect.Message {
	mi := &file_yak_shell_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YaklangShellRequest.ProtoReflect.Descriptor instead.
func (*YaklangShellRequest) Descriptor() ([]byte, []int) {
	return file_yak_shell_api_proto_rawDescGZIP(), []int{0}
}

func (x *YaklangShellRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

type YaklangShellKVPair struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key          string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value        []byte `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	ValueVerbose string `protobuf:"bytes,3,opt,name=ValueVerbose,proto3" json:"ValueVerbose,omitempty"`
	SymbolId     int64  `protobuf:"varint,4,opt,name=SymbolId,proto3" json:"SymbolId,omitempty"`
}

func (x *YaklangShellKVPair) Reset() {
	*x = YaklangShellKVPair{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yak_shell_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *YaklangShellKVPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YaklangShellKVPair) ProtoMessage() {}

func (x *YaklangShellKVPair) ProtoReflect() protoreflect.Message {
	mi := &file_yak_shell_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YaklangShellKVPair.ProtoReflect.Descriptor instead.
func (*YaklangShellKVPair) Descriptor() ([]byte, []int) {
	return file_yak_shell_api_proto_rawDescGZIP(), []int{1}
}

func (x *YaklangShellKVPair) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *YaklangShellKVPair) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *YaklangShellKVPair) GetValueVerbose() string {
	if x != nil {
		return x.ValueVerbose
	}
	return ""
}

func (x *YaklangShellKVPair) GetSymbolId() int64 {
	if x != nil {
		return x.SymbolId
	}
	return 0
}

type YaklangShellResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RawResult *ExecResult           `protobuf:"bytes,1,opt,name=RawResult,proto3" json:"RawResult,omitempty"`
	Scope     []*YaklangShellKVPair `protobuf:"bytes,2,rep,name=Scope,proto3" json:"Scope,omitempty"`
}

func (x *YaklangShellResponse) Reset() {
	*x = YaklangShellResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yak_shell_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *YaklangShellResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YaklangShellResponse) ProtoMessage() {}

func (x *YaklangShellResponse) ProtoReflect() protoreflect.Message {
	mi := &file_yak_shell_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YaklangShellResponse.ProtoReflect.Descriptor instead.
func (*YaklangShellResponse) Descriptor() ([]byte, []int) {
	return file_yak_shell_api_proto_rawDescGZIP(), []int{2}
}

func (x *YaklangShellResponse) GetRawResult() *ExecResult {
	if x != nil {
		return x.RawResult
	}
	return nil
}

func (x *YaklangShellResponse) GetScope() []*YaklangShellKVPair {
	if x != nil {
		return x.Scope
	}
	return nil
}

var File_yak_shell_api_proto protoreflect.FileDescriptor

var file_yak_shell_api_proto_rawDesc = []byte{
	0x0a, 0x13, 0x79, 0x61, 0x6b, 0x5f, 0x73, 0x68, 0x65, 0x6c, 0x6c, 0x5f, 0x61, 0x70, 0x69, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x79, 0x70, 0x62, 0x1a, 0x11, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2b, 0x0a,
	0x13, 0x59, 0x61, 0x6b, 0x6c, 0x61, 0x6e, 0x67, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x22, 0x7c, 0x0a, 0x12, 0x59, 0x61,
	0x6b, 0x6c, 0x61, 0x6e, 0x67, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x4b, 0x56, 0x50, 0x61, 0x69, 0x72,
	0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x56, 0x65, 0x72, 0x62, 0x6f, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x56, 0x65, 0x72, 0x62, 0x6f, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x49, 0x64, 0x22, 0x74, 0x0a, 0x14, 0x59, 0x61, 0x6b, 0x6c,
	0x61, 0x6e, 0x67, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2d, 0x0a, 0x09, 0x52, 0x61, 0x77, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x79, 0x70, 0x62, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x52, 0x09, 0x52, 0x61, 0x77, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x2d, 0x0a, 0x05, 0x53, 0x63, 0x6f, 0x70, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x79, 0x70, 0x62, 0x2e, 0x59, 0x61, 0x6b, 0x6c, 0x61, 0x6e, 0x67, 0x53, 0x68, 0x65, 0x6c,
	0x6c, 0x4b, 0x56, 0x50, 0x61, 0x69, 0x72, 0x52, 0x05, 0x53, 0x63, 0x6f, 0x70, 0x65, 0x32, 0x5c,
	0x0a, 0x0b, 0x59, 0x61, 0x6b, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x41, 0x70, 0x69, 0x12, 0x4d, 0x0a,
	0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x59, 0x61, 0x6b, 0x6c, 0x61, 0x6e, 0x67, 0x53, 0x68,
	0x65, 0x6c, 0x6c, 0x12, 0x18, 0x2e, 0x79, 0x70, 0x62, 0x2e, 0x59, 0x61, 0x6b, 0x6c, 0x61, 0x6e,
	0x67, 0x53, 0x68, 0x65, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e,
	0x79, 0x70, 0x62, 0x2e, 0x59, 0x61, 0x6b, 0x6c, 0x61, 0x6e, 0x67, 0x53, 0x68, 0x65, 0x6c, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42, 0x07, 0x5a, 0x05,
	0x2f, 0x3b, 0x79, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_yak_shell_api_proto_rawDescOnce sync.Once
	file_yak_shell_api_proto_rawDescData = file_yak_shell_api_proto_rawDesc
)

func file_yak_shell_api_proto_rawDescGZIP() []byte {
	file_yak_shell_api_proto_rawDescOnce.Do(func() {
		file_yak_shell_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_yak_shell_api_proto_rawDescData)
	})
	return file_yak_shell_api_proto_rawDescData
}

var file_yak_shell_api_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_yak_shell_api_proto_goTypes = []interface{}{
	(*YaklangShellRequest)(nil),  // 0: ypb.YaklangShellRequest
	(*YaklangShellKVPair)(nil),   // 1: ypb.YaklangShellKVPair
	(*YaklangShellResponse)(nil), // 2: ypb.YaklangShellResponse
	(*ExecResult)(nil),           // 3: ypb.ExecResult
}
var file_yak_shell_api_proto_depIdxs = []int32{
	3, // 0: ypb.YaklangShellResponse.RawResult:type_name -> ypb.ExecResult
	1, // 1: ypb.YaklangShellResponse.Scope:type_name -> ypb.YaklangShellKVPair
	0, // 2: ypb.YakShellApi.CreateYaklangShell:input_type -> ypb.YaklangShellRequest
	2, // 3: ypb.YakShellApi.CreateYaklangShell:output_type -> ypb.YaklangShellResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_yak_shell_api_proto_init() }
func file_yak_shell_api_proto_init() {
	if File_yak_shell_api_proto != nil {
		return
	}
	file_message_api_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_yak_shell_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*YaklangShellRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yak_shell_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*YaklangShellKVPair); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yak_shell_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*YaklangShellResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_yak_shell_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_yak_shell_api_proto_goTypes,
		DependencyIndexes: file_yak_shell_api_proto_depIdxs,
		MessageInfos:      file_yak_shell_api_proto_msgTypes,
	}.Build()
	File_yak_shell_api_proto = out.File
	file_yak_shell_api_proto_rawDesc = nil
	file_yak_shell_api_proto_goTypes = nil
	file_yak_shell_api_proto_depIdxs = nil
}
