// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: ysoserial_go_api.proto

package ypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 已弃用
type YsoClassGeneraterOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	Type  string `protobuf:"bytes,3,opt,name=Type,proto3" json:"Type,omitempty"`
}

func (x *YsoClassGeneraterOptions) Reset() {
	*x = YsoClassGeneraterOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ysoserial_go_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *YsoClassGeneraterOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YsoClassGeneraterOptions) ProtoMessage() {}

func (x *YsoClassGeneraterOptions) ProtoReflect() protoreflect.Message {
	mi := &file_ysoserial_go_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YsoClassGeneraterOptions.ProtoReflect.Descriptor instead.
func (*YsoClassGeneraterOptions) Descriptor() ([]byte, []int) {
	return file_ysoserial_go_api_proto_rawDescGZIP(), []int{0}
}

func (x *YsoClassGeneraterOptions) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *YsoClassGeneraterOptions) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *YsoClassGeneraterOptions) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// 已弃用
type YsoOptionsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gadget  string                      `protobuf:"bytes,1,opt,name=Gadget,proto3" json:"Gadget,omitempty"`
	Class   string                      `protobuf:"bytes,2,opt,name=Class,proto3" json:"Class,omitempty"`
	Options []*YsoClassGeneraterOptions `protobuf:"bytes,3,rep,name=Options,proto3" json:"Options,omitempty"`
}

func (x *YsoOptionsRequest) Reset() {
	*x = YsoOptionsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ysoserial_go_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *YsoOptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YsoOptionsRequest) ProtoMessage() {}

func (x *YsoOptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ysoserial_go_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YsoOptionsRequest.ProtoReflect.Descriptor instead.
func (*YsoOptionsRequest) Descriptor() ([]byte, []int) {
	return file_ysoserial_go_api_proto_rawDescGZIP(), []int{1}
}

func (x *YsoOptionsRequest) GetGadget() string {
	if x != nil {
		return x.Gadget
	}
	return ""
}

func (x *YsoOptionsRequest) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *YsoOptionsRequest) GetOptions() []*YsoClassGeneraterOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type YsoClassOptionsResponseWithVerbose struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Options []*YsoClassGeneraterOptionsWithVerbose `protobuf:"bytes,1,rep,name=Options,proto3" json:"Options,omitempty"`
}

func (x *YsoClassOptionsResponseWithVerbose) Reset() {
	*x = YsoClassOptionsResponseWithVerbose{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ysoserial_go_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *YsoClassOptionsResponseWithVerbose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YsoClassOptionsResponseWithVerbose) ProtoMessage() {}

func (x *YsoClassOptionsResponseWithVerbose) ProtoReflect() protoreflect.Message {
	mi := &file_ysoserial_go_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YsoClassOptionsResponseWithVerbose.ProtoReflect.Descriptor instead.
func (*YsoClassOptionsResponseWithVerbose) Descriptor() ([]byte, []int) {
	return file_ysoserial_go_api_proto_rawDescGZIP(), []int{2}
}

func (x *YsoClassOptionsResponseWithVerbose) GetOptions() []*YsoClassGeneraterOptionsWithVerbose {
	if x != nil {
		return x.Options
	}
	return nil
}

type YsoDumpResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *YsoDumpResponse) Reset() {
	*x = YsoDumpResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ysoserial_go_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *YsoDumpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YsoDumpResponse) ProtoMessage() {}

func (x *YsoDumpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ysoserial_go_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YsoDumpResponse.ProtoReflect.Descriptor instead.
func (*YsoDumpResponse) Descriptor() ([]byte, []int) {
	return file_ysoserial_go_api_proto_rawDescGZIP(), []int{3}
}

func (x *YsoDumpResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type YsoBytesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileName string `protobuf:"bytes,1,opt,name=FileName,proto3" json:"FileName,omitempty"`
	Bytes    []byte `protobuf:"bytes,2,opt,name=Bytes,proto3" json:"Bytes,omitempty"`
}

func (x *YsoBytesResponse) Reset() {
	*x = YsoBytesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ysoserial_go_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *YsoBytesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YsoBytesResponse) ProtoMessage() {}

func (x *YsoBytesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ysoserial_go_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YsoBytesResponse.ProtoReflect.Descriptor instead.
func (*YsoBytesResponse) Descriptor() ([]byte, []int) {
	return file_ysoserial_go_api_proto_rawDescGZIP(), []int{4}
}

func (x *YsoBytesResponse) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *YsoBytesResponse) GetBytes() []byte {
	if x != nil {
		return x.Bytes
	}
	return nil
}

type YsoBytesObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *YsoBytesObject) Reset() {
	*x = YsoBytesObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ysoserial_go_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *YsoBytesObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YsoBytesObject) ProtoMessage() {}

func (x *YsoBytesObject) ProtoReflect() protoreflect.Message {
	mi := &file_ysoserial_go_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YsoBytesObject.ProtoReflect.Descriptor instead.
func (*YsoBytesObject) Descriptor() ([]byte, []int) {
	return file_ysoserial_go_api_proto_rawDescGZIP(), []int{5}
}

func (x *YsoBytesObject) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type YsoCodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=Code,proto3" json:"Code,omitempty"`
}

func (x *YsoCodeResponse) Reset() {
	*x = YsoCodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ysoserial_go_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *YsoCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YsoCodeResponse) ProtoMessage() {}

func (x *YsoCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ysoserial_go_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YsoCodeResponse.ProtoReflect.Descriptor instead.
func (*YsoCodeResponse) Descriptor() ([]byte, []int) {
	return file_ysoserial_go_api_proto_rawDescGZIP(), []int{6}
}

func (x *YsoCodeResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// 获取Gadget的Options
type YsoOption struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	NameVerbose string `protobuf:"bytes,2,opt,name=NameVerbose,proto3" json:"NameVerbose,omitempty"`
	Help        string `protobuf:"bytes,3,opt,name=Help,proto3" json:"Help,omitempty"`
}

func (x *YsoOption) Reset() {
	*x = YsoOption{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ysoserial_go_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *YsoOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YsoOption) ProtoMessage() {}

func (x *YsoOption) ProtoReflect() protoreflect.Message {
	mi := &file_ysoserial_go_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YsoOption.ProtoReflect.Descriptor instead.
func (*YsoOption) Descriptor() ([]byte, []int) {
	return file_ysoserial_go_api_proto_rawDescGZIP(), []int{7}
}

func (x *YsoOption) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *YsoOption) GetNameVerbose() string {
	if x != nil {
		return x.NameVerbose
	}
	return ""
}

func (x *YsoOption) GetHelp() string {
	if x != nil {
		return x.Help
	}
	return ""
}

type YsoOptionsWithVerbose struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Options []*YsoOption `protobuf:"bytes,1,rep,name=Options,proto3" json:"Options,omitempty"`
}

func (x *YsoOptionsWithVerbose) Reset() {
	*x = YsoOptionsWithVerbose{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ysoserial_go_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *YsoOptionsWithVerbose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YsoOptionsWithVerbose) ProtoMessage() {}

func (x *YsoOptionsWithVerbose) ProtoReflect() protoreflect.Message {
	mi := &file_ysoserial_go_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YsoOptionsWithVerbose.ProtoReflect.Descriptor instead.
func (*YsoOptionsWithVerbose) Descriptor() ([]byte, []int) {
	return file_ysoserial_go_api_proto_rawDescGZIP(), []int{8}
}

func (x *YsoOptionsWithVerbose) GetOptions() []*YsoOption {
	if x != nil {
		return x.Options
	}
	return nil
}

// 生成代码和字节码
type YsoOptionsRequerstWithVerbose struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Gadget  string                                 `protobuf:"bytes,1,opt,name=Gadget,proto3" json:"Gadget,omitempty"`
	Class   string                                 `protobuf:"bytes,2,opt,name=Class,proto3" json:"Class,omitempty"`
	Options []*YsoClassGeneraterOptionsWithVerbose `protobuf:"bytes,3,rep,name=Options,proto3" json:"Options,omitempty"`
}

func (x *YsoOptionsRequerstWithVerbose) Reset() {
	*x = YsoOptionsRequerstWithVerbose{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ysoserial_go_api_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *YsoOptionsRequerstWithVerbose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YsoOptionsRequerstWithVerbose) ProtoMessage() {}

func (x *YsoOptionsRequerstWithVerbose) ProtoReflect() protoreflect.Message {
	mi := &file_ysoserial_go_api_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YsoOptionsRequerstWithVerbose.ProtoReflect.Descriptor instead.
func (*YsoOptionsRequerstWithVerbose) Descriptor() ([]byte, []int) {
	return file_ysoserial_go_api_proto_rawDescGZIP(), []int{9}
}

func (x *YsoOptionsRequerstWithVerbose) GetGadget() string {
	if x != nil {
		return x.Gadget
	}
	return ""
}

func (x *YsoOptionsRequerstWithVerbose) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *YsoOptionsRequerstWithVerbose) GetOptions() []*YsoClassGeneraterOptionsWithVerbose {
	if x != nil {
		return x.Options
	}
	return nil
}

// 类生成器的参数
type YsoClassGeneraterOptionsWithVerbose struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key         string                                         `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	KeyVerbose  string                                         `protobuf:"bytes,2,opt,name=KeyVerbose,proto3" json:"KeyVerbose,omitempty"`
	Help        string                                         `protobuf:"bytes,3,opt,name=Help,proto3" json:"Help,omitempty"`
	Value       string                                         `protobuf:"bytes,4,opt,name=Value,proto3" json:"Value,omitempty"`
	Type        string                                         `protobuf:"bytes,5,opt,name=Type,proto3" json:"Type,omitempty"`
	BindOptions map[string]*YsoClassOptionsResponseWithVerbose `protobuf:"bytes,6,rep,name=BindOptions,proto3" json:"BindOptions,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *YsoClassGeneraterOptionsWithVerbose) Reset() {
	*x = YsoClassGeneraterOptionsWithVerbose{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ysoserial_go_api_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *YsoClassGeneraterOptionsWithVerbose) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YsoClassGeneraterOptionsWithVerbose) ProtoMessage() {}

func (x *YsoClassGeneraterOptionsWithVerbose) ProtoReflect() protoreflect.Message {
	mi := &file_ysoserial_go_api_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YsoClassGeneraterOptionsWithVerbose.ProtoReflect.Descriptor instead.
func (*YsoClassGeneraterOptionsWithVerbose) Descriptor() ([]byte, []int) {
	return file_ysoserial_go_api_proto_rawDescGZIP(), []int{10}
}

func (x *YsoClassGeneraterOptionsWithVerbose) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *YsoClassGeneraterOptionsWithVerbose) GetKeyVerbose() string {
	if x != nil {
		return x.KeyVerbose
	}
	return ""
}

func (x *YsoClassGeneraterOptionsWithVerbose) GetHelp() string {
	if x != nil {
		return x.Help
	}
	return ""
}

func (x *YsoClassGeneraterOptionsWithVerbose) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *YsoClassGeneraterOptionsWithVerbose) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *YsoClassGeneraterOptionsWithVerbose) GetBindOptions() map[string]*YsoClassOptionsResponseWithVerbose {
	if x != nil {
		return x.BindOptions
	}
	return nil
}

var File_ysoserial_go_api_proto protoreflect.FileDescriptor

var file_ysoserial_go_api_proto_rawDesc = []byte{
	0x0a, 0x16, 0x79, 0x73, 0x6f, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x5f, 0x67, 0x6f, 0x5f, 0x61,
	0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x79, 0x70, 0x62, 0x1a, 0x11, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x56, 0x0a, 0x18, 0x59, 0x73, 0x6f, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x47, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x74, 0x65, 0x72, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x10, 0x0a, 0x03,
	0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x22, 0x7a, 0x0a, 0x11, 0x59, 0x73, 0x6f, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x47, 0x61, 0x64, 0x67, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x47,
	0x61, 0x64, 0x67, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x37, 0x0a, 0x07, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x79,
	0x70, 0x62, 0x2e, 0x59, 0x73, 0x6f, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x61, 0x74, 0x65, 0x72, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x07, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x22, 0x68, 0x0a, 0x22, 0x59, 0x73, 0x6f, 0x43, 0x6c, 0x61, 0x73, 0x73,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x57,
	0x69, 0x74, 0x68, 0x56, 0x65, 0x72, 0x62, 0x6f, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x07, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x79, 0x70,
	0x62, 0x2e, 0x59, 0x73, 0x6f, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x74, 0x65, 0x72, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x57, 0x69, 0x74, 0x68, 0x56, 0x65,
	0x72, 0x62, 0x6f, 0x73, 0x65, 0x52, 0x07, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x25,
	0x0a, 0x0f, 0x59, 0x73, 0x6f, 0x44, 0x75, 0x6d, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x44, 0x0a, 0x10, 0x59, 0x73, 0x6f, 0x42, 0x79, 0x74, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x46, 0x69, 0x6c,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x46, 0x69, 0x6c,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x42, 0x79, 0x74, 0x65, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x42, 0x79, 0x74, 0x65, 0x73, 0x22, 0x24, 0x0a, 0x0e, 0x59,
	0x73, 0x6f, 0x42, 0x79, 0x74, 0x65, 0x73, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x44, 0x61, 0x74,
	0x61, 0x22, 0x25, 0x0a, 0x0f, 0x59, 0x73, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x55, 0x0a, 0x09, 0x59, 0x73, 0x6f, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x4e, 0x61, 0x6d,
	0x65, 0x56, 0x65, 0x72, 0x62, 0x6f, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x4e, 0x61, 0x6d, 0x65, 0x56, 0x65, 0x72, 0x62, 0x6f, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x48,
	0x65, 0x6c, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x48, 0x65, 0x6c, 0x70, 0x22,
	0x41, 0x0a, 0x15, 0x59, 0x73, 0x6f, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x57, 0x69, 0x74,
	0x68, 0x56, 0x65, 0x72, 0x62, 0x6f, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x07, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x79, 0x70, 0x62, 0x2e,
	0x59, 0x73, 0x6f, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x22, 0x91, 0x01, 0x0a, 0x1d, 0x59, 0x73, 0x6f, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x72, 0x73, 0x74, 0x57, 0x69, 0x74, 0x68, 0x56, 0x65, 0x72,
	0x62, 0x6f, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x47, 0x61, 0x64, 0x67, 0x65, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x47, 0x61, 0x64, 0x67, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x43, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x43, 0x6c, 0x61,
	0x73, 0x73, 0x12, 0x42, 0x0a, 0x07, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x79, 0x70, 0x62, 0x2e, 0x59, 0x73, 0x6f, 0x43, 0x6c, 0x61,
	0x73, 0x73, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x72, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x57, 0x69, 0x74, 0x68, 0x56, 0x65, 0x72, 0x62, 0x6f, 0x73, 0x65, 0x52, 0x07, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0xdb, 0x02, 0x0a, 0x23, 0x59, 0x73, 0x6f, 0x43, 0x6c,
	0x61, 0x73, 0x73, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x72, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x57, 0x69, 0x74, 0x68, 0x56, 0x65, 0x72, 0x62, 0x6f, 0x73, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79,
	0x12, 0x1e, 0x0a, 0x0a, 0x4b, 0x65, 0x79, 0x56, 0x65, 0x72, 0x62, 0x6f, 0x73, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x4b, 0x65, 0x79, 0x56, 0x65, 0x72, 0x62, 0x6f, 0x73, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x48, 0x65, 0x6c, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x48, 0x65, 0x6c, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x5b,
	0x0a, 0x0b, 0x42, 0x69, 0x6e, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x06, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x39, 0x2e, 0x79, 0x70, 0x62, 0x2e, 0x59, 0x73, 0x6f, 0x43, 0x6c, 0x61,
	0x73, 0x73, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x72, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x57, 0x69, 0x74, 0x68, 0x56, 0x65, 0x72, 0x62, 0x6f, 0x73, 0x65, 0x2e, 0x42, 0x69,
	0x6e, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0b,
	0x42, 0x69, 0x6e, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x67, 0x0a, 0x10, 0x42,
	0x69, 0x6e, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x3d, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x27, 0x2e, 0x79, 0x70, 0x62, 0x2e, 0x59, 0x73, 0x6f, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x57, 0x69,
	0x74, 0x68, 0x56, 0x65, 0x72, 0x62, 0x6f, 0x73, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x32, 0xec, 0x03, 0x0a, 0x0e, 0x59, 0x73, 0x6f, 0x53, 0x65, 0x72, 0x69,
	0x61, 0x6c, 0x47, 0x6f, 0x41, 0x70, 0x69, 0x12, 0x40, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x59, 0x73, 0x6f, 0x47, 0x61, 0x64, 0x67, 0x65, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x0a, 0x2e, 0x79, 0x70, 0x62, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1a, 0x2e,
	0x79, 0x70, 0x62, 0x2e, 0x59, 0x73, 0x6f, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x57, 0x69,
	0x74, 0x68, 0x56, 0x65, 0x72, 0x62, 0x6f, 0x73, 0x65, 0x12, 0x57, 0x0a, 0x15, 0x47, 0x65, 0x74,
	0x41, 0x6c, 0x6c, 0x59, 0x73, 0x6f, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x12, 0x22, 0x2e, 0x79, 0x70, 0x62, 0x2e, 0x59, 0x73, 0x6f, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x72, 0x73, 0x74, 0x57, 0x69, 0x74, 0x68, 0x56,
	0x65, 0x72, 0x62, 0x6f, 0x73, 0x65, 0x1a, 0x1a, 0x2e, 0x79, 0x70, 0x62, 0x2e, 0x59, 0x73, 0x6f,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x57, 0x69, 0x74, 0x68, 0x56, 0x65, 0x72, 0x62, 0x6f,
	0x73, 0x65, 0x12, 0x6d, 0x0a, 0x1e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x59, 0x73, 0x6f, 0x43,
	0x6c, 0x61, 0x73, 0x73, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x72, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x12, 0x22, 0x2e, 0x79, 0x70, 0x62, 0x2e, 0x59, 0x73, 0x6f, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x72, 0x73, 0x74, 0x57, 0x69, 0x74,
	0x68, 0x56, 0x65, 0x72, 0x62, 0x6f, 0x73, 0x65, 0x1a, 0x27, 0x2e, 0x79, 0x70, 0x62, 0x2e, 0x59,
	0x73, 0x6f, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x57, 0x69, 0x74, 0x68, 0x56, 0x65, 0x72, 0x62, 0x6f, 0x73,
	0x65, 0x12, 0x4b, 0x0a, 0x0f, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x59, 0x73, 0x6f,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x22, 0x2e, 0x79, 0x70, 0x62, 0x2e, 0x59, 0x73, 0x6f, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x72, 0x73, 0x74, 0x57, 0x69, 0x74,
	0x68, 0x56, 0x65, 0x72, 0x62, 0x6f, 0x73, 0x65, 0x1a, 0x14, 0x2e, 0x79, 0x70, 0x62, 0x2e, 0x59,
	0x73, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4d,
	0x0a, 0x10, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x59, 0x73, 0x6f, 0x42, 0x79, 0x74,
	0x65, 0x73, 0x12, 0x22, 0x2e, 0x79, 0x70, 0x62, 0x2e, 0x59, 0x73, 0x6f, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x72, 0x73, 0x74, 0x57, 0x69, 0x74, 0x68, 0x56,
	0x65, 0x72, 0x62, 0x6f, 0x73, 0x65, 0x1a, 0x15, 0x2e, 0x79, 0x70, 0x62, 0x2e, 0x59, 0x73, 0x6f,
	0x42, 0x79, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a,
	0x07, 0x59, 0x73, 0x6f, 0x44, 0x75, 0x6d, 0x70, 0x12, 0x13, 0x2e, 0x79, 0x70, 0x62, 0x2e, 0x59,
	0x73, 0x6f, 0x42, 0x79, 0x74, 0x65, 0x73, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x1a, 0x14, 0x2e,
	0x79, 0x70, 0x62, 0x2e, 0x59, 0x73, 0x6f, 0x44, 0x75, 0x6d, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x07, 0x5a, 0x05, 0x2f, 0x3b, 0x79, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ysoserial_go_api_proto_rawDescOnce sync.Once
	file_ysoserial_go_api_proto_rawDescData = file_ysoserial_go_api_proto_rawDesc
)

func file_ysoserial_go_api_proto_rawDescGZIP() []byte {
	file_ysoserial_go_api_proto_rawDescOnce.Do(func() {
		file_ysoserial_go_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_ysoserial_go_api_proto_rawDescData)
	})
	return file_ysoserial_go_api_proto_rawDescData
}

var file_ysoserial_go_api_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_ysoserial_go_api_proto_goTypes = []interface{}{
	(*YsoClassGeneraterOptions)(nil),            // 0: ypb.YsoClassGeneraterOptions
	(*YsoOptionsRequest)(nil),                   // 1: ypb.YsoOptionsRequest
	(*YsoClassOptionsResponseWithVerbose)(nil),  // 2: ypb.YsoClassOptionsResponseWithVerbose
	(*YsoDumpResponse)(nil),                     // 3: ypb.YsoDumpResponse
	(*YsoBytesResponse)(nil),                    // 4: ypb.YsoBytesResponse
	(*YsoBytesObject)(nil),                      // 5: ypb.YsoBytesObject
	(*YsoCodeResponse)(nil),                     // 6: ypb.YsoCodeResponse
	(*YsoOption)(nil),                           // 7: ypb.YsoOption
	(*YsoOptionsWithVerbose)(nil),               // 8: ypb.YsoOptionsWithVerbose
	(*YsoOptionsRequerstWithVerbose)(nil),       // 9: ypb.YsoOptionsRequerstWithVerbose
	(*YsoClassGeneraterOptionsWithVerbose)(nil), // 10: ypb.YsoClassGeneraterOptionsWithVerbose
	nil,           // 11: ypb.YsoClassGeneraterOptionsWithVerbose.BindOptionsEntry
	(*Empty)(nil), // 12: ypb.Empty
}
var file_ysoserial_go_api_proto_depIdxs = []int32{
	0,  // 0: ypb.YsoOptionsRequest.Options:type_name -> ypb.YsoClassGeneraterOptions
	10, // 1: ypb.YsoClassOptionsResponseWithVerbose.Options:type_name -> ypb.YsoClassGeneraterOptionsWithVerbose
	7,  // 2: ypb.YsoOptionsWithVerbose.Options:type_name -> ypb.YsoOption
	10, // 3: ypb.YsoOptionsRequerstWithVerbose.Options:type_name -> ypb.YsoClassGeneraterOptionsWithVerbose
	11, // 4: ypb.YsoClassGeneraterOptionsWithVerbose.BindOptions:type_name -> ypb.YsoClassGeneraterOptionsWithVerbose.BindOptionsEntry
	2,  // 5: ypb.YsoClassGeneraterOptionsWithVerbose.BindOptionsEntry.value:type_name -> ypb.YsoClassOptionsResponseWithVerbose
	12, // 6: ypb.YsoSerialGoApi.GetAllYsoGadgetOptions:input_type -> ypb.Empty
	9,  // 7: ypb.YsoSerialGoApi.GetAllYsoClassOptions:input_type -> ypb.YsoOptionsRequerstWithVerbose
	9,  // 8: ypb.YsoSerialGoApi.GetAllYsoClassGeneraterOptions:input_type -> ypb.YsoOptionsRequerstWithVerbose
	9,  // 9: ypb.YsoSerialGoApi.GenerateYsoCode:input_type -> ypb.YsoOptionsRequerstWithVerbose
	9,  // 10: ypb.YsoSerialGoApi.GenerateYsoBytes:input_type -> ypb.YsoOptionsRequerstWithVerbose
	5,  // 11: ypb.YsoSerialGoApi.YsoDump:input_type -> ypb.YsoBytesObject
	8,  // 12: ypb.YsoSerialGoApi.GetAllYsoGadgetOptions:output_type -> ypb.YsoOptionsWithVerbose
	8,  // 13: ypb.YsoSerialGoApi.GetAllYsoClassOptions:output_type -> ypb.YsoOptionsWithVerbose
	2,  // 14: ypb.YsoSerialGoApi.GetAllYsoClassGeneraterOptions:output_type -> ypb.YsoClassOptionsResponseWithVerbose
	6,  // 15: ypb.YsoSerialGoApi.GenerateYsoCode:output_type -> ypb.YsoCodeResponse
	4,  // 16: ypb.YsoSerialGoApi.GenerateYsoBytes:output_type -> ypb.YsoBytesResponse
	3,  // 17: ypb.YsoSerialGoApi.YsoDump:output_type -> ypb.YsoDumpResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_ysoserial_go_api_proto_init() }
func file_ysoserial_go_api_proto_init() {
	if File_ysoserial_go_api_proto != nil {
		return
	}
	file_message_api_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_ysoserial_go_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*YsoClassGeneraterOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ysoserial_go_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*YsoOptionsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ysoserial_go_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*YsoClassOptionsResponseWithVerbose); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ysoserial_go_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*YsoDumpResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ysoserial_go_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*YsoBytesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ysoserial_go_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*YsoBytesObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ysoserial_go_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*YsoCodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ysoserial_go_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*YsoOption); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ysoserial_go_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*YsoOptionsWithVerbose); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ysoserial_go_api_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*YsoOptionsRequerstWithVerbose); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ysoserial_go_api_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*YsoClassGeneraterOptionsWithVerbose); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ysoserial_go_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ysoserial_go_api_proto_goTypes,
		DependencyIndexes: file_ysoserial_go_api_proto_depIdxs,
		MessageInfos:      file_ysoserial_go_api_proto_msgTypes,
	}.Build()
	File_ysoserial_go_api_proto = out.File
	file_ysoserial_go_api_proto_rawDesc = nil
	file_ysoserial_go_api_proto_goTypes = nil
	file_ysoserial_go_api_proto_depIdxs = nil
}
