// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: ysoserial_go_api.proto

package ypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	YsoSerialGoApi_GetAllYsoGadgetOptions_FullMethodName         = "/ypb.YsoSerialGoApi/GetAllYsoGadgetOptions"
	YsoSerialGoApi_GetAllYsoClassOptions_FullMethodName          = "/ypb.YsoSerialGoApi/GetAllYsoClassOptions"
	YsoSerialGoApi_GetAllYsoClassGeneraterOptions_FullMethodName = "/ypb.YsoSerialGoApi/GetAllYsoClassGeneraterOptions"
	YsoSerialGoApi_GenerateYsoCode_FullMethodName                = "/ypb.YsoSerialGoApi/GenerateYsoCode"
	YsoSerialGoApi_GenerateYsoBytes_FullMethodName               = "/ypb.YsoSerialGoApi/GenerateYsoBytes"
	YsoSerialGoApi_YsoDump_FullMethodName                        = "/ypb.YsoSerialGoApi/YsoDump"
)

// YsoSerialGoApiClient is the client API for YsoSerialGoApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type YsoSerialGoApiClient interface {
	// Yso
	GetAllYsoGadgetOptions(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*YsoOptionsWithVerbose, error)
	GetAllYsoClassOptions(ctx context.Context, in *YsoOptionsRequerstWithVerbose, opts ...grpc.CallOption) (*YsoOptionsWithVerbose, error)
	GetAllYsoClassGeneraterOptions(ctx context.Context, in *YsoOptionsRequerstWithVerbose, opts ...grpc.CallOption) (*YsoClassOptionsResponseWithVerbose, error)
	GenerateYsoCode(ctx context.Context, in *YsoOptionsRequerstWithVerbose, opts ...grpc.CallOption) (*YsoCodeResponse, error)
	GenerateYsoBytes(ctx context.Context, in *YsoOptionsRequerstWithVerbose, opts ...grpc.CallOption) (*YsoBytesResponse, error)
	YsoDump(ctx context.Context, in *YsoBytesObject, opts ...grpc.CallOption) (*YsoDumpResponse, error)
}

type ysoSerialGoApiClient struct {
	cc grpc.ClientConnInterface
}

func NewYsoSerialGoApiClient(cc grpc.ClientConnInterface) YsoSerialGoApiClient {
	return &ysoSerialGoApiClient{cc}
}

func (c *ysoSerialGoApiClient) GetAllYsoGadgetOptions(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*YsoOptionsWithVerbose, error) {
	out := new(YsoOptionsWithVerbose)
	err := c.cc.Invoke(ctx, YsoSerialGoApi_GetAllYsoGadgetOptions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ysoSerialGoApiClient) GetAllYsoClassOptions(ctx context.Context, in *YsoOptionsRequerstWithVerbose, opts ...grpc.CallOption) (*YsoOptionsWithVerbose, error) {
	out := new(YsoOptionsWithVerbose)
	err := c.cc.Invoke(ctx, YsoSerialGoApi_GetAllYsoClassOptions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ysoSerialGoApiClient) GetAllYsoClassGeneraterOptions(ctx context.Context, in *YsoOptionsRequerstWithVerbose, opts ...grpc.CallOption) (*YsoClassOptionsResponseWithVerbose, error) {
	out := new(YsoClassOptionsResponseWithVerbose)
	err := c.cc.Invoke(ctx, YsoSerialGoApi_GetAllYsoClassGeneraterOptions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ysoSerialGoApiClient) GenerateYsoCode(ctx context.Context, in *YsoOptionsRequerstWithVerbose, opts ...grpc.CallOption) (*YsoCodeResponse, error) {
	out := new(YsoCodeResponse)
	err := c.cc.Invoke(ctx, YsoSerialGoApi_GenerateYsoCode_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ysoSerialGoApiClient) GenerateYsoBytes(ctx context.Context, in *YsoOptionsRequerstWithVerbose, opts ...grpc.CallOption) (*YsoBytesResponse, error) {
	out := new(YsoBytesResponse)
	err := c.cc.Invoke(ctx, YsoSerialGoApi_GenerateYsoBytes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ysoSerialGoApiClient) YsoDump(ctx context.Context, in *YsoBytesObject, opts ...grpc.CallOption) (*YsoDumpResponse, error) {
	out := new(YsoDumpResponse)
	err := c.cc.Invoke(ctx, YsoSerialGoApi_YsoDump_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// YsoSerialGoApiServer is the server API for YsoSerialGoApi service.
// All implementations must embed UnimplementedYsoSerialGoApiServer
// for forward compatibility
type YsoSerialGoApiServer interface {
	// Yso
	GetAllYsoGadgetOptions(context.Context, *Empty) (*YsoOptionsWithVerbose, error)
	GetAllYsoClassOptions(context.Context, *YsoOptionsRequerstWithVerbose) (*YsoOptionsWithVerbose, error)
	GetAllYsoClassGeneraterOptions(context.Context, *YsoOptionsRequerstWithVerbose) (*YsoClassOptionsResponseWithVerbose, error)
	GenerateYsoCode(context.Context, *YsoOptionsRequerstWithVerbose) (*YsoCodeResponse, error)
	GenerateYsoBytes(context.Context, *YsoOptionsRequerstWithVerbose) (*YsoBytesResponse, error)
	YsoDump(context.Context, *YsoBytesObject) (*YsoDumpResponse, error)
	mustEmbedUnimplementedYsoSerialGoApiServer()
}

// UnimplementedYsoSerialGoApiServer must be embedded to have forward compatible implementations.
type UnimplementedYsoSerialGoApiServer struct {
}

func (UnimplementedYsoSerialGoApiServer) GetAllYsoGadgetOptions(context.Context, *Empty) (*YsoOptionsWithVerbose, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllYsoGadgetOptions not implemented")
}
func (UnimplementedYsoSerialGoApiServer) GetAllYsoClassOptions(context.Context, *YsoOptionsRequerstWithVerbose) (*YsoOptionsWithVerbose, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllYsoClassOptions not implemented")
}
func (UnimplementedYsoSerialGoApiServer) GetAllYsoClassGeneraterOptions(context.Context, *YsoOptionsRequerstWithVerbose) (*YsoClassOptionsResponseWithVerbose, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllYsoClassGeneraterOptions not implemented")
}
func (UnimplementedYsoSerialGoApiServer) GenerateYsoCode(context.Context, *YsoOptionsRequerstWithVerbose) (*YsoCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateYsoCode not implemented")
}
func (UnimplementedYsoSerialGoApiServer) GenerateYsoBytes(context.Context, *YsoOptionsRequerstWithVerbose) (*YsoBytesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateYsoBytes not implemented")
}
func (UnimplementedYsoSerialGoApiServer) YsoDump(context.Context, *YsoBytesObject) (*YsoDumpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method YsoDump not implemented")
}
func (UnimplementedYsoSerialGoApiServer) mustEmbedUnimplementedYsoSerialGoApiServer() {}

// UnsafeYsoSerialGoApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to YsoSerialGoApiServer will
// result in compilation errors.
type UnsafeYsoSerialGoApiServer interface {
	mustEmbedUnimplementedYsoSerialGoApiServer()
}

func RegisterYsoSerialGoApiServer(s grpc.ServiceRegistrar, srv YsoSerialGoApiServer) {
	s.RegisterService(&YsoSerialGoApi_ServiceDesc, srv)
}

func _YsoSerialGoApi_GetAllYsoGadgetOptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YsoSerialGoApiServer).GetAllYsoGadgetOptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: YsoSerialGoApi_GetAllYsoGadgetOptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YsoSerialGoApiServer).GetAllYsoGadgetOptions(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _YsoSerialGoApi_GetAllYsoClassOptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(YsoOptionsRequerstWithVerbose)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YsoSerialGoApiServer).GetAllYsoClassOptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: YsoSerialGoApi_GetAllYsoClassOptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YsoSerialGoApiServer).GetAllYsoClassOptions(ctx, req.(*YsoOptionsRequerstWithVerbose))
	}
	return interceptor(ctx, in, info, handler)
}

func _YsoSerialGoApi_GetAllYsoClassGeneraterOptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(YsoOptionsRequerstWithVerbose)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YsoSerialGoApiServer).GetAllYsoClassGeneraterOptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: YsoSerialGoApi_GetAllYsoClassGeneraterOptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YsoSerialGoApiServer).GetAllYsoClassGeneraterOptions(ctx, req.(*YsoOptionsRequerstWithVerbose))
	}
	return interceptor(ctx, in, info, handler)
}

func _YsoSerialGoApi_GenerateYsoCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(YsoOptionsRequerstWithVerbose)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YsoSerialGoApiServer).GenerateYsoCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: YsoSerialGoApi_GenerateYsoCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YsoSerialGoApiServer).GenerateYsoCode(ctx, req.(*YsoOptionsRequerstWithVerbose))
	}
	return interceptor(ctx, in, info, handler)
}

func _YsoSerialGoApi_GenerateYsoBytes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(YsoOptionsRequerstWithVerbose)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YsoSerialGoApiServer).GenerateYsoBytes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: YsoSerialGoApi_GenerateYsoBytes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YsoSerialGoApiServer).GenerateYsoBytes(ctx, req.(*YsoOptionsRequerstWithVerbose))
	}
	return interceptor(ctx, in, info, handler)
}

func _YsoSerialGoApi_YsoDump_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(YsoBytesObject)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YsoSerialGoApiServer).YsoDump(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: YsoSerialGoApi_YsoDump_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YsoSerialGoApiServer).YsoDump(ctx, req.(*YsoBytesObject))
	}
	return interceptor(ctx, in, info, handler)
}

// YsoSerialGoApi_ServiceDesc is the grpc.ServiceDesc for YsoSerialGoApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var YsoSerialGoApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ypb.YsoSerialGoApi",
	HandlerType: (*YsoSerialGoApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllYsoGadgetOptions",
			Handler:    _YsoSerialGoApi_GetAllYsoGadgetOptions_Handler,
		},
		{
			MethodName: "GetAllYsoClassOptions",
			Handler:    _YsoSerialGoApi_GetAllYsoClassOptions_Handler,
		},
		{
			MethodName: "GetAllYsoClassGeneraterOptions",
			Handler:    _YsoSerialGoApi_GetAllYsoClassGeneraterOptions_Handler,
		},
		{
			MethodName: "GenerateYsoCode",
			Handler:    _YsoSerialGoApi_GenerateYsoCode_Handler,
		},
		{
			MethodName: "GenerateYsoBytes",
			Handler:    _YsoSerialGoApi_GenerateYsoBytes_Handler,
		},
		{
			MethodName: "YsoDump",
			Handler:    _YsoSerialGoApi_YsoDump_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ysoserial_go_api.proto",
}
