package pcaputil

import (
	"container/list"
	"encoding/binary"
	"encoding/hex"
	"errors"
	"fmt"
	"strconv"
	"time"
)

// Wrapper v1 transports complete unciphered LN Get-normal observations. wPorts
// are application addresses, separate from TCP/UDP ports. Observed pairing is
// not evidence of an authenticated or negotiated application association.
// Fixed overhead covers native, session and structured map projections. Wire
// strings and nested scalar fields are charged separately by complete frame size.
const wrapperProjectionBytes int64 = 4096

func wrapperError(k ProtocolErrorKind, why string) error {
	return protocolError(k, "DLMS Wrapper %s", why)
}
func wrapperFrameSize(w []byte, limit int) (int, error) {
	if len(w) < 8 {
		return 0, nil
	}
	n := 8 + int(binary.BigEndian.Uint16(w[6:8]))
	if n > limit {
		return 0, wrapperError(ErrResourceExceeded, "announced frame exceeds byte budget")
	}
	if len(w) < n {
		return 0, nil
	}
	return n, nil
}

type wrapperMessage struct {
	fields              map[string]any
	source, destination uint16
	invoke, flags       byte
	request, confirmed  bool
}

func decodeDLMSWrapper(w []byte, limit int) (*wrapperMessage, error) {
	bad := func(s string) (*wrapperMessage, error) { return nil, wrapperError(ErrMalformedMessage, s) }
	unsupported := func(s string) (*wrapperMessage, error) { return nil, wrapperError(ErrUnsupportedFeature, s) }
	if len(w) < 8 {
		return bad("Wrapper header truncated")
	}
	v, src, dst, n := binary.BigEndian.Uint16(w), binary.BigEndian.Uint16(w[2:]), binary.BigEndian.Uint16(w[4:]), int(binary.BigEndian.Uint16(w[6:]))
	if len(w) != 8+n {
		return bad("Wrapper declared payload length differs from complete frame")
	}
	if v != 1 {
		return unsupported("Wrapper version1 only")
	}
	p := w[8:]
	if len(p) == 0 {
		return unsupported("empty WPDU has no selected Get APDU")
	}
	if p[0] != 0xc0 && p[0] != 0xc4 {
		return unsupported("APDU outside unciphered LN Get")
	}
	if len(p) < 3 {
		return bad("Get service header truncated")
	}
	if p[1] != 1 {
		return unsupported("Get block/list choice separate work item")
	}
	if p[2]&0x30 != 0 {
		return unsupported("flag pattern not generated by fixed reference")
	}
	f := map[string]any{"wrapper_version": v, "source_wport": src, "destination_wport": dst, "payload_length": n, "wrapper_header_hex": hex.EncodeToString(w[:8]), "apdu_hex": hex.EncodeToString(p), "association_observed": false, "authentication_verified": false, "object_model_verified": false, "command": p[0], "service_choice": p[1], "invoke_id_and_priority": p[2], "invoke_id": p[2] & 15, "high_priority": p[2]&128 != 0, "confirmed_service": p[2]&64 != 0, "unused_flag_bits_raw": p[2] & 0x30}
	m := &wrapperMessage{fields: f, source: src, destination: dst, invoke: p[2] & 15, flags: p[2], request: p[0] == 0xc0, confirmed: p[2]&64 != 0}
	if m.request {
		if len(p) < 13 {
			return bad("Get-normal descriptor truncated")
		}
		if p[12] != 0 {
			return unsupported("selective access separate work item")
		}
		if len(p) != 13 {
			return bad("Get-normal descriptor has trailing bytes")
		}
		if int8(p[11]) <= 0 {
			return unsupported("positive signed8 attribute profile")
		}
		f["kind"], f["class_id"], f["logical_name_hex"], f["logical_name"], f["attribute_id"], f["selective_access"] = "GetRequestNormal", binary.BigEndian.Uint16(p[3:5]), hex.EncodeToString(p[5:11]), fmt.Sprintf("%d.%d.%d.%d.%d.%d", p[5], p[6], p[7], p[8], p[9], p[10]), int8(p[11]), false
	} else {
		if len(p) < 5 {
			return bad("Get-normal result truncated")
		}
		f["kind"] = "GetResponseNormal"
		switch p[3] {
		case 0:
			data, err := wrapperScalar(p[4:], limit)
			if err != nil {
				return nil, err
			}
			f["result_choice"], f["data"] = "data", data
		case 1:
			if len(p) != 5 {
				return bad("data-access-result trailing or missing bytes")
			}
			switch p[4] {
			case 0, 1, 2, 3, 4, 9, 11, 12, 13, 14, 15, 16, 17, 18, 19, 250:
			default:
				return unsupported("data-access-result not in pinned ErrorCode enumeration")
			}
			f["result_choice"], f["data_access_result"], f["operation_success"] = "data-access-result", p[4], p[4] == 0
		default:
			return unsupported("Get result discriminator outside selected reference encoding0/1")
		}
	}
	return m, nil
}
func wrapperScalar(w []byte, limit int) (map[string]any, error) {
	bad := func(s string) (map[string]any, error) { return nil, wrapperError(ErrMalformedMessage, s) }
	if len(w) == 0 {
		return bad("A-XDR Data missing")
	}
	tag, v := w[0], w[1:]
	out := map[string]any{"type": tag, "raw_hex": hex.EncodeToString(w)}
	sizes := map[byte]int{0: 0, 3: 1, 5: 4, 6: 4, 15: 1, 16: 2, 17: 1, 18: 2, 20: 8, 21: 8, 22: 1}
	if n, ok := sizes[tag]; ok {
		if len(v) != n {
			return bad("fixed A-XDR scalar size mismatch")
		}
		switch tag {
		case 0:
			out["value"] = nil
		case 3:
			out["value"], out["boolean_raw"] = v[0] != 0, v[0]
		default:
			var x uint64
			for _, b := range v {
				x = x<<8 | uint64(b)
			}
			if tag == 5 || tag == 15 || tag == 16 || tag == 20 {
				signed := int64(x)
				if n < 8 && v[0]&128 != 0 {
					signed -= int64(uint64(1) << (8 * n))
				}
				if signed <= -(1<<53) || signed >= (1<<53) {
					out["value"] = strconv.FormatInt(signed, 10)
				} else {
					out["value"] = signed
				}
			} else if x >= 1<<53 {
				out["value"] = strconv.FormatUint(x, 10)
			} else {
				out["value"] = x
			}
		}
		return out, nil
	}
	if tag != 9 {
		return nil, wrapperError(ErrUnsupportedFeature, "Data type outside bounded scalar/octet-string profile")
	}
	if len(v) == 0 {
		return bad("octet-string length missing")
	}
	count, at := uint64(v[0]), 1
	if v[0]&128 != 0 {
		k := int(v[0] & 127)
		if k != 1 && k != 2 && k != 4 {
			return nil, wrapperError(ErrUnsupportedFeature, "A-XDR count width outside pinned getObjectCount widths1/2/4")
		}
		if len(v) < 1+k {
			return bad("octet-string count truncated")
		}
		count = 0
		for _, b := range v[1 : 1+k] {
			count = count<<8 | uint64(b)
		}
		at += k
	}
	if count != uint64(len(v)-at) {
		return bad("octet-string length differs from complete value")
	}
	if count > uint64(limit) {
		return nil, wrapperError(ErrResourceExceeded, "octet-string exceeds value-byte/collection budget")
	}
	out["length"], out["length_encoding_hex"], out["value_hex"] = count, hex.EncodeToString(v[:at]), hex.EncodeToString(v[at:])
	return out, nil
}
func wrapperPortStart(w []byte, ports [2]uint16) bool {
	return len(w) > 0 && w[0] == 0 && (ports[0] == 4059 || ports[1] == 4059)
}
func probeDLMSWrapper(w []byte, limit int) ProbeResult {
	if len(w) < 2 || w[0] != 0 || w[1] != 1 {
		return ProbeResult{Verdict: ProbeReject}
	}
	n, err := wrapperFrameSize(w, limit)
	if err != nil {
		return ProbeResult{Verdict: ProbeReject}
	}
	if n == 0 {
		// The version prefix 0001 is also a valid Modbus transaction ID.
		// Once the APDU tag is available, retain only the selected Get prefix;
		// an unrelated incomplete envelope must reach the other probes.
		if !wrapperIncompletePrefix(w, limit) {
			return ProbeResult{Verdict: ProbeReject}
		}
		return probeNeed("dlms-wrapper", "v1-get-normal", len(w), max(8, len(w)+1))
	}
	if _, err := decodeDLMSWrapper(w[:n], 4096); err != nil {
		return ProbeResult{Verdict: ProbeReject}
	}
	return probeAccept("dlms-wrapper", "v1-get-normal", 98)
}

type wrapperToken struct {
	dir                 int
	source, destination uint16
	invoke              byte
}
type wrapperPending struct {
	id                 uint64
	flags              byte
	pending, ambiguous bool
}
type binDLMSWrapper struct {
	seen    map[wrapperToken]*wrapperPending
	blocked bool
}

func (s *binDLMSWrapper) storage() int64 { return 512 + 256*int64(len(s.seen)) }
func (s *binDLMSWrapper) outstanding() int {
	n := 0
	for _, p := range s.seen {
		if p.pending {
			n++
		}
	}
	return n
}
func (s *binDLMSWrapper) invalidate() {
	for _, p := range s.seen {
		p.pending = false
		p.ambiguous = true
	}
	s.blocked = true
}
func (f *binFlow) consumeWrapper(dir int, w []byte, e *ProtocolEvent) error {
	s := f.wrapper
	if s == nil {
		s = &binDLMSWrapper{}
		f.wrapper = s
	}
	// Reserve the complete field/projection graph and any new association slot
	// before allocating maps, raw hex strings or committing request identity.
	target := s.storage() + wrapperProjectionBytes + 256 + 128*int64(len(w))
	if err := f.reserveSession(target); err != nil {
		s.invalidate()
		var pe *ProtocolError
		if errors.As(err, &pe) {
			return pe
		}
		return err
	}
	if f.a.budget.MaxRecursionDepth < 2 {
		s.invalidate()
		return wrapperError(ErrResourceExceeded, "field depth exceeds recursion budget")
	}
	m, err := decodeDLMSWrapper(w, f.a.budget.MaxCollectionElements)
	if err != nil {
		s.invalidate()
		return err
	}
	assoc := "unmatched-response"
	if s.blocked {
		assoc = "ambiguous-conversation"
	} else if m.request {
		key := wrapperToken{dir, m.source, m.destination, m.invoke}
		if !m.confirmed {
			assoc = "unconfirmed-observation"
		} else if old := s.seen[key]; old != nil {
			old.pending, old.ambiguous = false, true
			assoc = "ambiguous-invoke"
		} else if len(s.seen) >= f.a.budget.MaxCollectionElements {
			s.invalidate()
			return wrapperError(ErrResourceExceeded, "retained invoke context exceeds collection budget")
		} else {
			if s.seen == nil {
				s.seen = make(map[wrapperToken]*wrapperPending)
			}
			s.seen[key] = &wrapperPending{id: e.ID, flags: m.flags, pending: true}
			e.TransactionID = e.ID
			assoc = "observed-request"
		}
	} else {
		key := wrapperToken{1 - dir, m.destination, m.source, m.invoke}
		p := s.seen[key]
		if p != nil && p.ambiguous {
			assoc = "ambiguous-invoke"
		} else if p != nil && p.pending && p.flags == m.flags {
			p.pending = false
			e.ResponseTo, e.TransactionID = p.id, p.id
			assoc = "observed-response"
		}
	}
	e.semanticFields = cloneSession(m.fields)
	e.Session = cloneSession(m.fields)
	e.Session["Association"], e.Session["Outstanding"] = assoc, s.outstanding()
	return nil
}

const wrapperIdleTTL = 30 * time.Second

func (a *binParser) expireWrapper(ts time.Time) {
	a.udpMu.Lock()
	defer a.udpMu.Unlock()
	s := a.udpSessions
	if s == nil {
		return
	}
	if ts.After(s.clock) {
		s.clock = ts
	}
	for el := s.lru.Front(); el != nil; {
		next := el.Next()
		v := el.Value.(*binUDPEntry)
		if v.flow.wrapper != nil && s.clock.Sub(v.touched) >= wrapperIdleTTL {
			v.flow.closeSession()
			delete(s.entries, v.key)
			s.lru.Remove(el)
		}
		el = next
	}
}
func (a *binParser) decodeWrapperDatagram(e *ProtocolEvent, w []byte, src, dst uint16, explicit bool) bool {
	ports := [2]uint16{src, dst}
	// The registry supplies admission using real UDP ports. Explicit binding may
	// report malformed input; automatic admission requires wrapper-v1 or port hint.
	if !explicit && !wrapperPortStart(w, ports) && a.probeWrapperDatagram(w).Verdict != ProbeAccept {
		return false
	}
	a.expireWrapper(e.Timestamp)
	e.Protocol, e.Profile, e.Admission, e.Completeness = "dlms-wrapper", "dlms-wrapper-v1-get-normal", "wire-signature", "message"
	if explicit {
		e.Admission = "explicit-decode-as"
	}
	if e.ID == 0 {
		e.ID = a.ids.Add(1)
	}
	key := binUDPKey{"wrapper/" + e.Source, "wrapper/" + e.Destination, e.Domain}
	if key.a > key.b {
		key.a, key.b = key.b, key.a
	}
	a.udpMu.Lock()
	defer a.udpMu.Unlock()
	store := a.udpSessions
	var el *list.Element
	if store != nil {
		el = store.entries[key]
	}
	f := &binFlow{a: a, wrapper: &binDLMSWrapper{}, protocol: "dlms-wrapper"}
	created := el == nil
	if el != nil {
		f = el.Value.(*binUDPEntry).flow
		e.FlowID = f.id
		e.Direction = 0
		if e.Source != f.endpoints[0] {
			e.Direction = 1
		}
		v := el.Value.(*binUDPEntry)
		v.touched = store.clock
		store.lru.MoveToBack(el)
	}
	var err error
	limit := min(a.budget.MaxFrameBytes, a.config.MaxMessageBytes)
	if len(w) > limit {
		f.wrapper.invalidate()
		retained := f.wrapper.storage()
		if retained < f.sessionBytes {
			a.buffered.Add(retained - f.sessionBytes)
			f.sessionBytes = retained
		}
		err = wrapperError(ErrResourceExceeded, "datagram exceeds frame byte budget")
	} else {
		err = f.consumeWrapper(e.Direction, w, e)
	}
	if err == nil && created && f.wrapper.outstanding() > 0 {
		if store != nil && len(store.entries) >= sessionCollectionLimit(a.budget.MaxCollectionElements) {
			err = wrapperError(ErrResourceExceeded, "UDP conversation limit")
		} else {
			if store == nil {
				store = &binUDPStore{entries: make(map[binUDPKey]*list.Element), clock: e.Timestamp}
				a.udpSessions = store
			}
			f.id, f.endpoints, f.domain = a.flows.Add(1), [2]string{e.Source, e.Destination}, e.Domain
			store.entries[key] = store.lru.PushBack(&binUDPEntry{key, f, store.clock})
			e.FlowID = f.id
			created = false
		}
	}
	if created {
		defer f.closeSession()
	}
	if err != nil {
		e.semanticFields, e.Session = nil, nil
		e.TransactionID, e.ResponseTo = 0, 0
	}
	raw := w
	if len(w) > limit || f.sessionBytes == 0 {
		raw = nil
		var typed *ProtocolError
		if errors.As(err, &typed) && typed.Kind == ErrResourceExceeded {
			a.limited.Add(uint64(len(w)))
		}
	}
	a.finishProtocolDatagram(e, raw, nil, err)
	if err != nil {
		e.Completeness = e.Status
	}
	return true
}

func (a *binParser) probeWrapper(w []byte) ProbeResult {
	if len(w) < 2 || w[0] != 0 || w[1] != 1 {
		return ProbeResult{Verdict: ProbeReject}
	}
	n, err := wrapperFrameSize(w, min(a.budget.MaxFrameBytes, a.config.MaxMessageBytes))
	if err != nil {
		return ProbeResult{Verdict: ProbeReject}
	}
	if n == 0 {
		if !wrapperIncompletePrefix(w, min(a.budget.MaxFrameBytes, a.config.MaxMessageBytes)) {
			return ProbeResult{Verdict: ProbeReject}
		}
		return probeNeed("dlms-wrapper", "v1-get-normal", len(w), max(8, len(w)+1))
	}
	temp := &binFlow{a: a}
	defer temp.closeSession()
	if err := temp.reserveSession(512 + 128*int64(n)); err != nil {
		return ProbeResult{Verdict: ProbeReject}
	}
	return probeDLMSWrapper(w[:n], a.budget.MaxFrameBytes)
}

func wrapperIncompletePrefix(w []byte, limit int) bool {
	if len(w) < 2 || w[0] != 0 || w[1] != 1 {
		return false
	}
	n, err := wrapperFrameSize(w, limit)
	return err == nil && n == 0 && (len(w) <= 8 || w[8] == 0xc0 || w[8] == 0xc4)
}
func (a *binParser) probeWrapperDatagram(w []byte) ProbeResult {
	n, err := wrapperFrameSize(w, min(a.budget.MaxFrameBytes, a.config.MaxMessageBytes))
	if err != nil || n == 0 || n != len(w) {
		return ProbeResult{Verdict: ProbeReject}
	}
	return a.probeWrapper(w)
}
