package sca

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"reflect"
	"sort"
	"strings"
	"testing"
	"testing/fstest"

	"github.com/yaklang/yaklang/common/sca/analyzer/dep-parser/nodejs/pnpm"
	"github.com/yaklang/yaklang/common/sca/analyzer/dep-parser/python/poetry"
	"github.com/yaklang/yaklang/common/sca/analyzer/dep-parser/rust/cargo"
	"github.com/yaklang/yaklang/common/sca/analyzer/dep-parser/types"
	"github.com/yaklang/yaklang/common/sca/core/budget"
	"github.com/yaklang/yaklang/common/sca/core/scanerr"
	"github.com/yaklang/yaklang/common/sca/dxtypes"
	"github.com/yaklang/yaklang/common/sca/model"
)

func modernBytes(t *testing.T, name string) []byte {
	t.Helper()
	b, err := fixtures.ReadFile("testdata/modern/" + name)
	if err != nil {
		t.Fatal(err)
	}
	return b
}
func modernScan(t *testing.T, name, filename string) *model.Report {
	t.Helper()
	r, err := ScanReport(context.Background(), fstest.MapFS{filename: {Data: modernBytes(t, name)}}, WithSnapshotID("modern"))
	if err != nil || r == nil || !r.Complete {
		t.Fatalf("%s: %v %+v", name, err, r)
	}
	// Repeat with the same snapshot identity: map iteration must not affect SBOM.
	r2, err := ScanReport(context.Background(), fstest.MapFS{filename: {Data: modernBytes(t, name)}}, WithSnapshotID("modern"))
	if err != nil || !reflect.DeepEqual(r, r2) {
		t.Fatalf("nondeterministic %s: %v", name, err)
	}
	bom := dxtypes.CreateCycloneDXSBOMFromReport(r)
	if bom.Components == nil || len(bom.Components) != len(r.Components) {
		t.Fatal("SBOM inventory differs")
	}
	foundObservations := false
	for _, property := range bom.Properties {
		if property.Name == "sca:observations" {
			var observations []model.Observation
			if err := json.Unmarshal([]byte(property.Value), &observations); err != nil || !reflect.DeepEqual(observations, r.Observations) {
				t.Fatal("SBOM lost source/group/marker evidence", err)
			}
			foundObservations = true
		}
	}
	if !foundObservations {
		t.Fatal("missing SBOM observations")
	}
	refs := map[string]bool{}
	for _, c := range bom.Components {
		if c.BOMRef == "" || refs[c.BOMRef] {
			t.Fatal("invalid BOM identity")
		}
		refs[c.BOMRef] = true
	}
	if bom.Dependencies != nil {
		for _, d := range bom.Dependencies {
			if !refs[d.Ref] {
				t.Fatalf("missing BOM source %s", d.Ref)
			}
			if d.DependsOn != nil {
				for _, ref := range d.DependsOn {
					if !refs[ref] {
						t.Fatalf("dangling BOM dependency %s", ref)
					}
				}
			}
		}
	}
	return r
}

func TestModernLockCorpora(t *testing.T) {
	for _, tc := range []struct {
		name, file string
		count      int
	}{
		{"cargo_v4/upstream.lock", "Cargo.lock", 7},
		{"pnpm_v9/pnpm-peer.yaml", "pnpm-lock.yaml", 8},
		{"pnpm_v9/pnpm-alias.yaml", "pnpm-lock.yaml", 2},
		{"pnpm_v9/pnpm-workspace.yaml", "pnpm-lock.yaml", 4},
		{"poetry_v2_1/upstream.lock", "poetry.lock", 0},
	} {
		t.Run(tc.name, func(t *testing.T) {
			r := modernScan(t, tc.name, tc.file)
			if tc.count > 0 && len(r.Components) != tc.count {
				t.Fatalf("components=%d want %d", len(r.Components), tc.count)
			}
		})
	}
	// Independent Python tomllib projections pin every upstream package, not just
	// a minimum count. They are frozen inputs and never generated by this parser.
	for _, tc := range []struct {
		group string
		p     types.Parser
	}{{"cargo_v4", cargo.NewParser()}, {"poetry_v2_1", poetry.NewParser()}} {
		t.Run(tc.group+"-oracle", func(t *testing.T) {
			var oracle []struct {
				Name, Version, Checksum string
				Groups                  []string
				Markers                 any
				Optional                bool
				Source                  any
				Files                   []struct{ Hash string }
			}
			if err := json.Unmarshal(modernBytes(t, tc.group+"/upstream-oracle.json"), &oracle); err != nil {
				t.Fatal(err)
			}
			libs, _, err := tc.p.Parse(nil, bytes.NewReader(modernBytes(t, tc.group+"/upstream.lock")))
			if err != nil {
				t.Fatal(err)
			}
			if len(libs) != len(oracle) {
				t.Fatalf("inventory %d want %d", len(libs), len(oracle))
			}
			got := map[string][]types.Library{}
			for _, l := range libs {
				got[l.Name+"@"+l.Version] = append(got[l.Name+"@"+l.Version], l)
			}
			for _, o := range oracle {
				matches := got[o.Name+"@"+o.Version]
				if len(matches) != 1 {
					t.Fatalf("oracle identity %s@%s: %d", o.Name, o.Version, len(matches))
				}
				l := matches[0]
				if tc.group == "cargo_v4" {
					source, _ := o.Source.(string)
					if l.Source != source || o.Checksum != "" && l.Verification != "sha256:"+o.Checksum {
						t.Fatalf("source/hash lost: %+v", l)
					}
				} else {
					sort.Strings(o.Groups)
					g, _ := json.Marshal(o.Groups)
					scope := "groups:" + string(g)
					if o.Optional {
						scope += "; optional"
					}
					if l.Scope != scope {
						t.Fatalf("groups %s: %s want %s", l.Name, l.Scope, scope)
					}
					condition := ""
					switch v := o.Markers.(type) {
					case string:
						condition = v
					case map[string]any:
						b, _ := json.Marshal(v)
						condition = "markers:" + string(b)
					}
					if l.Condition != condition {
						t.Fatalf("markers %s: %q want %q", l.Name, l.Condition, condition)
					}
					for _, f := range o.Files {
						if !strings.Contains(l.Verification, f.Hash) {
							t.Fatalf("hash lost %s: %s", l.Name, f.Hash)
						}
					}
				}
			}
		})
	}
}

func TestModernLockSemantics(t *testing.T) {
	t.Run("cargo-encoded-source-identities", func(t *testing.T) {
		r := modernScan(t, "cargo_v4/encoded-sources.lock", "Cargo.lock")
		if len(r.Components) != 4 {
			t.Fatalf("encoded URLs collapsed: %+v", r.Components)
		}
		sources := map[string]bool{}
		for _, c := range r.Components {
			if c.Key.Name == "dep" {
				sources[c.Key.Source] = true
			}
		}
		if !sources["git+https://example.invalid/a?branch=feature%2Bsafe#abc"] || !sources["git+https://example.invalid/a?branch=feature+safe#abc"] {
			t.Fatal(sources)
		}
		resolved := map[string]bool{}
		for _, q := range r.Requirements {
			if q.Target == "dep" {
				if len(q.Resolved) != 1 {
					t.Fatalf("exact source unresolved %+v", q)
				}
				resolved[q.Resolved[0]] = true
				assertSBOMReq(t, r, q.From, q.Target, q.Constraint, q.Condition, q.Resolved)
			}
		}
		if len(resolved) != 2 {
			t.Fatal("encoded sources bound to same observation")
		}
	})
	t.Run("pnpm-peer-alias-workspace-optional", func(t *testing.T) {
		r := modernScan(t, "pnpm_v9/contexts.yaml", "pnpm-lock.yaml")
		if len(r.Components) != 8 {
			t.Fatalf("inventory: %+v", r.Components)
		}
		ui := 0
		for _, c := range r.Components {
			if c.Key.Name == "ui" {
				ui++
				if c.Key.Source != "https://example.invalid/ui.tgz" || !strings.Contains(c.Key.Variant, "(react@") {
					t.Fatal(c)
				}
			}
		}
		if ui != 2 {
			t.Fatal("peer contexts collapsed")
		}
		alias, dev, optional := false, false, false
		observations := map[string]model.Observation{}
		for _, o := range r.Observations {
			observations[o.ID()] = o
		}
		for _, q := range r.Requirements {
			if q.Target == "compat" {
				alias = true
				if q.Constraint != "npm:react@19.0.0" || len(q.Resolved) != 1 || observations[q.Resolved[0]].NativeID != "pnpm-lock.yaml#react@19.0.0" {
					t.Fatal(q)
				}
			}
			if q.Target == "ui" && q.Scope == "dev" {
				dev = true
				if len(q.Resolved) != 1 || observations[q.Resolved[0]].NativeID != "pnpm-lock.yaml#ui@1.0.0(react@19.0.0)" {
					t.Fatal(q)
				}
			}
			if q.Scope == "optional" {
				optional = true
			}
			if len(q.Resolved) > 0 {
				assertSBOMReq(t, r, q.From, q.Target, q.Constraint, q.Condition, q.Resolved)
			}
		}
		if !alias || !dev || !optional {
			t.Fatalf("missing declarations %v %v %v", alias, dev, optional)
		}
	})
	t.Run("poetry-groups-markers-alternatives", func(t *testing.T) {
		r := modernScan(t, "poetry_v2_1/groups.lock", "poetry.lock")
		if len(r.Components) != 5 {
			t.Fatal(r.Components)
		}
		app := mustNamed(t, r, "app", "1.0.0")
		if app.Key.Verification != "sha256:"+strings.Repeat("ab", 32) {
			t.Fatal("package hash lost")
		}
		grouped := false
		for _, o := range r.Observations {
			if o.Component == app.Key.ID() {
				grouped = o.Scope == `groups:["docs","main"]` && strings.Contains(o.Condition, `"docs":"sys_platform == 'linux'"`)
			}
		}
		if !grouped {
			t.Fatal("group marker mapping lost")
		}
		count := 0
		optional := false
		for _, q := range r.Requirements {
			if q.Target == "child" {
				count++
				if q.Condition == "" || len(q.Resolved) != 0 {
					t.Fatalf("conditional alternatives guessed %+v", q)
				}
			}
			if q.Target == "opt" {
				optional = true
				if q.Scope != "optional" || !strings.Contains(q.Condition, "extras=[fast]") || len(q.Resolved) != 1 {
					t.Fatal(q)
				}
			}
			assertSBOMReq(t, r, q.From, q.Target, q.Constraint, q.Condition, q.Resolved)
		}
		if count != 2 || !optional {
			t.Fatalf("declarations lost %d %v", count, optional)
		}
	})
}

func TestModernLockFailures(t *testing.T) {
	for _, tc := range []struct {
		group, file string
		names       []string
	}{{"cargo_v4", "Cargo.lock", []string{"future.lock", "malformed.lock"}}, {"pnpm_v9", "pnpm-lock.yaml", []string{"future.yaml", "missing-metadata.yaml", "missing-snapshots.yaml", "malformed.yaml"}}, {"poetry_v2_1", "poetry.lock", []string{"future.lock", "malformed.lock", "bad-marker.lock"}}} {
		for _, name := range tc.names {
			t.Run(tc.group+"/"+name, func(t *testing.T) {
				r, err := ScanReport(context.Background(), fstest.MapFS{tc.file: {Data: modernBytes(t, tc.group+"/"+name)}})
				if err == nil || r == nil || r.Complete {
					t.Fatalf("invalid lock accepted: %v %+v", err, r)
				}
				want := "malformed_input"
				if strings.HasPrefix(name, "future") {
					want = "unsupported_syntax"
				}
				if strings.HasPrefix(name, "missing") {
					want = "evidence_insufficient"
				}
				found := false
				for _, d := range r.Diagnostics {
					if d.Code == want && d.Incomplete {
						found = true
					}
				}
				if !found {
					t.Fatalf("want %s: %+v", want, r.Diagnostics)
				}
			})
		}
	}
	for _, tc := range []struct{ group, file, name string }{{"cargo_v4", "Cargo.lock", "upstream.lock"}, {"pnpm_v9", "pnpm-lock.yaml", "contexts.yaml"}, {"poetry_v2_1", "poetry.lock", "upstream.lock"}} {
		t.Run(tc.group+"-budget-cancel", func(t *testing.T) {
			in := fstest.MapFS{tc.file: {Data: modernBytes(t, tc.group+"/"+tc.name)}}
			r, err := ScanReport(context.Background(), in, WithResourceLimits(ResourceLimits{MaxResultBytes: 256}))
			if !errors.Is(err, scanerr.ErrResourceLimit) || r == nil || r.Complete {
				t.Fatalf("budget %v %+v", err, r)
			}
			ctx, cancel := context.WithCancel(context.Background())
			cancel()
			_, err = ScanReport(ctx, in)
			if !errors.Is(err, context.Canceled) {
				t.Fatalf("cancellation %v", err)
			}
		})
	}
}

func TestModernPoetryRejectsInvalidDeclarations(t *testing.T) {
	raw := string(modernBytes(t, "poetry_v2_1/groups.lock"))
	for _, value := range []string{"true", "[true]", "[]", "{version=5}", "{version='*', optional='yes'}", "{version='*', extras=[true]}"} {
		t.Run(value, func(t *testing.T) {
			text := strings.Replace(raw, `opt = { version = "*", optional = true, extras = ["fast"], markers = "sys_platform == 'linux'" }`, "opt = "+value, 1)
			_, _, err := poetry.NewParser().Parse(nil, bytes.NewReader([]byte(text)))
			if !errors.Is(err, scanerr.ErrMalformedInput) {
				t.Fatalf("invalid declaration accepted: %v", err)
			}
		})
	}
}

func TestModernPnpmSnapshotIdentity(t *testing.T) {
	raw := modernBytes(t, "pnpm_v9/contexts.yaml")
	libs, deps, err := pnpm.NewParser().Parse(nil, bytes.NewReader(raw))
	if err != nil {
		t.Fatal(err)
	}
	byID := map[string]types.Library{}
	for _, l := range libs {
		byID[l.ID] = l
	}
	for id, want := range map[string]bool{"ui@1.0.0(react@18.0.0)": false, "ui@1.0.0(react@19.0.0)": true, "react@19.0.0": false} {
		l, ok := byID[id]
		if !ok || l.Indirect != want {
			t.Fatalf("direct snapshot %s: %+v", id, l)
		}
	}
	edges := map[string][]string{}
	for _, d := range deps {
		edges[d.ID] = d.DependsOn
	}
	for id, target := range map[string]string{"ui@1.0.0(react@18.0.0)": "react@18.0.0", "ui@1.0.0(react@19.0.0)": "react@19.0.0", "@scope/nested@1.0.0(ui@1.0.0(react@18.0.0))": "ui@1.0.0(react@18.0.0)"} {
		if !reflect.DeepEqual(edges[id], []string{target}) {
			t.Fatalf("peer/optional edge %s: %v", id, edges[id])
		}
	}
	patched := bytes.ReplaceAll(raw, []byte("ui@1.0.0(react@18.0.0)"), []byte("ui@1.0.0(patch_hash=abc)(react@18.0.0)"))
	patchedLibs, _, err := pnpm.NewParser().Parse(nil, bytes.NewReader(patched))
	if err != nil {
		t.Fatal(err)
	}
	foundPatch := false
	for _, l := range patchedLibs {
		if l.ID == "ui@1.0.0(patch_hash=abc)(react@18.0.0)" {
			foundPatch = true
			if l.Version != "1.0.0" || l.Variant != l.ID {
				t.Fatal("patch identity lost", l)
			}
		}
	}
	if !foundPatch {
		t.Fatal("missing patched snapshot")
	}
	// Omitting the peer context must remain unresolved, even if only one
	// snapshot has that name/version. No O(packages) fallback for each edge.
	ambiguous := strings.Replace(string(raw), "version: 1.0.0(react@18.0.0)", "version: 1.0.0", 1)
	_, unresolved, err := pnpm.NewParser().Parse(nil, bytes.NewReader([]byte(ambiguous)))
	if err != nil {
		t.Fatal(err)
	}
	checked := false
	for _, d := range unresolved {
		if d.ID == "importer:." {
			for _, q := range d.Requirements {
				if q.Target == "ui" {
					checked = true
					if q.Resolved != "" {
						t.Fatal("guessed peer context", q)
					}
				}
			}
		}
	}
	if !checked {
		t.Fatal("missing unqualified peer declaration")
	}
	for _, suffix := range []string{"(react@18.0.0", "(react@18.0.0)garbage", ")"} {
		bad := strings.Replace(string(raw), "  ui@1.0.0(react@18.0.0):", "  ui@1.0.0"+suffix+":", 1)
		if _, _, err := pnpm.NewParser().Parse(nil, bytes.NewReader([]byte(bad))); err == nil {
			t.Fatalf("malformed snapshot suffix %q accepted", suffix)
		}
	}
}

type modernContextReader struct {
	*bytes.Reader
	ctx context.Context
}

func (r modernContextReader) Context() context.Context { return r.ctx }

func FuzzModernLockVersions(f *testing.F) {
	for i, name := range []string{"cargo_v4/encoded-sources.lock", "pnpm_v9/contexts.yaml", "poetry_v2_1/groups.lock"} {
		raw, err := fixtures.ReadFile("testdata/modern/" + name)
		if err != nil {
			f.Fatal(err)
		}
		f.Add(uint8(i), raw)
	}
	f.Fuzz(func(t *testing.T, selector uint8, raw []byte) {
		if len(raw) > 128<<10 {
			t.Skip()
		}
		ctx := budget.Bind(context.Background(), mustLimits(t, ResourceLimits{MaxResultBytes: 4 << 20, MaxFileBytes: 128 << 10, MaxExpressionNodes: 10000, MaxSyntaxDepth: 32}))
		parsers := []types.Parser{cargo.NewParser(), pnpm.NewParser(), poetry.NewParser()}
		_, _, _ = parsers[int(selector)%len(parsers)].Parse(nil, modernContextReader{bytes.NewReader(raw), ctx})
	})
}

func TestModernPnpmRejectsInvalidImporter(t *testing.T) {
	raw := string(modernBytes(t, "pnpm_v9/contexts.yaml"))
	for _, replacement := range []string{"specifier: true", "specifier: null", "specifier: []"} {
		bad := strings.Replace(raw, "specifier: ^1.0.0", replacement, 1)
		if _, _, err := pnpm.NewParser().Parse(nil, bytes.NewReader([]byte(bad))); err == nil {
			t.Fatalf("invalid importer %s accepted", replacement)
		}
	}
	for _, replacement := range []string{"react@18.0.0: null", "react@18.0.0: true"} {
		bad := strings.Replace(raw, "react@18.0.0: {}", replacement, 1)
		if _, _, err := pnpm.NewParser().Parse(nil, bytes.NewReader([]byte(bad))); err == nil {
			t.Fatalf("invalid metadata %s accepted", replacement)
		}
	}
}

func TestModernPoetrySameVersionConditions(t *testing.T) {
	raw := modernBytes(t, "poetry_v2_1/groups.lock")
	raw = bytes.Replace(raw, []byte("name = \"child\"\nversion = \"2.0.0\""), []byte("name = \"child\"\nversion = \"1.0.0\""), 1)
	r, err := ScanReport(context.Background(), fstest.MapFS{"poetry.lock": {Data: raw}}, WithSnapshotID("same-version"))
	if err != nil || !r.Complete {
		t.Fatal(err)
	}
	child := mustNamed(t, r, "child", "1.0.0")
	conditions := map[string]bool{}
	instances := map[string]bool{}
	for _, o := range r.Observations {
		if o.Component == child.Key.ID() {
			conditions[o.Condition] = true
			instances[o.NativeID] = true
		}
	}
	if len(conditions) != 2 || len(instances) != 2 {
		t.Fatalf("conditional occurrences overwritten: %v %v", conditions, instances)
	}
	for _, q := range r.Requirements {
		if q.Target == "child" && len(q.Resolved) != 0 {
			t.Fatalf("ambiguous condition guessed: %+v", q)
		}
	}
}
