package mutate_tests

import (
	"context"
	"fmt"
	"github.com/yaklang/yaklang/common/yak/yaklang"
	"github.com/yaklang/yaklang/common/yak/yaklib/codec"
	"testing"
)

type HybridTestCase struct {
	Code         string
	Debug        bool
	EncodeBase64 bool
}

func TestYaklangHybridFuzz(t *testing.T) {
	initDB()

	/*
	   这个测试案例非常有意思，如果他过不了，意味着参数提取是有问题的，是不对的
	*/
	cases := []*HybridTestCase{
		{
			Code:         `cGFja2V0ID0gYFBPU1QgL2FkbWluL3Rlc3QucGhwP2FiYz0xMjMmJmM9eyJhYmMiOjEyLCJiIjpbIjEyIix7ImVmZyI6NCwiYWciOiIxMjMifV0sImMiOjF9IEhUVFAvMS4xCkhvc3Q6IHd3dy5iYWlkdS5jb20KQ29va2llOiBqc29uQmFzZTY0UGFyYW09ZXlKaFltTWlPakV5TENKaUlqcGJJakV5SWl4N0ltVm1aeUk2TkN3aVlXY2lPaUl4TWpNaWZWMHNJbU1pT2pGOTsganNvblVybFBhcmFtPSU3QiUyMmFiYyUyMiUzQTEyJTJDJTIyYiUyMiUzQSU1QiUyMjEyJTIyJTJDJTdCJTIyZWZnJTIyJTNBNCUyQyUyMmFnJTIyJTNBJTIyMTIzJTIyJTdEJTVEJTJDJTIyYyUyMiUzQTElN0QKCnsiYWJjIjoxMiwiYiI6WyIxMiIseyJlZmciOjQsImFnIjoiMTIzIn1dLCJjIjoxfQpgCgpwYWNrZXQyID0gYFBPU1QgL2FkbWluL3Rlc3QucGhwP2FiYz0xMjMmJmM9JTdCJTIyYWJjJTIyJTNBMTIlMkMlMjJiJTIyJTNBJTVCJTIyMTIlMjIlMkMlN0IlMjJlZmclMjIlM0E0JTJDJTIyYWclMjIlM0ElMjIxMjMlMjIlN0QlNUQlMkMlMjJjJTIyJTNBMSU3RCBIVFRQLzEuMQpIb3N0OiB3d3cuYmFpZHUuY29tCkNvb2tpZToganNvbkJhc2U2NFBhcmFtPWV5SmhZbU1pT2pFeUxDSmlJanBiSWpFeUlpeDdJbVZtWnlJNk5Dd2lZV2NpT2lJeE1qTWlmVjBzSW1NaU9qRjk7IGpzb25VcmxQYXJhbT0lN0IlMjJhYmMlMjIlM0ExMiUyQyUyMmIlMjIlM0ElNUIlMjIxMiUyMiUyQyU3QiUyMmVmZyUyMiUzQTQlMkMlMjJhZyUyMiUzQSUyMjEyMyUyMiU3RCU1RCUyQyUyMmMlMjIlM0ExJTdECgpkZGQ9JTdCJTIyYWJjJTIyJTNBMTIlMkMlMjJiJTIyJTNBJTVCJTIyMTIlMjIlMkMlN0IlMjJlZmclMjIlM0E0JTJDJTIyYWclMjIlM0ElMjIxMjMlMjIlN0QlNUQlMkMlMjJjJTIyJTNBMSU3RCYmYzI1PTEyJiZwb3N0QmFzZTY0PWV5SmhZbU1pT2pFeUxDSmlJanBiSWpFeUlpeDdJbVZtWnlJNk5Dd2lZV2NpT2lJeE1qTWlmVjBzSW1NaU9qRjlgCgphbGxQYXJhbXMgOj0gZnV6ei5IVFRQUmVxdWVzdChwYWNrZXQpfi5HZXRBbGxQYXJhbXMoKQppZiBhbGxQYXJhbXMuTGVuZ3RoKCkgPCAzMiB7CiAgICBwYW5pYygi6Iez5bCR6ZyA6KaBMzLkuKrlj4LmlbDvvIzlj4LmlbDmj5Dlj5bmlbDmja7ph4/kuI3otrMiKQp9CgpyZXN1bHRMaW5lcyA9IGFsbFBhcmFtcy5NYXAoaSA9PiBpLlN0cmluZygpKQpwYXJhbXNUYWJsZSA9ICIiLkpvaW4ocmVzdWx0TGluZXMpCmlmIHN0ci5Db3VudChwYXJhbXNUYWJsZSwgYGdldC1xdWVyeS1qc29uYCkgPCA3IHsKICAgIHBhbmljKCJnZXQtcXVlcnktanNvbiDmj5Dlj5blpLHotKUiKQp9CgppZiBzdHIuQ291bnQocGFyYW1zVGFibGUsIGBwb3N0LWpzb25gKSA8IDcgewogICAgcGFuaWMoInBvc3QtanNvbiDmj5Dlj5blpLHotKUiKQp9CgppZiBzdHIuQ291bnQocGFyYW1zVGFibGUsIGBjb29raWUtYmFzZTY0LWpzb25gKSA8IDcgewogICAgcGFuaWMoImNvb2tpZS1iYXNlNjQtanNvbiDmj5Dlj5blpLHotKUiKQp9CgppZiBzdHIuQ291bnQocGFyYW1zVGFibGUsIGBjb29raWUtanNvbmApIDwgNyB7CiAgICBwYW5pYygiY29va2llLWpzb24g5o+Q5Y+W5aSx6LSlIikKfQoKaWYgc3RyLkNvdW50KHBhcmFtc1RhYmxlLCBgJC5iWzFdLmVmZ2ApIDwgNCB7CiAgICBwYW5pYygiSlNPTlBBVEgg5o+Q5Y+W5aSx6LSlIikKfQpwcmludGxuKHBhcmFtc1RhYmxlKQ==`,
			EncodeBase64: true,
		},
		{
			Code:         `cGFja2V0ID0gYFBPU1QgL2FkbWluL3Rlc3QucGhwP2FiYz0xMjMmJmM9ZXlKaFltTWlPakV5TENKaUlqcGJJakV5SWl4N0ltVm1aeUk2TkN3aVlXY2lPaUl4TWpNaWZWMHNJbU1pT2pGOSBIVFRQLzEuMQpIb3N0OiB3d3cuYmFpZHUuY29tCkNvb2tpZToganNvbkJhc2U2NFBhcmFtPWV5SmhZbU1pT2pFeUxDSmlJanBiSWpFeUlpeDdJbVZtWnlJNk5Dd2lZV2NpT2lJeE1qTWlmVjBzSW1NaU9qRjk7IGpzb25VcmxQYXJhbT0lN0IlMjJhYmMlMjIlM0ExMiUyQyUyMmIlMjIlM0ElNUIlMjIxMiUyMiUyQyU3QiUyMmVmZyUyMiUzQTQlMkMlMjJhZyUyMiUzQSUyMjEyMyUyMiU3RCU1RCUyQyUyMmMlMjIlM0ExJTdECgpkZGQ9JTdCJTIyYWJjJTIyJTNBMTIlMkMlMjJiJTIyJTNBJTVCJTIyMTIlMjIlMkMlN0IlMjJlZmclMjIlM0E0JTJDJTIyYWclMjIlM0ElMjIxMjMlMjIlN0QlNUQlMkMlMjJjJTIyJTNBMSU3RCYmYzI1PTEyJiZwb3N0QmFzZTY0PWV5SmhZbU1pT2pFeUxDSmlJanBiSWpFeUlpeDdJbVZtWnlJNk5Dd2lZV2NpT2lJeE1qTWlmVjBzSW1NaU9qRjlgCgphbGxQYXJhbXMgOj0gZnV6ei5IVFRQUmVxdWVzdChwYWNrZXQpfi5HZXRBbGxQYXJhbXMoKQppZiBhbGxQYXJhbXMuTGVuZ3RoKCkgPCA0MiB7CiAgICBwYW5pYygi6Iez5bCR6ZyA6KaBNDLkuKrlj4LmlbDvvIzlj4LmlbDmj5Dlj5bmlbDmja7ph4/kuI3otrMiKQp9CgpyZXN1bHRMaW5lcyA9IGFsbFBhcmFtcy5NYXAoaSA9PiBpLlN0cmluZygpKQpwYXJhbXNUYWJsZSA9ICIiLkpvaW4ocmVzdWx0TGluZXMpCnByaW50bG4oc3RyaW5nKHBhcmFtc1RhYmxlKSkKaWYgc3RyLkNvdW50KHBhcmFtc1RhYmxlLCBgZ2V0LXF1ZXJ5LWJhc2U2NC1qc29uYCkgPCA3IHsKICAgIHBhbmljKCJldC1xdWVyeS1iYXNlNjQtanNvbiDmj5Dlj5blpLHotKUiKQp9CgppZiBzdHIuQ291bnQocGFyYW1zVGFibGUsIGBwb3N0LXF1ZXJ5LWpzb25gKSA8IDcgewogICAgcGFuaWMoInBvc3QtcXVlcnktanNvbiDmj5Dlj5blpLHotKUiKQp9CgppZiBzdHIuQ291bnQocGFyYW1zVGFibGUsIGBwb3N0LXF1ZXJ5LWJhc2U2NC1qc29uYCkgPCA3IHsKICAgIHBhbmljKCJwb3N0LXF1ZXJ5LWJhc2U2NC1qc29uIOaPkOWPluWksei0pSIpCn0KCmlmIHN0ci5Db3VudChwYXJhbXNUYWJsZSwgYGNvb2tpZS1iYXNlNjQtanNvbmApIDwgNyB7CiAgICBwYW5pYygiY29va2llLWJhc2U2NC1qc29uIOaPkOWPluWksei0pSIpCn0KCmlmIHN0ci5Db3VudChwYXJhbXNUYWJsZSwgYGNvb2tpZS1qc29uYCkgPCA3IHsKICAgIHBhbmljKCJjb29raWUtanNvbiDmj5Dlj5blpLHotKUiKQp9CgppZiBzdHIuQ291bnQocGFyYW1zVGFibGUsIGAkLmJbMV0uZWZnYCkgPCA1IHsKICAgIHBhbmljKCJKU09OUEFUSCDmj5Dlj5blpLHotKUiKQp9CnByaW50bG4ocGFyYW1zVGFibGUpCgovLyBwYWNrZXRzID0gW3BhY2tldCwgcGFja2V0Ml0KLy8gcGFja2V0cyA9IFtwYWNrZXRdCi8vIGZvciBwIGluIHBhY2tldHMgewovLyAgICAgY291bnQgPSAwCi8vICAgICBmb3IgcGFyYW0gaW4gZnV6ei5IVFRQUmVxdWVzdChwKX4uR2V0QWxsUGFyYW1zKCkgewovLyAgICAgICAgIGNvdW50KysKLy8gICAgICAgICBwYXJhbS5EZWJ1ZygpCi8vICAgICB9Ci8vICAgICBwcmludGxuKCJUT1RBTDogIiwgY291bnQpCi8vIH0=`,
			EncodeBase64: true,
		},
	}

	var debugCases []*HybridTestCase
	var normalCases []*HybridTestCase
	for _, c := range cases {
		if c.Debug {
			debugCases = append(debugCases, c)
		} else {
			normalCases = append(normalCases, c)
		}
	}

	handleCase := func(data *HybridTestCase) {
		if data.EncodeBase64 {
			var raw, err = codec.DecodeBase64(data.Code)
			if err != nil {
				panic("decode base64 failed: " + data.Code)
			}
			data.Code = string(raw)
		}

		err := yaklang.New().Eval(context.Background(), data.Code)
		if err != nil {
			fmt.Println()
			fmt.Println(data.Code)
			panic(err)
		}
	}

	for _, c := range debugCases {
		handleCase(c)
	}
	for _, c := range normalCases {
		handleCase(c)
	}
}
