package yarn

import (
	"bytes"
	"strings"
	"testing"

	"github.com/yaklang/yaklang/common/sca/analyzer/dep-parser/types"
)

func yarnLock(blocks ...string) string {
	return strings.Join(blocks, "\n\n") + "\n"
}

func TestParseYarnOriginalRanges(t *testing.T) {
	reqOf := func(t *testing.T, src string) []types.Requirement {
		t.Helper()
		_, deps, err := NewParser().Parse(nil, bytes.NewReader([]byte(src)))
		if err != nil {
			t.Fatal(err)
		}
		var out []types.Requirement
		for _, d := range deps {
			out = append(out, d.Requirements...)
			for _, id := range d.DependsOn {
				if strings.HasPrefix(id, "unresolved-yarn:") {
					t.Fatalf("synthetic unresolved target: %q", id)
				}
			}
		}
		return out
	}

	jsTokens := `js-tokens@^2.0.0:
  version "2.0.0"
  resolved "https://example/js-tokens-2.0.0.tgz"
  integrity sha512-aaa==

"js-tokens@^3.0.0 || ^4.0.0":
  version "4.0.0"
  resolved "https://example/js-tokens-4.0.0.tgz"
  integrity sha512-bbb==`

	t.Run("or-range-resolves-matching-descriptor", func(t *testing.T) {
		src := yarnLock(`loose-envify@^1.4.0:
  version "1.4.0"
  resolved "https://example/loose-envify-1.4.0.tgz"
  integrity sha512-ccc==
  dependencies:
    js-tokens "^3.0.0 || ^4.0.0"`, jsTokens)
		qs := reqOf(t, src)
		if len(qs) != 1 {
			t.Fatalf("got %+v", qs)
		}
		q := qs[0]
		if q.Target != "js-tokens" || q.Constraint != "^3.0.0 || ^4.0.0" || q.Condition != "js-tokens@^3.0.0 || ^4.0.0" {
			t.Fatalf("original range lost: %+v", q)
		}
		if q.Resolved == "" {
			t.Fatal("matching descriptor must resolve")
		}
		if q.Constraint == "4.0.0" {
			t.Fatalf("invented locked version as constraint: %+v", q)
		}
	})

	t.Run("or-range-does-not-pick-other-js-tokens-by-name", func(t *testing.T) {
		src := yarnLock(`app@1.0.0:
  version "1.0.0"
  dependencies:
    js-tokens "^3.0.0 || ^4.0.0"`, `js-tokens@^2.0.0:
  version "2.0.0"
  resolved "https://example/js-tokens-2.0.0.tgz"
  integrity sha512-aaa==`)
		qs := reqOf(t, src)
		if len(qs) != 1 || qs[0].Target != "js-tokens" || qs[0].Constraint != "^3.0.0 || ^4.0.0" || qs[0].Resolved != "" {
			t.Fatalf("must not pick js-tokens@2.0.0 by name/order: %+v", qs)
		}
	})

	t.Run("alias-two-descriptors-same-lock", func(t *testing.T) {
		src := yarnLock(`loose-envify@^1.1.0, loose-envify@^1.4.0:
  version "1.4.0"
  resolved "https://example/loose-envify-1.4.0.tgz"
  integrity sha512-ccc==
  dependencies:
    js-tokens "^3.0.0 || ^4.0.0"`, jsTokens, `scheduler@0.13.6:
  version "0.13.6"
  dependencies:
    loose-envify "^1.1.0"`)
		qs := reqOf(t, src)
		found := false
		for _, q := range qs {
			if q.Target == "loose-envify" && q.Constraint == "^1.1.0" {
				found = true
				if q.Resolved == "" {
					t.Fatalf("alias ^1.1.0 must resolve to 1.4.0 lock: %+v", q)
				}
			}
		}
		if !found {
			t.Fatalf("missing alias requirement: %+v", qs)
		}
	})

	t.Run("missing-descriptor", func(t *testing.T) {
		src := yarnLock(`app@1.0.0:
  version "1.0.0"
  dependencies:
    missing "^1.0.0"`, jsTokens)
		qs := reqOf(t, src)
		if len(qs) != 1 || qs[0].Target != "missing" || qs[0].Constraint != "^1.0.0" || qs[0].Condition != "missing@^1.0.0" || qs[0].Resolved != "" {
			t.Fatalf("missing: %+v", qs)
		}
	})

	t.Run("empty-constraint-not-invented", func(t *testing.T) {
		src := yarnLock(`app@1.0.0:
  version "1.0.0"
  dependencies:
    foo "1.0.0"`, `foo@1.0.0:
  version "1.0.0"
  resolved "https://example/foo-1.0.0.tgz"
  integrity sha512-ddd==`)
		qs := reqOf(t, src)
		if len(qs) != 1 || qs[0].Constraint != "1.0.0" || qs[0].Target != "foo" {
			t.Fatalf("%+v", qs)
		}
	})

	t.Run("optional-after-dependencies-keeps-original-range", func(t *testing.T) {
		src := yarnLock(`app@1.0.0:
  version "1.0.0"
  dependencies:
    foo "^1.0.0"
  optionalDependencies:
    bar "^2.0.0"`, `foo@^1.0.0:
  version "1.0.0"`, `bar@^2.0.0:
  version "2.0.0"`)
		qs := reqOf(t, src)
		if len(qs) != 2 {
			t.Fatalf("optional section dropped: %+v", qs)
		}
		var foo, bar types.Requirement
		for _, q := range qs {
			switch q.Target {
			case "foo":
				foo = q
			case "bar":
				bar = q
			default:
				t.Fatalf("unexpected %+v", q)
			}
		}
		if foo.Constraint != "^1.0.0" || foo.Scope != "" || foo.Condition != "foo@^1.0.0" || foo.Resolved == "" {
			t.Fatalf("foo %+v", foo)
		}
		if bar.Constraint != "^2.0.0" || bar.Scope != "optional" || bar.Condition != "bar@^2.0.0" || bar.Resolved == "" {
			t.Fatalf("bar %+v", bar)
		}
	})

	t.Run("berry-or-range-exact-descriptor", func(t *testing.T) {
		src := `# This file is generated by running "yarn install" inside your project.

__metadata:
  version: 4
  cacheKey: 6

"js-tokens@npm:^2.0.0":
  version: 2.0.0
  resolution: "js-tokens@npm:2.0.0"
  languageName: node
  linkType: hard

"js-tokens@npm:^3.0.0 || ^4.0.0":
  version: 4.0.0
  resolution: "js-tokens@npm:4.0.0"
  languageName: node
  linkType: hard

"loose-envify@npm:^1.4.0":
  version: 1.4.0
  resolution: "loose-envify@npm:1.4.0"
  dependencies:
    js-tokens: ^3.0.0 || ^4.0.0
  languageName: node
  linkType: hard
`
		qs := reqOf(t, src)
		if len(qs) != 1 || qs[0].Target != "js-tokens" || qs[0].Constraint != "^3.0.0 || ^4.0.0" || qs[0].Condition != "js-tokens@^3.0.0 || ^4.0.0" || qs[0].Resolved == "" {
			t.Fatalf("berry original range: %+v", qs)
		}
		if qs[0].Constraint == "4.0.0" {
			t.Fatalf("invented locked version: %+v", qs[0])
		}
	})

	t.Run("berry-same-name-does-not-pick-by-order", func(t *testing.T) {
		src := `# This file is generated by running "yarn install" inside your project.

"is-number@npm:^6.0.0":
  version: 6.0.0
  resolution: "is-number@npm:6.0.0"
  languageName: node
  linkType: hard

"is-number@npm:^7.0.0":
  version: 7.0.0
  resolution: "is-number@npm:7.0.0"
  languageName: node
  linkType: hard

"is-odd@npm:^3.0.1":
  version: 3.0.1
  resolution: "is-odd@npm:3.0.1"
  dependencies:
    is-number: ^6.0.0
  languageName: node
  linkType: hard
`
		got, deps, err := NewParser().Parse(nil, bytes.NewReader([]byte(src)))
		if err != nil {
			t.Fatal(err)
		}
		if len(deps) != 1 || len(deps[0].Requirements) != 1 {
			t.Fatalf("%+v", deps)
		}
		q := deps[0].Requirements[0]
		if q.Target != "is-number" || q.Constraint != "^6.0.0" || q.Condition != "is-number@^6.0.0" {
			t.Fatalf("%+v", q)
		}
		idOf := map[string]string{}
		for _, lib := range got {
			idOf[lib.Name+"@"+lib.Version] = lib.ID
		}
		if q.Resolved != idOf["is-number@6.0.0"] {
			t.Fatalf("resolved %q want is-number@6.0.0 %q not 7.0.0 %q", q.Resolved, idOf["is-number@6.0.0"], idOf["is-number@7.0.0"])
		}
	})
}
