name: palm-build-test

on:
  pull_request:
    branches:
      - palm/*
      - feverk1ng/*
      - feverking/*
  push:
    branches:
      - palm/*
      - feverk1ng/*
      - feverking/*

jobs:

  test:
    name: Build Palm
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Dependence
        run: |
          sudo apt-get update
          sudo apt-get install libpcap-dev

      - name: Building
        run: go build server/cmd/server.go