name: Push web docs

on:
  workflow_dispatch:
  push:
    branches:
      - "doc/ci/*"
    tags:
      - "v*"

jobs:
  build:
    if: ${{ startsWith(github.ref, 'refs/tags/v') || startsWith(github.ref, 'refs/heads/doc/ci/') }}
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Install libpcap (Linux)
      run: |
        sudo apt-get update && sudo apt-get install libpcap-dev=1.9.1-3
    
    - name: Set Node.js and yarn
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: Generate docs
      run: |
        echo "Generating docs..."
        go run common/yak/yakdoc/generate_web_doc/generate_web_doc.go web_doc/
        echo "Generating docs finished"
        
    - name: Checkout yaklang.github.io repo
      uses: actions/checkout@v2
      with:
        repository: yaklang/yaklang.github.io
        token: ${{ secrets.GH_TOKEN }}
        path: websize

    - name: Copy docs
      run: |
        cp -rf web_doc/* websize/docs/api

    - name: Add tag and Push
      run: |
        cd websize
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        yarn --version
        git add . && (git commit -m "Update api docs" && yarn version --minor && git push && git push --tags)