name: Push web docs

on:
  push:
    branches:
      - "ci/*"
    tags:
      - "v*"

jobs:
  build:
    if: ${{ startsWith(github.ref, 'refs/tags/v') || startsWith(github.ref, 'refs/heads/ci/') }}
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Install libpcap (Linux)
      run: |
        sudo apt-get update && sudo apt-get install libpcap-dev=1.9.1-3

    - name: Generate docs
      run: |
        echo "Generating docs..."
        go run common/yak/yakdoc/generate_web_doc/generate_web_doc.go web_doc/
        echo "Generating docs finished"
        
    - name: Checkout yaklang.github.io repo
      uses: actions/checkout@v2
      with:
        repository: yaklang/yaklang.github.io
        token: ${{ secrets.GH_TOKEN }}
        path: websize

    - name: Copy docs
      run: |
        cp -rf web_doc/* websize/docs/api

    - name: Push
      run: |
        cd websize
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Update api docs"
        git push