name: WIP

on:
  pull_request:
    types:
      - opened
      - edited
      - labeled
      - unlabeled
      - synchronize

jobs:
  WIP:
    # fork PR should not run this action
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: WAY29/wip@v1.3.0
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

          # Set action to failed when wip.
          setFailed: false

          # Match with PR labels. Comma separated and case insensitive labels.
          labels: "'do-not-merge','work in progress','wip','rfc','WIP'"

          # Match with PR title. Comma separated and case insensitive keywords.
          keywords: "'do-not-merge', 'work in progress', 'wip', 'rfc','WIP'"

          # A string label to differentiat  e this status from the status of
          # other systems. This field is case-insensitive.
          # @see: https://docs.github.com/en/rest/reference/repos#create-a-commit-status
          context: WIP

          # The target URL to associate with this status. This URL will be
          # linked from the GitHub UI to allow users to easily see the source
          # of the status. For example, if your continuous integration system
          # is posting build status, you would want to provide the deep link
          # for the build output for this specific SHA: http://ci.example.com/user/repo/build/sha
          # @see: https://docs.github.com/en/rest/reference/repos#create-a-commit-status
          target_url: ''

          # A short description of the status.
          # @see: https://docs.github.com/en/rest/reference/repos#create-a-commit-status
          wip_description: 'work in progress'
          ready_description: 'ready for review'